export default {
  "__actions": "الإجراءات",
  "__actions_outcomes": "الإجراءات والنتائج",
  "__assumptions": "الافتراضات",
  "__assumptions_intro": "الوصول الى اعدادات تغير الافتراضات الرئيسية لنموذج En-ROADS. تؤثر هذه الإعدادات على السيناريو الحالي فقط وليس السيناريو الأساسي ، مما يسمح بإجراء مقارنات بينها.",
  "__beta": "الإصدار التجريبي",
  "__cancel": "الغاء",
  "__close": "اغلاق",
  "__continue_to_en_roads": "تابع إلى En-ROADS",
  "__detailed_settings_active": "الخيارات التفصيلية نشطة",
  "__en_roads_climate_ambassador_training": "تدريب سفير مناخ En-ROADS",
  "__enter_full_screen": "ادخل وضع ملء الشاشة",
  "__exit_full_screen": "الخروج من وضع ملئ للشاشة",
  "__full_screen_unavailable": "وضع ملء الشاشة غير متاح",
  "__graph": "الرسم البياني",
  "__graph_dashed_baseline": "الخطوط المتقطعة تمثل خط الأساس",
  "__graph_data_copied_to_the_clipboard": "نسخ بيانات الرسم البياني إلى الحافظة",
  "__help": "مساعدة",
  "__here_is_a_climate_scenario": "إليك سيناريو مناخي ، تم إنشاؤه باستخدام #EnROADS simulator منclimateinteract وMITSloanSusty",
  "__input_range_error_message": "أدخل قيمة بين {minValue} و {maxValue}.",
  "__invalid_url_params": "لا يمكن تحميل رابط السيناريو الذي جربته بشكل صحيح. يرجى إعادة إنشاء السيناريو في أحدث إصدار.",
  "__kaya_graphs": "رسوم كايا البيانية",
  "__no": "لا",
  "__outcomes": "النتائج",
  "__redo": "إعادة",
  "__register_your_event": "سجل فعالية En-ROADS الخاص بك",
  "__related_examples": "أمثلة مشابهة",
  "__related_graphs": "رسوم بيانية مشابهة",
  "__reload": "إعادة تحميل",
  "__replay_last_change": "إعادة آخر تغيير",
  "__reset_assumptions": "إعادة تعيين الافتراضات",
  "__reset_graphs": "إعادة تعيين الرسوم البيانية",
  "__reset_sliders": "إعادة تعيين السياسات والافتراضات",
  "__scenario_link_copied_to_the_clipboard": "تم نسخ ارتباط السيناريو إلى الحافظة",
  "__sea_level_rise": "ارتفاع مستوى سطح البحر",
  "__show_all_regions": "إظهار جميع المناطق…",
  "__show_main_graphs": "اظهر الرسوم البيانية الرئيسية",
  "__show_miniature_graphs": "اظهر الرسوم البيانية المصغرة",
  "__show_more": "أظهر المزيد…",
  "__undo": "تراجَع",
  "__unsupported_browser": "لا يعمل En-ROADS حاليًا على أجهزة Android اللوحية. يمكنك استخدام En-ROADS على أجهزة الكمبيوتر التي تعمل بنظام Windows مع شاشات تعمل باللمس ، ولكن مع لوحة اللمس(touch pad) ليس مع شاشة اللمس.",
  "__url_input_change_warning": "يتضمن رابط السيناريو قيم لشريط التمرير لا تعمل مع الإصدار الحالي من En-ROADS. تمت إعادة التعيين إلى القيم الافتراضية الحالية:",
  "__url_input_value_warning": "يتضمن رابط السيناريو قيم لشريط التمرير تقع خارج النطاق المسموح. تم إعادة تعيين أشرطة التمرير هذه إلى القيم الافتراضية الحالية:",
  "__yes": "نعم",
  "advanced_section_title__air_and_water": "الهواء والماء",
  "advanced_section_title__carbon_pricing": "تسعير الكربون",
  "advanced_section_title__clean_electricity_standard": "معيار الكهرباء النظيفة",
  "advanced_section_title__emissions_performance_standard": "معيار أداء الانبعاثات",
  "advanced_section_title__energy_storage_for_wind_and_solar": "تخزين الطاقة للرياح والطاقة الشمسية",
  "advanced_section_title__road_and_rail": "الطرق والسكك الحديدية",
  "assumption_category_title__carbon_capture_and_removals": "احتجاز الكربون وإزالته",
  "assumption_category_title__earth_system": "منظومة الأرض",
  "assumption_category_title__economy": "الاقتصاد",
  "assumption_category_title__energy": "الطاقة",
  "assumption_group_title__afforestation_and_reforestation": "التشجير",
  "assumption_group_title__agricultural_carbon_dioxide_removal": "الإزالة الزراعية لثاني أكسيد الكربون",
  "assumption_group_title__agriculture": "الزراعة",
  "assumption_group_title__air_pollution_from_energy": "تلوث الهواء الناجم عن الطاقة",
  "assumption_group_title__bioenergy": "الطاقة الحيوية",
  "assumption_group_title__breakthrough_commercialization_time": "مدة تسويق الاختراق التكنولوجي",
  "assumption_group_title__carbon_dioxide_capture_and_transport": "احتجاز ونقل ثاني أكسيد الكربون",
  "assumption_group_title__carbon_dioxide_storage": "تخزين ثاني أكسيد الكربون",
  "assumption_group_title__climate_system_sensitivities": "حساسيات النظام المناخي",
  "assumption_group_title__direct_air_carbon_capture_and_storage_daccs": "الاحتجاز المباشر للكربون من الهواء وتخزينه (DACCS)",
  "assumption_group_title__economic_impact_of_climate_change": "الأثر الاقتصادي لتغير المناخ",
  "assumption_group_title__electricity_storage_and_demand_response": "تخزين الكهرباء والاستجابة للطلب عليها",
  "assumption_group_title__electrification": "الكهربة",
  "assumption_group_title__forest_fires": "حرائق الغابات",
  "assumption_group_title__initial_fossil_fuel_resource_remaining": "مورد الوقود الأحفوري الأولي المتبقي",
  "assumption_group_title__land_carbon_and_methane_cycles": "دورات الكربون والميثان الأرضية",
  "assumption_group_title__methane_n2o_and_f_gases": "الميثان وأكسيد النيتروز والغازات المفلورة",
  "assumption_group_title__mineralization": "التمعدن",
  "assumption_group_title__phase_out_of_new_investments": "الإنهاء التدريجي للاستثمارات الجديدة",
  "assumption_group_title__plant_construction_time": "مدة بناء المنشأة",
  "assumption_group_title__plant_development_time": "مدة تطوير المنشأة",
  "assumption_group_title__policy_timing": "توقيت السياسات",
  "assumption_group_title__progress_ratio": "نسبة التقدم",
  "assumption_group_title__renewables_flow_constraint_on_source": "قيود تدفق الطاقة المتجددة حسب المصدر",
  "assumption_group_title__sea_level_rise": "ارتفاع مستوى البحر",
  "assumptions__preset": "المعد مسبقا:",
  "assumptions__related_graph": "رسم بياني ذو صلة:",
  "basic_section_header__buildings_and_industry": "المباني والصناعة",
  "basic_section_header__carbon_removal": "إزالة ثاني أكسيد الكربون",
  "basic_section_header__energy_supply": "إمدادات الطاقة",
  "basic_section_header__growth": "النمو",
  "basic_section_header__other_sources_of_greenhouse_gases": "مصادر أخرى لغازات الاحتباس الحراري",
  "basic_section_header__transport": "النقل",
  "data_table_139_footnote": "تعتمد هذه الكميات العددية على الافتراضات المعدلة في إعدادات <a href=\"#\"> التأثير الاقتصادي</a>:",
  "data_table_row_001_label": "التكلفة المجتمعية للكربون في {year}",
  "data_table_row_002_label": "الأضرار التراكمية المخصومة حتى عام 2100",
  "data_table_units__per_ton_co2": "/ طن CO<sub>2</sub>",
  "data_table_units__trillion": "تريليون",
  "data_table_value__dollars": "${num}",
  "graph_001_mini_title": "الطلب على الطاقة الأولية",
  "graph_001_title": "المصادر العالمية للطاقة الأولية",
  "graph_002_menu_title": "المصادر العالمية للطاقة الأولية -المجال",
  "graph_002_mini_title": "مصادر الطاقة الأولية",
  "graph_002_title": "المصادر العالمية للطاقة الأولية",
  "graph_003_title": "الطلب على الطاقة الأولية للفحم",
  "graph_005_title": "الطلب على الطاقة الأولية للنفط",
  "graph_006_menu_title": "الطلب على الطاقة الأولية للنفط - مساحة",
  "graph_006_title": "الطلب على الطاقة الأولية للنفط حسب الاستخدام",
  "graph_007_title": "الطلب على الطاقة الأولية للغاز الطبيعي",
  "graph_009_title": "الطلب على الطاقة الأولية للطاقة الحيوية",
  "graph_011_title": "الطلب على الطاقة الأولية المتجددة",
  "graph_012_title": "الطلب على الطاقة الأولية النووية",
  "graph_013_title": "الطلب على الطاقة الأولية لصفر-كربون جديد",
  "graph_018_title": "إجمالي الطاقة الأولية",
  "graph_024_menu_title": "التكلفة الحدية للطاقة المتجددة - المجال",
  "graph_024_title": "التكلفة الحدية لمصادر الطاقة المتجددة",
  "graph_026_title": "حدة الكربون للطاقة الأولية",
  "graph_028_title": "حدة الكربون للطاقة الكهربائية الأولية",
  "graph_029_mini_title": "الطلب على الطاقة",
  "graph_029_title": "إجمالي الاستهلاك النهائي لمصادر الطاقة",
  "graph_030_title": "استهلاك الطاقة النهائي حسب المصدر",
  "graph_031_menu_title": "الاستهلاك النهائي للطاقة حسب المصدر - مساحة",
  "graph_031_title": "استهلاك الطاقة النهائي حسب المصدر",
  "graph_032_menu_title": "حصة الاستهلاك النهائي حسب مصدر الطاقة - مساحة",
  "graph_032_title": "حصة الاستهلاك النهائي حسب مصدر الطاقة",
  "graph_033_title": "الاستهلاك النهائي للفحم",
  "graph_034_title": "الاستهلاك النهائي للنفط",
  "graph_035_title": "الاستهلاك النهائي للغاز الطبيعي",
  "graph_036_title": "الاستهلاك النهائي للطاقة الحيوية",
  "graph_037_title": "الاستهلاك النهائي للطاقة النووية",
  "graph_038_title": "الاستهلاك النهائي للطاقة المتجددة",
  "graph_039_title": "الاستهلاك النهائي للطاقة الجديدة الخالية من الكربون",
  "graph_040_title": "الاستهلاك النهائي للطاقة منخفضة الكربون",
  "graph_041_menu_title": "استهلاك الطاقة الكهربائية النهائي حسب المصدر- المجال",
  "graph_041_title": "استهلاك الطاقة الكهربائية النهائي حسب المصدر",
  "graph_042_menu_title": "الاستهلاك النهائي للطاقة حسب الاستخدام - مساحة",
  "graph_042_title": "الاستهلاك النهائي للطاقة حسب الاستخدام",
  "graph_043_title": "% الاستهلاك النهائي من الطاقة المتجددة",
  "graph_044_title": "% استهلاك الكهرباء من مصادر الطاقة المتجددة",
  "graph_045_title": "الحصة الكهربائية من الإجمالي-مباني صناعات",
  "graph_046_title": "الحصة الكهربائية من الإجمالي - النقل",
  "graph_047_mini_title": "كثافة انبعاثات الكربون للطاقة النهائية",
  "graph_047_title": "حدة الكربون للطاقة النهائية",
  "graph_048_title": "حدة الكربون للطاقة الكهربائية النهائية",
  "graph_051_mini_title": "الناتج المحلي الإجمالي للفرد الواحد",
  "graph_051_title": "الناتج المحلي الإجمالي للفرد الواحد",
  "graph_052_title": "الناتج المحلي الإجمالي للفرد حسب المنطقة",
  "graph_053_title": "حدة الطاقة في الناتج المحلي الإجمالي",
  "graph_054_title": "الناتج العالمي الخام",
  "graph_055_title": "انبعاثات ثاني أكسيد الكربون من الطاقة والصناعة حسب المصدر",
  "graph_057_title": "انبعاثات و إزالة ثاني أكسيد الكربون",
  "graph_058_title": "انبعاثات ثاني أكسيد الكربون للفرد",
  "graph_059_title": "كثافة الكربون في الناتج المحلي الإجمالي",
  "graph_061_mini_title": "انبعاثات ثاني أكسيد الكربون من الطاقة",
  "graph_061_title": "انبعاثات ثاني أكسيد الكربون من الطاقة والصناعة",
  "graph_062_mini_title": "صافي انبعاثات غازات الدفيئة",
  "graph_062_title": "صافي انبعاثات غازات الاحتباس الحراري",
  "graph_063_menu_title": "صافي انبعاثات الغازات الدفيئة حسب الغاز - المجال",
  "graph_063_mini_title": "انبعاثات غازات الدفيئة وإزالتها",
  "graph_063_title": "صافي انبعاثات غازات الاحتباس الحراري حسب الغاز",
  "graph_065_title": "انبعاثات غازات الاحتباس الحراري دون CO<sub>2</sub>",
  "graph_067_title": "انبعاثات الميثان",
  "graph_068_title": "انبعاثات N<sub>2</sub>O",
  "graph_069_title": "انبعاثات الغازات المفلورة بحسب النوع",
  "graph_073_title": "إزالة ثاني أكسيد الكربون البشري المنشأ",
  "graph_074_title": "الأراضي لإزالة ثاني أكسيد الكربون",
  "graph_075_title": "انبعاثات الكربون من استخدام الأراضي دون الطاقة الحيوية",
  "graph_076_title": "صافي انبعاثات ثاني أكسيد الكربون من استخدام الأراضي",
  "graph_077_menu_title": "مصادر إزالة ثاني أكسيد الكربون البشري المنشأ - مساحة",
  "graph_077_mini_title": "إزالة ثاني أكسيد الكربون",
  "graph_077_title": "مصادر إزالة ثاني أكسيد الكربون البشري المنشأ",
  "graph_078_mini_title": "سعر الطاقة",
  "graph_078_title": "متوسط سعر الطاقة للمستهلك",
  "graph_079_title": "سعر الكربون",
  "graph_082_title": "سعر السوق للكهرباء",
  "graph_085_title": "إجمالي الإنفاق السنوي على الطاقة",
  "graph_086_mini_title": "درجة الحرارة",
  "graph_086_title": "تغير درجة الحرارة",
  "graph_087_title": "تغير درجة الحرارة درجة فهرنهايت",
  "graph_088_title": "تركيز ثاني أكسيد الكربون",
  "graph_089_title": "تركيز غازات الاحتباس الحراري",
  "graph_090_title": "ارتفاع مستوى سطح البحر",
  "graph_091_title": "ارتفاع مستوى سطح البحر - قدم",
  "graph_092_title": "تحمض المحيطات",
  "graph_093_title": "الإيرادات و التكاليف من الضرائب و الدعم",
  "graph_094_title": "عدد سكان العالم",
  "graph_095_title": "عدد السكان حسب المنطقة",
  "graph_097_menu_title": "ثاني أكسيد الكربون البشري المنشأ التراكمي الذي تمت إزالته حسب المصدر—مساحة",
  "graph_097_title": "CO<sub>2</sub>&nbsp;البشري المنشأ التراكمي الذي تمت إزالته حسب المصدر",
  "graph_101_title": "إزالة ثاني أكسيد الكربون عن طريق التشجير",
  "graph_102_title": "صافي انبعاثات ثاني أكسيد الكربون التراكمية",
  "graph_104_mini_title": "صافي انبعاثات ثاني أكسيد الكربون",
  "graph_104_title": "صافي انبعاثات ثاني أكسيد الكربون",
  "graph_106_title": "تاريخ درجة الحرارة",
  "graph_110_menu_title": "التكلفة الحدية(MC) للإنتاج الكهرباء حسب المصدر",
  "graph_110_mini_title": "تكلفة الكهرباء",
  "graph_110_title": "التكلفة الحدية(MC) للإنتاج الكهرباء",
  "graph_111_title": "الأراضي لإزالة ثاني أكسيد الكربون - Acres",
  "graph_112_menu_title": "تلوث الهواء من الطاقة",
  "graph_112_title": "تلوث الهواء من الطاقة —انبعاثات PM2.5",
  "graph_113_menu_title": "تلوث الهواء من الطاقة حسب المصدر - المجال",
  "graph_113_title": "تلوث الهواء من الطاقة حسب المصدر — PM2.5",
  "graph_115_menu_title": "التكلفة الحدية(MC) لإنتاج الكهرباء من المصادر منخفضة الكربون حسب المصدر",
  "graph_115_title": "التكلفة الحدية للإنتاج من المصادر منخفضة الكربون",
  "graph_117_menu_title": "الأراضي المخصصة لزراعة الكتلة الحيوية لإزالة ثاني أكسيد الكربون—مساحة",
  "graph_117_title": "الأرض من أجل زراعة الكتلة الحيوية لإزالةCO<sub>2</sub>",
  "graph_118_title": "الأراضي للزراعة مع إزالة ثاني أكسيد الكربون",
  "graph_119_title": "المواد الخام للتمعدن",
  "graph_120_menu_title": "% استهلاك الكهرباء من مصادر منخفضة الكربون",
  "graph_120_title": "% استهلاك الكهرباء من مصادر منخفضة الكربون",
  "graph_121_title": "الأراضي المخصصة للزراعة مع إزالة Acres - CO<sub>2</sub>",
  "graph_124_menu_title": "الأراضي المخصصة لزراعة الكتلة الحيوية لإزالة ثاني أكسيد الكربون—مساحة",
  "graph_124_title": "أراضي زراعة الكتلة الحيوية لإزالة Acres - CO<sub>2</sub>",
  "graph_125_title": "انخفاض الناتج المحلي الإجمالي مقابل درجة الحرارة",
  "graph_126_title": "انخفاض الناتج المحلي من التأثيرات المناخية",
  "graph_127_title": "سعة نقل ثاني أكسيد الكربون",
  "graph_128_menu_title": "ثاني أكسيد الكربون التراكمي المخزن تحت الأرض—مساحة",
  "graph_128_title": "ثاني أكسيد الكربون التراكمي المخزن تحت الأرض",
  "graph_129_title": "الخسارةفي الناتج الإجمالي العالمي",
  "graph_130_title": "معدل نمو نصيب الفرد من الناتج المحلي الإجمالي",
  "graph_132_title": "تاريخ التكلفة الحدية للكهرباء الشمسية",
  "graph_133_title": "تاريخ الطلب على الطاقة الأولية فحم نفط غاز",
  "graph_134_title": "تاريخ الطلب على الطاقة الأولية للرياح و الشمس",
  "graph_135_title": "تاريخ صافي انبعاثات غازات الاحتباس الحراري",
  "graph_138_title": "% لاستهلاك الكهرباء من المصادر المؤهلة",
  "graph_139_menu_title": "التكلفة الاجتماعية للكربون - جدول",
  "graph_139_title": "التكلفة الاجتماعية للكربون",
  "graph_140_mini_title": "ارتفاع مستوى سطح البحر",
  "graph_140_title": "ارتفاع مستوى البحر - خريطة خطر الفيضانات",
  "graph_141_title": "احتمالية صيف خالي من الجليد في القطب الشمالي",
  "graph_142_title": "السكان المعرضون لارتفاع مستوى سطح البحر",
  "graph_143_title": "انخفاض غلة المحاصيل من الاحتباس الحراري",
  "graph_144_title": "الأنواع التي تفقد أكثر من 50٪ من النطاق المناخي",
  "graph_145_title": "الوفيات الناجمة عن الحرارة الشديدة حسب المنطقة",
  "graph_146_title": "انبعاثات الكربون التراكمية من الطاقة الحيوية للغابات",
  "graph_147_title": "مساحة الغابات حسب العمر",
  "graph_148_title": "مساحة الغابات",
  "graph_149_title": "مساحة الأراضي الزراعية",
  "graph_151_menu_title": "الطلب على الطاقة الأولية للطاقة الحيوية حسب المواد الأولية—مساحة",
  "graph_151_title": "الطلب الأولي على الطاقة الحيوية حسب المواد الأولية",
  "graph_152_menu_title": "انبعاثات الميثان حسب المصدر—المساحة",
  "graph_152_title": "انبعاثات الميثان حسب المصدر",
  "graph_153_menu_title": "انبعاثات أكسيد النيتروز حسب المصدر—مساحة",
  "graph_153_title": "انبعاثات أكسيد النيتروس حسب المصدر",
  "graph_154_title": "إجمالي انبعاثات الكربون من الطاقة الحيوية الحرجية",
  "graph_156_title": "صافي انبعاثات الكربون من الطاقة الحيوية الحرجية",
  "graph_157_menu_title": "عمليات إزالة ثاني أكسيد الكربون حسب النوع—مساحة",
  "graph_157_title": "عمليات إزالة ثاني أكسيد الكربون حسب النوع",
  "graph_159_menu_title": "الطاقة الأولية من الوقود بما في ذلك احتجاز ثاني أكسيد الكربون وتخزينه—مساحة",
  "graph_159_title": "الطاقة الأولية من الوقود بما في ذلك احتجاز ثاني أكسيد الكربون وتخزينه",
  "graph_160_menu_title": "الطاقة الكهربائية الأولية بما في ذلك احتجاز ثاني أكسيد الكربون وتخزينه—مساحة",
  "graph_160_title": "الطاقة الكهربائية الأولية بما في ذلك احتجاز ثاني أكسيد الكربون وتخزينه",
  "graph_161_menu_title": "ثاني أكسيد الكربون المحتجز بواسطة CCS حسب المصدر—مساحة",
  "graph_161_title": "ثاني أكسيد الكربون الملتقط بواسطة CCS حسب المصدر",
  "graph_163_title": "عمليات إزالة ثاني أكسيد الكربون من اليابسة",
  "graph_164_menu_title": "ثاني أكسيد الكربون المنبعث من الفحم والمحتجز بواسطة CCS—مساحة",
  "graph_164_title": "ثاني أكسيد الكربون المنبعث من الفحم والمحتجز بواسطة CCS",
  "graph_165_menu_title": "ثاني أكسيد الكربون المنبعث من النفط—مساحة",
  "graph_165_title": "ثاني أكسيد الكربون المنبعث من النفط",
  "graph_166_menu_title": "ثاني أكسيد الكربون المنبعث من الغاز والمحتجز بواسطة احتجاز ثاني أكسيد الكربون وتخزينه (CCS)—مساحة",
  "graph_166_title": "ثاني أكسيد الكربون المنبعث من الغاز والمحتجز بواسطة CCS",
  "graph_168_title": "انبعاثات ثاني أكسيد الكربون من الوقود الأحفوري",
  "graph_169_title": "إزالة الغابات",
  "graph_171_title": "الكثافة الكربونية للغابات",
  "graph_175_menu_title": "إزالة الغابات وتدهور الغابات تامة النمو - المساحة",
  "graph_175_title": "إزالة الغابات وتدهور الغابات تامة النمو",
  "graph_177_menu_title": "الأراضي المستغلة لإنتاج الطاقة الحيوية - المساحة",
  "graph_177_title": "الأراضي المستغلة لإنتاج الطاقة الحيوية",
  "graph_178_title": "إزالة الغابات وتدهور الغابات مكتملة النمو",
  "graph_183_title": "إنتاجية المحاصيل",
  "graph_185_title": "النسبة المئوية للغذاء من الحيوانات",
  "graph_191_menu_title": "إجمالي انبعاثات ثاني أكسيد الكربون من الغابات - المساحة",
  "graph_191_title": "إجمالي انبعاثات ثاني أكسيد الكربون من الغابات",
  "graph_192_title": "تكلفة احتجاز ثاني أكسيد الكربون الأحفوري وتخزينه",
  "graph_194_title": "الطاقة المستخدمة في احتجاز الكربون وتخزينه",
  "graph_195_title": "الطاقة الأولية مع احتجاز ثاني أكسيد الكربون وتخزينه حسب المصدر",
  "graph_196_title": "الحصة الكهربائية من مبيعات وسائل النقل",
  "graph_197_title": "حصة الكهربة من مبيعات معدات الصناعة والمباني",
  "graph_204_menu_title": "ثاني أكسيد الكربون المنبعث من الطاقة الحيوية والمحتجز بواسطة CCS—مساحة",
  "graph_204_title": "ثاني أكسيد الكربون المنبعث من الطاقة الحيوية والمحتجز بواسطة CCS",
  "graph_205_title": "إجمالي التكلفة السنوية لاحتجاز الكربون وتخزينه",
  "graph_207_menu_title": "الطلب الأولي على الطاقة من الفحم حسب الاستخدام وCCS—مساحة",
  "graph_207_title": "الطلب الأولي على الطاقة من الفحم حسب الاستخدام وCCS",
  "graph_208_menu_title": "الطلب الأولي على الطاقة من الغاز الطبيعي حسب الاستخدام وCCS—مساحة",
  "graph_208_title": "الطلب الأولي على الطاقة من الغاز الطبيعي حسب الاستخدام وCCS",
  "graph_209_menu_title": "الطلب الأولي على الطاقة الحيوية حسب الاستخدام وCCS—مساحة",
  "graph_209_title": "الطلب الأولي على الطاقة الحيوية حسب الاستخدام وCCS",
  "graph_211_menu_title": "الكربون في الغابات - المساحة",
  "graph_211_title": "الكربون في الغابات",
  "graph_214_title": "نسبة تكلفة النقل العامل بالكهرباء إلى الذي يعمل بالنفط",
  "graph_215_title": "نسبة كلفة المعدات العاملة بالكهرباء إلى العاملة بالوقود",
  "graph_220_caption_1850": "عند <span class=\"caption-value\">{temperature}</span><br> من المحتمل وقوع<br> أحداث الحرارة الشديدة<br> في <span class=\"caption-value\">1</span> من أصل 50 سنة ",
  "graph_220_caption_future": "عند درجة الحرارة <span class=\"caption-value\">{temperature}</span><br>من المحتمل حدوث <br>أحداث الحرارة الشديدة<br> في <span class=\"caption-value\">{years} </span> من أصل 50 سنة ",
  "graph_220_caption_today": "عند درجة الحرارة<span class=\"caption-value\">{temperature}</span><br>من المحتمل حدوث<br>أحداث الحرارة الشديدة<br> في <span class=\"caption-value\">{years}</span> من أصل 50 سنة ",
  "graph_220_title": "تواتر الحرارة الشديدة",
  "graph_224_title": "السعر السوقي للنفط",
  "graph_225_title": "السعر السوقي للغاز الطبيعي",
  "graph_227_title": "تكلفة الاحتجاز المباشر للكربون من الهواء وتخزينه",
  "graph_228_title": "تكلفة احتجاز ثاني أكسيد الكربون وتخزينه من الطاقة الحيوية",
  "graph_230_title": "تركيز الميثان",
  "graph_233_menu_title": "سعة تخزين الطاقة التي تم تركيبها حسب التكنولوجيا—مساحة",
  "graph_233_title": "سعة التخزين المثبتة للطاقة حسب التكنولوجيا",
  "graph_234_menu_title": "سعة تخزين الطاقة التي تم تركيبها حسب المدة الزمنية—مساحة",
  "graph_234_title": "سعة التخزين المثبتة للطاقة حسب المدة",
  "graph_235_title": "متوسط التكلفة المستوية لتخزين الطاقة",
  "graph_246_title": "الطاقة الأولية من الوقود الأحفوري",
  "graph_247_menu_title": "الاستهلاك النهائي للطاقة المتجددة حسب النوع—مساحة",
  "graph_247_title": "الاستهلاك النهائي للطاقة المتجددة حسب النوع",
  "graph_249_title": "% استهلاك الكهرباء من مصادر الطاقة المتجددة المتغيرة",
  "graph_251_title": "أيام الحرارة الشديدة—خريطة",
  "graph_252_title": "أيام خطر حرائق الغابات من الاحتباس الحراري—خريطة",
  "graph_253_title": "أيام الرطوبة والحرارة الشديدة—خريطة",
  "graph_257_title": "تحولات النظام البيئي من الاحتباس الحراري",
  "graph_258_title": "نصيب الفرد من انبعاثات غاز الميثان",
  "graph_259_title": "كثافة الميثان في الناتج المحلي الإجمالي",
  "graph_260_title": "كثافة غاز الميثان في الزراعة",
  "graph_261_title": "إجمالي الإنتاج الزراعي",
  "graph_262_title": "كثافة غاز الميثان للطاقة الأولية",
  "graph_263_title": "كثافة غاز الميثان للنفايات",
  "graph_265_menu_title": "انبعاثات الميثان من الطاقة حسب المصدر—مساحة",
  "graph_265_title": "انبعاثات الميثان من الطاقة حسب المصدر",
  "graph_269_title": "توسع الأراضي القاحلة من الاحتباس الحراري",
  "graph_270_title": "السكان المعرضون للأعاصير",
  "graph_275_title": "الوفيات الناجمة عن الحرارة الشديدة",
  "graph_278_title": "فقدان الحياة في المحيطات بسبب الاحتباس الحراري",
  "graph_279_title": "خطر انقراض أنواع الكائنات المتوطنة",
  "graph_280_title": "خسائر العمالة الخارجية من الحرارة الشديدة",
  "graph_281_title": "التعرض الإضافي للملاريا وحمى الضنك بسبب الاحتباس الحراري",
  "graph_282_menu_title": "انبعاثات الغازات المفلورة حسب النوع—مساحة",
  "graph_282_title": "انبعاثات الغازات المفلورة حسب النوع",
  "graph_283_menu_title": "انبعاثات الغازات المفلورة التراكمية—مساحة",
  "graph_283_title": "انبعاثات الغازات المفلورة التراكمية",
  "graph_284_title": "سعر السوق للفحم",
  "graph_285_title": "سعر السوق للطاقة الحيوية",
  "graph_287_title": "انخفاض القيمة الغذائية للمحاصيل بسبب تركيز ثاني أكسيد الكربون",
  "graph_289_title": "الاستهلاك النهائي للطاقة الكهربائية",
  "graph_292_title": "السكان المعرضون لفيضان الأنهار",
  "graph_300_title": "احتمالية الجفاف الممتد—خريطة",
  "graph_actions_menu__copy_data_to_clipboard": "نسخ البيانات إلى الحافظة",
  "graph_actions_menu__hide_description": "إخفاء الوصف",
  "graph_actions_menu__hide_no_impact_from_temp": "إخفاء ”لا تأثير من درجة الحرارة“",
  "graph_actions_menu__hide_un_pledges": "إخفاء تعهدات الأمم المتحدة (NDCs)",
  "graph_actions_menu__show_description": "إظهار الوصف",
  "graph_actions_menu__show_no_impact_from_temp": "إظهار ”لا تأثير من درجة الحرارة“",
  "graph_actions_menu__show_un_pledges": "إظهار تعهدات الأمم المتحدة (NDCs)",
  "graph_actions_menu__view_in_new_window": "عرض في نافذة جديدة",
  "graph_actions_menu__view_larger": "اعرض بشكل أكبر",
  "graph_dataset_label__0_50_years": "من صفر إلى 50 عام",
  "graph_dataset_label__50_100_years": "من 50 إلى 100 عام",
  "graph_dataset_label__66pct_chance_of_2degrees_c_or_15degrees_c": "66٪ فرصة 2 أو 1.5 درجة مئوية",
  "graph_dataset_label__afforestation_and_reforestation": "التشجير",
  "graph_dataset_label__ag_soil_carbon": "كربون التربة الزراعية",
  "graph_dataset_label__agricultural_soil_carbon": "كربون التربة الزراعية",
  "graph_dataset_label__agriculture": "الزراعة",
  "graph_dataset_label__all_countries_follow_ndcs": "كلّ الدول تتبع المساهمات المحددة وطنيًا",
  "graph_dataset_label__area_of_india": "منطقة الهند",
  "graph_dataset_label__area_of_sahara_desert": "مساحة الصحراء الكبرى",
  "graph_dataset_label__area_of_south_america": "منطقة أمريكا الجنوبية",
  "graph_dataset_label__at_risk_to_annual_flooding_in_millions": "معرض لخطر الفيضانات السنوية<br>(ملايين)",
  "graph_dataset_label__australia": "أستراليا",
  "graph_dataset_label__baseline": "الخط المرجعي",
  "graph_dataset_label__baseline_in_2100": "الخط المرجعي في 2100",
  "graph_dataset_label__beccs": "الطاقة الحيوية مع CCS",
  "graph_dataset_label__biochar": "الفحم النباتي",
  "graph_dataset_label__bioenergy": "الطاقة الحيوية",
  "graph_dataset_label__birds": "طيور",
  "graph_dataset_label__buildings_and_industry_electric": "المباني والصناعة (كهرباء)",
  "graph_dataset_label__buildings_and_industry_fuel": "المباني والصناعة ( المستخدمة للوقود)",
  "graph_dataset_label__burke_2015": "بورك 2015",
  "graph_dataset_label__burke_2018_default": "بورك 2018 (الإعدادات المسبقة)",
  "graph_dataset_label__butterflies_and_moths": "الفراشات والعث",
  "graph_dataset_label__captured_by_ccs": "تم التقاطه بواسطة CCS",
  "graph_dataset_label__carbon_in_plants": "الكربون في النباتات",
  "graph_dataset_label__carbon_in_soils": "الكربون في التربة",
  "graph_dataset_label__central_america": "أمريكا الوسطى",
  "graph_dataset_label__central_europe": "أوروبا الوسطى",
  "graph_dataset_label__ch4": "الميثان CH4",
  "graph_dataset_label__cheapest_storage": "التخزين الأرخص",
  "graph_dataset_label__china": "الصين",
  "graph_dataset_label__co2_emissions": "انبعاثات ثاني أكسيد الكربون",
  "graph_dataset_label__co2_removals": "عمليات إزالة ثاني أوكسيد الكاربون",
  "graph_dataset_label__co2_transport_capacity": "سعة نقل ثاني أكسيد الكربون",
  "graph_dataset_label__coal": "الفحم",
  "graph_dataset_label__coal_ccs": "احتجاز ثاني أكسيد الكربون وتخزينه من الفحم",
  "graph_dataset_label__coal_production": "إنتاج الفحم",
  "graph_dataset_label__cost_parity": "تكافؤ التكلفة",
  "graph_dataset_label__costs_of_subsidies": "تكاليف الدعم",
  "graph_dataset_label__crops": "المحاصيل",
  "graph_dataset_label__current_scenario": "السيناريو الحالي",
  "graph_dataset_label__current_scenario_discounted": "السيناريو الحالي—مخصوم",
  "graph_dataset_label__current_scenario_in_2100": "السيناريو الحالي في عام 2100",
  "graph_dataset_label__daccs": "الاحتجاز المباشر للهواء مع تخزين الكربون",
  "graph_dataset_label__daily": "يومي",
  "graph_dataset_label__deforestation": "إزالة الغابات",
  "graph_dataset_label__degradation___bioenergy": "التدهور - الطاقة الحيوية",
  "graph_dataset_label__degradation___fires_from_warming": "التدهور - الحرائق الناجمة عن الاحتباس الحراري",
  "graph_dataset_label__degradation___wood_products": "التدهور - المنتجات الخشبية",
  "graph_dataset_label__dengue": "حمى الضنك",
  "graph_dataset_label__dietz_and_stern": "العالمان ديتز و ستيرن",
  "graph_dataset_label__dragonflies_and_damselflies": "اليعسوب ودامليليس",
  "graph_dataset_label__east_asia": "شرق آسيا",
  "graph_dataset_label__electric": "كهربائي",
  "graph_dataset_label__electric_with_ccs": "كهربائي مع نظام احتجاز ثاني أكسيد الكربون",
  "graph_dataset_label__emissions": "الانبعاثات",
  "graph_dataset_label__emissions_baseline": "خط أساس الانبعاثات",
  "graph_dataset_label__en_roads_baseline": "خط الأساس En-ROADS",
  "graph_dataset_label__en_roads_coal": "En-ROADS فحم",
  "graph_dataset_label__en_roads_gas": "En-ROADS غاز",
  "graph_dataset_label__en_roads_ghg_net_emissions": "En-ROADSصافي انبعاثات GHG",
  "graph_dataset_label__en_roads_oil": "En-ROADS النفط",
  "graph_dataset_label__en_roads_solar": "En-ROADS الطاقة الشمسية",
  "graph_dataset_label__en_roads_wind": "En-ROADS طاقة الرياح",
  "graph_dataset_label__energy_production": "إنتاج الطاقة",
  "graph_dataset_label__eu": "الاتحاد الأوروبي",
  "graph_dataset_label__f_gases": "الغازات المفلورة (F-gases)",
  "graph_dataset_label__farmland": "الأراضي الزراعية",
  "graph_dataset_label__forest": "الغابات",
  "graph_dataset_label__fossil_ccs": "احتباس ثاني أكسيد الكربون الأحفوري",
  "graph_dataset_label__fossil_fuel_co2": "ثاني أكسيد الكربون من الوقود الأحفوري",
  "graph_dataset_label__fuel": "الوقود",
  "graph_dataset_label__fuel_with_ccs": "الوقود مع احتجاز ثاني أكسيد الكربون وتخزينه",
  "graph_dataset_label__gas": "الغاز",
  "graph_dataset_label__gas_ccs": "احتجاز ثاني أكسيد الكربون وتخزينه من الغاز",
  "graph_dataset_label__geothermal": "الحرارة الأرضية",
  "graph_dataset_label__global": "عالمي",
  "graph_dataset_label__global_gdp_in_2022": "GDP العالمي في 2022",
  "graph_dataset_label__gross_co2_removals": "إجمالي إزالة ثاني أكسيد الكربون",
  "graph_dataset_label__hfc": "مركبات الكربون الهيدروفلورية(HFC)",
  "graph_dataset_label__hfc_follows_kigali": "HFC يتبع كيغالي",
  "graph_dataset_label__historical_ghg_net_emissions": "صافي انبعاثات غازات الدفيئة التاريخية",
  "graph_dataset_label__hourly": "بالساعة",
  "graph_dataset_label__howard_and_sterner": "هاورد وسترنر",
  "graph_dataset_label__hydro": "مائي",
  "graph_dataset_label__hydrogen_storage": "تخزين الهيدروجين",
  "graph_dataset_label__iea": "وكالة الطاقة الدولية",
  "graph_dataset_label__iea_coal": "IEA الفحم",
  "graph_dataset_label__iea_gas": "IEA الغاز",
  "graph_dataset_label__iea_oil": "IEA النفط",
  "graph_dataset_label__iea_solar": "IEA الطاقة الشمسية",
  "graph_dataset_label__iea_wind": "IEA الرياح",
  "graph_dataset_label__in_2100": "في عام 2100",
  "graph_dataset_label__india": "الهند",
  "graph_dataset_label__industrial_processes": "العمليات الصناعية",
  "graph_dataset_label__industry": "القطاع الصناعي",
  "graph_dataset_label__insects": "الحشرات",
  "graph_dataset_label__invertebrates": "اللافقاريات",
  "graph_dataset_label__irena": "ايرينا",
  "graph_dataset_label__land_removals": "إزالة الأراضي",
  "graph_dataset_label__land_species": "الكائنات البرية",
  "graph_dataset_label__land_use_co2": "CO2 من استخدامات الأراضي",
  "graph_dataset_label__lazard": "شركة لازارد",
  "graph_dataset_label__living_below_high_tide_line_in_millions": "الذين يعيشون تحت خط المد العالي<br>(ملايين)",
  "graph_dataset_label__low_carbon_sources": "المصادر منخفضة الكربون",
  "graph_dataset_label__maize": "الذرة",
  "graph_dataset_label__malaria": "الملاريا",
  "graph_dataset_label__mammals": "الثدييات",
  "graph_dataset_label__marine_animal": "الكائنات البحرية",
  "graph_dataset_label__marine_species": "الكائنات البحرية",
  "graph_dataset_label__met_office": "مكتب الارصاد الجوية البريطاني",
  "graph_dataset_label__mineralization": "التمعدن",
  "graph_dataset_label__mineralization_rock": "تمعدن الصخور",
  "graph_dataset_label__montreal_gases": "غازات مونتريال",
  "graph_dataset_label__more_than_100_years": "أكثر من 100 عام",
  "graph_dataset_label__n2o": "N2O",
  "graph_dataset_label__nasa": "ناسا",
  "graph_dataset_label__nasa_upper_per_lower_95pct": "ناسا علوي / سفلي 95٪",
  "graph_dataset_label__natural_gas_pipeline_capacity": "سعة خطوط أنابيب الغاز الطبيعي",
  "graph_dataset_label__net_bioenergy": "صافي الطاقة الحيوية",
  "graph_dataset_label__net_revenue_minus_costs": "الصافي: الإيرادات ناقص التكاليف",
  "graph_dataset_label__new_zero": "الصفر الجديد",
  "graph_dataset_label__new_zero_carbon_baseline": "خط المرجع لصفر-كربون جديد",
  "graph_dataset_label__north_america": "أمريكا الشمالية",
  "graph_dataset_label__northern_europe": "شمال أوروبا",
  "graph_dataset_label__nuclear": "الطاقة النووية",
  "graph_dataset_label__nuclear_baseline": "خط المرجع النووي",
  "graph_dataset_label__ocean_removals": "عمليات الإزالة من المحيطات",
  "graph_dataset_label__oil": "النفط",
  "graph_dataset_label__other_cdr": "CDR أخرى",
  "graph_dataset_label__other_developed": "غيرها من المتقدمة",
  "graph_dataset_label__other_developing": "النامية الأخرى",
  "graph_dataset_label__other_renewables": "مصادر الطاقة المتجددة الأخرى",
  "graph_dataset_label__other_storage": "وسائل تخزين أخرى",
  "graph_dataset_label__pfc": "الهيدروكربون المشبع بالفلور",
  "graph_dataset_label__phytoplankton": "العوالق النباتية",
  "graph_dataset_label__plants": "النباتات",
  "graph_dataset_label__price": "السعر",
  "graph_dataset_label__price_plus_taxes_minus_subsidies": "السعر زائد الضرائب ناقص الدعم",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_at_least_once_before_2100": "احتمالية صيف خالي من الجليد في القطب الشمالي <br> مرة واحدة على الأقل قبل 2100",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2050": "احتمال صيف خالي من الجليد في القطب الشمالي<br>في 2050",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2100": "احتمال صيف خالي من الجليد في القطب الشمالي<br>في 2100",
  "graph_dataset_label__renewables": "المصادر المتجددة",
  "graph_dataset_label__revenue_from_taxes": "الإيرادات من الضرائب",
  "graph_dataset_label__rice": "الأرز",
  "graph_dataset_label__scenario_if_no_economic_impact_from_temp": "سيناريو عدم تأثير الحرارة على الاقتصاد",
  "graph_dataset_label__seasonal": "موسمي",
  "graph_dataset_label__sf6": "SF6",
  "graph_dataset_label__solar": "شمسي",
  "graph_dataset_label__south_america": "أمريكا الجنوبية",
  "graph_dataset_label__southeast_asia": "جنوب شرق آسيا",
  "graph_dataset_label__southern_africa": "جنوب القارة الأفريقية",
  "graph_dataset_label__southern_europe": "جنوب اوروبا",
  "graph_dataset_label__soybean": "فول الصويا",
  "graph_dataset_label__storage_cost": "تكلفة التخزين",
  "graph_dataset_label__today": "اليوم",
  "graph_dataset_label__transport_electric": "النقل (كهربائي)",
  "graph_dataset_label__transport_fuel": "النقل (الوقود)",
  "graph_dataset_label__us": "الولايات المتحدة",
  "graph_dataset_label__us_gdp_in_2022": "الولايات المتحدة<br>GDP في 2022",
  "graph_dataset_label__vertebrates": "الفقاريات",
  "graph_dataset_label__waste": "النفايات",
  "graph_dataset_label__waste_per_other": "النفايات/غير ذلك",
  "graph_dataset_label__west_asia": "غرب آسيا",
  "graph_dataset_label__wheat": "القمح",
  "graph_dataset_label__wind": "رياح",
  "graph_dataset_label__wind_and_solar": "الرياح والطاقة الشمسية",
  "graph_dataset_label__wind_and_solar_cost": "تكلفة الرياح والطاقة الشمسية",
  "graph_dataset_label__with_ccs": "مع احتجاز ثاني أكسيد الكربون وتخزينه",
  "graph_dataset_label__without_ccs": "دون احتجاز ثاني أكسيد الكربون وتخزينه",
  "graph_dataset_label__wood": "الأخشاب",
  "graph_dataset_label__zooplankton": "العوالق الحيوانية",
  "graph_menu__favorites_empty_detail": "انقر على النجمة بجوار أي رسم بياني لبدء حفظ مفضلاتك.",
  "graph_menu__favorites_empty_title": "لا توجد مفضلات بعد",
  "graph_menu__favorites_title": "المفضلة لديك",
  "graph_menu__search_empty_title": "لم يتم العثور على نتائج",
  "graph_menu__search_placeholder": "البحث في الرسوم البيانية",
  "graph_menu__view_as_grid": "عرض كشبكة",
  "graph_menu__view_as_list": "العرض كقائمة",
  "graph_menu_grouping__agriculture": "الزراعة",
  "graph_menu_grouping__atmosphere": "الغلاف الجوي",
  "graph_menu_grouping__carbon_capture_and_storage": "احتجاز الكربون وتخزينه",
  "graph_menu_grouping__consumer_prices": "أسعار المستهلك",
  "graph_menu_grouping__ecosystems_and_biodiversity": "النظم البيئية والتنوع البيولوجي",
  "graph_menu_grouping__emissions_from_energy_and_industrial_processes": "الانبعاثات من الطاقة والعمليات الصناعية",
  "graph_menu_grouping__emissions_from_land_use": "الانبعاثات من استخدام الأراضي",
  "graph_menu_grouping__extreme_weather": "الأحوال الجوية القاسية",
  "graph_menu_grouping__fluorinated_gases": "الغازات المفلورة",
  "graph_menu_grouping__forestry": "الغابات",
  "graph_menu_grouping__general": "عام",
  "graph_menu_grouping__health_and_economy": "الصحة والاقتصاد",
  "graph_menu_grouping__land_use": "استخدامات الأراضي",
  "graph_menu_grouping__methane": "الميثان",
  "graph_menu_grouping__nitrous_oxide": "أكسيد النيتروس",
  "graph_menu_grouping__oceans": "المحيطات",
  "graph_menu_grouping__production_costs": "تكاليف الإنتاج",
  "graph_menu_grouping__totals": "الإجمالي",
  "graph_value__percent": "{num}٪",
  "graph_xaxis_label__temperature_change_from_1850___degrees_celsius": "تغير درجة الحرارة من 1850 — درجة مئوية",
  "graph_yaxis_label__billion_dollars_per_year": "مليار دولار/السنة",
  "graph_yaxis_label__billion_tons_per_year": "مليار طن/سنة",
  "graph_yaxis_label__billions_of_people": "مليار إنسان",
  "graph_yaxis_label__ch4_parts_per_million_ppm": "تركيز الميثان CH4 (جزء في المليون)",
  "graph_yaxis_label__co2_equivalent_parts_per_million_ppm": "أجزاء مكافئة من CO2 في المليون",
  "graph_yaxis_label__co2_parts_per_million_ppm": "أجزاء CO2 في المليون (ppm)",
  "graph_yaxis_label__days_per_year_per_worker": "يوم/عامل/السنة",
  "graph_yaxis_label__deaths_per_100000_people_per_year": "عدد الوفيات لكل 100,000 شخص/السنة",
  "graph_yaxis_label__degrees_celsius": "درجة مئوية",
  "graph_yaxis_label__degrees_fahrenheit": "درجة فهرنهايت",
  "graph_yaxis_label__dollars_per_barrel": "دولار/برميل",
  "graph_yaxis_label__dollars_per_boe": "$/ برميل النفط المكافئ",
  "graph_yaxis_label__dollars_per_gigajoule": "$/جيجاجول",
  "graph_yaxis_label__dollars_per_kwh": "$/كيلوواط ساعة",
  "graph_yaxis_label__dollars_per_mcf": "$/ مليون قدم مكعب",
  "graph_yaxis_label__dollars_per_mwh": "$/ميغاواط ساعة",
  "graph_yaxis_label__dollars_per_person_per_year": "$/شخص/سنة",
  "graph_yaxis_label__dollars_per_ton": "دولار/طن",
  "graph_yaxis_label__dollars_per_ton_co2": "$/طن CO2",
  "graph_yaxis_label__exajoule_per_trillion_dollars": "إكساجول/ تريليون $",
  "graph_yaxis_label__exajoules": "إكساجول",
  "graph_yaxis_label__exajoules_per_year": "إكساجول / سنة",
  "graph_yaxis_label__exposure_per_100000_people_per_year": "نسبة التعرض لكل 100,000 شخص/السنة",
  "graph_yaxis_label__feet_ft": "قدم (قدم)",
  "graph_yaxis_label__gigatons_c": "جيجا طن كربون",
  "graph_yaxis_label__gigatons_co2": "جيجاتون CO2",
  "graph_yaxis_label__gigatons_co2_equivalent": "جيجا طن من مكافئ ثاني أكسيد الكربون",
  "graph_yaxis_label__gigatons_co2_equivalent_per_year": "جيغا طن CO2 مكافئ/ السنة",
  "graph_yaxis_label__gigatons_co2_per_year": "جيجا طن CO2 / سنة",
  "graph_yaxis_label__gigatons_produced_per_year": "جيجا طن منتج سنوياً",
  "graph_yaxis_label__kg_ch4_per_ton_of_waste": "كجم من الميثان/طن من النفايات",
  "graph_yaxis_label__kg_ch4_per_ton_produced": "كجم من الميثان/طن من الإنتاج",
  "graph_yaxis_label__kg_ch4_per_year_per_person": "كجم من الميثان/سنوياً/شخص",
  "graph_yaxis_label__kg_per_year_per_hectare": "كجم/سنة/هكتار",
  "graph_yaxis_label__kilograms_co2_per_mwh": "كجم CO2 / ميغاواط ساعة",
  "graph_yaxis_label__kilotons_ch4_per_exajoule": "كيلوطن من الميثان لكل إكساجول",
  "graph_yaxis_label__megatons_ch4_per_year": "ميغا طن CH4/سنة",
  "graph_yaxis_label__megatons_co2_per_exajoule": "ميغاطن CO2/إكساجول",
  "graph_yaxis_label__megatons_nitrogen_per_year": "ميجا طن نيتروجين سنوياً",
  "graph_yaxis_label__megatons_pm25_per_year": "ميغاطن PM2.5/سنة",
  "graph_yaxis_label__meters_m": "متر (م)",
  "graph_yaxis_label__million_acres": "مليون acres",
  "graph_yaxis_label__million_hectares": "مليون هكتار",
  "graph_yaxis_label__million_hectares_per_year": "مليون هكتار سنوياً",
  "graph_yaxis_label__millions_of_people_per_year": "ملايين الأشخاص/السنة",
  "graph_yaxis_label__pct_reduction_in_gdp": "٪ انخفاض في الناتج المحلي الإجمالي",
  "graph_yaxis_label__percent": "نسبه مئويه",
  "graph_yaxis_label__percent_loss": "نسبة الخسارة المئوية",
  "graph_yaxis_label__percent_of_species": "النسبة المئوية من الأنواع",
  "graph_yaxis_label__percent_per_year": "النسبة المئوية / سنة",
  "graph_yaxis_label__ph": "pH",
  "graph_yaxis_label__ratio": "النسبة",
  "graph_yaxis_label__tons_ch4_per_million_dollars_gdp": "طن من الميثان/مليون $ من الناتج المحلي",
  "graph_yaxis_label__tons_co2_per_million_dollars_gdp": "طن CO2/مليون دولار GDP",
  "graph_yaxis_label__tons_co2_per_year_per_person": "طن CO2 / سنة / شخص",
  "graph_yaxis_label__tonsc_per_hectare": "طن من الكربون لكل هكتار",
  "graph_yaxis_label__trillion_cubic_meters_per_year": "تريليون متر مكعب/السنة",
  "graph_yaxis_label__trillion_dollars_per_year": "تريليون $/ سنة",
  "input_001_label": "الفحم (ضريبة / دعم)",
  "input_002_label": "سنة بدأ ضريبة/دعم الفحم",
  "input_003_label": "سنة توقف ضريبة/دعم الفحم",
  "input_004_label": "تسريع تقاعد محطات الفحم",
  "input_007_label": "النفط (ضريبة / دعم)",
  "input_008_label": "سنة بدء دعم/ ضريبة النفط",
  "input_009_label": "سنة توقف ضريبة/دعم النفط",
  "input_010_label": "الغاز الطبيعي (الضرائب/الدعم)",
  "input_011_label": "سنة بدء الدعم/ الضريبة للغاز الطبيعي",
  "input_012_label": "سنة وقف الدعم/ الضريبة للغاز الطبيعي",
  "input_016_label": "المصادر المتجددة (ضريبة / دعم)",
  "input_017_label": "سنة بدء دعم/ ضريبة الطاقة المتجددة",
  "input_018_label": "سنة توقف ضريبة/دعم الطاقة المتجددة",
  "input_019_label": "تحقيق طفرة في خفض تكاليف الطاقة المتجددة",
  "input_020_label": "سنة الاختراق التكنولوجي للطاقة المتجددة",
  "input_021_label": "طفرة في خفض تكلفة تقنيات التخزين الأخرى",
  "input_022_label": "سنة الاختراق التكنولوجي لتقنيات التخزين الأخرى",
  "input_023_label": "الطاقة الحيوية (ضريبة / دعم)",
  "input_024_label": "سنة بدء دعم/ ضريبة الطاقة الحيوية",
  "input_025_label": "سنة توقف ضريبة / دعم الطاقة الحيوية",
  "input_026_label": "طفرة في خفض تكلفة الطاقة الحيوية",
  "input_027_label": "سنة الاختراق التكنولوجي للطاقة الحيوية",
  "input_030_label": "الطاقة النووية (ضريبة / دعم)",
  "input_031_label": "سنة بدء دعم/ ضريبة الطاقة النووية",
  "input_032_label": "سنة توقف ضريبة/دعم الطاقة النووية",
  "input_033_label": "خفض تكلفة البحث والتطوير للطاقة النووية",
  "input_034_label": "سنة الاختراق التكنولوجي للطاقة النووية",
  "input_035_label": "سنة الاختراق التكنولوجي لصفر-كربون جديد",
  "input_036_label": "سنة الاختراق التكنولوجي لصفر-كربون جديد",
  "input_037_label": "الوقت اللازم لتسويق تكنولوجيا صفر-كربون جديدة",
  "input_038_label": "التكلفة الأولية بالنسبة للفحم",
  "input_039_label": "سعر الكربون",
  "input_040_label": "السنة التي يبدأ فيها تسعير الكربون",
  "input_041_label": "السنوات لتحقيق سعر الكربون الأولي",
  "input_042_label": "سعر الكربون النهائي (اضبط \"سنة البدء ...\" أدناه)",
  "input_043_label": "السنة للبدء في تحقيق سعر الكربون النهائي",
  "input_044_label": "السنوات لتحقيق سعر الكربون النهائي",
  "input_045_label": "معيار كفاءة الانبعاثات",
  "input_046_label": "سنة البدء بتطبيق معيار كفاءة الانبعاثات",
  "input_047_label": "كفاءة الطاقة في المباني الجديدة والصناعة",
  "input_048_label": "سنة البدء",
  "input_050_label": "كفاءة الطاقة في النقل الجديد",
  "input_051_label": "سنة البدء",
  "input_053_action_label": "حد مبيعات وسائل النقل التي تعمل بالوقود - الطرق والسكك الحديدية",
  "input_053_label": "حد مبيعات وسائل النقل التي تعمل بالوقود",
  "input_054_action_label": "عام بدء سياسة الكهربة - الطرق والسكك الحديدية",
  "input_054_label": "عام بدء سياسة الكهربة",
  "input_055_label": "حد مبيعات المعدات التي تعمل بالوقود",
  "input_056_label": "سنة بدء سياسات الكهربة",
  "input_057_label": "إزالة الغابات وتدهور الغابات مكتملة النمو (تقليل/زيادة)",
  "input_060_label": "الميثان وأكسيد االنيتروس من الزراعة",
  "input_061_label": "غاز الميثان والغازات الأخرى الناتجة عن النفايات والتسرب",
  "input_062_label": "عام البدء لإجراءات الحد من النفايات و التسرب",
  "input_063_action_label": "عدد السكان",
  "input_063_label": "عدد السكان (مجال سيناريو الأمم المتحدة)",
  "input_064_label": "النمو الاقتصادي على المدى القريب (الناتج المحلي للفرد الواحد)",
  "input_065_label": "النسبة المئوية للأراضي المتاحة المستخدمة للتشجير",
  "input_066_label": "سنة بدء التشجير",
  "input_067_label": "الإزالة التكنولوجية للكربون",
  "input_071_label": "عام بدء الدعم المالي لالتقاط الكربون المباشر من الهواء",
  "input_072_label": "الترسيب المعدني المعزز",
  "input_073_label": "سنة بدء التمعدن المحسن",
  "input_074_label": "احتجاز الكربون في التربة الزراعية",
  "input_075_label": "سنة بدء الكربون للتربة الزراعية",
  "input_076_label": "الفحم الحيوي",
  "input_077_label": "سنة بدء الفحم الحيوي",
  "input_078_label": "حساسية المناخ",
  "input_079_label": "امتزاج المحيط",
  "input_080_label": "تخصيب ثاني أكسيد الكربون",
  "input_082_label": "جزء استيعاب المحيطات لدورة الكربون",
  "input_083_label": "تأثير درجة الحرارة على معدلات تنفس الميثان",
  "input_084_label": "تأثير درجة الحرارة على انبعاثات غاز الميثان من التربة المتجمدة والكلثرات",
  "input_085_label": "عتبة درجة الحرارة للتربة المتجمدة والكلثرات",
  "input_087_label": "معدل فقد الترسيب المعدني",
  "input_088_label": "معدل فقد الفحم الحيوي",
  "input_091_label": "معدل فقد الكربون في التربة الزراعية",
  "input_095_label": "الفحم النباتي",
  "input_096_label": "كربون التربة الزراعية",
  "input_110_action_label": "مدة الاختراق التكنولوجي(الطاقة النووية)",
  "input_110_label": "الطاقة النووية",
  "input_112_action_label": "مدة الاختراق التكنولوجي(الطاقة المتجددة)",
  "input_112_label": "مصادر متجددة",
  "input_117_action_label": "مدة الاختراق التكنولوجي (الطاقة الحيوية)",
  "input_117_label": "الطاقة الحيوية",
  "input_131_action_label": "وقت تطوير المحطة (نووي)",
  "input_131_label": "الطاقة النووية",
  "input_132_action_label": "وقت تطوير المحطة (مائي)",
  "input_132_label": "مائي",
  "input_133_action_label": "وقت تطوير المحطة (متجددة)",
  "input_133_label": "مصادر متجددة",
  "input_134_action_label": "وقت تطوير المحطة (صفر-كربون جديد)",
  "input_134_label": "صفر-كربون جديد",
  "input_139_action_label": "مدة بناء المحطة (نووي)",
  "input_139_label": "الطاقة النووية",
  "input_140_action_label": "مدة بناء المحطة (مائي)",
  "input_140_label": "مائي",
  "input_141_action_label": "مدة بناء المحطة (متجددة)",
  "input_141_label": "مصادر متجددة",
  "input_142_action_label": "مدة بناء المحطة(صفر-كربون جديد)",
  "input_142_label": "صفر-كربون جديد",
  "input_155_label": "الحد الأقصى لإمكانية الاستجابة للطلب",
  "input_160_action_label": "قيد التدفق على المصدر (مائي)",
  "input_160_label": "مائي",
  "input_166_action_label": "نسبة التقدم (الفحم)",
  "input_166_label": "الفحم",
  "input_167_action_label": "نسبة التقدم (النفط)",
  "input_167_label": "النفط",
  "input_168_action_label": "نسبة التقدم (الغاز)",
  "input_168_label": "الغاز",
  "input_169_action_label": "نسبة التقدم (الطاقة الحيوية)",
  "input_169_label": "الطاقة الحيوية",
  "input_170_action_label": "نسبة التقدم (الطاقة النووية)",
  "input_170_label": "الطاقة النووية",
  "input_171_action_label": "نسبة التقدم (الطاقة المتجددة)",
  "input_171_label": "مصادر متجددة",
  "input_172_action_label": "نسبة التقدم (الطاقة المائية)",
  "input_172_label": "مائي",
  "input_173_action_label": "نسبة التقدم (صفر-كربون جديد)",
  "input_173_label": "صفر-كربون جديد",
  "input_174_label": "نسبة تقدم طرق التخزين الأخرى",
  "input_175_label": "نسبة التقدم (البنية التحتية لاحتجاز ثاني أكسيد الكربون وتخزينه)",
  "input_176_label": "نسبة التقدم المحرز في الاستجابة للطلب",
  "input_177_action_label": "الموارد الأولية المتبقية (الفحم)",
  "input_177_label": "الفحم",
  "input_178_action_label": "الموارد الأولية المتبقية (النفط)",
  "input_178_label": "النفط",
  "input_179_action_label": "الموارد الأولية المتبقية (الغاز)",
  "input_179_label": "الغاز",
  "input_196_label": "٪ انخفاض في استخدام الفحم",
  "input_197_label": "عام الحد من البنية التحتية الجديدة للفحم",
  "input_198_label": "٪ انخفاض في استخدام النفط",
  "input_199_label": "عام الحد من البنية التحتية الجديدة للنفط",
  "input_200_label": "٪ انخفاض في استخدام الغاز",
  "input_201_label": "عام الحد من البنية التحتية الجديدة للغاز",
  "input_202_label": "سنة البدأ في تقليل استخدام الفحم بنسبة%",
  "input_203_label": "سنة التوقف عن تقليل استخدام الفحم بنسبة%",
  "input_204_label": "سنة البدأ في تقليل استخدام النفط بنسبة%",
  "input_205_label": "سنة التوقف عن تقليل استخدام النفط بنسبة%",
  "input_206_label": "سنة البدأ في تقليل استخدام الغاز بنسبة%",
  "input_207_label": "سنة التوقف عن تقليل استخدام الغاز بنسبة%",
  "input_208_label": "استخدم الإعدادات التفصيلية",
  "input_209_label": "استخدم الإعدادات التفصيلية",
  "input_210_label": "استخدم الإعدادات التفصيلية",
  "input_211_label": "الحد من البنية التحتية الجديدة للفحم",
  "input_212_label": "الحد من البنية التحتية الجديدة للنفط",
  "input_213_label": "الحد من البنية التحتية الجديدة للغاز",
  "input_214_label": "أقصى الأراضي المتاحة للتشجير",
  "input_215_label": "الأرض المطلوبة لكربون التربة الزراعية لكل وحدة تمت إزالتها",
  "input_218_label": "المدة لتأمين الأراضي للتشجير",
  "input_219_label": "مدة التشجير والغرس",
  "input_221_label": "عدد السنوات لتحقيق تعديل استغلال الفحم والنفط والغاز",
  "input_222_label": "الفحم",
  "input_223_label": "النفط",
  "input_224_label": "الغاز",
  "input_225_label": "الطاقة الحيوية",
  "input_230_action_label": "قيود التدفق على المصدر (طاقة الرياح)",
  "input_230_label": "الرياح",
  "input_231_action_label": "قيد التدفق على المصدر (الطاقة الشمسية)",
  "input_231_label": "شمسي",
  "input_232_action_label": "قيود التدفق على المصدر (الحرارة الجوفية)",
  "input_232_label": "الحرارة الأرضية",
  "input_233_action_label": "قيود التدفق على المصدر (مصادر الطاقة المتجددة الأخرى)",
  "input_233_label": "المصادر المتجددة الأخرى",
  "input_235_label": "النمو الاقتصادي طويل الأجل (الناتج المحلي الإجمالي للفرد)",
  "input_236_label": "مدة التحول",
  "input_237_label": "المساحة القصوى للتمعدن",
  "input_238_label": "استخدام الصخور الممعدنة",
  "input_239_label": "شدة الطاقة للتمعدن",
  "input_240_label": "مدى التمعدن النوعي",
  "input_241_label": "المدة لتشغيل الترسيب المعدني",
  "input_242_label": "الحد الأقصى للانخفاض في الناتج المحلي الإجمالي",
  "input_243_label": "انخفاض الناتج المحلي الإجمالي عند 1.5ºC من تأثيرات المناخ",
  "input_245_label": "استخدام معيار الكهرباء النظيفة",
  "input_246_label": "المصادر المؤهلة للكهرباء النظيفة",
  "input_247_label": "الهدف % للكهرباء من المصادر المؤهلة",
  "input_248_label": "سنة بدء معيار الكهرباء النظيفة",
  "input_249_label": "السنوات لتحقيق معيار الكهرباء النظيفة",
  "input_251_label": "نسبة التقدم",
  "input_252_label": "معدل الخصم الاجتماعي",
  "input_253_label": "معدل تسرب تخزين ثاني أكسيد الكربون",
  "input_258_action_label": "حد مبيعات وسائل النقل التي تعمل بالوقود - الهواء والماء",
  "input_258_label": "حد مبيعات وسائل النقل التي تعمل بالوقود",
  "input_259_action_label": "العام الأول للحد من مبيعات وسائل النقل التي تعمل بالوقود - الهواء والماء",
  "input_259_label": "العام الأول للحد من مبيعات وسائل النقل التي تعمل بالوقود",
  "input_260_label": "وقت الحد من مبيعات المعدات التي تعمل بالوقود",
  "input_261_action_label": "وقت الحد من مبيعات وسائل النقل التي تعمل بالوقود - الطرق والسكك الحديدية",
  "input_261_label": "الوقت للحد من مبيعات وسائل النقل التي تعمل بالوقود",
  "input_262_action_label": "الوقت للحد من مبيعات وسائل النقل التي تعمل بالوقود - الهواء والماء",
  "input_262_label": "الوقت للحد من مبيعات وسائل النقل التي تعمل بالوقود",
  "input_263_label": "مصادر متجددة",
  "input_264_label": "الطاقة النووية",
  "input_265_label": "صفر-كربون جديد",
  "input_266_label": "الوقود الأحفوري مع احتجاز ثاني أكسيد الكربون وتخزينه",
  "input_267_label": "الطاقة الحيوية",
  "input_268_label": "الغاز الطبيعي",
  "input_284_label": "عدد السنوات اللازمة لتنفيذ إجراءات الحد من النفايات والتسرب",
  "input_285_label": "المساهمة في ارتفاع مستوى البحر من ذوبان الغطاء الجليدي في أنتاركتيكا",
  "input_286_label": "المساهمة في ارتفاع مستوى البحر من ذوبان الغطاء الجليدي في غرينلاند",
  "input_287_label": "الغذاء من المنتجات الحيوانية",
  "input_288_label": "إنتاجية المحاصيل المحتملة",
  "input_292_label": "المواد الأولية الخشبية للطاقة الحيوية (الضرائب/الدعم)",
  "input_293_label": "المواد الأولية للمحاصيل للطاقة الحيوية (الضرائب/الدعم)",
  "input_294_label": "النفايات/ مواد أولية أخرى للطاقة الحيوية (الضرائب/الدعم)",
  "input_296_label": "دعم احتجاز الكربون وتخزينه (CCS) للغاز",
  "input_298_label": "سعر الكربون يشجع على احتجاز الكربون وتخزينه (CCS)",
  "input_299_label": "سعر الكربون يشجع الاحتجاز المباشر للكربون من الهواء وتخزينه (DACCS)",
  "input_300_label": "دعم الاحتجاز المباشر للكربون من الهواء وتخزينه (DACCS)",
  "input_304_label": "تأثير درجة الحرارة على إنتاجية المحاصيل",
  "input_305_label": "هدر الطعام",
  "input_306_label": "استخدام الإعدادات المفصلة",
  "input_307_label": "الحد من إزالة الغابات",
  "input_308_label": "سنة بدء الحد من إزالة الغابات",
  "input_309_label": "عدد السنوات لتحقيق سياسة الحد من إزالة الغابات",
  "input_310_label": "الحد من تدهور الغابات مكتملة النمو",
  "input_311_label": "استخدام الإعدادات المفصلة",
  "input_312_label": "ينطبق سعر الكربون على انبعاثات الطاقة الحيوية",
  "input_313_label": "الحد من البنية التحتية الجديدة للطاقة الحيوية",
  "input_314_label": "عام الحد من البنية التحتية الجديدة للطاقة الحيوية",
  "input_315_label": "سنة البدء في الحد من تدهور الغابات مكتملة النمو",
  "input_316_label": "المدة لتحقيق سياسة الحد من تدهور الغابات مكتملة النمو",
  "input_317_label": "دعم احتجاز الكربون وتخزينه من الطاقة الحيوية (BECCS)",
  "input_318_label": "حد التسميد بثاني أكسيد الكربون",
  "input_319_label": "تأثير درجة الحرارة على معدلات تنفس ثاني أكسيد الكربون",
  "input_320_label": "تضاعف تكاليف قطع الغابات للحصول على الأخشاب",
  "input_321_label": "تضاعف كلفة حصاد الأراضي الزراعية لمحاصيل الطاقة الحيوية",
  "input_322_label": "المواد الأولية لتغذية الطاقة الحيوية",
  "input_327_label": "نسبة تحويل علف المواشي",
  "input_328_label": "معدل تغير عامل انبعاثات الميثان من المحاصيل",
  "input_329_label": "معدل تغير عامل انبعاثات أكسيد النيتروس في المحاصيل",
  "input_330_label": "معدل تغير عامل انبعاثات الميثان من الثروة الحيوانية",
  "input_331_label": "معدل تغير عامل انبعاثات أكسيد النيتروس من الثروة الحيوانية",
  "input_332_label": "دعم النقل الكهربائي",
  "input_334_label": "سنة توقف دعم النقل الكهربائي",
  "input_337_label": "سنة توقف دعم المعدات الكهربائية",
  "input_338_label": "الاهتمام بالتكلفة الإجمالية للملكية - النقل",
  "input_339_label": "الاهتمام بالتكلفة الإجمالية للملكية - المباني",
  "input_341_label": "الاهتمام بالتكلفة الإجمالية للملكية - الصناعة",
  "input_342_label": "دعم احتجاز الكربون وتخزينه (CCS) من الفحم",
  "input_343_label": "سعة تخزين ثاني أكسيد الكربون بحيث تتضاعف التكلفة",
  "input_347_label": "نسبة التقدم (احتجاز الكربون المباشر من الهواء وتخزينه)",
  "input_348_label": "التكلفة الأولية لنظام DACCS",
  "input_349_label": "صياغة معادلة الضرر الاقتصادي",
  "input_350_label": "سنة بدء الدعم المالي لاحتجاز ثاني أكسيد الكربون وتخزينه",
  "input_351_action_label": "كفاءة احتجاز الكربون وتخزينه (CCS)",
  "input_351_label": "كفاءة الاحتجاز لنظام CCS",
  "input_352_label": "وقت إنجاز البنية التحتية لنظام احتجاز ثاني أكسيد الكربون وتخزينه",
  "input_360_label": "نسبة التقدم (الطاقة مع نظم احتجاز ثاني أكسيد الكربون وتخزينه)",
  "input_361_label": "سنة بدء دعم احتجاز ثاني أكسيد الكربون وتخزينه (CCS)",
  "input_362_label": "سنة بدء الدعم المقدم لاحتجاز وتخزين الكربون من الطاقة الحيوية (BECCS)",
  "input_365_label": "سوق DACCS عند تعادل التكلفة",
  "input_366_label": "التكلفة الرأسمالية القابلة للتخفيض بنسبة التقدم - النقل",
  "input_367_label": "التكلفة الرأسمالية القابلة للتخفيض بنسبة التقدم - المباني",
  "input_368_label": "التكلفة الرأسمالية القابلة للتخفيض بنسبة التقدم - الصناعة",
  "input_369_label": "تغير المناخ يبطئ النمو الاقتصادي",
  "input_370_label": "إنشاء بنية تحتية للشحن لتلبية الطلب المستقبلي",
  "input_371_label": "الوقت المستغرق لبناء بنية تحتية لشحن وسائل النقل لتلبية الطلب المستقبلي",
  "input_372_label": "استخدام الإعدادات المفصلة",
  "input_373_label": "دعم النقل الكهربائي والبنية التحتية للشحن الكهربائي",
  "input_375_label": "دعم المعدات الكهربائية",
  "input_379_label": "زيادة حرائق الغابات بسبب الاحتباس الحراري",
  "input_380_label": "النسبة المئوية لحرائق الغابات الشديدة التي تؤدي إلى إزالة الغابات",
  "input_387_label": "طفرة في تخفيض تكلفة تخزين الهيدروجين",
  "input_388_label": "عام تحقيق الطفرة في تخزين الهيدروجين",
  "input_390_label": "كفاءة تخزين الهيدروجين للرحلة (ذهاباً وإياباً)",
  "input_391_label": "نسبة تقدم تخزين الهيدروجين",
  "input_392_label": "معدل تسرب الهيدروجين المخزّن",
  "input_401_label": "استخدام الإعدادات المفصلة",
  "input_402_label": "الميثان وأكسيد االنيتروس من الثروة الحيوانية",
  "input_403_label": "الميثان وأكسيد االنيتروس من المحاصيل",
  "input_404_label": "الميثان وأكسيد النيتروس من النفايات",
  "input_405_label": "تسرب الميثان من أنظمة الطاقة",
  "input_406_label": "أكسيد النييتروس من الصناعة",
  "input_410_label": "عدد السنوات لتطبيق ضرائب أو دعم إمدادات الطاقة",
  "input_411_label": "المدة لتحسين معدلات كفاءة الطاقة",
  "input_412_label": "المدة لتحقيق تخفيضات في البنية التحتية الجديدة للفحم والنفط والغاز والطاقة الحيوية",
  "input_414_label": "الطاقة الحيوية مع احتجاز ثاني أكسيد الكربون وتخزينه",
  "input_415_label": "الغازات المفلورة",
  "input_416_label": "% مساحة الأراضي العالمية المعرضة لخطر تحولات النظام البيئي عند درجة حرارة 2ºC",
  "input_417_label": "وسائل تعتمد على الطبيعة لإزالة الكربون",
  "input_418_label": "استخدام الإعدادات المفصلة",
  "input_419_label": "الحد الأقصى لخفض الميثان في أنظمة الطاقة",
  "input_421_label": "سنة البدء في إجراءات الحد من الانبعاثات الزراعية",
  "input_422_label": "السنوات لتحقيق إجراءات الحد من الانبعاثات الزراعية",
  "input_424_label": "كثافة الكربون المتوازنة للكتلة الحيوية",
  "input_425_label": "التغير في معدل نمو الأراضي المشجرة",
  "input_431_label": "استجابة المستهلك للتخفيفات في البنية التحتية الجديدة للوقود",
  "input_432_label": "الحد الأقصى لخفض انبعاثات الغازات المفلورة والانبعاثات الصناعية الأخرى من الممارسات الجيدة",
  "input_433_label": "الحد الأقصى لتخفيض الغازات المفلورة عن طريق البدائل",
  "input_434_label": "الحد الأقصى لمعدل تدمير الغازات المفلورة",
  "input_435_label": "المخزون التراكمي من غازات مونتريال في الوقت الحاضر",
  "input_436_label": "سعة تخزين DACCS بحيث تتضاعف التكلفة",
  "input_437_label": "سعة تخزين CCS بحيث تتضاعف التكلفة",
  "input_441_label": "ثاني أكسيد الكربون من العمليات الصناعية",
  "input_range__breakthrough": "اختراق",
  "input_range__discouraged": "غير مشجعة",
  "input_range__future_breakthrough": "اختراق في المستقبل",
  "input_range__high": "عالي",
  "input_range__high_growth": "نمو مرتفع",
  "input_range__highest_growth": "أعلى نمو",
  "input_range__highly_increased": "زيادة كبيرة",
  "input_range__highly_reduced": "مخفض للغاية",
  "input_range__highly_subsidized": "مدعومة بشكل كبير",
  "input_range__highly_taxed": "ضرائب عالية",
  "input_range__huge_breakthrough": "اختراق ضخم",
  "input_range__increased": "زياده",
  "input_range__low": "منخفض",
  "input_range__low_growth": "نمو منخفض",
  "input_range__lowest_growth": "أدنى نمو",
  "input_range__medium": "متوسط",
  "input_range__medium_growth": "نمو متوسط",
  "input_range__near_term_breakthrough": "اختراق على المدى القريب",
  "input_range__negative_growth": "نمو سلبي",
  "input_range__no_growth": "بدون نمو",
  "input_range__reduced": "مخفض",
  "input_range__status_quo": "الوضع الحالي",
  "input_range__subsidized": "مدعوم",
  "input_range__taxed": "خاضع للضريبة",
  "input_range__very_high": "مرتفع جدا",
  "input_range__very_highly_taxed": "ضرائب عالية للغاية",
  "input_units__billion_people_in_2100": "مليار شخص في عام 2100",
  "input_units__degrees_c": "درجة مئوية",
  "input_units__dollars_per_barrel": "دولار/البرميل",
  "input_units__dollars_per_boe": "$/برميل نفط مكافئ",
  "input_units__dollars_per_kwh": "$/كيلوواط ساعة",
  "input_units__dollars_per_mcf": "$/مليون قدم مكعب",
  "input_units__dollars_per_ton": "دولار/الطن",
  "input_units__dollars_per_ton_co2": "$/طنCO<sub>2</sub>",
  "input_units__dollars_per_ton_co2_captured": "دولار/طن ثاني أكسيد الكربون المحتجز",
  "input_units__ej": "EJ",
  "input_units__ej_per_year": "EJ/سنة",
  "input_units__gj_per_ton_rock": "جيجا جول / طن صخر",
  "input_units__gtons_co2": "جيجا طن من ثاني أكسيد الكربون",
  "input_units__gtons_co2_per_year": "جيجا طن CO<sub>2</sub>/ سنة",
  "input_units__gtons_co2e": "جيجا طن من مكافئ ثاني أكسيد الكربون",
  "input_units__meters_by_2100": "أمتار بحلول 2100",
  "input_units__meters_meters_per_year": "متر*متر/سنة",
  "input_units__mha": "مليون هكتار",
  "input_units__mha_per_gton_co2_per_year": "ميجا هكتار/طن CO<sub>2</sub>/ السنة",
  "input_units__mtons_per_ej": "ايكساجول/مليون طن",
  "input_units__pct": "%",
  "input_units__pct_of_diet_by_2100": "% من الغذاء بحلول عام 2100",
  "input_units__pct_of_food_produced_by_2100": "% الغذاء المنتج بحلول عام 2100",
  "input_units__pct_of_land_available": "% من الأراضي المتاحة",
  "input_units__pct_of_max_potential": "% من أقصى الإمكانات",
  "input_units__pct_of_potential_reduction": "% من التخفيض المحتمل",
  "input_units__pct_of_purchase_cost": "% من تكلفة الشراء",
  "input_units__pct_of_required": "% من التكلفة المطلوبة",
  "input_units__pct_per_degrees_c": "% لكل درجة مئوية",
  "input_units__pct_per_year": "٪/السنة",
  "input_units__pct_per_year_per_degrees_c": "% في السنة لكل درجة مئوية",
  "input_units__ratio": "نسبة",
  "input_units__times_2020_value_by_2100": "أضعاف قيمة 2020 بحلول 2100",
  "input_units__ton_co2_per_tj": "طن CO<sub>2</sub>&nbsp;/ تيرا جول",
  "input_units__ton_co2_per_ton_rock": "طن CO<sub>2</sub>/طن من الصخور",
  "input_units__tons_c_per_hectare": "طن كربون/هكتار",
  "input_units__tons_per_ha_per_year": "طن/هكتار/السنة",
  "input_units__years": "سنوات",
  "map__error_failed_to_load": "تعذر تحميل الخريطة في الوقت الحالي.",
  "map__error_internet_required": "تتطلب الخرائط اتصالاً ثابتاً بالإنترنت.",
  "map__legend_annual_likelihood_of_drought": "الاحتمالية السنوية للجفاف لمدة 12 شهرًا فأكثر",
  "map__legend_change_in_days_range": "{low} إلى {high}",
  "map__legend_change_in_wildfire_days": "التغير في أيام خطر حرائق الغابات في السنة",
  "map__legend_days_per_year_above_temp": "عدد الأيام في السنة فوق درجة الحرارة {temp_c} ({temp_f})",
  "map__legend_days_per_year_above_temp_wet_bulb": "عدد الأيام في السنة فوق درجة حرارة الميزان المبلل {temp_c} ({temp_f})",
  "map__map_year": "سنة الخريطة:",
  "map__search_places": "البحث عن أماكن",
  "map__show_baseline": "إظهار خط الأساس",
  "map__show_current_scenario": "إظهار السيناريو الحالي",
  "map__temperature_by_year": "{temp} بحلول {year}",
  "map_slr__error_internet_required": "تتطلب خرائط ارتفاع مستوى سطح البحر اتصالا مستقرا بالإنترنت.",
  "map_slr__loading": "تحميل الخريطة من Climate Central …",
  "map_slr__map_type": "نوع الخريطة:",
  "map_slr__map_type_21st_century": "القرن 21",
  "map_slr__map_type_21st_century_with_surge": "القرن 21 مع مد عاصفي",
  "map_slr__map_type_longterm": "التوازن طويل المدى",
  "map_slr__meters": "{num} م",
  "map_slr__storm_surge": "المد العاصفي:",
  "menu__actions_and_outcomes": "الإجراءات والنتائج",
  "menu__assumptions": "الافتراضات",
  "menu__en_roads_overview": "نظرة عامة على En-ROADS",
  "menu__en_roads_training": "تدريب En-ROADS",
  "menu__en_roads_user_guide": "دليل مستخدم En-ROADS",
  "menu__graph_selection": "تحديد الرسم البياني",
  "menu__graphs": "الرسوم البيانية",
  "menu__help": "مساعدة",
  "menu__kaya_graphs": "رسوم كايا(Kaya) البيانية",
  "menu__language": "اللغة",
  "menu__main_graphs": "الرسوم البيانية الرئيسية",
  "menu__metric_units": "الوحدات المترية",
  "menu__miniature_graphs": "رسوم بيانية مصغرة",
  "menu__model_technical_reference": "المرجع الفني لنموذج المحاكاة",
  "menu__play_sounds": "تشغيل الأصوات",
  "menu__related_examples": "أمثلة مشابهة",
  "menu__release_notes": "ملاحظات الإصدار",
  "menu__reset_assumptions": "إعادة تعيين الافتراضات",
  "menu__reset_policies": "إعادة تعيين السياسات",
  "menu__reset_policies_and_assumptions": "إعادة تعيين السياسات والافتراضات",
  "menu__return_to_default_graphs": "العودة إلى الرسوم البيانية الافتراضية",
  "menu__show_graph_tooltips": "إظهار المعلومات التفاعلية في الرسم البياني",
  "menu__simulation": "المحاكاة",
  "menu__slider_information": "معلومات شريط التمرير",
  "menu__support": "الدعم",
  "menu__us_units": "الوحدات الأمريكية",
  "menu__uses_for_en_roads": "استخدامات En-ROADS",
  "menu__video_tours": "جولات الفيديو",
  "menu__view": "العرض",
  "menu_graphs__co2_emissions": "انبعاثات ثاني أكسيد الكربون",
  "menu_graphs__co2_removals": "عمليات إزالة ثاني أكسيد الكربون",
  "menu_graphs__final_energy_consumption_totals": "إجمالي استهلاك الطاقة النهائي",
  "menu_graphs__final_energy_consumption_types": "أنواع استهلاك الطاقة النهائية",
  "menu_graphs__financial": "الأمور المالية",
  "menu_graphs__greenhouse_gas_emissions": "انبعاثات غازات الاحتباس الحراري",
  "menu_graphs__impacts": "التأثيرات",
  "menu_graphs__land_forestry_and_food": "الأرض والغابات والغذاء",
  "menu_graphs__model_comparison_history": "مقارنة نموذج المحاكاة - البيانات التاريخية",
  "menu_graphs__population_and_gdp": "عدد السكان والناتج المحلي الإجمالي",
  "menu_graphs__primary_energy_demand_totals": "إجمالي الطلب على الطاقة الأولية",
  "menu_graphs__primary_energy_demand_types": "أنواع الطلب على الطاقة الأولية",
  "menu_graphs__view_more_graphs": "عرض المزيد من الرسوم البيانية",
  "outcome_13_label": "الأضرار التراكمية المخصومة حتى عام 2100",
  "outcome_13_units_metric": "تريليون دولار",
  "outcome_1_label": "الإرتفاع في درجة الحرارة في عام 2100",
  "outcome_1_units_metric": "درجة مئوية",
  "outcome_1_units_us": "درجة فهرنهايت",
  "outcome_2_label": "تركيز ثاني أكسيد الكربون في عام 2100",
  "outcome_2_units_metric": "جزء في المليون",
  "outcome_3_label": "ارتفاع مستوى سطح البحر في عام 2100",
  "outcome_3_units_metric": "م",
  "outcome_3_units_us": "قدم",
  "outcome_4_label": "ثاني أكسيد الكربون المتجنب التراكمي بحلول 2100",
  "outcome_4_units_metric": "جيجا طن CO<sub>2</sub>",
  "policy_group_001_description": "شَجّع أو قلل تعدين الفحم وحرقه في محطات توليد الطاقة. الفحم هو الوقود الأحفوري الأكثر ضررا من حيث انبعاثات الكربون، وكذلك في ملوثات الهواء الأخرى التي تسبب آثارا صحية شديدة. ومع ذلك، فهي مصدر مهيمن للطاقة على الصعيد العالمي، لأنه رخيص نسبيا.",
  "policy_group_001_example_1": "الضرائب",
  "policy_group_001_example_2": "دعم أقل",
  "policy_group_001_example_3": "تلوث الهواء",
  "policy_group_001_short_title": "الفحم",
  "policy_group_001_title": "الفحم",
  "policy_group_002_description": "قلل أو شجّع استخراج و تكرير واستهلاك النفط للحصول على الطاقة. النفط هو الوقود الأحفوري الذي يستخدم على نطاق واسع في السيارات والسفن والطائرات. كما أنه يستخدم للصناعة والتدفئة والكهرباء. وقد أشعل النفط صراعات و حروب كبرى ويمكن أن تهدد انسكابات و حوادث النفط النظم البيئية و مصادر المياه.",
  "policy_group_002_example_1": "دعم أقل",
  "policy_group_002_example_2": "خطوط الأنابيب",
  "policy_group_002_example_3": "تنويع الاستثمار",
  "policy_group_002_short_title": "النفط",
  "policy_group_002_title": "النفط",
  "policy_group_003_description": "شَجّع أو قلل من استخراج و وحرق الغاز الطبيعي لتوليد الطاقة. الغاز الطبيعي هو وقود أحفوري يستخدم في الكهرباء والتدفئة والصناعة. عند الاحتراق ، يطلق ثاني أكسيد الكربون (على الرغم من أنه أقل من الفحم والنفط) ، وإذا تسرب إلى الهواء ، فإنه يحتوي على كميات عالية من الميثان. تستخدم كميات كبيرة من الماء عند استخراج الغاز الطبيعي مما يمكن أن يسبب التلوث.",
  "policy_group_003_example_1": "التكسير(Fracking)",
  "policy_group_003_example_2": "خطوط الأنابيب",
  "policy_group_003_example_3": "تنويع الاستثمار",
  "policy_group_003_short_title": "الغاز الطبيعي",
  "policy_group_003_title": "الغاز الطبيعي",
  "policy_group_004_description": "تثبيط أو تشجيع استخدام الأشجار والنفايات والمحاصيل الزراعية لإنتاج الطاقة. تنتج هذه المصادر (المواد الأولية) الطاقة عند حرقها كمواد صلبة (مثل الخشب) أو سوائل (مثل الإيثانول) أو غاز (مثل الميثان الناتج عن التحلل). بعض المواد الأولية يمكن أن تكون مستدامة والبعض الآخر يمكن أن يكون أسوأ من حرق الفحم. يمكن استخدام تكنولوجيا احتجاز الكربون وتخزينه مع الطاقة الحيوية (BECCS)، لكنها لم تستخدم بعد على نطاق واسع وتواجه عوائق في عملية التطبيق.",
  "policy_group_004_example_1": "الوقود الحيوي",
  "policy_group_004_example_2": "وقود الخشب",
  "policy_group_004_short_title": "الطاقة الحيوية",
  "policy_group_004_title": "الطاقة الحيوية",
  "policy_group_005_description": "شجّع أو قلل من استخدام الألواح الشمسية وتوربينات الرياح والطاقة الحرارية الأرضية . تشمل الطاقة المتجددة طاقة الرياح والطاقة الشمسية والطاقة الحرارية الأرضية والطاقة الكهرومائية وغيرها من التقنيات التي تنتج الطاقة مع انبعاثات قليلة أو معدومة من ثاني أكسيد الكربون أو تلوث الهواء. لاحظ أن الطاقة النووية والطاقة الحيوية يتم اعتبارها بشكل منفصل.",
  "policy_group_005_example_1": "الرياح، الشمس، الماء",
  "policy_group_005_example_2": "الطاقة النظيفة",
  "policy_group_005_example_3": "تخزين الطاقة",
  "policy_group_005_short_title": "مصادر متجددة",
  "policy_group_005_title": "مصادر متجددة",
  "policy_group_006_description": "شجّع أو قلل من بناء محطات الطاقة النووية. إن إنتاج الطاقة النووية لا يطلق ثاني أكسيد الكربون، ولكنه ينتج نفايات يتعين إدارتها لعدة قرون.",
  "policy_group_006_example_1": "الإشعاع",
  "policy_group_006_example_2": "تخزين النفايات",
  "policy_group_006_short_title": "الطاقة النووية",
  "policy_group_006_title": "الطاقة النووية",
  "policy_group_007_description": "اكتشف مصدرا رخيصا جديدا للكهرباء لا تنبعث منه غازات الاحتباس الحراري. يتأمّل البعض بأن مثل هذا الاختراق يمكن أن يكون الاندماج النووي أو الانشطار النووي القائم على الثوريوم، ومع ذلك، هناك مخاطر غير معروفة مرتبطة بأي مصدر جديدة للطاقة. انت قرر متى يحدث هذا الاختراق ، وتكلفته الأولية بالمقارنة مع الفحم ، وكم من الوقت سيكون التأخير في الاستخدام التجاري والتوسع.",
  "policy_group_007_example_1": "انشطار الثوريوم",
  "policy_group_007_example_2": "الاندماج النووي",
  "policy_group_007_short_title": "صفر-كربون جديد",
  "policy_group_007_title": "صفر-كربون جديد",
  "policy_group_008_description": "حدد سعرًا عالميًا للكربون يجعل مصادر الطاقة أكثر تكلفة اعتمادًا على كمية ثاني أكسيد الكربون التي تطلقها ، أو أصدر معيارًا للكهرباء النظيفة أو معيار أداء الانبعاثات. يمكن لمنتجي الطاقة تحميل عملائهم تكاليف إضافية ، لذلك يجب تصميم السياسة لتقليل التأثيرات على الفِئات الأشد فقرا.",
  "policy_group_008_example_1": "سعر الكربون",
  "policy_group_008_example_2": "الحد الأقصى والتجارة",
  "policy_group_008_short_title": "سعر الكربون",
  "policy_group_008_title": "تسعير الكربون ومعايير الطاقة",
  "policy_group_009_description": "زيادة أو تقليل كفاءة الطاقة في المركبات، والشحن، والسفر الجوي، وأنظمة النقل. وتشمل كفاءة استخدام الطاقة استخدام السيارات الهجينة، و تحسين وسائل النقل العام، و الوسائل التي يمكن للناس استخدامها للتنقل مع استهلاك أقل للطاقة. ويمكن أن يؤدي اعتماد ممارسات أكثر كفاءة في استخدام الطاقة إلى تحسين الصحة العامة وتوفير المال.",
  "policy_group_009_example_1": "السيارات الهجينة",
  "policy_group_009_example_2": "قابلية المشي",
  "policy_group_009_example_3": "وسائل النقل العام",
  "policy_group_009_short_title": "كفاءة الطاقة",
  "policy_group_009_title": "كفاءة الطاقة لقطاع النقل",
  "policy_group_010_description": "زيادة مشتريات السيارات الكهربائية الجديدة والشاحنات والحافلات والقطارات، وربما حتى السفن والطائرات. يساعد استخدام المحركات الكهربائية للنقل على الحد من انبعاثات غازات الاحتباس الحراري وتلوث الهواء إذا كانت الكهرباء من مصادر منخفضة الكربون مثل الطاقة الشمسية والرياح.",
  "policy_group_010_example_1": "السيارات الكهربائية",
  "policy_group_010_example_2": "تكنولوجيا البطاريات",
  "policy_group_010_example_3": "البنية التحتيةللشحن",
  "policy_group_010_short_title": "الكهربة",
  "policy_group_010_title": "كهربة النقل",
  "policy_group_011_description": "زيادة أو تقليل كفاءة الطاقة في المباني و آلات والأجهزة الأخرى. تشمل كفاءة استخدام الطاقة بناء منازل معزولة بشكل جيد وتقليل استهلاك المصانع للطاقة. ويمكن للممارسات الفعالة في استخدام الطاقة أن توفر المال من خلال خفض الاستهلاك، فضلا عن تحسين صحة الناس في تلك المباني.",
  "policy_group_011_example_1": "المباني الخضراء",
  "policy_group_011_example_2": "صناعة ذات كفاءة",
  "policy_group_011_example_3": "حفظ الطاقة",
  "policy_group_011_short_title": "كفاءة الطاقة",
  "policy_group_011_title": "كفاءة الطاقة في المباني والصناعة",
  "policy_group_012_description": "زيادة استخدام الكهرباء بدلا من الوقود مثل النفط أو الغاز في المباني والأجهزة وأنظمة التدفئة وغيرها من الآلات. استخدام المحركات الكهربائية يساعد على الحد من الانبعاثات وتحسين نوعية الهواء بشرط أن تكون الكهرباء من مصادر منخفضة الكربون مثل الطاقة الشمسية والرياح.",
  "policy_group_012_example_1": "التدفئة الكهربائية",
  "policy_group_012_example_2": "المضخات الحرارية",
  "policy_group_012_short_title": "الكهربة",
  "policy_group_012_title": "كهربة المباني والصناعة",
  "policy_group_013_description": "افترض نمو سكاني أعلى أو أقل. في حين أن هناك مسارا متوقعا للنمو السكاني، فإن هناك خطوات مثل تعليم المرأة و تنظيم الأسرة تسرع التحول إلى الأسر الأصغر حجما، مما من شأنه أن يبطئ النمو السكاني.",
  "policy_group_013_example_1": "تمكين المرأة",
  "policy_group_013_example_2": "معدلات الخصوبة",
  "policy_group_013_short_title": "عدد السكان",
  "policy_group_013_title": "عدد السكان",
  "policy_group_014_description": "افترض نموًا أعلى أو أقل في السلع المنتجة والخدمات المقدمة. يُقاس النمو الاقتصادي بإجمالي الناتج المحلي (GDP) للفرد وهو محرك رئيسي لاستهلاك الطاقة. توجد بدائل لتلبية احتياجات الناس من خلال أطر اقتصادية لا تستند إلى نمو دائم للناتج المحلي الإجمالي.",
  "policy_group_014_example_1": "GDP للفرد",
  "policy_group_014_example_2": "حركة البساطة",
  "policy_group_014_short_title": "النمو الاقتصادي",
  "policy_group_014_title": "النمو الاقتصادي",
  "policy_group_015_description": "تغيير مستوى اعتماد أفضل ممارسات للحد من الانبعاثات المتعلقة بالنفايات والطاقة والصناعة. ينبعث كل من الميثان (CH<sub>4</sub>) وأكسيد النيتروز (N<sub>2</sub>O) وثاني أكسيد الكربون (CO<sub>2</sub>) والغازات المفلورة (مركبات الكربون الهيدروفلورية والهيدروكربونية المشبعة بالفلور وسادس فلوريد الكبريت وغيرها) حيثما وجدت أوجه قصور وتسريبات. يمكن أن يقلل التصميم الأفضل وإدارة النفايات من انبعاثات الميثان وأكسيد النيتروز من مدافن النفايات ومياه الصرف الصحي. يمكن أن يؤدي إصلاح التسريبات إلى تقليل الميثان من عمليات الوقود الأحفوري. يمكن أن تقلل كفاءة العمليات من أكسيد النيتروز من العمليات الصناعية، مثل إنتاج الأسمدة، وثاني أكسيد الكربون من عمليات مثل إنتاج الأسمنت. يمكن أن تقلل كفاءة العمليات وإدارة النفايات من الغازات المفلورة من الصناعة الكيميائية والمنتجات الاستهلاكية مثل مكيفات الهواء.",
  "policy_group_015_example_1": "ميثان/أكسيد النيتروس/HFC",
  "policy_group_015_example_2": "غازات التبريد",
  "policy_group_015_short_title": "النفايات والتسربات",
  "policy_group_015_title": "النفايات والتسربات",
  "policy_group_016_description": "تغيير مستوى اعتماد أفضل ممارسات الانبعاثات في الزراعة والعادات الغذائية. ينشأ غاز الميثان (CH<sub>4</sub>) من مصادر مثل الأبقار وحقول الأرز، بينما يأتي أكسيد النيتروس (N<sub>2</sub>O) من الأسمدة والسماد الطبيعي. ويمكن أن تؤدي أساليب الزراعة المحسنة إلى خفض الانبعاثات بشكل مباشر، ويمكن أن يؤدي تغيير العادات الغذائية إلى تقليل الطلب على الماشية والمحاصيل، مما يقلل من الحاجة إلى أراضٍ زراعية جديدة ويساعد على منع إزالة الغابات.",
  "policy_group_016_example_1": "إدارة السماد العضوي",
  "policy_group_016_example_2": "الأسمدة",
  "policy_group_016_example_3": "الأنظمة الغذائية النباتية",
  "policy_group_016_short_title": "الإنبعاثات الزراعية",
  "policy_group_016_title": "الانبعاثات الزراعية والخيارات الغذائية",
  "policy_group_017_description": "التشجيع على توسيع الغابات (التشجير)، واستعادة الغابات المتدهورة، وتنفيذ الممارسات الزراعية التي تحتجز الكربون، وإنتاج الفحم الحيوي. يمكن لهذه الطرق القائمة على الطبيعة إزالة ثاني أكسيد الكربون من الغلاف الجوي وتخزينه في النباتات والتربة. ومع ذلك، يمكن أن ينطلق هذا الكربون مرة أخرى إذا تم تغيير الأرض، سواء من خلال إجراءات متعمدة مثل الزراعة أو أحداث عرضية مثل حرائق الغابات.",
  "policy_group_017_example_1": "التشجير",
  "policy_group_017_example_2": "كربون التربة الزراعية",
  "policy_group_017_example_3": "الفحم الحيوي",
  "policy_group_017_short_title": "قائمة على الطبيعة",
  "policy_group_017_title": "إزالة ثاني أكسيد الكربون القائمة على الطبيعة",
  "policy_group_018_description": "تعزيز استخدام تكنولوجيات إزالة ثاني أكسيد الكربون مثل الالتقاط المباشر للهواء والترسيب المعدني المعزز. وتعتمد هذه الأساليب على صناعات ثقيلة لإزالة ثاني أكسيد الكربون مباشرة من الغلاف الجوي. وفي حين أن هذه التكنولوجيات تقدم حلولاً واعدة للحد من الكربون في الغلاف الجوي، إلا أنها تتطلب طاقة واستثمارات كبيرة لتنفيذها على نطاق واسع. يمكن العثور على أشكال احتجاز ثاني أكسيد الكربون وتخزينه المقترنة بتوليد الطاقة تحت أشرطة التمرير الخاصة بكل منها (الفحم والغاز والطاقة الحيوية).",
  "policy_group_018_example_1": "احتجاز الهواء المباشر",
  "policy_group_018_example_2": "الترسيب المعدني",
  "policy_group_018_short_title": "تكنولوجي",
  "policy_group_018_title": "إزالة ثاني أكسيد الكربون القائم على التكنولوجيا",
  "policy_group_019_description": "تشجيع أو عدم تشجيع حماية الغابات لتغيير التوجه الحالي لإزالة الغابات وتدهورها. وإزالة الغابات هي تحويل أراضي الغابات إلى استخدامات أخرى، في المقام الأول للزراعة. وتدهور الغابات هو الفقدان المؤقت للغابات بسبب الحصاد من أجل المنتجات الخشبية أو الطاقة الحيوية. أما إزالة الغابات فهي مدفوعة بالحاجة إلى الأراضي الزراعية، والتي يمكن أن تتأثر بالتغيرات في النظام الغذائي في إطار الانبعاثات الزراعية.",
  "policy_group_019_example_1": "حماية الغابات",
  "policy_group_019_example_2": "الغابات الجديدة",
  "policy_group_019_short_title": "إزالة الغابات",
  "policy_group_019_title": "إزالة الغابات وتدهور الغابات المكتملة النمو",
  "selector__custom": "حسب الطلب",
  "selector__default": "افتراضي",
  "selector__select": "اختار…",
  "share_by_email__enter_from_addr": "أدخل عنوان بريدك الإلكتروني",
  "share_by_email__enter_from_name": "أدخل اسمك",
  "share_by_email__enter_note": "ملاحظة إضافية في الأعلى (اختياري)",
  "share_by_email__enter_to_addr": "أدخل عنوان البريد الإلكتروني للمستلم",
  "share_by_email__failed": "حدث خطأ أثناء إرسال السيناريو بالبريد الإلكتروني. حاول مرة اخرى.",
  "share_by_email__from_label": "من",
  "share_by_email__invalid_from_addr": "أدخل عنوان بريد إلكتروني صالح للمرسل",
  "share_by_email__invalid_from_name": "أدخل اسمك",
  "share_by_email__invalid_to_addr": "أدخل عنوان بريد إلكتروني صالح للمستلم",
  "share_by_email__note_label": "ملاحظة",
  "share_by_email__preview_label": "معاينة",
  "share_by_email__privacy": "نحن نحترم خصوصيتك. يتم استخدام المعلومات التي تم إدخالها في هذا النموذج فقط لإرسال بريد إلكتروني واحد إلى المستلم.",
  "share_by_email__send": "إرسال",
  "share_by_email__succeeded": "تم إرسال رابط السيناريو بنجاح إلى {toAddress}",
  "share_by_email__template_line1": "تمت مشاركة سيناريو جديد لسياسة المناخ معك.",
  "share_by_email__template_line2": "فيما يلي رابط لسيناريو مناخ عالمي مصمم خصيصًا تم إنشاؤه باستخدام محاكي En-ROADS:",
  "share_by_email__template_line3": "تحقق من ذلك.",
  "share_by_email__template_line4": "تم تطوير En-ROADS من قبل<i> كلايميت انتراكتيف </i> و <i> و مدرسة MIT سلون للإدارة </i> . للمزيد من المعلومات قم بزيارة {link} .",
  "share_by_email__template_subject": "تمت مشاركة سيناريو مناخ En-ROADS معك",
  "share_by_email__to_label": "الى",
  "share_menu__copy_scenario_link": "انسخ رابط السيناريو",
  "share_menu__share_by_email": "المشاركة عن طريق البريد الإلكتروني",
  "share_menu__share_on_facebook": "شارك على فايسبوك",
  "share_menu__share_on_linked_in": "شارك على لينكد إن",
  "share_menu__share_on_twitter": "شارك على منصة X",
  "share_menu__share_your_scenario": "شارك السيناريو الخاص بك",
  "temperature_box__increase_by_2100": "إرتفاع <br>درجة الحرارة في 2100",
  "welcome__announcement_line1": "تم تحديث En-ROADS في {date} بميزات وتحسينات جديدة.",
  "welcome__announcement_line2": "يرجى زيارة {linkRelease} ملاحظات الإصدار وتوثيق {linkClose} نموذج المحاكاة لمعرفة المزيد.",
  "welcome__line1": "مرحباً بكم في برنامج En-ROADS من Climate Interactive ومدرسة سلون للإدارة بمعهد ماساتشوستس للتكنولوجيا (MIT).",
  "welcome__line2": "يكون المحاكي أكثر فاعلية عند استخدامه في {linkSimulation} لعبة تمثيل الأدوار {linkClose} أو {linkWorkshop} ورشة عمل السياسات {linkClose}.",
  "welcome__line3": "استكشف{linkUserGuide} دليل المستخدم في En-ROADS {linkClose} أو انضم إلى {linkTrainings} الدورات التدريبية{linkClose} لتصبح ميسّرًا، أو قم بزيارة {linkSupport}support.climateinteractive.org للاستفسارات{linkClose}."
}