export default {
  "__actions": "क्रिया",
  "__actions_outcomes": "क्रिया एवं परिणाम",
  "__assumptions": "धारणा",
  "__assumptions_intro": "एन-रोड्स मॉडल को चलाने वाली महत्वपूर्ण मान्यताओं तक पहुंचें और बदलें। ये सेटिंग्स केवल वर्तमान परिदृश्य को प्रभावित करती हैं, न कि आधारभूत परिदृश्य को, जिससे उनके बीच तुलना की अनुमति मिलती है।",
  "__beta": "बीटा",
  "__cancel": "रद्दीकरण",
  "__close": "धन्यवाद",
  "__continue_to_en_roads": "एन -रोड्स की तरफ",
  "__en_roads_climate_ambassador_training": "एन-रोड्स पर्यावरण मित्र प्रशिक्षण",
  "__enter_full_screen": "पूरे पर्दे पर",
  "__exit_full_screen": "पूरे पर्दे से बाहर",
  "__full_screen_unavailable": "पूरा पर्दा अनुपलब्ध",
  "__graph": "लेखाचित्र",
  "__graph_data_copied_to_the_clipboard": "लेखाचित्र क्लिपबोर्ड पर नकल किया गया",
  "__help": "मदद",
  "__here_is_a_climate_scenario": "यहाँ एक जलवायु परिदृश्य है, जिसे @climateinteract और @MITSloanSusty से #EnROADS सिम्युलेटर के साथ बनाया गया है",
  "__input_range_error_message": "{minValue} और {maxValue} के बीच का मान डालें.",
  "__invalid_url_params": "आपने जिस परिदृश्य लिंक का प्रयास किया है उसे ठीक से दिखाया नहीं किया जा सकता है। कृपया नवीनतम संस्करण में परिदृश्य को फिर से बनाएँ।",
  "__kaya_graphs": "काया रेखांकन",
  "__no": "नहीं",
  "__outcomes": "परिणामों",
  "__redo": "फिर से करें",
  "__register_your_event": "अपना एन-रोड्स कार्यक्रम पंजीकृत करें",
  "__related_examples": "संबंधित उदाहरण",
  "__related_graphs": "संबंधित रेखांकन",
  "__reload": "पुनः लोड करें",
  "__replay_last_change": "अंतिम परिवर्तन फिर से चलाएं",
  "__reset_assumptions": "मान्यताओं को पुनः प्रविष्ट करें",
  "__reset_graphs": "लेखांकन पुनः प्रविष्ट करें",
  "__reset_sliders": "नीतियां और धारणाएं पुनः प्रविष्ट करें",
  "__scenario_link_copied_to_the_clipboard": "परिदृश्य लिंक क्लिपबोर्ड पर नकल किया गया",
  "__sea_level_rise": "समुद्र तल से वृद्धि",
  "__show_main_graphs": "मुख्य रेखांकन दिखाएं",
  "__show_miniature_graphs": "लघु रेखांकन दिखाएं",
  "__show_more": "और दिखाओ…",
  "__undo": "पूर्ववत",
  "__unsupported_browser": "En-ROADS वर्तमान में Android टैबलेट पर नहीं चलता है। टच स्क्रीन वाले विंडोज पीसी पर, आप टचपैड के साथ एन-रोड्स का उपयोग कर सकते हैं लेकिन टच स्क्रीन का नहीं।",
  "__url_input_change_warning": "परिदृश्य लिंक में स्लाइडर मान शामिल हैं जो En-ROADS के वर्तमान संस्करण के साथ काम नहीं करते हैं। इन स्लाइडर को वर्तमान डिफ़ॉल्ट मानों पर रीसेट कर दिया गया है:",
  "__url_input_value_warning": "परिदृश्य लिंक में स्लाइडर मान शामिल हैं जो मान्य सीमा से बाहर हैं। इन स्लाइडर को वर्तमान डिफ़ॉल्ट मानों पर रीसेट कर दिया गया है:",
  "__yes": "हां",
  "advanced_section_title__carbon_pricing": "कार्बन मूल्य निर्धारण",
  "advanced_section_title__clean_electricity_standard": "स्वच्छ बिजली मानक",
  "advanced_section_title__emissions_performance_standard": "उत्सर्जन प्रदर्शन मानक",
  "assumption_group_title__breakthrough_commercialization_time": "निर्णायक व्यावसायीकरण समय",
  "assumption_group_title__climate_system_sensitivities": "जलवायु प्रणाली संवेदनशीलता",
  "assumption_group_title__economic_impact_of_climate_change": "जलवायु परिवर्तन का आर्थिक प्रभाव",
  "assumption_group_title__energy_supply_progress_ratios": "प्रगति अनुपात",
  "assumption_group_title__plant_construction_time": "संयंत्र निर्माण समय",
  "assumption_group_title__plant_development_time": "पौधे के विकास का समय",
  "assumption_group_title__sea_level_rise": "समुद्र तल से वृद्धि",
  "assumptions__preset": "पूर्व निर्धारित:",
  "assumptions__related_graph": "संबंधित ग्राफ:",
  "basic_section_header__buildings_and_industry": "भवन एवं उद्योग",
  "basic_section_header__carbon_removal": "कार्बन हटाना",
  "basic_section_header__energy_supply": "ऊर्जा आपूर्ति",
  "basic_section_header__growth": "वृद्धि",
  "basic_section_header__transport": "परिवहन",
  "data_table_139_footnote": "ये मान <a href=\"#\">आर्थिक प्रभाव</a> सेटिंग में समायोजित अनुमानों पर निर्भर करते हैं:",
  "data_table_row_001_label": "कार्बन की सामाजिक लागत {year} में",
  "data_table_row_002_label": "2100 . के माध्यम से रियायती संचयी नुकसान",
  "data_table_units__per_ton_co2": "/ टन CO<sub>2</sub>",
  "data_table_units__trillion": "खरब",
  "data_table_value__dollars": "${num}",
  "graph_001_mini_title": "ऊर्जा मांग के स्रोत",
  "graph_001_title": "प्राथमिक ऊर्जा के वैश्विक स्रोत",
  "graph_002_menu_title": "प्राथमिक ऊर्जा के वैश्विक स्रोत—क्षेत्र",
  "graph_002_mini_title": "ऊर्जा मांग के स्रोत",
  "graph_002_title": "प्राथमिक ऊर्जा के वैश्विक स्रोत",
  "graph_003_title": "कोयला प्राथमिक ऊर्जा मांग",
  "graph_005_title": "तेल प्राथमिक ऊर्जा मांग",
  "graph_006_menu_title": "तेल प्राथमिक ऊर्जा मांग-क्षेत्र",
  "graph_006_title": "तेल प्राथमिक ऊर्जा मांग",
  "graph_007_title": "प्राकृतिक गैस प्राथमिक ऊर्जा मांग",
  "graph_009_title": "जैविक-ऊर्जा प्राथमिक ऊर्जा मांग",
  "graph_011_title": "अक्षय ऊर्जा प्राथमिक ऊर्जा मांग",
  "graph_012_title": "परमाणु प्राथमिक ऊर्जा मांग",
  "graph_013_title": "नवीन शून्य-कार्बन प्राथमिक ऊर्जा मांग",
  "graph_018_title": "कुल प्राथमिक ऊर्जा",
  "graph_024_menu_title": "पवन और सौर-क्षेत्र की सीमांत लागत",
  "graph_024_title": "पवन और सौर की सीमांत लागत",
  "graph_026_title": "प्राथमिक ऊर्जा की कार्बन तीव्रता",
  "graph_028_title": "प्राथमिक विद्युत ऊर्जा की कार्बन तीव्रता",
  "graph_029_mini_title": "ऊर्जा की खपत",
  "graph_029_title": "अंतिम ऊर्जा खपत",
  "graph_030_title": "स्रोत द्वारा अंतिम ऊर्जा खपत",
  "graph_031_menu_title": "स्रोत-क्षेत्र द्वारा अंतिम ऊर्जा खपत",
  "graph_031_title": "स्रोत द्वारा अंतिम ऊर्जा खपत",
  "graph_033_title": "कोयला अंतिम ऊर्जा खपत",
  "graph_034_title": "तेल अंतिम ऊर्जा खपत",
  "graph_035_title": "प्राकृतिक गैस अंतिम ऊर्जा खपत",
  "graph_036_title": "जैविक-ऊर्जा अंतिम ऊर्जा खपत",
  "graph_037_title": "परमाणु अंतिम ऊर्जा खपत",
  "graph_038_title": "नवीकरणीय अंतिम ऊर्जा खपत",
  "graph_039_title": "नवीन शून्य-कार्बन अंतिम ऊर्जा खपत",
  "graph_040_title": "कम कार्बन अंतिम ऊर्जा खपत",
  "graph_041_menu_title": "स्रोत-क्षेत्र द्वारा विद्युत अंतिम ऊर्जा खपत",
  "graph_041_title": "स्रोत द्वारा विद्युत अंतिम ऊर्जा खपत",
  "graph_042_menu_title": "अंतिम उपयोग द्वारा अंतिम ऊर्जा खपत—क्षेत्र",
  "graph_042_title": "अंतिम उपयोग द्वारा अंतिम ऊर्जा खपत",
  "graph_043_title": "अक्षय ऊर्जा से % अंतिम ऊर्जा खपत",
  "graph_045_title": "कुल पूंजी का इलेक्ट्रिक शेयर-भवन एवं उद्योग",
  "graph_046_title": "कुल पूंजी का इलेक्ट्रिक शेयर-परिवहन",
  "graph_047_mini_title": "सी अंतिम ऊर्जा की तीव्रता",
  "graph_047_title": "अंतिम ऊर्जा की कार्बन तीव्रता",
  "graph_048_title": "अंतिम विद्युत ऊर्जा की कार्बन तीव्रता",
  "graph_051_mini_title": "प्रति व्यक्ति जी डी पी",
  "graph_051_title": "प्रति व्यक्ति जी डी पी",
  "graph_052_title": "क्षेत्र के अनुसार प्रति व्यक्ति सकल घरेलू उत्पाद",
  "graph_053_title": "जीडीपी की ऊर्जा तीव्रता",
  "graph_054_title": "सकल विश्व उत्पाद",
  "graph_057_title": "CO<sub>2</sub>&nbsp;उत्सर्जन और निष्कासन",
  "graph_058_title": "CO<sub>2</sub>&nbsp;प्रति व्यक्ति उत्सर्जन",
  "graph_059_title": "CO<sub>2</sub>&nbsp;वास्तविक सकल घरेलू उत्पाद के प्रति डॉलर उत्सर्जन",
  "graph_061_mini_title": "CO<sub>2</sub>&nbsp;ऊर्जा से उत्सर्जन",
  "graph_061_title": "CO<sub>2</sub>&nbsp;ऊर्जा से उत्सर्जन",
  "graph_062_mini_title": "शुद्ध जीएचजी उत्सर्जन",
  "graph_062_title": "ग्रीनहाउस गैस शुद्ध उत्सर्जन",
  "graph_063_menu_title": "गैस-क्षेत्र द्वारा ग्रीनहाउस गैस शुद्ध उत्सर्जन",
  "graph_063_mini_title": "गैस द्वारा शुद्ध जीएचजी उत्सर्जन",
  "graph_063_title": "गैस द्वारा ग्रीनहाउस गैस शुद्ध उत्सर्जन",
  "graph_065_title": "गैर-सीओ2 ग्रीनहाउस गैस उत्सर्जन",
  "graph_067_title": "सीएच4 उत्सर्जन",
  "graph_068_title": "N<sub>2</sub>O उत्सर्जन",
  "graph_069_title": "SF<sub>6</sub>, PFC, और HFC उत्सर्जन",
  "graph_074_title": "कार्बन डाइऑक्साइड हटाने के लिए भूमि",
  "graph_077_menu_title": "शुद्ध CO<sub>2</sub>&nbsp;निष्कासन के स्रोत—क्षेत्र",
  "graph_077_mini_title": "शुद्ध सीओ2 निष्कासन",
  "graph_077_title": "शुद्ध CO<sub>2</sub>&nbsp;निष्कासन . के स्रोत",
  "graph_078_mini_title": "ऊर्जा की लागत",
  "graph_078_title": "ऊर्जा की लागत",
  "graph_079_title": "कार्बन मूल्य",
  "graph_082_title": "बिजली का बाजार मूल्य",
  "graph_085_title": "ऊर्जा की कुल वार्षिक लागत",
  "graph_086_mini_title": "तापमान परिवर्तन",
  "graph_086_title": "तापमान परिवर्तन",
  "graph_087_title": "तापमान परिवर्तन °F",
  "graph_088_title": "सीओ2 एकाग्रता",
  "graph_089_title": "ग्रीनहाउस गैस एकाग्रता",
  "graph_090_title": "समुद्र तल से वृद्धि",
  "graph_091_title": "समुद्र के स्तर में वृद्धि—फीट",
  "graph_092_title": "महासागर अम्लीकरण",
  "graph_093_title": "करों और सब्सिडी से राजस्व और लागत",
  "graph_094_title": "वैश्विक जनसंख्या",
  "graph_095_title": "क्षेत्र द्वारा जनसंख्या",
  "graph_097_menu_title": "शुद्ध संचयी CO<sub>2</sub>&nbsp;प्रकार—क्षेत्र द्वारा हटाया गया",
  "graph_097_title": "शुद्ध संचयी CO<sub>2</sub>&nbsp;प्रकार द्वारा हटाया गया",
  "graph_101_title": "CO<sub>2</sub>&nbsp;वनरोपण से हटाना",
  "graph_102_title": "शुद्ध संचयी CO<sub>2</sub>&nbsp;उत्सर्जन",
  "graph_104_mini_title": "शुद्ध सीओ2 उत्सर्जन",
  "graph_104_title": "शुद्ध सीओ2 उत्सर्जन",
  "graph_106_title": "तापमान इतिहास",
  "graph_110_menu_title": "स्रोत द्वारा विद्युत उत्पादन की सीमांत लागत",
  "graph_110_mini_title": "बिजली की लागत",
  "graph_110_title": "बिजली उत्पादन की सीमांत लागत",
  "graph_111_title": "कार्बन डाइऑक्साइड हटाने के लिए भूमि-एकड़",
  "graph_112_menu_title": "ऊर्जा से वायु प्रदूषण",
  "graph_112_title": "ऊर्जा से वायु प्रदूषण - PM2.5 उत्सर्जन",
  "graph_113_menu_title": "स्रोत-क्षेत्र द्वारा ऊर्जा से वायु प्रदूषण",
  "graph_113_title": "स्रोत द्वारा ऊर्जा से वायु प्रदूषण — PM2.5",
  "graph_115_menu_title": "स्रोत द्वारा बिजली उत्पादन की कम कार्बन सीमांत लागत",
  "graph_115_title": "उत्पादन की कम कार्बन सीमांत लागत",
  "graph_117_title": "CO<sub>2</sub>-हटाने वाले बायोमास . उगाने के लिए भूमि",
  "graph_118_title": "CO<sub>2</sub>-हटाने वाले बायोमास . उगाने के लिए भूमि",
  "graph_119_title": "खनिज के लिए थोक सामग्री",
  "graph_120_menu_title": "% कम कार्बन स्रोतों से बिजली की खपत",
  "graph_120_title": "% लो-सी स्रोतों से बिजली की खपत",
  "graph_121_title": "CO<sub>2</sub>&nbsp;हटाने के साथ खेती के लिए भूमि—एकड़",
  "graph_124_title": "बढ़ते CO<sub>2</sub>-हटाने के लिए भूमि बायोमास—एकड़",
  "graph_125_title": "जीडीपी बनाम तापमान में कमी",
  "graph_126_title": "जलवायु प्रभाव से सकल घरेलू उत्पाद में कमी",
  "graph_129_title": "वैश्विक जीडीपी हानि",
  "graph_130_title": "जीडीपी प्रति व्यक्ति विकास दर",
  "graph_132_title": "सौर विद्युत इतिहास की सीमांत लागत",
  "graph_133_title": "कोयला, तेल और गैस इतिहास की प्राथमिक ऊर्जा मांग",
  "graph_134_title": "पवन और सौर इतिहास की प्राथमिक ऊर्जा मांग",
  "graph_135_title": "ग्रीनहाउस गैस शुद्ध उत्सर्जन इतिहास",
  "graph_138_title": "योग्यता स्रोतों से बिजली की खपत%",
  "graph_139_menu_title": "कार्बन की सामाजिक लागत-तालिका",
  "graph_139_title": "कार्बन की सामाजिक लागत",
  "graph_140_mini_title": "समुद्र तल से वृद्धि",
  "graph_140_title": "समुद्र के स्तर में वृद्धि-बाढ़ जोखिम मानचित्र",
  "graph_141_title": "बर्फ मुक्त आर्कटिक ग्रीष्मकाल की संभावना",
  "graph_142_title": "समुद्र के स्तर में वृद्धि के संपर्क में आने वाली जनसंख्या",
  "graph_143_title": "तापमान से फसल की उपज में कमी",
  "graph_144_title": "जलवायु सीमा का 50% से अधिक नुकसान करने वाली प्रजातियां",
  "graph_145_title": "अत्यधिक गर्मी से अतिरिक्त मौतें",
  "graph_actions_menu__copy_data_to_clipboard": "डेटा को क्लिपबोर्ड पर कॉपी करें",
  "graph_actions_menu__hide_description": "विवरण छुपाएं",
  "graph_actions_menu__hide_un_pledges": "संयुक्त राष्ट्र प्रतिज्ञा (एनडीसी) छुपाएं",
  "graph_actions_menu__show_description": "विवरण दिखाएं",
  "graph_actions_menu__show_un_pledges": "संयुक्त राष्ट्र प्रतिज्ञा दिखाएं (एनडीसी)",
  "graph_actions_menu__view_in_new_window": "नई विंडो में देखें",
  "graph_actions_menu__view_larger": "नई विंडो में देखें",
  "graph_dataset_label__66pct_chance_of_2degrees_c_or_15degrees_c": "2ºC या 1.5ºC . की 66% संभावना",
  "graph_dataset_label__afforestation_and_reforestation": "वनीकरण",
  "graph_dataset_label__agricultural_soil_carbon": "कृषि मिट्टी कार्बन",
  "graph_dataset_label__all_countries_follow_ndcs": "सभी देश एनडीसी का पालन करते हैं",
  "graph_dataset_label__area_of_india": "भारत का क्षेत्र",
  "graph_dataset_label__at_risk_to_annual_flooding_in_millions": "वार्षिक बाढ़ का खतरा<br>(लाखों में)",
  "graph_dataset_label__australia": "ऑस्ट्रेलिया",
  "graph_dataset_label__baseline": "आधारभूत",
  "graph_dataset_label__baseline_in_2100": "2100 में आधार-रेखा",
  "graph_dataset_label__beccs": "बीईसीसीएस",
  "graph_dataset_label__biochar": "बायोचार",
  "graph_dataset_label__bioenergy": "जैविक-ऊर्जा",
  "graph_dataset_label__birds": "पक्षियों",
  "graph_dataset_label__butterflies_and_moths": "तितलियाँ और पतंगे",
  "graph_dataset_label__central_america": "मध्य अमरीका",
  "graph_dataset_label__central_europe": "मध्य यूरोप",
  "graph_dataset_label__ch4": "सीएच4",
  "graph_dataset_label__china": "चीन",
  "graph_dataset_label__co2_emissions": "सीओ 2 उत्सर्जन",
  "graph_dataset_label__co2_removals": "CO2 निष्कासन",
  "graph_dataset_label__coal": "कोयला",
  "graph_dataset_label__coal_production": "कोयला उत्पादन",
  "graph_dataset_label__costs_of_subsidies": "सब्सिडी की लागत",
  "graph_dataset_label__current_scenario": "वर्तमान परिदृश्य",
  "graph_dataset_label__current_scenario_in_2100": "2100 में वर्तमान परिदृश्य",
  "graph_dataset_label__dietz_and_stern": "डिट्ज़ एंड स्टर्न",
  "graph_dataset_label__dragonflies_and_damselflies": "ड्रैगनफलीज़ और डैम्फ़्लिज़",
  "graph_dataset_label__east_asia": "पूर्व एशिया",
  "graph_dataset_label__en_roads_baseline": "एन-रोड्स बेसलाइन",
  "graph_dataset_label__en_roads_coal": "एन-रोड्स कोयला",
  "graph_dataset_label__en_roads_gas": "एन-रोड्स गैस",
  "graph_dataset_label__en_roads_ghg_net_emissions": "एन-रोड्स जीएचजी शुद्ध उत्सर्जन",
  "graph_dataset_label__en_roads_oil": "एन-रोड्स ऑयल",
  "graph_dataset_label__en_roads_solar": "एन-रोड्स सोलर",
  "graph_dataset_label__en_roads_wind": "एन-रोड्स विंड",
  "graph_dataset_label__eu": "यूरोपीय संघ",
  "graph_dataset_label__f_gases": "एफ-गैस",
  "graph_dataset_label__gas": "गैस",
  "graph_dataset_label__global": "वैश्विक",
  "graph_dataset_label__global_gdp_in_2024": "2024 में वैश्विक जीडीपी",
  "graph_dataset_label__gross_co2_removals": "सकल CO2 निष्कासन",
  "graph_dataset_label__hfc": "एचएफसी",
  "graph_dataset_label__hfc_follows_kigali": "एचएफसी किगाली का अनुसरण करता है",
  "graph_dataset_label__historical_ghg_net_emissions": "ऐतिहासिक जीएचजी शुद्ध उत्सर्जन",
  "graph_dataset_label__hydro": "हाइड्रो",
  "graph_dataset_label__iea": "आईईए",
  "graph_dataset_label__iea_coal": "आईईए कोयला",
  "graph_dataset_label__iea_gas": "आईईए गैस",
  "graph_dataset_label__iea_oil": "आईईए तेल",
  "graph_dataset_label__iea_solar": "आईईए सोलर",
  "graph_dataset_label__iea_wind": "आईईए विंड",
  "graph_dataset_label__india": "भारत",
  "graph_dataset_label__insects": "कीड़े",
  "graph_dataset_label__invertebrates": "अकशेरूकीय",
  "graph_dataset_label__irena": "इरिना",
  "graph_dataset_label__land_use_co2": "भू उपयोग CO2",
  "graph_dataset_label__lazard": "लाजार्ड",
  "graph_dataset_label__living_below_high_tide_line_in_millions": "उच्च ज्वार रेखा के नीचे रहना<br>(लाखों में)",
  "graph_dataset_label__maize": "मक्का",
  "graph_dataset_label__mammals": "स्तनधारियों",
  "graph_dataset_label__met_office": "मेट ऑफिस",
  "graph_dataset_label__mineralization": "खनिज",
  "graph_dataset_label__mineralization_rock": "खनिजकरण रॉक",
  "graph_dataset_label__n2o": "N2O",
  "graph_dataset_label__nasa": "NASA",
  "graph_dataset_label__nasa_upper_per_lower_95pct": "नासा ऊपरी/निचला 95%",
  "graph_dataset_label__net_revenue_minus_costs": "शुद्ध: राजस्व घटा लागत",
  "graph_dataset_label__new_zero": "नवीन शून्य",
  "graph_dataset_label__new_zero_carbon_baseline": "नवीन शून्य - कार्बन आधारभूत",
  "graph_dataset_label__north_america": "उत्तरी अमेरिका",
  "graph_dataset_label__northern_europe": "उत्तरी यूरोप",
  "graph_dataset_label__nuclear": "नाभिकीय",
  "graph_dataset_label__nuclear_baseline": "परमाणु आधार रेखा",
  "graph_dataset_label__oil": "तेल",
  "graph_dataset_label__other_cdr": "अन्य सीडीआर",
  "graph_dataset_label__other_developed": "अन्य विकसित",
  "graph_dataset_label__other_developing": "अन्य विकासशील",
  "graph_dataset_label__pfc": "पीएफसी",
  "graph_dataset_label__plants": "पौधे",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_at_least_once_before_2100": "बर्फ मुक्त आर्कटिक गर्मी की संभावना<br>2100 से पहले कम से कम एक बार",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2050": "बर्फ रहित आर्कटिक गर्मी की संभावना<br>2050 में",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2100": "बर्फ मुक्त आर्कटिक गर्मी की संभावना<br>2100 में",
  "graph_dataset_label__renewables": "नवीकरणीय ऊर्जा",
  "graph_dataset_label__revenue_from_taxes": "करों से राजस्व",
  "graph_dataset_label__rice": "चावल",
  "graph_dataset_label__sf6": "SF6",
  "graph_dataset_label__solar": "सौर",
  "graph_dataset_label__south_america": "दक्षिण अमेरिका",
  "graph_dataset_label__southeast_asia": "दक्षिण - पूर्व एशिया",
  "graph_dataset_label__southern_europe": "दक्षिणी यूरोप",
  "graph_dataset_label__soybean": "सोयाबीन",
  "graph_dataset_label__storage_cost": "भण्डारण लागत",
  "graph_dataset_label__today": "आज",
  "graph_dataset_label__transport_electric": "परिवहन (इलेक्ट्रिक)",
  "graph_dataset_label__us": "अमेरिका",
  "graph_dataset_label__us_gdp_in_2024": "2024 में यूएस जीडीपी",
  "graph_dataset_label__vertebrates": "रीढ़",
  "graph_dataset_label__wheat": "गेहूँ",
  "graph_dataset_label__wind": "हवा",
  "graph_dataset_label__wind_and_solar": "पवन और सौर",
  "graph_dataset_label__wind_and_solar_cost": "पवन और सौर लागत",
  "graph_value__percent": "{num}%",
  "graph_xaxis_label__temperature_change_from_1850___degrees_celsius": "1850 से तापमान परिवर्तन — डिग्री सेल्सियस",
  "graph_yaxis_label__billion_tons_per_year": "अरब टन/वर्ष",
  "graph_yaxis_label__billions_of_people": "अरबों लोग",
  "graph_yaxis_label__co2_equivalent_parts_per_million_ppm": "CO2 समकक्ष भाग प्रति मिलियन (पीपीएम)",
  "graph_yaxis_label__co2_parts_per_million_ppm": "CO2 भाग प्रति मिलियन (पीपीएम)",
  "graph_yaxis_label__degrees_celsius": "डिग्री सेल्सियस",
  "graph_yaxis_label__degrees_fahrenheit": "डिग्रीज़ फारेनहाइट",
  "graph_yaxis_label__dollars_per_gigajoule": "$/गीगाजूल",
  "graph_yaxis_label__dollars_per_kwh": "$/किलोवाट-आवर",
  "graph_yaxis_label__dollars_per_mwh": "$/ मेगावाट-आवर",
  "graph_yaxis_label__dollars_per_person_per_year": "$/व्यक्ति/वर्ष",
  "graph_yaxis_label__dollars_per_ton_co2": "$/टन CO2",
  "graph_yaxis_label__exajoule_per_trillion_dollars": "एक्साजूल/ट्रिलियन $",
  "graph_yaxis_label__exajoules_per_year": "एक्जाजौल/वर्ष",
  "graph_yaxis_label__feet_ft": "पैर (फीट)",
  "graph_yaxis_label__gigatons_co2": "गीगाटन CO2",
  "graph_yaxis_label__gigatons_co2_equivalent_per_year": "Gigatons CO2 समकक्ष/वर्ष",
  "graph_yaxis_label__gigatons_co2_per_year": "गीगाटन CO2/वर्ष",
  "graph_yaxis_label__kilograms_co2_per_mwh": "kgCO2/ मेगावाट-आवर",
  "graph_yaxis_label__megatons_ch4_per_year": "मेगाटन सीएच4/वर्ष",
  "graph_yaxis_label__megatons_co2_per_exajoule": "मेगाटन CO2/exajoule",
  "graph_yaxis_label__megatons_pm25_per_year": "मेगाटन पीएम2.5/वर्ष",
  "graph_yaxis_label__meters_m": "मीटर (एम)",
  "graph_yaxis_label__million_acres": "मिलियन एकड़",
  "graph_yaxis_label__million_hectares": "मिलियन हेक्टेयर",
  "graph_yaxis_label__pct_reduction_in_gdp": "जीडीपी में % कमी",
  "graph_yaxis_label__percent": "प्रतिशत",
  "graph_yaxis_label__percent_per_year": "प्रतिशत/वर्ष",
  "graph_yaxis_label__ph": "पीएच",
  "graph_yaxis_label__tons_co2_per_million_dollars_gdp": "टन CO2/मिलियन $ GDP",
  "graph_yaxis_label__tons_co2_per_year_per_person": "टन CO2/वर्ष/व्यक्ति",
  "graph_yaxis_label__trillion_dollars_per_year": "ट्रिलियन $/वर्ष",
  "input_001_label": "कोयला (कर/सब्सिडी)",
  "input_002_label": "कोयला कर/सब्सिडी प्रारंभ वर्ष",
  "input_003_label": "कोयला कर/सब्सिडी रोक वर्ष",
  "input_004_label": "कोयला संयंत्र त्वरित सेवानिवृत्ति",
  "input_007_label": "तेल (कर/सब्सिडी)",
  "input_008_label": "तेल कर/सब्सिडी प्रारंभ वर्ष",
  "input_009_label": "तेल कर/सब्सिडी रोक वर्ष",
  "input_010_label": "प्राकृतिक गैस (कर/सब्सिडी)",
  "input_011_label": "प्राकृतिक गैस कर/सब्सिडी प्रारंभ वर्ष",
  "input_012_label": "प्राकृतिक गैस कर/सब्सिडी रोक वर्ष",
  "input_016_label": "नवीकरणीय (कर/सब्सिडी)",
  "input_017_label": "नवीकरणीय कर/सब्सिडी प्रारंभ वर्ष",
  "input_018_label": "अक्षय कर/सब्सिडी रोक वर्ष",
  "input_019_label": "नवीकरणीय आर एंड डी सफलता लागत में कमी",
  "input_020_label": "नवीकरणीय सफलता वर्ष",
  "input_021_label": "भंडारण आर एंड डी सफलता लागत में कमी",
  "input_022_label": "संग्रहण सफलता वर्ष",
  "input_023_label": "जविक-ऊर्जा (कर/रियायत)",
  "input_024_label": "जविक-ऊर्जा टैक्स/सब्सिडी प्रारंभ वर्ष",
  "input_025_label": "जविक-ऊर्जा टैक्स/सब्सिडी समापन वर्ष",
  "input_026_label": "जैविक-ऊर्जा अनुसंधान में निवेश की कमी",
  "input_027_label": "बायोएनेर्जी सफलता वर्ष",
  "input_030_label": "परमाणु (कर/सब्सिडी)",
  "input_031_label": "परमाणु कर/सब्सिडी प्रारंभ वर्ष",
  "input_032_label": "परमाणु कर/सब्सिडी रोक वर्ष",
  "input_033_label": "परमाणु अनुसंधान एवं विकास सफलता लागत में कमी",
  "input_034_label": "परमाणु सफलता वर्ष",
  "input_035_label": "नवीन शून्य-कार्बन सफलता",
  "input_036_label": "नवीन शून्य-कार्बन सफलता वर्ष",
  "input_037_label": "व्यावसायीकरण के लिए नवीन शून्य-कार्बन समय",
  "input_038_label": "कोयले के सापेक्ष प्रारंभिक लागत",
  "input_039_label": "कार्बन मूल्य",
  "input_040_label": "वर्ष कार्बन मूल्य चरण में शुरू होता है",
  "input_041_label": "प्रारंभिक कार्बन मूल्य प्राप्त करने के लिए वर्ष",
  "input_042_label": "अंतिम कार्बन मूल्य (नीचे \"शुरू करने का वर्ष...\" समायोजित करें)",
  "input_043_label": "अंतिम कार्बन मूल्य प्राप्त करना शुरू करने का वर्ष",
  "input_044_label": "अंतिम कार्बन मूल्य प्राप्त करने के लिए वर्ष",
  "input_045_label": "उत्सर्जन प्रदर्शन मानक",
  "input_046_label": "उत्सर्जन प्रदर्शन मानक प्रारंभ वर्ष",
  "input_047_label": "नई इमारतों और उद्योग की ऊर्जा दक्षता",
  "input_048_label": "साल की शुरुआत",
  "input_050_label": "नए परिवहन की ऊर्जा दक्षता",
  "input_051_label": "साल की शुरुआत",
  "input_062_label": "अन्य ग्रीनहाउस गैसें वर्ष शुरू होती हैं",
  "input_063_action_label": "जनसंख्या",
  "input_063_label": "जनसंख्या (संयुक्त राष्ट्र परिदृश्य रेंज)",
  "input_064_label": "निकट अवधि की आर्थिक वृद्धि (प्रति व्यक्ति जीडीपी)",
  "input_065_label": "वृक्षारोपण पण के लिए उपयोग की जाने वाली उपलब्ध भूमि का प्रतिशत",
  "input_066_label": "वनरोपण प्रारंभ वर्ष",
  "input_067_label": "तकनीकी कार्बन निष्कासन (अधिकतम क्षमता का %)",
  "input_071_label": "डायरेक्ट एयर कैप्चर स्टार्ट ईयर",
  "input_072_label": "उन्नत खनिजकरण (अधिकतम क्षमता का %)",
  "input_073_label": "संवर्धित खनिजकरण प्रारंभ वर्ष",
  "input_074_label": "कृषि मृदा कार्बन ज़ब्ती (अधिकतम क्षमता का %)",
  "input_075_label": "कृषि मृदा कार्बन प्रारंभ वर्ष",
  "input_076_label": "बायोचार (अधिकतम क्षमता का %)",
  "input_077_label": "बायोचार प्रारंभ वर्ष",
  "input_078_label": "जलवायु संवेदनशीलता",
  "input_079_label": "महासागर मिश्रण",
  "input_080_label": "सीओ2 निषेचन",
  "input_082_label": "कार्बन चक्र भूमि और महासागर का उठाव",
  "input_084_label": "पर्माफ्रॉस्ट और क्लैथ्रेट से मीथेन उत्सर्जन पर तापमान का प्रभाव",
  "input_085_label": "पर्माफ्रॉस्ट और क्लैथ्रेट के लिए तापमान सीमा",
  "input_095_label": "बायोचार",
  "input_096_label": "कृषि मिट्टी कार्बन",
  "input_110_action_label": "निर्णायक व्यावसायीकरण समय (परमाणु)",
  "input_110_label": "नाभिकीय",
  "input_112_action_label": "निर्णायक व्यावसायीकरण समय (नवीकरणीय)",
  "input_112_label": "नवीकरणीय ऊर्जा",
  "input_117_action_label": "निर्णायक व्यावसायीकरण समय (वितरित बायोएनेर्जी)",
  "input_117_label": "जैविक-ऊर्जा",
  "input_131_action_label": "संयंत्र विकास समय (परमाणु)",
  "input_131_label": "विकास समय (परमाणु)",
  "input_132_action_label": "संयंत्र विकास समय (हाइड्रो)",
  "input_132_label": "हाइड्रो",
  "input_133_action_label": "संयंत्र विकास समय (नवीकरणीय)",
  "input_133_label": "नवीकरणीय ऊर्जा",
  "input_134_action_label": "संयंत्र विकास समय (नवीन शून्य-कार्बन)",
  "input_134_label": "नवीन शून्य-कार्बन",
  "input_139_action_label": "संयंत्र निर्माण समय (परमाणु)",
  "input_139_label": "नाभिकीय",
  "input_140_action_label": "संयंत्र निर्माण समय (हाइड्रो)",
  "input_140_label": "हाइड्रो",
  "input_141_action_label": "संयंत्र निर्माण समय (नवीकरणीय)",
  "input_141_label": "नवीकरणीय ऊर्जा",
  "input_142_action_label": "संयंत्र निर्माण समय (नया शून्य कार्बन)",
  "input_142_label": "न्यू जीरो-कार्बन",
  "input_155_label": "विद्युत मांग प्रतिक्रिया प्रौद्योगिकी के लिए अधिकतम क्षमता",
  "input_160_action_label": "स्रोत पर प्रवाह बाधा (हाइड्रो)",
  "input_160_label": "हाइड्रो",
  "input_166_action_label": "प्रगति अनुपात (कोयला)",
  "input_166_label": "कोयला",
  "input_167_action_label": "प्रगति अनुपात (तेल)",
  "input_167_label": "तेल",
  "input_168_action_label": "प्रगति अनुपात (गैस)",
  "input_168_label": "गैस",
  "input_169_action_label": "प्रगति अनुपात (बायोएनेर्जी)",
  "input_169_label": "जैविक-ऊर्जा",
  "input_170_action_label": "प्रगति अनुपात (परमाणु)",
  "input_170_label": "नाभिकीय",
  "input_171_action_label": "प्रगति अनुपात (नवीकरणीय)",
  "input_171_label": "नवीकरणीय ऊर्जा",
  "input_172_action_label": "प्रगति अनुपात (हाइड्रो)",
  "input_172_label": "हाइड्रो",
  "input_173_action_label": "प्रगति अनुपात (नया शून्य-कार्बन)",
  "input_173_label": "न्यू जीरो-कार्बन",
  "input_174_label": "भंडारण",
  "input_176_label": "विद्युत मांग प्रतिक्रिया प्रौद्योगिकी",
  "input_196_label": "कोयले के उपयोग में % कमी",
  "input_198_label": "तेल के उपयोग में % कमी",
  "input_200_label": "गैस के उपयोग में % कमी",
  "input_202_label": "कोयला उपयोग में % कमी प्रारंभ वर्ष",
  "input_203_label": "कोयला उपयोग बंद वर्ष में % कमी",
  "input_204_label": "तेल उपयोग में % कमी प्रारंभ वर्ष",
  "input_205_label": "तेल उपयोग स्टॉप ईयर में % कमी",
  "input_206_label": "गैस उपयोग में % कमी प्रारंभ वर्ष",
  "input_207_label": "गैस उपयोग स्टॉप ईयर में % कमी",
  "input_208_label": "विस्तृत सेटिंग्स का प्रयोग करें",
  "input_209_label": "विस्तृत सेटिंग्स का प्रयोग करें",
  "input_210_label": "विस्तृत सेटिंग्स का प्रयोग करें",
  "input_214_label": "वनीकरण के लिए अधिकतम उपलब्ध भूमि",
  "input_215_label": "कृषि भूमि के लिए आवश्यक भूमि कार्बन प्रति यूनिट हटाया गया",
  "input_218_label": "वनरोपण के लिए भूमि सुरक्षित करने का समय",
  "input_219_label": "वृक्षारोपण रोपण का समय",
  "input_221_label": "कोयला, तेल या गैस उपयोग समायोजन समय",
  "input_222_label": "कोयला",
  "input_223_label": "तेल",
  "input_224_label": "गैस",
  "input_225_label": "जैविक-ऊर्जा",
  "input_230_action_label": "स्रोत पर प्रवाह बाधा (पवन)",
  "input_230_label": "हवा",
  "input_231_action_label": "स्रोत पर प्रवाह बाधा (सौर)",
  "input_231_label": "सौर",
  "input_232_action_label": "स्रोत पर प्रवाह बाधा (भूतापीय)",
  "input_232_label": "जियोथर्मल",
  "input_233_action_label": "स्रोत पर प्रवाह बाधा (अन्य नवीकरणीय ऊर्जा)",
  "input_233_label": "अन्य अक्षय ऊर्जा",
  "input_235_label": "दीर्घकालिक आर्थिक विकास (प्रति व्यक्ति जीडीपी)",
  "input_236_label": "संक्रमण का समय",
  "input_237_label": "खनिजकरण अधिकतम क्षेत्र",
  "input_238_label": "खनिजकरण रॉक अनुप्रयोग",
  "input_239_label": "खनिजकरण की ऊर्जा तीव्रता",
  "input_240_label": "विशिष्ट खनिजकरण क्षमता",
  "input_241_label": "खनिजकरण को तैनात करने का समय",
  "input_242_label": "सकल घरेलू उत्पाद में अधिकतम कमी",
  "input_243_label": "जलवायु प्रभावों से सकल घरेलू उत्पाद में 1.5ºC की कमी",
  "input_245_label": "स्वच्छ बिजली मानक का प्रयोग करें",
  "input_246_label": "स्रोत जो स्वच्छ बिजली के रूप में योग्य हैं",
  "input_247_label": "क्वालिफाइंग स्रोतों से बिजली का लक्ष्य%",
  "input_248_label": "स्वच्छ बिजली मानक प्रारंभ वर्ष",
  "input_249_label": "स्वच्छ बिजली मानक प्राप्त करने के लिए वर्ष",
  "input_252_label": "सामाजिक छूट दर",
  "input_263_label": "नवीकरणीय ऊर्जा",
  "input_264_label": "नाभिकीय",
  "input_265_label": "नया शून्य-कार्बन",
  "input_266_label": "सीसीएस के साथ जीवाश्म ईंधन",
  "input_267_label": "जैविक-ऊर्जा",
  "input_268_label": "प्राकृतिक गैस",
  "input_284_label": "अन्य ग्रीनहाउस गैस लक्ष्यों को प्राप्त करने के लिए वर्ष",
  "input_285_label": "अंटार्कटिका में पिघली बर्फ की चादर से समुद्र के स्तर में वृद्धि में योगदान",
  "input_286_label": "ग्रीनलैंड में पिघली बर्फ की चादर से समुद्र के स्तर में वृद्धि में योगदान",
  "input_482_action_label": "प्रारंभिक संसाधन शेष (कोयला)",
  "input_482_label": "कोयला",
  "input_483_action_label": "प्रारंभिक संसाधन शेष (तेल)",
  "input_483_label": "तेल",
  "input_484_action_label": "प्रारंभिक संसाधन शेष (गैस)",
  "input_484_label": "गैस",
  "input_range__breakthrough": "दरार",
  "input_range__discouraged": "हतोत्साहित",
  "input_range__future_breakthrough": "भविष्य की सफलता",
  "input_range__high": "ऊँचा",
  "input_range__high_growth": "उच्च विकास",
  "input_range__highest_growth": "उच्चतम वृद्धि",
  "input_range__highly_increased": "अत्यधिक वृद्धि हुई",
  "input_range__highly_reduced": "अत्यधिक कम",
  "input_range__highly_subsidized": "अत्यधिक सब्सिडी वाला",
  "input_range__highly_taxed": "अत्यधिक कर",
  "input_range__huge_breakthrough": "बड़ी सफलता",
  "input_range__increased": "बढ़ाया हुआ",
  "input_range__low": "कम",
  "input_range__low_growth": "कम वृद्धि",
  "input_range__lowest_growth": "सबसे कम वृद्धि",
  "input_range__medium": "मध्यम",
  "input_range__medium_growth": "मध्यम वृद्धि",
  "input_range__near_term_breakthrough": "निकट अवधि की सफलता",
  "input_range__negative_growth": "नकारात्मक वृद्धि",
  "input_range__no_growth": "कोई विकास नहीं",
  "input_range__status_quo": "यथास्थिति",
  "input_range__subsidized": "सब्सिडी",
  "input_range__taxed": "कर लगाया",
  "input_range__very_high": "बहुत ऊँचा",
  "input_range__very_highly_taxed": "बहुत अधिक कर",
  "input_units__billion_people_in_2100": "2100 में अरब लोग",
  "input_units__degrees_c": "ºC",
  "input_units__dollars_per_boe": "$/बोए",
  "input_units__dollars_per_kwh": "$/किलोवाट-आवर",
  "input_units__dollars_per_mcf": "$/MCF",
  "input_units__dollars_per_ton": "$/टन",
  "input_units__dollars_per_ton_co2": "$/टन CO<sub>2</sub>",
  "input_units__ej_per_year": "ईजे/वर्ष",
  "input_units__gj_per_ton_rock": "जीजे/टन रॉक",
  "input_units__gtons_co2_per_year": "Gtons CO<sub>2</sub>/वर्ष",
  "input_units__mha": "हेक्टेयर",
  "input_units__mtons_per_ej": "एमटन/ईजे",
  "input_units__pct": "%",
  "input_units__pct_per_year": "%/साल",
  "input_units__ratio": "अनुपात",
  "input_units__ton_co2_per_tj": "टन CO<sub>2</sub>/TJ",
  "input_units__years": "वर्षों",
  "map__error_failed_to_load": "इस समय नक्शा लोड नहीं किया जा सका।",
  "map__map_year": "नक्शा वर्ष:",
  "map_slr__error_internet_required": "समुद्र के स्तर में वृद्धि के नक्शे के लिए एक स्थिर इंटरनेट कनेक्शन की आवश्यकता होती है।",
  "map_slr__loading": "क्लाइमेट सेंट्रल से नक्शा लोड हो रहा है…",
  "map_slr__map_type": "नक्शा प्रकार:",
  "map_slr__map_type_21st_century": "21 वीं सदी",
  "map_slr__map_type_21st_century_with_surge": "21वीं सदी में तूफ़ान बढ़ गया",
  "map_slr__map_type_longterm": "दीर्घकालिक संतुलन",
  "map_slr__meters": "{num} मी",
  "map_slr__storm_surge": "बढ़ता तूफान:",
  "menu__actions_and_outcomes": "क्रियाएँ और परिणाम",
  "menu__assumptions": "मान्यताओं",
  "menu__en_roads_overview": "एन-रोड्स अवलोकन",
  "menu__en_roads_training": "एन-रोड्स प्रशिक्षण",
  "menu__en_roads_user_guide": "एन-रोड्स यूजर गाइड",
  "menu__graph_selection": "ग्राफ चयन",
  "menu__graphs": "ग्राफ",
  "menu__help": "मदद",
  "menu__kaya_graphs": "काया रेखांकन",
  "menu__language": "भाषा",
  "menu__main_graphs": "मुख्य रेखांकन",
  "menu__metric_units": "मीट्रिक इकाइयां",
  "menu__miniature_graphs": "लघु रेखांकन",
  "menu__play_sounds": "ध्वनि खेलें",
  "menu__related_examples": "संबंधित उदाहरण",
  "menu__release_notes": "रिलीज नोट्स",
  "menu__reset_assumptions": "मान्यताओं को रीसेट करें",
  "menu__reset_policies": "नीतियां रीसेट करें",
  "menu__reset_policies_and_assumptions": "नीतियां और धारणाएं रीसेट करें",
  "menu__return_to_default_graphs": "डिफ़ॉल्ट ग्राफ़ पर लौटें",
  "menu__show_graph_tooltips": "ग्राफ़ टूलटिप्स दिखाएं",
  "menu__simulation": "सिमुलेशन",
  "menu__slider_information": "स्लाइडर जानकारी",
  "menu__support": "सहायता",
  "menu__us_units": "यू.एस. इकाइयां",
  "menu__uses_for_en_roads": "एन-रोड्स के लिए उपयोग",
  "menu__video_tours": "वीडियो टूर",
  "menu__view": "देखना",
  "menu_graphs__co2_emissions": "सीओ2 उत्सर्जन",
  "menu_graphs__final_energy_consumption_totals": "सीओ2 उत्सर्जन",
  "menu_graphs__final_energy_consumption_types": "अंतिम ऊर्जा खपत प्रकार",
  "menu_graphs__financial": "सीओ2 उत्सर्जन",
  "menu_graphs__greenhouse_gas_emissions": "ग्रीनहाउस गैस उत्सर्जन",
  "menu_graphs__impacts": "प्रभाव डालता है",
  "menu_graphs__model_comparison_history": "मॉडल तुलना—ऐतिहासिक",
  "menu_graphs__population_and_gdp": "जनसंख्या और जीडीपी",
  "menu_graphs__primary_energy_demand_totals": "प्राथमिक ऊर्जा मांग योग",
  "menu_graphs__primary_energy_demand_types": "प्राथमिक ऊर्जा मांग प्रकार",
  "menu_graphs__view_more_graphs": "और ग्राफ़ देखें",
  "outcome_13_label": "2100 के माध्यम से रियायती संचयी नुकसान",
  "outcome_13_units_metric": "ट्रिलियन $",
  "outcome_1_label": "2100 तक तापमान में वृद्धि",
  "outcome_1_units_metric": "सी",
  "outcome_1_units_us": "एफ",
  "outcome_2_label": "2100 में CO<sub>2</sub>&nbsp;सांद्रता",
  "outcome_2_units_metric": "पीपीएम",
  "outcome_3_label": "2100 में समुद्र-स्तर में वृद्धि",
  "outcome_3_units_metric": "एम",
  "outcome_3_units_us": "एम",
  "outcome_4_label": "संचयी परिहार CO<sub>2</sub>&nbsp;द्वारा 2100",
  "outcome_4_units_metric": "गिगाटन्स CO<sub>2</sub>",
  "policy_group_001_description": "कोयले के खनन और उसे बिजली संयंत्रों में जलाने को हतोत्साहित या प्रोत्साहित करें। कार्बन उत्सर्जन के साथ-साथ वायु प्रदूषकों के मामले में कोयला सबसे हानिकारक जीवाश्म ईंधन है जो स्वास्थ्य पर गंभीर प्रभाव डालता है। हालाँकि, यह विश्व स्तर पर ऊर्जा का एक प्रमुख स्रोत है, क्योंकि यह खदान और परिवहन के लिए अपेक्षाकृत सस्ता है।",
  "policy_group_001_example_1": "करों",
  "policy_group_001_example_2": "कम सब्सिडी",
  "policy_group_001_example_3": "वायु प्रदूषण",
  "policy_group_001_short_title": "कोयला",
  "policy_group_001_title": "कोयला",
  "policy_group_002_description": "ऊर्जा के लिए तेल की ड्रिलिंग, रिफाइनिंग और खपत को हतोत्साहित या प्रोत्साहित करें। तेल एक जीवाश्म ईंधन है जिसका व्यापक रूप से कारों, जहाजों और विमानों में उपयोग किया जाता है; इसका उपयोग उद्योग, हीटिंग और बिजली के लिए भी किया जाता है। तेल तक पहुंच ने बड़े संघर्षों को जन्म दिया है और तेल फैलने से पारिस्थितिकी तंत्र और पानी को खतरा हो सकता है।",
  "policy_group_002_example_1": "कम सब्सिडी",
  "policy_group_002_example_2": "पाइपलाइनों",
  "policy_group_002_example_3": "भंडाफोड़",
  "policy_group_002_short_title": "तेल",
  "policy_group_002_title": "तेल",
  "policy_group_003_description": "ऊर्जा के लिए ड्रिलिंग और प्राकृतिक गैस जलाने को हतोत्साहित या प्रोत्साहित करें। प्राकृतिक गैस एक जीवाश्म ईंधन है जिसका उपयोग बिजली, हीटिंग और उद्योग के लिए किया जाता है। जब जलाया जाता है, तो यह कार्बन डाइऑक्साइड (हालांकि कोयले और तेल से कम) छोड़ता है और अगर हवा में लीक हो जाता है, तो इसमें उच्च मात्रा में मीथेन होता है। प्राकृतिक गैस ड्रिलिंग बड़ी मात्रा में पानी का उपयोग करती है और प्रदूषण का कारण बन सकती है।",
  "policy_group_003_example_1": "तोड़ना",
  "policy_group_003_example_2": "पाइपलाइनों",
  "policy_group_003_example_3": "भंडाफोड़",
  "policy_group_003_short_title": "प्राकृतिक गैस",
  "policy_group_003_title": "प्राकृतिक गैस",
  "policy_group_004_description": "ऊर्जा पैदा करने के लिए पेड़ों, कचरे और कृषि फसलों के उपयोग को हतोत्साहित या प्रोत्साहित करें। बायोएनेर्जी जीवित कार्बनिक पदार्थों के ठोस (जैसे, लकड़ी के छर्रों), तरल पदार्थ (जैसे, इथेनॉल), या गैस (जैसे, अपघटन से मीथेन) के जलने, या दहन से उत्पन्न ऊर्जा है। विभिन्न प्रकार के स्रोत हैं, जिनमें से कुछ टिकाऊ हो सकते हैं और अन्य जो कोयले को जलाने से भी बदतर हो सकते हैं।",
  "policy_group_004_example_1": "जैविक-ईंधन",
  "policy_group_004_example_2": "महिला सशक्तिकरण",
  "policy_group_004_short_title": "जैविक-ऊर्जा",
  "policy_group_004_title": "जैविक-ऊर्जा",
  "policy_group_005_description": "सौर पैनलों, भूतापीय और पवन टरबाइनों के निर्माण को प्रोत्साहित या हतोत्साहित करना। अक्षय ऊर्जा में पवन, सौर, भू-तापीय, जल विद्युत, और अन्य प्रौद्योगिकियां शामिल हैं जो कार्बन डाइऑक्साइड उत्सर्जन या वायु प्रदूषण के बिना ऊर्जा का उत्पादन करती हैं। ध्यान दें कि परमाणु और बायोएनेर्जी को अलग-अलग माना जाता है।",
  "policy_group_005_example_1": "पवन, सौर, हाइड्रो",
  "policy_group_005_example_2": "स्वच्छ ताक़त",
  "policy_group_005_example_3": "सब्सिडी",
  "policy_group_005_short_title": "नवीकरणीय ऊर्जा",
  "policy_group_005_title": "नवीकरणीय ऊर्जा",
  "policy_group_006_description": "परमाणु ऊर्जा संयंत्रों के निर्माण को प्रोत्साहित या हतोत्साहित करना। परमाणु ऊर्जा उत्पादन कार्बन डाइऑक्साइड नहीं छोड़ता है, लेकिन यह अपशिष्ट पैदा करता है जिसे सदियों से प्रबंधित करना पड़ता है।",
  "policy_group_006_example_1": "विकिरण",
  "policy_group_006_example_2": "कूड़ा संचयन",
  "policy_group_006_short_title": "नाभिकीय",
  "policy_group_006_title": "नाभिकीय",
  "policy_group_007_description": "बिजली के बिल्कुल नए सस्ते स्रोत की खोज करें जो ग्रीनहाउस गैसों का उत्सर्जन नहीं करता है। कुछ लोग अनुमान लगाते हैं कि ऐसी सफलता परमाणु संलयन या थोरियम-आधारित परमाणु विखंडन हो सकती है, हालांकि, किसी भी नई ऊर्जा आपूर्ति से जुड़े अज्ञात जोखिम हैं। तय करें कि सफलता कब होगी, कोयले की तुलना में इसकी प्रारंभिक लागत, और व्यावसायीकरण और स्केल अप में कितनी देर होगी।",
  "policy_group_007_example_1": "थोरियम विखंडन",
  "policy_group_007_example_2": "परमाणु संलयन",
  "policy_group_007_short_title": "नवीन कार्बन-शून्यता",
  "policy_group_007_title": "न्यू जीरो-कार्बन",
  "policy_group_008_description": "एक वैश्विक कार्बन मूल्य निर्धारित करें जो ऊर्जा स्रोतों को अधिक महंगा बनाता है जो इस पर निर्भर करता है कि वे कितना कार्बन डाइऑक्साइड छोड़ते हैं, या एक स्वच्छ बिजली मानक या उत्सर्जन प्रदर्शन मानक बनाते हैं। ऊर्जा उत्पादक अपने ग्राहकों को अतिरिक्त लागत दे सकते हैं, इसलिए सबसे गरीब लोगों पर प्रभाव को कम करने के लिए नीति तैयार की जानी चाहिए।",
  "policy_group_008_example_1": "कार्बन मूल्य",
  "policy_group_008_example_2": "कैप एंड ट्रेड",
  "policy_group_008_short_title": "कार्बन मूल्य",
  "policy_group_008_title": "कार्बन मूल्य निर्धारण और ऊर्जा मानक",
  "policy_group_009_description": "वाहनों, शिपिंग, हवाई यात्रा और परिवहन प्रणालियों की ऊर्जा दक्षता में वृद्धि या कमी। ऊर्जा दक्षता में हाइब्रिड कार, विस्तारित सार्वजनिक परिवहन, और ऐसे तरीके शामिल हैं जिनसे लोग कम ऊर्जा का उपयोग करके अपने आस-पास घूम सकते हैं। अधिक ऊर्जा कुशल प्रथाओं को अपनाने से सार्वजनिक स्वास्थ्य में सुधार हो सकता है और धन की बचत हो सकती है।",
  "policy_group_009_example_1": "हाइब्रिड कारें",
  "policy_group_009_example_2": "चलने योग्यता",
  "policy_group_009_example_3": "सार्वजनिक परिवहन",
  "policy_group_009_short_title": "ऊर्जा दक्षता",
  "policy_group_009_title": "परिवहन ऊर्जा दक्षता",
  "policy_group_010_description": "नई इलेक्ट्रिक कारों, ट्रकों, बसों और ट्रेनों और संभवतः जहाजों और हवाई जहाजों की खरीद में वृद्धि करें। परिवहन के लिए इलेक्ट्रिक मोटर्स का उपयोग करने से ग्रीनहाउस गैस उत्सर्जन और वायु प्रदूषण को कम करने में मदद मिलती है यदि कम कार्बन स्रोतों वाली बिजली जैसे सौर और पवन से होती है।",
  "policy_group_010_example_1": "बिजली के वाहन",
  "policy_group_010_example_2": "बैटरी तकनीक",
  "policy_group_010_example_3": "चार्जिंग इंफ्रास्ट्रक्चर",
  "policy_group_010_short_title": "विद्युतीकरण",
  "policy_group_010_title": "परिवहन विद्युतीकरण",
  "policy_group_011_description": "इमारतों, उपकरणों और अन्य मशीनों की ऊर्जा दक्षता में वृद्धि या कमी। ऊर्जा दक्षता में अच्छी तरह से अछूता घरों का निर्माण और ऊर्जा कारखानों के उपयोग की मात्रा को कम करने जैसी चीजें शामिल हैं। ऊर्जा कुशल प्रथाएं कम ऊर्जा की जरूरतों के साथ-साथ उन इमारतों में लोगों के स्वास्थ्य में सुधार के माध्यम से पैसे बचा सकती हैं।",
  "policy_group_011_example_1": "हरी इमारतें",
  "policy_group_011_example_2": "कुशल उद्योग",
  "policy_group_011_example_3": "उर्जा संरक्षण",
  "policy_group_011_short_title": "ऊर्जा दक्षता",
  "policy_group_011_title": "भवन और उद्योग ऊर्जा दक्षता",
  "policy_group_012_description": "इमारतों, उपकरणों, हीटिंग सिस्टम और अन्य मशीनों में तेल या गैस जैसे ईंधन के बजाय बिजली का उपयोग बढ़ाएं। इलेक्ट्रिक मोटर्स का उपयोग केवल उत्सर्जन को कम करने और हवा की गुणवत्ता में सुधार करने में मदद करता है अगर बिजली कम कार्बन स्रोतों जैसे सौर और पवन से हो।",
  "policy_group_012_example_1": "बिजली की हीटिंग",
  "policy_group_012_example_2": "उपयोगिता-पैमाने की बैटरी",
  "policy_group_012_short_title": "विद्युतीकरण",
  "policy_group_012_title": "भवन और उद्योग विद्युतीकरण",
  "policy_group_013_description": "उच्च या निम्न जनसंख्या वृद्धि मान लें। जबकि जनसंख्या वृद्धि का एक अपेक्षित प्रक्षेपवक्र है, महिलाओं की शिक्षा और परिवार नियोजन तक पहुंच जैसे कदम हैं जो छोटे परिवारों में बदलाव में तेजी लाने के लिए दिखाए गए हैं, जो जनसंख्या वृद्धि को धीमा कर देंगे।",
  "policy_group_013_example_1": "महिला सशक्तिकरण",
  "policy_group_013_example_2": "प्रजनन दर",
  "policy_group_013_short_title": "जनसंख्या",
  "policy_group_013_title": "जनसंख्या",
  "policy_group_014_description": "उत्पादित वस्तुओं और प्रदान की गई सेवाओं में उच्च या निम्न वृद्धि मान लें। आर्थिक विकास को प्रति व्यक्ति सकल घरेलू उत्पाद (जीडीपी) में मापा जाता है और यह ऊर्जा खपत में एक प्रमुख चालक है। निरंतर जीडीपी विकास पर आधारित नहीं बल्कि आर्थिक ढांचे के माध्यम से लोगों की जरूरतों को पूरा करने के विकल्प मौजूद हैं।",
  "policy_group_014_example_1": "प्रति व्यक्ति सकल घरेलू उत्पाद",
  "policy_group_014_example_2": "सादगी आंदोलन",
  "policy_group_014_short_title": "आर्थिक विकास",
  "policy_group_014_title": "आर्थिक विकास",
  "policy_group_018_short_title": "प्रौद्योगिकीय",
  "policy_group_019_short_title": "वनोन्मूलन",
  "selector__custom": "रिवाज़",
  "selector__default": "चूक",
  "selector__select": "चुनना…",
  "share_by_email__enter_from_addr": "अपना ईमेल पता दर्ज करें",
  "share_by_email__enter_from_name": "अपना नाम दर्ज करें",
  "share_by_email__enter_note": "शीर्ष पर शामिल अतिरिक्त नोट (वैकल्पिक)",
  "share_by_email__enter_to_addr": "प्राप्तकर्ता ईमेल पता दर्ज करें",
  "share_by_email__failed": "परिदृश्य ईमेल भेजते समय कोई त्रुटि उत्पन्न हुई। कृपया पुन: प्रयास करें।",
  "share_by_email__from_label": "से",
  "share_by_email__invalid_from_addr": "एक वैध प्रेषक ईमेल पता दर्ज करें",
  "share_by_email__invalid_from_name": "अपना नाम दर्ज करें",
  "share_by_email__invalid_to_addr": "एक मान्य प्राप्तकर्ता ईमेल पता दर्ज करें",
  "share_by_email__note_label": "टिप्पणी",
  "share_by_email__preview_label": "पूर्वावलोकन",
  "share_by_email__privacy": "हम आपकी निजता का सम्मान करते हैं। इस फॉर्म में दर्ज की गई जानकारी का उपयोग केवल प्राप्तकर्ता को एक ईमेल भेजने के लिए किया जाता है।",
  "share_by_email__send": "भेजना",
  "share_by_email__succeeded": "परिदृश्य लिंक सफलतापूर्वक {toAddress} पर भेज दिया गया",
  "share_by_email__template_line1": "एक नया जलवायु नीति परिदृश्य आपके साथ साझा किया गया है।",
  "share_by_email__template_line2": "एन-रोड्स सिम्युलेटर के साथ बनाए गए कस्टम-निर्मित वैश्विक जलवायु परिदृश्य का लिंक यहां दिया गया है:",
  "share_by_email__template_line3": "इसकी जांच - पड़ताल करें।",
  "share_by_email__template_line4": "En-ROADS को <i>क्लाइमेट इंटरेक्टिव</i> और <i>MIT स्लोन सस्टेनेबिलिटी इनिशिएटिव</i> द्वारा विकसित किया गया है । अधिक जानकारी के लिए {link} पर जाएँ।",
  "share_by_email__template_subject": "आपके साथ साझा किया गया: एन-रोड्स जलवायु परिदृश्य",
  "share_by_email__to_label": "सेवा",
  "share_menu__copy_scenario_link": "कॉपी परिदृश्य लिंक",
  "share_menu__share_by_email": "ईमेल द्वारा साझा करें",
  "share_menu__share_on_facebook": "फेसबुक पर साझा करें",
  "share_menu__share_on_linked_in": "लिंक्डइन पर साझा करें",
  "share_menu__share_on_twitter": "ट्विटर पर साझा करें",
  "share_menu__share_your_scenario": "अपना परिदृश्य साझा करें",
  "temperature_box__increase_by_2100": "2100 तक तापमान में वृद्धि",
  "welcome__line1": "क्लाइमेट इंटरेक्टिव और एमआईटी स्लोन सस्टैनबिलिटी इनीशिएटिव द्वारा प्रस्तुत एन-रोड्स में आपका स्वागत है।"
}