export default {
  "__actions": "Maatregelen",
  "__actions_outcomes": "Maatregelen & Resultaten",
  "__assumptions": "Aannames",
  "__assumptions_intro": "Pas de belangrijkste aannames die het En-ROADS model beïnvloeden aan. Deze aanpassingen zijn alleen van toepassing op het huidige scenario, niet het basisscenario, zodat deze scenario's kunnen worden vergeleken.",
  "__beta": "BETA",
  "__cancel": "Ongedaan maken",
  "__close": "Sluiten",
  "__continue_to_en_roads": "Verder naar En-ROADS",
  "__detailed_settings_active": "gedetailleerde instellingen actief",
  "__en_roads_climate_ambassador_training": "Training voor En-ROADS Klimaatambassadeur",
  "__enter_full_screen": "modus volledig scherm",
  "__exit_full_screen": "Verlaat modus volledig scherm",
  "__full_screen_unavailable": "Modus volledig scherm niet beschikbaar",
  "__graph": "Grafiek",
  "__graph_dashed_baseline": "Stippellijnen representeren Uitgangsscenario",
  "__graph_data_copied_to_the_clipboard": "Grafiekdata gekopieerd naar het klembord",
  "__help": "Help",
  "__here_is_a_climate_scenario": "Hier is een klimaatscenario, gecreëerd met de #EnROADS simulator van @climateinteract en @MITSloanSusty",
  "__input_range_error_message": "Voeg een waarde in tussen {minValue} en {maxValue}.",
  "__invalid_url_params": "De link die u heeft geprobeerd kan niet correct geladen worden. Creëer het scenario opnieuw met de nieuwste versie.",
  "__kaya_graphs": "Kayagrafieken",
  "__no": "Nee",
  "__outcomes": "Resultaten",
  "__redo": "Opnieuw uitvoeren",
  "__register_your_event": "En-ROADS evenement registreren",
  "__related_examples": "Gerelateerde voorbeelden",
  "__related_graphs": "Gerelateerde grafieken",
  "__reload": "Herladen",
  "__replay_last_change": "Laatste verandering herhalen",
  "__reset_assumptions": "Aannames terugzetten",
  "__reset_graphs": "Grafieken terugzetten",
  "__reset_sliders": "Maatregelen & aannames terugzetten",
  "__scenario_link_copied_to_the_clipboard": "Scenariolink naar het klembord gekopieerd",
  "__sea_level_rise": "Zeespiegelstijging",
  "__show_all_regions": "Toon alle regio's…",
  "__show_main_graphs": "Hoofdgrafieken tonen",
  "__show_miniature_graphs": "Miniatuurgrafieken tonen",
  "__show_more": "Meer tonen…",
  "__undo": "Ongedaan maken",
  "__unsupported_browser": "En-ROADS werkt op dit moment niet op Android tablets. Op Windows PCs met touch screen werkt En-ROADS met touch pad, maar niet met touch screen.",
  "__url_input_change_warning": "De scenariolink bevat instellingen die in de huidige versie van En-ROADS niet werken. Deze instellingen zijn teruggezet op hun standaardwaarde:",
  "__url_input_value_warning": "De scenariolink bevat waardes die buiten het bereik vallen. Deze schuifjes zijn teruggezet op de huidige standaardinstellingen:",
  "__yes": "Ja",
  "advanced_section_title__air_and_water_fuel_limits": "Lucht en water brandstoflimieten",
  "advanced_section_title__air_and_water_hydrogen_deployment": "Lucht en Water toepassing van waterstof",
  "advanced_section_title__buildings_and_industry_electrification": "Elektrificering van gebouwen en industrie",
  "advanced_section_title__buildings_and_industry_hydrogen_deployment": "Inzet van waterstof in gebouwen & industrie",
  "advanced_section_title__carbon_pricing": "Koolstofprijs",
  "advanced_section_title__clean_electricity_standard": "Norm voor schone elektriciteit",
  "advanced_section_title__emissions_performance_standard": "Uitstootnorm",
  "advanced_section_title__equipment_fuel_limits": "Verkooplimiet voor brandstof",
  "advanced_section_title__food_choices": "Voedselkeuzes",
  "advanced_section_title__hydrogen_for_energy_and_storage_of_wind_and_solar_electricity": "Waterstof als energiebron en opslag van wind- en zonne-energie",
  "advanced_section_title__other_storage_technologies_for_wind_and_solar_electricity": "Andere opslagtechnologie voor wind- en zonne-energie",
  "advanced_section_title__road_and_rail_electrification": "Elektrificering van transport per weg en spoor",
  "advanced_section_title__road_and_rail_fuel_limits": "Brandstoflimieten voor transport per weg en spoor",
  "assumption_category_title__carbon_capture_and_removals": "Koolstof afvangen en opslaan",
  "assumption_category_title__earth_system": "Aardsysteem",
  "assumption_category_title__economy": "Economie",
  "assumption_category_title__energy": "Energie",
  "assumption_group_title__afforestation_and_reforestation": "Bebossing en herbebossing",
  "assumption_group_title__agricultural_carbon_dioxide_removal": "Koolstofverwijdering in landbouw",
  "assumption_group_title__agriculture": "Landbouw",
  "assumption_group_title__air_pollution_from_energy": "Luchtvervuiling van energie",
  "assumption_group_title__bioenergy": "Bio-energie",
  "assumption_group_title__breakthrough_commercialization_time": "Tijd tussen doorbraak en commercieel gebruik",
  "assumption_group_title__carbon_dioxide_capture_and_transport": "Koolstofdioxide afvangst en transport",
  "assumption_group_title__carbon_dioxide_storage": "Koolstofdioxide opslag",
  "assumption_group_title__climate_system_sensitivities": "Gevoeligheid van het klimaatsysteem",
  "assumption_group_title__direct_air_carbon_capture_and_storage_daccs": "Direct air capture en opslag (DACCS)",
  "assumption_group_title__economic_impact_of_climate_change": "Economische impact van klimaatverandering",
  "assumption_group_title__electricity_storage_and_demand_response": "Elektriciteitsopslag en vraagsturing",
  "assumption_group_title__electrification_and_energy_efficiency": "Elektrificatie",
  "assumption_group_title__energy_supply_policy_timing": "Timing van beleid",
  "assumption_group_title__energy_supply_progress_ratios": "Vooruitgangsverhouding",
  "assumption_group_title__forest_fires": "Bosbranden",
  "assumption_group_title__hydrogen": "Waterstof",
  "assumption_group_title__industrial_feedstocks": "Industriële grondstoffen",
  "assumption_group_title__initial_fossil_fuel_resource_remaining": "Initiële voorraad fossiele brandstof",
  "assumption_group_title__land_carbon_and_methane_cycles": "Koolstof- en methaancyclus van de bodem",
  "assumption_group_title__methane_n2o_and_f_gases": "Methaan, N<sub>2</sub>O en F-gassen",
  "assumption_group_title__mineralization": "Mineralisatie",
  "assumption_group_title__plant_construction_time": "Bouwtijd energiecentrale",
  "assumption_group_title__plant_development_time": "Ontwikkelingstijd energiecentrale",
  "assumption_group_title__renewables_flow_constraint_on_source": "Beperking op hernieuwbare energie bij de bron",
  "assumption_group_title__sea_level_rise": "Zeespiegelstijging",
  "assumptions__preset": "Standaard:",
  "assumptions__related_graph": "Gerelateerde grafiek:",
  "basic_section_header__buildings_and_industry": "Gebouwen en Industrie",
  "basic_section_header__carbon_removal": "CO<sub>2</sub>-verwijdering",
  "basic_section_header__energy_supply": "Energievoorziening",
  "basic_section_header__growth": "Groei",
  "basic_section_header__other_sources_of_greenhouse_gases": "Andere Bronnen van Broeikasgassen",
  "basic_section_header__transport": "Transport",
  "data_table_139_footnote": "Deze waardes hangen af van aannames die in de instellingen onder <a href=\"#\">Economische Impact</a> kunnen worden aangepast:",
  "data_table_row_001_label": "Sociale Kosten van Koolstof in {year}",
  "data_table_row_002_label": "Verdisconteerde Cumulatieve Schade tot 2100",
  "data_table_units__per_ton_co2": "/ ton CO<sub>2</sub>",
  "data_table_units__trillion": "biljoen",
  "data_table_value__dollars": "${num}",
  "graph_001_mini_title": "Bronnen van Primaire Energie",
  "graph_001_title": "Globale Bronnen van Primaire Energie",
  "graph_002_menu_title": "Globale Bronnen van Primaire Energie—Oppervlakte",
  "graph_002_mini_title": "Bronnen van Primaire Energie",
  "graph_002_title": "Globale Bronnen van Primaire Energie",
  "graph_003_title": "Kool - Primaire Energiebehoefte",
  "graph_005_title": "Olie, Primaire Energiebehoefte",
  "graph_006_menu_title": "Olie, Primaire Energiebehoefte—Oppervlakte",
  "graph_006_title": "Olie, Primaire Energiebehoefte",
  "graph_007_title": "Aardgas, Primaire Energiebehoefte",
  "graph_009_title": "Bio-energie, Primaire Energiebehoefte",
  "graph_011_title": "Hernieuwbare Energie, Primaire Behoefte",
  "graph_012_title": "Nucleaire Energie, Primaire Energiebehoefte",
  "graph_013_title": "Nieuwe Zero-Carbon Energiebron, Primaire Behoefte",
  "graph_018_title": "Totale Primaire Energie",
  "graph_024_menu_title": "Marginale Kosten van Wind- en Zonne-energie—Oppervlakte",
  "graph_024_title": "Marginale Kosten Wind- en Zonne-energie",
  "graph_026_title": "Koolstofintensiteit van Primaire Energie",
  "graph_028_title": "Koolstofintensiteit Primaire Elektrische Energie",
  "graph_029_mini_title": "Energievraag",
  "graph_029_title": "Eindverbruik van Energiebronnen",
  "graph_030_title": "Eindverbruik per Energiebron",
  "graph_031_menu_title": "Eindverbruik per Energiebron—Oppervlakte",
  "graph_031_title": "Eindverbruik per Energiebron",
  "graph_033_title": "Eindverbruik van Kolen",
  "graph_034_title": "Eindverbruik van Olie",
  "graph_035_title": "Eindverbruik van Aardgas",
  "graph_036_title": "Eindverbruik van Bio-energie",
  "graph_037_title": "Eindverbruik van Kernenergie",
  "graph_038_title": "Eindverbruik van Hernieuwbare Energie",
  "graph_039_title": "Eindverbruik van New Zero-Carbon",
  "graph_040_title": "Eindverbruik Koolstofarme Bronnen",
  "graph_041_menu_title": "Elektrisch Eindenergieverbruik per Bron—Oppervlakte",
  "graph_041_title": "Elektrische Eindenergieverbruik per Bron",
  "graph_042_menu_title": "Eindverbruik per Eindgebruik—Oppervlak",
  "graph_042_title": "Eindverbruik per Eindgebruik",
  "graph_043_title": "% Eindverbruik Hernieuwbare Energie",
  "graph_045_title": "% Bestaande Apparatuur in Gebouwen & Industrie per Energiebron",
  "graph_046_title": "% Bestaand Transport per Energiebron",
  "graph_047_mini_title": "Koolstofintensiteit van Eindenergie",
  "graph_047_title": "Koolstofintensiteit van Eindenergie",
  "graph_048_title": "Koolstofintensiteit van Elektrische Eindenergie",
  "graph_051_mini_title": "BBP per hoofd van de bevolking",
  "graph_051_title": "BBP per hoofd van de bevolking",
  "graph_052_title": "BBP per hoofd van de bevolking per regio",
  "graph_053_title": "Energie-intensiteit van het BBP",
  "graph_054_title": "Bruto Wereldproduct",
  "graph_055_title": "CO<sub>2</sub>&nbsp;Uitstoot van Energie en Industrie per Bron",
  "graph_057_title": "CO<sub>2</sub>&nbsp;Uitstoot en Verwijdering",
  "graph_058_title": "CO<sub>2</sub>&nbsp;Uitstoot per Persoon",
  "graph_059_title": "Koolstofintensiteit van het BBP",
  "graph_061_mini_title": "CO<sub>2</sub>&nbsp;Uitstoot van Energie",
  "graph_061_title": "CO<sub>2</sub>&nbsp;Uitstoot van Energie en Industrie",
  "graph_062_mini_title": "Broeikasgassen Netto Uitstoot",
  "graph_062_title": "Netto Uitstoot Broeikasgassen",
  "graph_063_menu_title": "Netto Uitstoot Broeikasgassen per Gas—Oppervlakte",
  "graph_063_mini_title": "BKG Netto Uitstoot door&nbsp;Gas",
  "graph_063_title": "Netto Uitstoot Broeikasgassen per Gas",
  "graph_065_title": "Uitstoot van Niet-CO<sub>2</sub>&nbsp;Broeikasgassen",
  "graph_067_title": "Methaanuitstoot",
  "graph_068_title": "Uitstoot van N<sub>2</sub>O",
  "graph_069_title": "Uitstoot van F-gassen per soort",
  "graph_073_title": "Antropogene CO<sub>2</sub>&nbsp;Verwijdering",
  "graph_074_title": "Land voor Verwijdering van Koolstofdioxide",
  "graph_075_title": "Netto CO<sub>2</sub>&nbsp;Emissies van Landgebruik zonder Bio-energie",
  "graph_076_title": "Netto CO<sub>2</sub>&nbsp;Emissies van Landgebruik",
  "graph_077_menu_title": "Bronnen van Antropogene CO<sub>2</sub>&nbsp;Verwijdering—Oppervlakte",
  "graph_077_mini_title": "CO<sub>2</sub>&nbsp;Verwijdering",
  "graph_077_title": "Bronnen van Antropogene CO<sub>2</sub>&nbsp;Verwijdering",
  "graph_078_mini_title": "Energieprijs",
  "graph_078_title": "Gemiddelde Energieprijs voor Consumenten",
  "graph_079_title": "Koolstofprijs",
  "graph_082_title": "Marktprijs van Elektriciteit",
  "graph_085_title": "Totale Jaarlijkse Energie-uitgaven",
  "graph_086_mini_title": "Temperatuur",
  "graph_086_title": "Temperatuurverandering",
  "graph_087_title": "Temperatuurverandering °F",
  "graph_088_title": "CO<sub>2</sub>&nbsp;Concentratie",
  "graph_089_title": "Concentratie van Broeikasgassen",
  "graph_090_title": "Zeespiegelstijging",
  "graph_091_title": "Zeespiegelstijging—in voet",
  "graph_092_title": "Oceaanverzuring",
  "graph_093_title": "Inkomsten & Kosten Belastingen & Subsidies",
  "graph_094_title": "Wereldbevolking",
  "graph_095_title": "Bevolking per Regio",
  "graph_097_menu_title": "Cumulatieve Antropogene CO<sub>2</sub>&nbsp;Verwijderd per Type—Oppervlak",
  "graph_097_title": "Cumulatieve Antropogene CO<sub>2</sub>&nbsp;Verwijderd per Type",
  "graph_101_title": "CO<sub>2</sub>&nbsp;Verwijdering door Bebossing en Herbebossing",
  "graph_102_title": "Netto Cumulatieve CO<sub>2</sub>&nbsp;Uitstoot",
  "graph_104_mini_title": "CO<sub>2</sub>&nbsp;Netto Uitstoot",
  "graph_104_title": "Netto CO<sub>2</sub>&nbsp;Uitstoot",
  "graph_106_title": "Temperatuurverloop",
  "graph_110_menu_title": "Marginale Kosten van Elektriciteitsproductie per Bron",
  "graph_110_mini_title": "Kosten van Elektriciteit",
  "graph_110_title": "Marginale Kosten van Elektriciteitsproductie",
  "graph_111_title": "Landoppervlak voor Verwijdering CO<sub>2</sub>—Acre",
  "graph_112_menu_title": "Luchtvervuiling door Energieopwekking",
  "graph_112_title": "Luchtvervuiling Energieopwekking — PM2.5 Uitstoot",
  "graph_113_menu_title": "Luchtvervuiling door Energieopwekking per Bron—Oppervlakte",
  "graph_113_title": "Luchtvervuiling Energieopwekking — PM2.5",
  "graph_115_menu_title": "Marginale Kosten van Elektriciteitsproductie van Koolstofarme Bronnen per Bron",
  "graph_115_title": "Marginale Kosten Koolstofarme Energieproductie",
  "graph_117_menu_title": "Land benodigd voor groei van biomassa voor CO<sub>2</sub>-verwijdering—Oppervlakte",
  "graph_117_title": "Land voor Groei Biomassa voor CO<sub>2</sub>-Verwijdering",
  "graph_118_title": "Land voor Landbouw met CO<sub>2</sub>&nbsp;Verwijdering",
  "graph_119_title": "Bulkmateriaal voor Mineralisering",
  "graph_120_menu_title": "% Elektriciteitsgebruik van Koolstofarme Bronnen",
  "graph_120_title": "% Elektriciteitsgebruik Koolstofarme Bronnen",
  "graph_121_title": "Land voor Landbouw met CO<sub>2</sub>&nbsp;Verwijdering—Acres",
  "graph_124_menu_title": "Land benodigd voor groei van biomassa voor CO<sub>2</sub>-verwijdering—Oppervlakte",
  "graph_124_title": "Land voor Groei Biomassa voor CO<sub>2</sub>-Verwijdering—Acres",
  "graph_125_title": "Afname in BBP vs. Temperatuur",
  "graph_126_title": "Afname in BBP door Klimaatimpact",
  "graph_127_title": "CO<sub>2</sub>&nbsp;Transportcapaciteit",
  "graph_128_menu_title": "Cumulatieve ondergronds opgeslagen CO<sub>2</sub>—Oppervlak",
  "graph_128_title": "Cumulatieve ondergronds opgeslagen CO<sub>2</sub>",
  "graph_129_title": "Globaal Verlies van BBP",
  "graph_130_title": "Groeisnelheid van BBP per Hoofd",
  "graph_132_title": "Verloop Marginale Kosten Zonne-energie",
  "graph_133_title": "Verloop Primaire Energievraag Kool, Olie en Gas",
  "graph_134_title": "Verloop Primaire Energievraag Wind- en Zonne-energie",
  "graph_135_title": "Verloop van Netto Uitstoot Broeikasgassen",
  "graph_138_title": "% Elektriciteitsverbruik Gekwalificeerde Bronnen",
  "graph_139_menu_title": "Sociale kosten van Klimaatverandering—Tabel",
  "graph_139_title": "Sociale Kosten van Klimaatverandering",
  "graph_140_mini_title": "Zeespiegelstijging",
  "graph_140_title": "Zeespiegelstijging—Overstromingsrisicokaart",
  "graph_141_title": "Kans op IJsvrije Arctische Zomer",
  "graph_142_title": "Bevolking Blootgesteld aan Zeespiegelstijging",
  "graph_143_title": "Afname van Oogst door Opwarming",
  "graph_144_title": "Soorten die meer dan 50% van hun klimaatregio verliezen",
  "graph_145_title": "Doden door Extreme Hitte per Regio",
  "graph_146_title": "Cumulatieve Netto CO<sub>2</sub>&nbsp;Uitstoot van Bio-energie uit Bos",
  "graph_147_title": "Bosoppervlak per Leeftijd",
  "graph_148_title": "Bosoppervlak",
  "graph_149_title": "Landbouwoppervlak",
  "graph_151_menu_title": "Bioenergie Primaire Energiebehoefte per Grondstof—Oppervlakte",
  "graph_151_title": "Bio-energie Primaire Energiebehoefte per Grondstof",
  "graph_152_menu_title": "Methaanuitstoot per Bron—Oppervlakte",
  "graph_152_title": "Methaanuitstoot per Bron",
  "graph_153_menu_title": "N<sub>2</sub>O Uitstoot per Bron—Oppervlakte",
  "graph_153_title": "N<sub>2</sub>O Uitstoot per Bron",
  "graph_154_title": "Bruto CO<sub>2</sub>&nbsp;Uitstoot van Bio-energie uit Bos",
  "graph_156_title": "Netto CO<sub>2</sub>&nbsp;Uitstoot van Bio-energie uit Bomen",
  "graph_157_menu_title": "CO<sub>2</sub>&nbsp;Verwijdering per Soort—Oppervlakte",
  "graph_157_title": "CO<sub>2</sub>&nbsp;Verwijdering per Soort",
  "graph_159_menu_title": "Primaire Energie van Brandstof Inclusief CCS—Oppervlak",
  "graph_159_title": "Primaire Energie van Brandstof Inclusief CCS",
  "graph_160_menu_title": "Primaire Elektrische Energie Inclusief CCS—Oppervlak",
  "graph_160_title": "Primaire Elektrische Energie Inclusief CCS",
  "graph_161_menu_title": "CO<sub>2</sub>&nbsp;opgeslagen door CCS per soort—Oppervlakte",
  "graph_161_title": "CO<sub>2</sub>&nbsp;Opgeslagen door CCS per Bron",
  "graph_163_title": "CO<sub>2</sub>&nbsp;Verwijdering door Land",
  "graph_164_menu_title": "CO<sub>2</sub>&nbsp;uitstoot van Kolen opgeslagen door CCS—Oppervlak",
  "graph_164_title": "CO<sub>2</sub>&nbsp;Uitgestoten door Kolen en Opgeslagen met CCS",
  "graph_165_menu_title": "CO<sub>2</sub>&nbsp;uitstoot van Olie—Oppervlak",
  "graph_165_title": "CO<sub>2</sub>&nbsp;Uitgestoten door Olie",
  "graph_166_menu_title": "CO<sub>2</sub>&nbsp;uitstoot van Gas opgeslagen door CCS—Oppervlak",
  "graph_166_title": "CO<sub>2</sub>&nbsp;Uitgestoten door Aardgas en Opgeslagen met CCS",
  "graph_168_title": "CO<sub>2</sub>&nbsp;Uitstoot van Fossiele Brandstoffen",
  "graph_169_title": "Ontbossing",
  "graph_171_title": "Koolstofdichtheid van Bossen",
  "graph_175_menu_title": "Ontbossing en Ernstige Aantasting van Bossen — Oppervlak",
  "graph_175_title": "Ontbossing en Ernstige Aantasting van Bos",
  "graph_177_menu_title": "Landgebruik voor Bio-energie—Oppervlak",
  "graph_177_title": "Landgebruik voor Bio-energie",
  "graph_178_title": "Ontbossing en Ernstige Aantasting van Bos",
  "graph_183_title": "Gewasopbrengst",
  "graph_185_title": "Percentage Dierlijke Voeding",
  "graph_191_menu_title": "Bruto CO<sub>2</sub>&nbsp;Uitstoot van Bossen—Oppervlak",
  "graph_191_title": "Bruto CO<sub>2</sub>&nbsp;Uitstoot van Bossen",
  "graph_192_title": "Kosten van Fossiele CCS",
  "graph_194_title": "Energiegebruik voor Koolstofafvangst en -opslag",
  "graph_195_title": "Primaire Energie met CCS per Bron",
  "graph_196_title": "% Verkoop Transport per Energiebron",
  "graph_197_title": "% Aankoop Apparatuur in Gebouwen & Industrie per Energiebron",
  "graph_204_menu_title": "CO<sub>2</sub>&nbsp;uitstoot van Bioenergie opgeslagen door CCS—Oppervlak",
  "graph_204_title": "CO<sub>2</sub>&nbsp;uitstoot van Bioenergie opgeslagen door CCS",
  "graph_205_title": "Totale Kosten/Jaar van Koolstofafvangst en -Opslag",
  "graph_207_menu_title": "Kolen - Primaire Behoefte per Soort en CCS—Oppervlakte",
  "graph_207_title": "Kolen - Primaire Energievraag per Soort en CCS",
  "graph_208_menu_title": "Aardgas - Primaire Vraag per Gebruikssoort en CCS—Oppervlakte",
  "graph_208_title": "Aardgas - Primaire Vraag per Gebruikssoort en CCS",
  "graph_209_menu_title": "Bio-energie Primaire Vraag per Gebruikssoort en CCS—Oppervlakte",
  "graph_209_title": "Bio-energie - Primaire Vraag per Gebruikssoort en CCS",
  "graph_211_menu_title": "Koolstof in Bossen—Oppervlak",
  "graph_211_title": "Koolstof in Bossen",
  "graph_220_caption_1850": "Bij <span class=\"caption-value\">{temperature}</span> vonden<br>hittegolven<br>waarschijnlijk plaats<br>in <span class=\"caption-value\">1 jaar</span><br>van de 50",
  "graph_220_caption_future": "Bij <span class=\"caption-value\">{temperature}</span> zullen<br>hittegolven<br>waarschijnlijk plaatsvinden<br>in <span class=\"caption-value\">{years} jaar</span><br>van de 50",
  "graph_220_caption_today": "Bij <span class=\"caption-value\">{temperature}</span> vinden<br>hittegolven<br>nu waarschijnlijk plaats<br>in <span class=\"caption-value\">{years} jaar</span><br>van de 50",
  "graph_220_title": "Frequentie van extreme hitte",
  "graph_224_title": "Marktprijs van olie",
  "graph_225_title": "Marktprijs van aardgas",
  "graph_227_title": "Kosten van Direct Air Capture en Opslag",
  "graph_228_title": "Kosten van Bioenergie CCS",
  "graph_230_title": "Methaanconcentratie",
  "graph_233_menu_title": "Opslagcapaciteit per Technologie—Oppervlakte",
  "graph_233_title": "Geïnstalleerde Opslagcapaciteit per Technologie",
  "graph_234_menu_title": "Opslagcapaciteit van energie per tijdsduur—Oppervlakte",
  "graph_234_title": "Geïnstalleerde Opslagcapaciteit per Tijdsduur",
  "graph_235_title": "Gemiddelde Kosten van Energie-opslag",
  "graph_240_title": "Nucleaire Capaciteit",
  "graph_241_title": "Capaciteit van hernieuwbare energiebronnen",
  "graph_246_title": "Primaire Energie van Fossiele Brandstoffen",
  "graph_247_menu_title": "Hernieuwbare Energiegebruik per Soort—Oppervlak",
  "graph_247_title": "Hernieuwbare Energiegebruik per Soort",
  "graph_249_title": "% Elektriciteit van Variabele Duurzame Bronnen",
  "graph_251_title": "Dagen met Extreme Hitte—Kaart",
  "graph_252_title": "Dagen met Risico op Bosbrand—Kaart",
  "graph_253_title": "Dagen met Extreme Luchtvochtigheid en Hitte—Kaart",
  "graph_257_title": "Ecosysteemveranderingen door Opwarming",
  "graph_258_title": "Methaanuitstoot per Persoon",
  "graph_259_title": "Methaanintensiteit van het BBP",
  "graph_260_title": "Methaanintensiteit van Landbouw",
  "graph_261_title": "Totale Landbouwproductie",
  "graph_262_title": "Methaanintensiteit van Primaire Energie",
  "graph_263_title": "Methaanintensiteit van Afval",
  "graph_265_menu_title": "Methaanuitstoot van Energie per Bron—Oppervlakte",
  "graph_265_title": "Methaanemissies per Energiebron",
  "graph_269_title": "Uitbreiding van Dor Land door Opwarming",
  "graph_270_title": "Bevolking Blootgesteld aan Orkanen en Tyfonen",
  "graph_275_title": "Sterfgevallen door Extreme Hitte",
  "graph_278_title": "Verlies van Oceaanleven door Opwarming",
  "graph_279_title": "Risico op Uitsterven van Inheemse Soorten",
  "graph_280_title": "Verlies van Arbeid Buiten door Extreme Hitte",
  "graph_281_title": "Extra Blootstelling aan Malaria en Dengue door Opwarming",
  "graph_282_menu_title": "Uitstoot van F-gas per bron—Oppervlakte",
  "graph_282_title": "Uitstoot van F-gas per Bron",
  "graph_283_menu_title": "Cumulatieve uitstoot van F-gas—Oppervlakte",
  "graph_283_title": "Cumulatieve uitstoot van F-gas",
  "graph_284_title": "Marktprijs van Kolen",
  "graph_285_title": "Marktprijs van Bioenergie",
  "graph_287_title": "Afname Voedingswaarde Gewassen door CO<sub>2</sub>&nbsp;Concentratie",
  "graph_289_title": "Eindverbruik van Elektriciteit",
  "graph_290_menu_title": "Waterstofproductie per Soort—Oppervlak",
  "graph_290_title": "Waterstofproductie per Soort",
  "graph_292_title": "Bevolking blootgesteld aan Overstroming van Rivieren",
  "graph_300_title": "Kans op Langdurige Droogte—Kaart",
  "graph_303_title": "Hernieuwbare Capaciteit voor Waterstofproductie",
  "graph_308_title": "Marktprijs van Waterstof",
  "graph_311_menu_title": "Elektriciteitsproductie per Toepassing—Oppervlak",
  "graph_311_title": "Elektriciteitsproducite per Toepassing",
  "graph_312_menu_title": "Waterstofproductie per Toepassing—Oppervlak",
  "graph_312_title": "Waterstofproductie per Toepassing",
  "graph_313_menu_title": "Eindgebruik in Gebouwen en Industrie per Toepassing—Oppervlak",
  "graph_313_title": "Eindgebruik in Gebouwen en Industrie per Toepassing",
  "graph_314_menu_title": "Eindgebruik in Transport per Toepassing—Oppervlak",
  "graph_314_title": "Eindgebruik in Transport per Toepassing",
  "graph_318_title": "Kostenratio Elektrische Apparatuur en Alternatieven",
  "graph_319_title": "Kostenratio van Waterstof en Alternatieven",
  "graph_actions_menu__copy_data_to_clipboard": "Kopieer Data",
  "graph_actions_menu__hide_description": "Verberg Beschrijving",
  "graph_actions_menu__hide_no_impact_from_temp": "Verberg \"Geen Impact van Temperatuur\"",
  "graph_actions_menu__hide_un_pledges": "Verberg beloftes VN (NDCs)",
  "graph_actions_menu__show_description": "Toon Beschrijving",
  "graph_actions_menu__show_no_impact_from_temp": "Toon \"Geen Impact van Temperatuur\"",
  "graph_actions_menu__show_un_pledges": "Toon beloftes VN (NDCs)",
  "graph_actions_menu__view_in_new_window": "Open in Nieuw Venster",
  "graph_actions_menu__view_larger": "Uitvergroten",
  "graph_dataset_label__0_50_years": "0-50 jaar",
  "graph_dataset_label__50_100_years": "50-100 jaar",
  "graph_dataset_label__66pct_chance_of_2degrees_c_or_15degrees_c": "66% kans op 2ºC or 1.5ºC",
  "graph_dataset_label__afforestation_and_reforestation": "Bebossing & Herbebossing",
  "graph_dataset_label__ag_soil_carbon": "Koolstof in Landbouwgrond",
  "graph_dataset_label__agricultural_soil_carbon": "Koolstof in agrarische bodems",
  "graph_dataset_label__agriculture": "Landbouw",
  "graph_dataset_label__air_and_water_fuels": "Lucht & Water (Brandstoffen)",
  "graph_dataset_label__air_and_water_hydrogen": "Lucht & Water (Waterstof)",
  "graph_dataset_label__all_countries_follow_ndcs": "Alle landen volgen NDCs",
  "graph_dataset_label__area_of_india": "Oppervlakte van India",
  "graph_dataset_label__area_of_sahara_desert": "Oppervlakte van de Sahara Woestijn",
  "graph_dataset_label__area_of_south_america": "Oppervlakte van Zuid-Amerika",
  "graph_dataset_label__at_risk_to_annual_flooding_in_millions": "Gevaar op jaarlijkse overstroming<br>(in miljoenen)",
  "graph_dataset_label__australia": "Australië",
  "graph_dataset_label__baseline": "Uitgangswaarde",
  "graph_dataset_label__baseline_in_2100": "Uitgangswaarde in 2100",
  "graph_dataset_label__beccs": "BECCS",
  "graph_dataset_label__biochar": "Biochar",
  "graph_dataset_label__bioenergy": "Bio-energie",
  "graph_dataset_label__birds": "Vogels",
  "graph_dataset_label__bldgs_and_ind_electric": "Gebouwen & Industrie (Elektrisch)",
  "graph_dataset_label__bldgs_and_ind_fuels": "Gebouwen & Industrie (Brandstoffen)",
  "graph_dataset_label__bldgs_and_ind_hydrogen": "Gebouwen & Industrie (Waterstof)",
  "graph_dataset_label__blue": "Blauw",
  "graph_dataset_label__brown": "Bruin",
  "graph_dataset_label__buildings": "Gebouwen",
  "graph_dataset_label__buildings___energy": "Gebouwen ‐ Energie",
  "graph_dataset_label__buildings_electric": "Gebouwen (Elektrisch)",
  "graph_dataset_label__buildings_fuels": "Gebouwen (Brandstoffen)",
  "graph_dataset_label__buildings_hydrogen": "Gebouwen (Waterstof)",
  "graph_dataset_label__burke_2015": "Burke 2015",
  "graph_dataset_label__burke_2018_default": "Burke 2018 (standaard)",
  "graph_dataset_label__butterflies_and_moths": "Vlinders & Motten",
  "graph_dataset_label__captured_by_ccs": "Opgeslagen door CCS",
  "graph_dataset_label__carbon_in_plants": "Koolstof in Planten",
  "graph_dataset_label__carbon_in_soils": "Koolstof in Bodem",
  "graph_dataset_label__central_america": "Centraal-Amerika",
  "graph_dataset_label__central_europe": "Centraal-Europa",
  "graph_dataset_label__ch4": "CH4",
  "graph_dataset_label__cheapest_storage": "Goedkoopste Opslag",
  "graph_dataset_label__china": "China",
  "graph_dataset_label__co2_emissions": "CO2 Uitstoot",
  "graph_dataset_label__co2_removals": "CO2 Verwijdering",
  "graph_dataset_label__co2_transport_capacity": "CO2 transportcapaciteit",
  "graph_dataset_label__coal": "Kool",
  "graph_dataset_label__coal_ccs": "Kolen CCS",
  "graph_dataset_label__coal_production": "Koolproductie",
  "graph_dataset_label__cost_parity": "Kostengelijkheid",
  "graph_dataset_label__costs_of_subsidies": "Kosten van subsidies",
  "graph_dataset_label__crops": "Gewassen",
  "graph_dataset_label__current_scenario": "Huidig Scenario",
  "graph_dataset_label__current_scenario_discounted": "Huidig scenario—Gedisconteerd",
  "graph_dataset_label__current_scenario_in_2100": "Huidig Scenario in 2100",
  "graph_dataset_label__daccs": "DACCS",
  "graph_dataset_label__daily": "Dagelijks",
  "graph_dataset_label__deforestation": "Ontbossing",
  "graph_dataset_label__degradation___bioenergy": "Degradatie ‐ Bio-energie",
  "graph_dataset_label__degradation___fires_from_warming": "Degradatie - Branden door Opwarming",
  "graph_dataset_label__degradation___wood_products": "Degradatie ‐ Houten Producten",
  "graph_dataset_label__dengue": "Dengue",
  "graph_dataset_label__dietz_and_stern": "Dietz & Stern",
  "graph_dataset_label__dragonflies_and_damselflies": "Libellen & Waterjuffers",
  "graph_dataset_label__east_asia": "Oost-Azië",
  "graph_dataset_label__electric": "Elektrisch",
  "graph_dataset_label__electric_with_ccs": "Elektrisch met CCS",
  "graph_dataset_label__emissions": "Uitstoot",
  "graph_dataset_label__emissions_baseline": "Emissie Baseline",
  "graph_dataset_label__en_roads_baseline": "En-ROADS Referentiescenario",
  "graph_dataset_label__en_roads_coal": "En-ROADS Kool",
  "graph_dataset_label__en_roads_gas": "En-ROADS Aardgas",
  "graph_dataset_label__en_roads_ghg_net_emissions": "En-ROADS Netto BKG-uitstoot",
  "graph_dataset_label__en_roads_oil": "En-ROADS Olie",
  "graph_dataset_label__en_roads_solar": "En-ROADS Zonne-energie",
  "graph_dataset_label__en_roads_wind": "En-ROADS Windenergie",
  "graph_dataset_label__energy_production": "Energieproductie",
  "graph_dataset_label__eu": "EU",
  "graph_dataset_label__f_gases": "F-gassen",
  "graph_dataset_label__farmland": "Landbouwgrond",
  "graph_dataset_label__forest": "Bos",
  "graph_dataset_label__fossil_ccs": "Fossiele CCS",
  "graph_dataset_label__fossil_fuel_co2": "Fossiele Brandstof CO2",
  "graph_dataset_label__fuel": "Brandstof",
  "graph_dataset_label__fuel_with_ccs": "Brandstof met CCS",
  "graph_dataset_label__fuels": "Brandstoffen",
  "graph_dataset_label__gas": "Aardgas",
  "graph_dataset_label__gas_ccs": "Gas CCS",
  "graph_dataset_label__geothermal_and_other": "Geothermisch en Overig",
  "graph_dataset_label__global": "Wereldwijd",
  "graph_dataset_label__global_gdp_in_2024": "Globaal BBP in 2024",
  "graph_dataset_label__gray": "Grijs",
  "graph_dataset_label__green": "Groen",
  "graph_dataset_label__gross_co2_removals": "Bruto CO2 Verwijdering",
  "graph_dataset_label__hfc": "HFK's",
  "graph_dataset_label__hfc_follows_kigali": "HFK's volgen Kigali",
  "graph_dataset_label__historical_ghg_net_emissions": "Historische Netto BKG-uitstoot",
  "graph_dataset_label__hourly": "per uur",
  "graph_dataset_label__howard_and_sterner": "Howard & Sterner",
  "graph_dataset_label__hydro": "Waterkracht",
  "graph_dataset_label__hydrogen": "Waterstof",
  "graph_dataset_label__hydrogen_storage": "Waterstofopslag",
  "graph_dataset_label__hydrogen_with_ccs": "Waterstof met CCS",
  "graph_dataset_label__iea": "IEA",
  "graph_dataset_label__iea_coal": "IEA Kool",
  "graph_dataset_label__iea_gas": "IEA Aardgas",
  "graph_dataset_label__iea_oil": "IEA Olie",
  "graph_dataset_label__iea_solar": "IEA Zonne-energie",
  "graph_dataset_label__iea_wind": "IEA Wind",
  "graph_dataset_label__in_2100": "in 2100",
  "graph_dataset_label__india": "India",
  "graph_dataset_label__industrial_processes": "Industriële Processen",
  "graph_dataset_label__industry": "Industrie",
  "graph_dataset_label__industry___energy": "Industrie - Energie",
  "graph_dataset_label__industry___feedstocks": "Industrie - Grondstoffen",
  "graph_dataset_label__industry_electric": "Industrie (Elektrisch)",
  "graph_dataset_label__industry_fuels": "Industrie (Brandstoffen)",
  "graph_dataset_label__industry_hydrogen": "Industrie (Waterstof)",
  "graph_dataset_label__insects": "Insecten",
  "graph_dataset_label__invertebrates": "Ongewervelden",
  "graph_dataset_label__irena": "IRENA",
  "graph_dataset_label__land_removals": "Verwijdering door Bodem",
  "graph_dataset_label__land_species": "Landdieren",
  "graph_dataset_label__land_use_co2": "CO2 Landgebruik",
  "graph_dataset_label__lazard": "Lazard",
  "graph_dataset_label__living_below_high_tide_line_in_millions": "Leven onder vloedlijn<br>(miljoenen)",
  "graph_dataset_label__low_carbon_sources": "Bronnen met Lage Koolstofemissie",
  "graph_dataset_label__maize": "Maïs",
  "graph_dataset_label__malaria": "Malaria",
  "graph_dataset_label__mammals": "Zoogdieren",
  "graph_dataset_label__marine_animal": "Zeedier",
  "graph_dataset_label__marine_species": "Zeedieren",
  "graph_dataset_label__met_office": "Met Office",
  "graph_dataset_label__mineralization": "Mineralisering",
  "graph_dataset_label__mineralization_rock": "Mineralisering Gesteente",
  "graph_dataset_label__montreal_gases": "Montreal gassen",
  "graph_dataset_label__more_than_100_years": "Meer dan 100 jaar",
  "graph_dataset_label__n2o": "N2O",
  "graph_dataset_label__nasa": "NASA",
  "graph_dataset_label__nasa_upper_per_lower_95pct": "NASA bovenste/onderste 95%",
  "graph_dataset_label__natural_gas_pipeline_capacity": "Pijplijncapaciteit aardgas",
  "graph_dataset_label__net_bioenergy": "Netto Bio-energie",
  "graph_dataset_label__net_revenue_minus_costs": "Netto: Inkomsten min kosten",
  "graph_dataset_label__new_zero": "New Zero",
  "graph_dataset_label__new_zero_carbon_baseline": "New Zero-Carbon Uitgangswaarde",
  "graph_dataset_label__north_america": "Noord-Amerika",
  "graph_dataset_label__northern_europe": "Noord-Europa",
  "graph_dataset_label__nuclear": "Nucleair",
  "graph_dataset_label__nuclear_baseline": "Nucleair Uitgangswaarde",
  "graph_dataset_label__ocean_removals": "Verwijdering door Oceanen",
  "graph_dataset_label__oil": "Olie",
  "graph_dataset_label__other_cdr": "Andere CDR",
  "graph_dataset_label__other_developed": "Andere Geïndustrialiseerde Landen",
  "graph_dataset_label__other_developing": "Andere Ontwikkelingslanden",
  "graph_dataset_label__other_storage": "Andere Opslag",
  "graph_dataset_label__pfc": "PFC's",
  "graph_dataset_label__phytoplankton": "Fytoplankton",
  "graph_dataset_label__pink": "Roze",
  "graph_dataset_label__plants": "Planten",
  "graph_dataset_label__price": "Prijs",
  "graph_dataset_label__price_plus_taxes_minus_subsidies": "Prijs plus belasting min subsidie",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_at_least_once_before_2100": "Kans op ijsvrije Arctische zomer<br>min. een keer voor 2100",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2050": "Kans op ijsvrije Arctische zomer<br>in 2050",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2100": "Kans op ijsvrije Arctische zomer<br>in 2100",
  "graph_dataset_label__renewables": "Hernieuwbare Energie",
  "graph_dataset_label__revenue_from_taxes": "Inkomsten van belastingen",
  "graph_dataset_label__rice": "Rijst",
  "graph_dataset_label__road_and_rail_electric": "Weg & Spoor (Elektrisch)",
  "graph_dataset_label__road_and_rail_fuels": "Weg & Spoor (Brandstoffen)",
  "graph_dataset_label__scenario_if_no_economic_impact_from_temp": "Scenario zonder temperatuurimpact op economie",
  "graph_dataset_label__seasonal": "Seizoensgebonden",
  "graph_dataset_label__sf6": "SF6",
  "graph_dataset_label__solar": "Zonne-energie",
  "graph_dataset_label__south_america": "Zuid-Amerika",
  "graph_dataset_label__southeast_asia": "Zuidoost-Azië",
  "graph_dataset_label__southern_africa": "Zuidelijk Afrika",
  "graph_dataset_label__southern_europe": "Zuid-Europa",
  "graph_dataset_label__soybean": "Sojaboon",
  "graph_dataset_label__storage_cost": "Opslagkosten",
  "graph_dataset_label__today": "Vandaag",
  "graph_dataset_label__transport___air_and_water": "Transport - Lucht & Water",
  "graph_dataset_label__transport___road_and_rail": "Transport - Weg & Spoor",
  "graph_dataset_label__transport_electric": "Transport (Elektrisch)",
  "graph_dataset_label__transport_fuels": "Transport (Brandstoffen)",
  "graph_dataset_label__transport_hydrogen": "Transport (Waterstof)",
  "graph_dataset_label__us": "VS",
  "graph_dataset_label__us_gdp_in_2024": "VS BBP in 2024",
  "graph_dataset_label__vertebrates": "Gewervelden",
  "graph_dataset_label__waste": "Afval",
  "graph_dataset_label__waste_per_other": "Afval/Overig",
  "graph_dataset_label__west_asia": "West-Azië",
  "graph_dataset_label__wheat": "Graan",
  "graph_dataset_label__wind": "Wind",
  "graph_dataset_label__wind_and_solar": "Wind & Zonne-energie",
  "graph_dataset_label__wind_and_solar_cost": "Kosten van Wind- en Zonne-energie",
  "graph_dataset_label__with_ccs": "Met CCS",
  "graph_dataset_label__without_ccs": "Zonder CCS",
  "graph_dataset_label__wood": "Hout",
  "graph_dataset_label__yellow": "Geel",
  "graph_dataset_label__zooplankton": "Zoöplankton",
  "graph_menu__favorites_empty_detail": "Klik op het sterretje naast een grafiek om het aan je favorieten toe te voegen.",
  "graph_menu__favorites_empty_title": "Nog geen favorieten",
  "graph_menu__favorites_title": "Favorieten",
  "graph_menu__search_empty_title": "Geen resultaten gevonden",
  "graph_menu__search_placeholder": "Zoek grafieken",
  "graph_menu__search_section_all_results": "Alle Resultaten per Categorie",
  "graph_menu__search_section_top_results": "Beste Resultaten",
  "graph_menu__view_as_grid": "Bekijk als raster",
  "graph_menu__view_as_list": "Bekijk als lijst",
  "graph_menu_grouping__agriculture": "Landbouw",
  "graph_menu_grouping__atmosphere": "Atmosfeer",
  "graph_menu_grouping__carbon_capture_and_storage": "Koolstofafvangst en -Opslag",
  "graph_menu_grouping__carbon_intensity_of_final_consumption": "Koolstofintensiteit van Eindgebruik",
  "graph_menu_grouping__consumer_prices": "Consumentenprijzen",
  "graph_menu_grouping__ecosystems_and_biodiversity": "Ecosystemen en Biodiversiteit",
  "graph_menu_grouping__electricity_and_hydrogen_production_by_use": "Elektriciteits- en Waterstofproductie per Toepassing",
  "graph_menu_grouping__emissions_from_energy_and_industrial_processes": "Uitstoot van Energie en Industriële Processen",
  "graph_menu_grouping__emissions_from_land_use": "Uitstoot van Landgebruik",
  "graph_menu_grouping__extreme_weather": "Extreem Weer",
  "graph_menu_grouping__final_consumption_by_end_use": "Eindgebruik per Toepassing",
  "graph_menu_grouping__final_consumption_totals": "Totale Eindgebruik",
  "graph_menu_grouping__fluorinated_gases": "Gefluoreerde Gassen",
  "graph_menu_grouping__forestry": "Bosbouw",
  "graph_menu_grouping__general": "Algemeen",
  "graph_menu_grouping__health_and_economy": "Gezondheid en Economie",
  "graph_menu_grouping__land_use": "Landgebruik",
  "graph_menu_grouping__methane": "Methaan",
  "graph_menu_grouping__nitrous_oxide": "Stikstofoxide",
  "graph_menu_grouping__oceans": "Oceanen",
  "graph_menu_grouping__production_costs": "Productiekosten",
  "graph_menu_grouping__share_of_capital": "Aandeel van het Kapitaal",
  "graph_menu_grouping__totals": "Totaal",
  "graph_value__percent": "{num}%",
  "graph_xaxis_label__temperature_change_from_1850___degrees_celsius": "Temperatuurverandering sinds 1850 — Graden Celsius",
  "graph_yaxis_label__billion_dollars_per_year": "Miljarden $/jaar",
  "graph_yaxis_label__billion_tons_per_year": "Miljarden tonnen/jaar",
  "graph_yaxis_label__billions_of_people": "Miljarden Mensen",
  "graph_yaxis_label__ch4_parts_per_million_ppm": "CH4 deeltjes per miljoen (ppm)",
  "graph_yaxis_label__co2_equivalent_parts_per_million_ppm": "CO2 equivalent, parts per million (ppm)",
  "graph_yaxis_label__co2_parts_per_million_ppm": "CO2, parts per million (ppm)",
  "graph_yaxis_label__days_per_year_per_worker": "Dagen/jaar/arbeider",
  "graph_yaxis_label__deaths_per_100000_people_per_year": "Doden per 100.000 mensen/jaar",
  "graph_yaxis_label__degrees_celsius": "Graden Celsius",
  "graph_yaxis_label__degrees_fahrenheit": "Graden Fahrenheit",
  "graph_yaxis_label__dollars_per_barrel": "$/vat",
  "graph_yaxis_label__dollars_per_boe": "$/olievatequivalent",
  "graph_yaxis_label__dollars_per_gigajoule": "$/gigajoule",
  "graph_yaxis_label__dollars_per_kg_h2": "$/kg H2",
  "graph_yaxis_label__dollars_per_kwh": "$/kWh",
  "graph_yaxis_label__dollars_per_mcf": "$/duizend kubieke voet (MCF)",
  "graph_yaxis_label__dollars_per_mwh": "$/MWh",
  "graph_yaxis_label__dollars_per_person_per_year": "$/persoon/jaar",
  "graph_yaxis_label__dollars_per_ton": "$/ton",
  "graph_yaxis_label__dollars_per_ton_co2": "$/ton CO2",
  "graph_yaxis_label__exajoule_per_trillion_dollars": "Exajoule/Biljoen $",
  "graph_yaxis_label__exajoules": "Exajoules",
  "graph_yaxis_label__exajoules_per_year": "Exajoule/jaar",
  "graph_yaxis_label__exposure_per_100000_people_per_year": "Blootstelling per 100.000 mensen/jaar",
  "graph_yaxis_label__feet_ft": "Voet (ft)",
  "graph_yaxis_label__gigatons_c": "Gigaton Koolstof",
  "graph_yaxis_label__gigatons_co2": "Gigaton CO2",
  "graph_yaxis_label__gigatons_co2_equivalent": "Gigaton CO2 equivalent",
  "graph_yaxis_label__gigatons_co2_equivalent_per_year": "Gigaton CO2 equivalent/jaar",
  "graph_yaxis_label__gigatons_co2_per_year": "GIgaton CO2/jaar",
  "graph_yaxis_label__gigatons_produced_per_year": "Gigatonnen geproduceerd/jaar",
  "graph_yaxis_label__kg_ch4_per_ton_of_waste": "kg CH4/ton afval",
  "graph_yaxis_label__kg_ch4_per_ton_produced": "kg CH4/ton geproduceerd",
  "graph_yaxis_label__kg_ch4_per_year_per_person": "kg CH4/jaar/persoon",
  "graph_yaxis_label__kg_per_year_per_hectare": "kg/jaar/hectare",
  "graph_yaxis_label__kilograms_co2_per_mwh": "kilogram CO2/MWh",
  "graph_yaxis_label__kilotons_ch4_per_exajoule": "Kiloton CH4/exajoule",
  "graph_yaxis_label__megatons_ch4_per_year": "Megaton CH4/jaar",
  "graph_yaxis_label__megatons_co2_per_exajoule": "Megaton CO2/exajoule",
  "graph_yaxis_label__megatons_nitrogen_per_year": "Megaton stikstof/jaar",
  "graph_yaxis_label__megatons_pm25_per_year": "Megaton PM2.5/jaar",
  "graph_yaxis_label__meters_m": "Meter (m)",
  "graph_yaxis_label__million_acres": "Miljoen acres",
  "graph_yaxis_label__million_hectares": "Miljoen hectares",
  "graph_yaxis_label__million_hectares_per_year": "Miljoenen hectares/jaar",
  "graph_yaxis_label__millions_of_people_per_year": "Miljoenen mensen/jaar",
  "graph_yaxis_label__pct_reduction_in_gdp": "% Afname BBP",
  "graph_yaxis_label__percent": "Procent",
  "graph_yaxis_label__percent_loss": "Percentage verlies",
  "graph_yaxis_label__percent_of_species": "Percentage van soorten",
  "graph_yaxis_label__percent_per_year": "Procent/jaar",
  "graph_yaxis_label__ph": "pH",
  "graph_yaxis_label__ratio": "Verhouding",
  "graph_yaxis_label__tons_ch4_per_million_dollars_gdp": "Ton CH4/miljoen $ BBP",
  "graph_yaxis_label__tons_co2_per_million_dollars_gdp": "Ton CO2/miljoen $ BBP",
  "graph_yaxis_label__tons_co2_per_year_per_person": "Ton CO2/jaar/persoon",
  "graph_yaxis_label__tonsc_per_hectare": "ton koolstof/hectare",
  "graph_yaxis_label__trillion_cubic_meters_per_year": "Biljoen kubieke meter/jaar",
  "graph_yaxis_label__trillion_dollars_per_year": "Biljoen $/jaar",
  "input_001_label": "Kool (belasting/subsidie)",
  "input_002_label": "Startjaar belasting/subsidie van kool",
  "input_003_label": "Eindjaar belasting/subsidie van kool",
  "input_004_label": "Versnelde stillegging steenkoolcentrales",
  "input_007_label": "Olie (belasting/subsidie)",
  "input_008_label": "Olie belasting/subsidie start jaar",
  "input_009_label": "Olie belasting/subsidie eindjaar",
  "input_010_label": "Aardgas (belasting/subsidie)",
  "input_011_label": "Aardgas belasting/subsidie startjaar",
  "input_012_label": "Aardgas belasting/subsidie eindjaar",
  "input_016_label": "Hernieuwbare energie (belasting/subsidie)",
  "input_017_label": "Hernieuwbare energie belasting/subsidie startjaar",
  "input_018_label": "Hernieuwbare energie belasting/subsidie eindjaar",
  "input_019_label": "Hernieuwbare energie – kostenbesparing door doorbraak",
  "input_020_label": "Hernieuwbare energie jaar van doorbraak",
  "input_021_label": "Overige opslag kostenbesparing door doorbraak",
  "input_022_label": "Overige opslag jaar van doorbraak",
  "input_023_label": "Bio-energie (belasting/subsidie)",
  "input_024_label": "Bio-energie belasting/subsidie startjaar",
  "input_025_label": "Bio-energie belasting/subsidie eindjaar",
  "input_026_label": "Bio-energie kostenbesparing door doorbraak",
  "input_027_label": "Bio-energie jaar van doorbraak",
  "input_030_label": "Kernenergie (belasting/subsidie)",
  "input_031_label": "Kernenergie belasting/subsidie startjaar",
  "input_032_label": "Kernenergie belasting/subsidie eindjaar",
  "input_033_label": "Kernenergie kostenbesparing door R&D doorbraak",
  "input_034_label": "Kernenergie jaar van doorbraak",
  "input_035_label": "Doorbraak van New Zero-Carbon",
  "input_036_label": "Doorbraakjaar van New Zero-Carbon",
  "input_037_label": "New Zero-Carbon tijd tot commercialisering",
  "input_038_label": "Beginkosten in vergelijking met kolen",
  "input_039_label": "Koolstofprijs",
  "input_040_label": "Invoeringsjaar van koolstofprijs",
  "input_041_label": "Jaren om initiële koolstofprijs te bereiken",
  "input_042_label": "Uiteindelijke koolstofprijs (pas \"Startjaar\" hieronder aan)",
  "input_043_label": "Startjaar toepassing uiteindelijke koolstofprijs",
  "input_044_label": "Jaren om uiteindelijke koolstofprijs te bereiken",
  "input_045_label": "Uitstootnorm",
  "input_046_label": "Startjaar van uitstootnorm",
  "input_047_label": "Energie-efficiëntie van gebouwen en industrie",
  "input_048_label": "Startjaar",
  "input_050_label": "Energie-efficiëntie van nieuw transport",
  "input_051_label": "Startjaar",
  "input_053_action_label": "Verkooplimiet brandstofgedreven transport — weg en spoor",
  "input_053_label": "Verkooplimiet brandstofgedreven transport",
  "input_054_action_label": "Startjaar beleid Elektrificatie — weg en spoor",
  "input_054_label": "Startjaar verkooplimiet brandstofgedreven transport",
  "input_055_label": "Verkooplimiet brandstofgedreven apparatuur",
  "input_056_label": "Startjaar verkooplimiet brandstofgedreven apparatuur",
  "input_057_label": "Ontbossing & Aantasting Volgroeid Bos (afname/toename)",
  "input_060_label": "Methaan en stikstofoxide van landbouw",
  "input_061_label": "Methaan en andere gassen van afval en lekstromen",
  "input_062_label": "Startjaar van beperking uitstoot van afval en lekkage",
  "input_063_action_label": "Bevolking",
  "input_063_label": "Bevolking (Bereik van VN-scenario)",
  "input_064_label": "Economische groei op de korte termijn (BBP per persoon)",
  "input_065_label": "Percentage beschikbaar land gebruikt voor bebossing en herbebossing",
  "input_066_label": "Startjaar bebossing en herbebossing",
  "input_067_label": "Technologische verwijdering van koolstof",
  "input_071_label": "Direct air capture subsidie - startjaar",
  "input_072_label": "Versterkte mineralisering",
  "input_073_label": "Versterkte mineralisering - startjaar",
  "input_074_label": "Koolstofvastlegging in landbouwgrond",
  "input_075_label": "Koolstofvastlegging in landbouwgrond - startjaar",
  "input_076_label": "Biochar",
  "input_077_label": "Biochar - startjaar",
  "input_078_label": "Klimaatgevoeligheid",
  "input_079_label": "Oceaanvermenging",
  "input_080_label": "CO<sub>2</sub>&nbsp;bemesting",
  "input_082_label": "Koolstofcyclus, opname door oceaan",
  "input_083_label": "Effect van temperatuur op CH<sub>4</sub>&nbsp;respiratie",
  "input_084_label": "Effect van temperatuur op methaanuitstoot van permafrost en clathraten",
  "input_085_label": "Temperatuurgrens voor permafrost en clathraten",
  "input_087_label": "Verliesratio van mineralisering",
  "input_088_label": "Verliesratio van biochar",
  "input_091_label": "Verliessnelheid van koolstof in landbouwgrond",
  "input_095_label": "Biochar",
  "input_096_label": "Koolstofvastlegging in landbouwgrond",
  "input_110_action_label": "Tijd tussen doorbraak en commercieel gebruik (Kernenergie)",
  "input_110_label": "Kernenergie",
  "input_112_action_label": "Tijd tussen doorbraak en commercieel gebruik (Hernieuwbare energie)",
  "input_112_label": "Hernieuwbare energie",
  "input_117_action_label": "Tijd tussen doorbraak en commercieel gebruik (Bruikbare bio-energie)",
  "input_117_label": "Bio-energie",
  "input_131_action_label": "Tijdsduur ontwikkeling energiecentrale (Nucleair)",
  "input_131_label": "Nucleair",
  "input_132_action_label": "Tijdsduur ontwikkeling energiecentrale (Waterkracht)",
  "input_132_label": "Waterkracht",
  "input_133_action_label": "Tijdsduur ontwikkeling energiecentrale (Hernieuwbare energie)",
  "input_133_label": "Hernieuwbare energie",
  "input_134_action_label": "Tijdsduur ontwikkeling energiecentrale (New Zero-Carbon)",
  "input_134_label": "New Zero-Carbon",
  "input_139_action_label": "Bouwtijd van energiecentrale (Nucleair)",
  "input_139_label": "Nucleair",
  "input_140_action_label": "Bouwtijd van energiecentrale (Waterkracht)",
  "input_140_label": "Waterkracht",
  "input_141_action_label": "Bouwtijd van energiecentrale (Hernieuwbare energie)",
  "input_141_label": "Hernieuwbare energie",
  "input_142_action_label": "Bouwtijd van energiecentrale (New Zero-Carbon)",
  "input_142_label": "New Zero-Carbon",
  "input_155_label": "Maximale potentieel voor vraagsturing",
  "input_160_action_label": "Energiestroombeperking bij bron (Waterkracht)",
  "input_160_label": "Waterkracht",
  "input_166_action_label": "Vooruitgangsquotient (Kolen)",
  "input_166_label": "Kolen",
  "input_167_action_label": "Vooruitgangsquotient (Olie)",
  "input_167_label": "Olie",
  "input_168_action_label": "Vooruitgangsquotient (Aardgas)",
  "input_168_label": "Aardgas",
  "input_169_action_label": "Vooruitgangsquotient (Bio-energie)",
  "input_169_label": "Bio-energie",
  "input_170_action_label": "Vooruitgangsquotient (Kernenergie)",
  "input_170_label": "Kernenergie",
  "input_171_action_label": "Vooruitgangsquotient (Hernieuwbare energie)",
  "input_171_label": "Hernieuwbare energie",
  "input_172_action_label": "Vooruitgangsquotient (Waterkracht)",
  "input_172_label": "Waterkracht",
  "input_173_action_label": "Vooruitgangsquotient (New Zero-Carbon)",
  "input_173_label": "New Zero-Carbon",
  "input_174_label": "Vooruitgangsratio van overige opslag",
  "input_175_label": "Voortgangsratio (CCS infrastructuur)",
  "input_176_label": "Vooruitgangsratio van vraagsturing",
  "input_196_label": "% Afname van kolengebruik",
  "input_197_label": "Jaren om nieuwe koleninfrastructuur te verminderen",
  "input_198_label": "% Afname van oliegebruik",
  "input_199_label": "Jaren om nieuwe olie-infrastructuur te verminderen",
  "input_200_label": "% Afname van gasgebruik",
  "input_201_label": "Jaren om nieuwe aardgasinfrastructuur te verminderen",
  "input_202_label": "% Afname in kolengebruik - startjaar",
  "input_203_label": "% Afname in kolengebruik - eindjaar",
  "input_204_label": "% Afname in oliegebruik - startjaar",
  "input_205_label": "% Afname in oliegebruik - eindjaar",
  "input_206_label": "% Afname in aardgasgebruik - startjaar",
  "input_207_label": "% Afname in aardgasgebruik - eindjaar",
  "input_208_label": "Detailinstellingen gebruiken",
  "input_209_label": "Detailinstellingen gebruiken",
  "input_210_label": "Detailinstellingen gebruiken",
  "input_211_label": "Verminder nieuwe koleninfrastructuur",
  "input_212_label": "Verminder nieuwe olie-infrastructuur",
  "input_213_label": "Verminder nieuwe aardgasinfrastructuur",
  "input_214_label": "Maximale oppervlak beschikbaar voor bebossing en herbebossing",
  "input_215_label": "Benodigde landbouwgrond koolstofvastlegging per verwijderde eenheid",
  "input_218_label": "Tijd voor de aanschaf van land voor bebossing en herbebossing",
  "input_219_label": "Tijd voor aanplanting van bos",
  "input_221_label": "Jaren voor aanpassing kolen-, olie- en gasgebruik",
  "input_222_label": "Kolen",
  "input_223_label": "Olie",
  "input_224_label": "Aardgas",
  "input_225_label": "Bio-energie",
  "input_230_action_label": "Energiestroombeperking bij bron (Wind)",
  "input_230_label": "Wind",
  "input_231_action_label": "Energiestroombeperking bij bron (Zonne-energie)",
  "input_231_label": "Zonne-energie",
  "input_232_action_label": "Energiestroombeperking bij bron (Aardwarmte)",
  "input_232_label": "Aardwarmte",
  "input_233_action_label": "Energiestroombeperking bij bron (andere hernieuwbare energie)",
  "input_233_label": "Andere hernieuwbare energie",
  "input_235_label": "Economische groei op lange termijn (BBP per persoon)",
  "input_236_label": "Transitieperiode",
  "input_237_label": "Maximaal oppervlak voor mineralisering",
  "input_238_label": "Toepassing van mineraliseringssteen",
  "input_239_label": "Energie-intensiteit van mineralisering",
  "input_240_label": "Potentieel voor mineralisering",
  "input_241_label": "Tijd voor realisatie van mineralisering",
  "input_242_label": "Maximale reductie van BBP",
  "input_243_label": "Reductie in BBP bij 1.5ºC temperatuurstijging door klimaatimpact",
  "input_245_label": "Schone elektriciteitsstandaard gebruiken",
  "input_246_label": "Bronnen die als schone elektriciteit erkend worden",
  "input_247_label": "Streven % elektriciteit van gekwalificeerde bronnen",
  "input_248_label": "Startjaar van schone elektriciteitsstandaard",
  "input_249_label": "Aantal jaar om schone elektriciteitsstandaard te bereiken",
  "input_251_label": "Voortgangsratio",
  "input_252_label": "Maatschappelijke discontovoet",
  "input_253_label": "Leksnelheid van CO<sub>2</sub>-opslag",
  "input_258_action_label": "Verkooplimiet brandstofgedreven transport—lucht en water",
  "input_258_label": "Verkooplimiet brandstofgedreven transport",
  "input_259_action_label": "Startjaar elektrificatiebeleid—lucht en water",
  "input_259_label": "Startjaar elektrificatiebeleid",
  "input_260_label": "Tijd tot limitatie verkoop brandstofgedreven apparatuur",
  "input_261_action_label": "Tijd tot limitatie verkoop brandstofgedreven transport—weg en spoor",
  "input_261_label": "Tijd tot limitatie verkoop brandstofgedreven transport",
  "input_262_action_label": "Tijd tot limitatie verkoop brandstofgedreven transport—lucht en water",
  "input_262_label": "Tijd tot limitatie verkoop brandstofgedreven transport",
  "input_263_label": "Hernieuwbare energie",
  "input_264_label": "Kernenergie",
  "input_265_label": "Nieuw Zero-Carbon",
  "input_266_label": "Fossiele brandstof met CCS",
  "input_267_label": "Bio-energie",
  "input_268_label": "Aardgas",
  "input_284_label": "Jaren om doelen mbt afval en lekkage te halen",
  "input_285_label": "Bijdrage aan zeespiegelstijging door smeltend ijs in Antarctica",
  "input_286_label": "Bijdrage aan zeespiegelstijging door smeltend ijs in Groenland",
  "input_287_label": "Dierlijke voeding",
  "input_288_label": "Potentiële gewasopbrengst",
  "input_292_label": "Hout voor bio-energie (belasting/subsidie)",
  "input_293_label": "Gewassen voor bio-energie (belasting/subsidie)",
  "input_294_label": "Afval/ander materiaal voor bio-energie (belasting/subsidie)",
  "input_296_label": "Koolstofafvangst en -opslag (CCS) subsidie voor gas",
  "input_298_label": "Koolstofprijs bevordert koolstofafvang en -opslag (CCS)",
  "input_299_label": "Koolstofprijs bemoedigt direct air capture en opslag",
  "input_300_label": "Direct air capture en opslag subsidie",
  "input_304_label": "Effect van temperatuur op gewasopbrengst",
  "input_305_label": "Voedselverspilling",
  "input_306_label": "Gebruik gedetailleerde instellingen",
  "input_307_label": "Afname in ontbossing",
  "input_308_label": "Startjaar afname ontbossing",
  "input_309_label": "Jaren om ontbossingsbeleid te bereiken",
  "input_310_label": "Afname van aantasting van volgroeid bos",
  "input_311_label": "Gebruik gedetailleerde instellingen",
  "input_312_label": "Koolstofprijs van toepassing op bio-energie uitstoot",
  "input_313_label": "Verminder nieuwe bio-energie infrastructuur",
  "input_314_label": "Jaren voor afname nieuwe bio-energie infrastructuur",
  "input_315_label": "Startjaar afname aantasting van volgroeid bos",
  "input_316_label": "Jaren om beleid tegen aantasting van bos te maken",
  "input_317_label": "Koolstofafvangst en -opslag subsidie voor bio-energie (BECCS)",
  "input_318_label": "Limiet van CO<sub>2</sub>-bemestingseffect",
  "input_319_label": "Effect van temperatuur op CO<sub>2</sub>&nbsp;respiratie",
  "input_320_label": "Houtoogst waarbij houtprijs verdubbelt",
  "input_321_label": "Oogst voor bio-energie waarbij gewasprijzen verdubbelen",
  "input_322_label": "Bio-energie grondstoffen",
  "input_327_label": "Veevoer omwisselverhouding",
  "input_328_label": "Verandersnelheid van de CH<sub>4</sub>-emissie van gewassen",
  "input_329_label": "Verandersnelheid van de N<sub>2</sub>O-emissie van gewassen",
  "input_330_label": "Verandersnelheid van de CH<sub>4</sub>-emissie van de veestapel",
  "input_331_label": "Verandersnelheid van de N<sub>2</sub>O-emissie van de veestapel",
  "input_332_label": "Subsidie van elektrisch transport",
  "input_334_label": "Eindjaar subsidie van elektrisch transport",
  "input_337_label": "Eindjaar subsidie elektrische apparatuur",
  "input_342_label": "Koolstofafvangst en -opslag subsidie voor kolen",
  "input_343_label": "CO<sub>2</sub>&nbsp;opslag voor kostenverdubbeling",
  "input_347_label": "Voortgangsratio (DACCS)",
  "input_348_label": "Initiële kosten van direct air capture",
  "input_349_label": "Formulering van economische schade",
  "input_350_label": "Startjaar CCS subsidie",
  "input_351_action_label": "Effectiviteit van koolstofafvang en -opslag (CCS)",
  "input_351_label": "Effectiviteit van Koolstofafvangst",
  "input_352_label": "Uitvoeringsduur CCS",
  "input_360_label": "Vooruitgangsratio (CCS energiegebruik)",
  "input_361_label": "Startjaar CCS subsidie",
  "input_362_label": "Startjaar BECCS subsidie",
  "input_365_label": "DACCS markt bij gelijke kosten",
  "input_369_label": "Klimaatverandering vertraagt economische groei",
  "input_370_label": "Bouw laadinfrastuctuur in lijn met toekomstige vraag",
  "input_371_label": "Tijd om laadinfrastructuur in lijn met toekomstige vraag te bouwen",
  "input_372_label": "Gebruik gedetailleerde instellingen",
  "input_373_label": "Subsidie voor elektrisch transport en laadinfrastructuur",
  "input_375_label": "Subsidie voor elektrische apparatuur",
  "input_379_label": "Toename van bosbranden door opwarming",
  "input_380_label": "Percentage ernstige bosbranden die tot ontbossing leiden",
  "input_392_label": "Leksnelheid van waterstof",
  "input_393_label": "Eindjaar waterstofsubsidie",
  "input_395_label": "Subsidie voor waterstof in gebouwen en infrastructuur",
  "input_396_label": "Eindjaar waterstofsubsidie",
  "input_398_label": "Subsidie en infrastructuur voor waterstof",
  "input_399_label": "Subsidie voor productie van groene waterstof",
  "input_401_label": "Gebruik gedetailleerde instellingen",
  "input_402_label": "Methaan en stikstofoxide van vee",
  "input_403_label": "Methaan en stikstofoxide van gewassen",
  "input_404_label": "Methaan en stikstofoxide van afval",
  "input_405_label": "Methaanlekkage van energiebronnen",
  "input_406_label": "Stikstofoxide van industrie",
  "input_410_label": "Jaren om belasting of subsidie op energie te implementeren",
  "input_411_label": "Jaren om verbetertempo van energie-efficiëntie te bereiken",
  "input_412_label": "Jaren om vermindering nieuwe infrastructuur voor kolen, olie, gas en bio-energie te bereiken",
  "input_414_label": "Bio-energie met CCS",
  "input_415_label": "F-gassen",
  "input_416_label": "% van landoppervlak met risico op ecosysteemveradering bij 2ºC",
  "input_417_label": "Natuurgebaseerde koolstofverwijdering",
  "input_418_label": "Gebruik gedetailleerde instellingen",
  "input_419_label": "Maximale haalbare reductie van methaan in energiesystemen",
  "input_421_label": "Startjaar acties ter vermindering van landbouw",
  "input_422_label": "Jaren om reductie van landbouwuitstoot te realiseren",
  "input_424_label": "Koolstofdichtheid van biomassa in evenwicht",
  "input_425_label": "Verandering in groeisnelheid van bebost en herbebost land",
  "input_432_label": "Maximale afname van F-gassen en andere industriële uitstoot",
  "input_433_label": "Maximale afname van uitstoot van F-gas door alternatieven",
  "input_434_label": "Max snelheid van destructie van F-gas",
  "input_435_label": "Huidige voorraad van Montrealgassen",
  "input_436_label": "DACCS capaciteit voor kostenverdubbeling",
  "input_437_label": "CCS capaciteit voor kostenverdubbeling",
  "input_441_label": "Koolstofdioxide van industriële processen",
  "input_447_label": "Voortgangsratio van grondstofintensiteit van het BBP",
  "input_449_label": "Subsidie en Infrastructuur voor waterstofindustrie",
  "input_450_label": "Verbeteringssnelheid van efficiëntie van waterstofproductie",
  "input_451_label": "Voortgangsratio van waterstofproductie via elektrolyse",
  "input_452_label": "Startjaar van voedselkeuzes",
  "input_454_label": "Infaseringstijd van waterstofbeleid",
  "input_482_action_label": "Initiële voorraad (Kolen)",
  "input_482_label": "Kolen",
  "input_483_action_label": "Initiële voorraad (Olie)",
  "input_483_label": "Olie",
  "input_484_action_label": "Initiële voorraad (Aardgas)",
  "input_484_label": "Aardgas",
  "input_range__breakthrough": "doorbraak",
  "input_range__discouraged": "ontmoedigd",
  "input_range__future_breakthrough": "toekomstige doorbraak",
  "input_range__high": "hoog",
  "input_range__high_growth": "snelle groei",
  "input_range__highest_growth": "snelste groei",
  "input_range__highly_increased": "sterk toegenomen",
  "input_range__highly_reduced": "sterk verminderd",
  "input_range__highly_subsidized": "sterk gesubsidieerd",
  "input_range__highly_taxed": "sterk belast",
  "input_range__huge_breakthrough": "enorme doorbraak",
  "input_range__increased": "toegenomen",
  "input_range__low": "laag",
  "input_range__low_growth": "langzame groei",
  "input_range__lowest_growth": "langzaamste groei",
  "input_range__medium": "gemiddeld",
  "input_range__medium_growth": "gemiddelde groei",
  "input_range__near_term_breakthrough": "doorbraak op de korte termijn",
  "input_range__negative_growth": "negatieve groei",
  "input_range__no_growth": "geen groei",
  "input_range__reduced": "verminderd",
  "input_range__status_quo": "status quo",
  "input_range__subsidized": "gesubsidieerd",
  "input_range__taxed": "belast",
  "input_range__very_high": "heel hoog",
  "input_range__very_highly_taxed": "heel zwaar belast",
  "input_units__billion_people_in_2100": "miljarden mensen in 2100",
  "input_units__degrees_c": "ºC",
  "input_units__dollars_per_barrel": "$/vat",
  "input_units__dollars_per_boe": "$ per olievatequivalent",
  "input_units__dollars_per_kg_h2": "$/kg H<sub>2</sub>",
  "input_units__dollars_per_kwh": "$/kWh",
  "input_units__dollars_per_mcf": "$ per duizend kubieke voet",
  "input_units__dollars_per_ton": "$/ ton",
  "input_units__dollars_per_ton_co2": "$/ton CO<sub>2</sub>",
  "input_units__dollars_per_ton_co2_captured": "$/ton opgeslagen CO<sub>2</sub>",
  "input_units__ej_per_year": "EJ/jaar",
  "input_units__gj_per_ton_rock": "GJ/ton gesteente",
  "input_units__gtons_co2": "Gton CO<sub>2</sub>",
  "input_units__gtons_co2_per_year": "Gton CO<sub>2</sub>/jaar",
  "input_units__gtons_co2e": "Gton CO<sub>2</sub>e",
  "input_units__meters_by_2100": "meter in 2100",
  "input_units__meters_meters_per_year": "meter*meter/jaar",
  "input_units__mha": "Mha",
  "input_units__mha_per_gton_co2_per_year": "Mha/Gton CO<sub>2</sub>/jaar",
  "input_units__mtons_per_ej": "Mton/EJ",
  "input_units__pct": "%",
  "input_units__pct_of_diet_by_2100": "% van dieet in 2100",
  "input_units__pct_of_food_produced_by_2100": "% van voedselproductie tot 2100",
  "input_units__pct_of_land_available": "% land beschikbaar",
  "input_units__pct_of_max_potential": "% van maximale potentie",
  "input_units__pct_of_potential_reduction": "% van potentiële afname",
  "input_units__pct_of_purchase_cost": "% van aanschafkosten",
  "input_units__pct_of_required": "% van benodigd",
  "input_units__pct_per_degrees_c": "% per ºC",
  "input_units__pct_per_year": "%/jaar",
  "input_units__pct_per_year_per_degrees_c": "% per jaar per ºC",
  "input_units__ratio": "ratio",
  "input_units__times_2020_value_by_2100": "keer 2020 waarde in 2100",
  "input_units__ton_co2_per_tj": "ton CO<sub>2</sub>/TJ",
  "input_units__ton_co2_per_ton_rock": "ton CO<sub>2</sub>/ton steen",
  "input_units__tons_c_per_hectare": "ton C/hectare",
  "input_units__tons_per_ha_per_year": "ton/ha/jaar",
  "input_units__years": "jaren",
  "map__error_failed_to_load": "De kaart kan op dit moment niet worden geladen.",
  "map__error_internet_required": "Kaarten vereisen een stabiele internetverbinding.",
  "map__legend_annual_likelihood_of_drought": "Jaarlijkse kans op 12+ maanden droogte",
  "map__legend_change_in_days_range": "{low} tot {high}",
  "map__legend_change_in_wildfire_days": "Verandering in aantal dagen met kans op bosbrand per jaar",
  "map__legend_days_per_year_above_temp": "Aantal dagen per jaar boven {temp_c} ({temp_f})",
  "map__legend_days_per_year_above_temp_wet_bulb": "Aantal dagen per jaar boven {temp_c} ({temp_f}) natteboltemperatuur",
  "map__map_year": "Kaart Jaar:",
  "map__search_places": "Zoek locaties",
  "map__show_baseline": "Toon Uitgangswaarde",
  "map__show_current_scenario": "Toon Huidig Scenario",
  "map__temperature_by_year": "{temp} in {year}",
  "map_slr__error_internet_required": "Kaarten met zeespiegelstijging vereisen een stabiele internetverbinding.",
  "map_slr__loading": "Kaart van Climate Central wordt geladen…",
  "map_slr__map_type": "Kaart Type:",
  "map_slr__map_type_21st_century": "21e Eeuw",
  "map_slr__map_type_21st_century_with_surge": "21e Eeuw met Toename van Storm",
  "map_slr__map_type_longterm": "Evenwicht op lange termijn",
  "map_slr__meters": "{num} m",
  "map_slr__storm_surge": "Storm Toename:",
  "menu__actions_and_outcomes": "Maatregelen & Resultaten",
  "menu__assumptions": "Aannames",
  "menu__en_roads_overview": "En-ROADS Overzicht",
  "menu__en_roads_training": "En-ROADS Training",
  "menu__en_roads_user_guide": "En-ROADS gebruikershandleiding",
  "menu__graph_selection": "Selectie van grafieken",
  "menu__graphs": "Grafieken",
  "menu__help": "Help",
  "menu__kaya_graphs": "Kaya grafieken",
  "menu__language": "Taal",
  "menu__main_graphs": "Hoofdgrafieken",
  "menu__metric_units": "Metrische Eenheden",
  "menu__miniature_graphs": "minigrafieken",
  "menu__model_technical_reference": "Model Technische Referentie",
  "menu__play_sounds": "Geluiden afspelen",
  "menu__related_examples": "Gerelateerde voorbeelden",
  "menu__release_notes": "Versiedocumentatie",
  "menu__reset_assumptions": "Terug naar standaard aannames",
  "menu__reset_policies": "Terug naar standaard beleid",
  "menu__reset_policies_and_assumptions": "Terug naar standaard aannames & beleid",
  "menu__return_to_default_graphs": "Terug naar standaardgrafieken",
  "menu__show_graph_tooltips": "Toon tooltips voor grafieken",
  "menu__simulation": "Simulatie",
  "menu__slider_information": "Info schuifbalk",
  "menu__support": "Ondersteuning",
  "menu__us_units": "Amerikaanse eenheden",
  "menu__uses_for_en_roads": "Gebruiksmogelijkheden van En-ROADS",
  "menu__video_tours": "Videorondleidingen",
  "menu__view": "Weergave",
  "menu_graphs__co2_emissions": "CO<sub>2</sub>&nbsp;Uitstoot",
  "menu_graphs__co2_removals": "CO<sub>2</sub>&nbsp;Verwijdering",
  "menu_graphs__final_energy_consumption_totals": "Totaal eindverbruik energie",
  "menu_graphs__final_energy_consumption_types": "Types van eindenergieverbruik",
  "menu_graphs__financial": "Financieel",
  "menu_graphs__greenhouse_gas_emissions": "Uitstoot broeikasgas",
  "menu_graphs__impacts": "Gevolgen",
  "menu_graphs__land_forestry_and_food": "Land, Bosbouw en Voedsel",
  "menu_graphs__model_comparison_history": "Modelvergelijking - Historisch",
  "menu_graphs__population_and_gdp": "Bevolking en BBP",
  "menu_graphs__primary_energy_demand_totals": "Totale Primaire Energiebehoefte",
  "menu_graphs__primary_energy_demand_types": "Primaire Energiebehoefte per Soort",
  "menu_graphs__view_more_graphs": "Meer grafieken tonen",
  "outcome_13_label": "Gedisconteerde Cumulatieve Schade tot 2100",
  "outcome_13_units_metric": "biljoen $",
  "outcome_1_label": "Temperatuurstijging in 2100",
  "outcome_1_units_metric": "ºC",
  "outcome_1_units_us": "ºF",
  "outcome_2_label": "CO<sub>2</sub>-concentratie in 2100",
  "outcome_2_units_metric": "ppm",
  "outcome_3_label": "Zeespiegelstijging in 2100",
  "outcome_3_units_metric": "m",
  "outcome_3_units_us": "voet",
  "outcome_4_label": "Cumulatieve vermeden CO<sub>2</sub>&nbsp;in 2100",
  "outcome_4_units_metric": "gigaton CO<sub>2</sub>",
  "policy_group_001_description": "Ontmoedigen of aanmoedigen van winning en verbranding van kolen in energiecentrales. Kolen zijn de meest schadelijke fossiele brandstof, in termen van zowel koolstofemissies als luchtvervuiling met grote impact op de gezondheid. Wereldwijd is het de meest gebruikte energiebron, omdat het relatief goedkoop te winnen en transporteren is.",
  "policy_group_001_example_1": "Belastingen",
  "policy_group_001_example_2": "Minder subsidies",
  "policy_group_001_example_3": "Luchtvervuiling",
  "policy_group_001_short_title": "Kolen",
  "policy_group_001_title": "Kolen",
  "policy_group_002_description": "Ontmoedigen of aanmoedigen van winning, raffinage en consumptie van olie voor energie. Olie is een veelgebruikte brandstof in auto's, schepen en vliegtuigen en wordt ook gebruikt in de industrie, voor verwarming en voor elektriciteitsopwekking. Toegang tot olie heeft tot grote conflicten geleid en olielekkages kunnen ecosystemen en water bedreigen.",
  "policy_group_002_example_1": "Minder subsidies",
  "policy_group_002_example_2": "Pijpleidingen",
  "policy_group_002_example_3": "Desinvestering",
  "policy_group_002_short_title": "Olie",
  "policy_group_002_title": "Olie",
  "policy_group_003_description": "Ontmoedigen of aanmoedigen van boringen en verbranding van aardgas als energiebron. Aardgas is een fossiele brandstof die gebruikt wordt voor elektriciteit, verwarming en industriële processen. Bij de verbranding komt koolstofdioxide vrij (minder dan bij kolen en olie) en bij lekkages komen grote hoeveelheden methaan vrij. Bij boringen worden grote hoeveelheden water gebruikt en kan vervuiling optreden.",
  "policy_group_003_example_1": "Fracking",
  "policy_group_003_example_2": "Pijpleidingen",
  "policy_group_003_example_3": "Desinvestering",
  "policy_group_003_short_title": "Aardgas",
  "policy_group_003_title": "Aardgas",
  "policy_group_004_description": "Ontmoedigen of aanmoedigen van het gebruik van bomen, afval en gewassen om energie op te wekken. Bio-energie wordt geproduceerd door het verbranden van organische materialen in vaste vorm (bijv. hout), in vloeibare vorm (bijv. ethanol) of als gas (bijv. methaan van verrotting van organisch materiaal). Er zijn verschillende bronnen, waarvan sommige duurzaam kunnen zijn en andere schadelijker zijn dan verbranding van kolen. CCS technologie zou kunnen worden gebruikt met bio-energie (BECCS), maar wordt nog niet op grote schaal gedaan en er zijn nog obstakels voor het opschalen.",
  "policy_group_004_example_1": "Biobrandstoffen",
  "policy_group_004_example_2": "Houtbrandstof",
  "policy_group_004_short_title": "Bio-energie",
  "policy_group_004_title": "Bio-energie",
  "policy_group_005_description": "Ontmoedigen of aanmoedigen van bouw van zonnepanelen, geothermische installaties en windmolens. Bij de hernieuwbare energiebronnen horen windenergie, zonne-energie, geothermische energie, waterkracht en andere technologieën met weinig of geen koolstofuitstoot of luchtvervuiling. Ondersteun ook waterstofproductie van hernieuwbare bronnen en ontwikkel opslagmogelijkheden om de energieproductie uit te balanceren. Bio-energie en kernenergie worden in dit model afzonderlijk behandeld.",
  "policy_group_005_example_1": "Wind, Zon, Hydro",
  "policy_group_005_example_2": "Schone energie",
  "policy_group_005_example_3": "Energie-opslag",
  "policy_group_005_short_title": "Hernieuwbare energie",
  "policy_group_005_title": "Hernieuwbare energie",
  "policy_group_006_description": "Stimuleer of ontmoedig de bouw van kerncentrales. Productie van kernenergie stoot geen koolstofdioxide uit, maar produceert wel afval dat eeuwen bewaard moet worden.",
  "policy_group_006_example_1": "Straling",
  "policy_group_006_example_2": "Afvalopslag",
  "policy_group_006_short_title": "Kernenergie",
  "policy_group_006_title": "Kernenergie",
  "policy_group_007_description": "Ontdek een gloednieuwe bron van elektriciteit die geen broeikasgassen uitstoot. Mensen speculeren over een doorbraak in kernfusie, kernsplijting van thorium, of kleine modulaire reactoren (SMRs). Iedere nieuwe energiebron brengt echter ook onbekende risico's mee. Bepaal het moment van de doorbraak, de initiële prijs in vergelijking met kolen, de lengte van de periode tot commercieel gebruik en opschaling.",
  "policy_group_007_example_1": "Thoriumsplijting",
  "policy_group_007_example_2": "Nucleaire fusie",
  "policy_group_007_short_title": "Nieuw Zero-Carbon",
  "policy_group_007_title": "Nieuw Zero-Carbon",
  "policy_group_008_description": "Stel een wereldwijde koolstofprijs in, die energiebronnen die meer koolstofdioxide uitstoten zwaarder belast of stel een norm in voor schone elektriciteit of een emissienorm. Energieproducenten zouden extra kosten bij hun klanten kunnen doorberekenen, dus er is beleid nodig om de armste bevolkingsgroepen te ontzien.",
  "policy_group_008_example_1": "Koolstofprijs",
  "policy_group_008_example_2": "Handel onder emissieplafond",
  "policy_group_008_short_title": "Koolstofprijs",
  "policy_group_008_title": "Koolstofprijs en Energienormen",
  "policy_group_009_description": "Verhoog of verlaag de energie-efficiëntie van voertuigen, schepen, luchtvaart en transportsystemen. Hiertoe behoren hybride auto's, uitbreidingen van openbaar vervoer, en manieren waarop mensen zich kunnen verplaatsen met minder energie. Energie-efficiënte maatregelen kunnen de volksgezondheid verbeteren en geld besparen.",
  "policy_group_009_example_1": "Hybride auto's",
  "policy_group_009_example_2": "Beloopbaarheid",
  "policy_group_009_example_3": "Openbaar vervoer",
  "policy_group_009_short_title": "Energie-efficiëntie",
  "policy_group_009_title": "Energie-efficiëntie van Transport",
  "policy_group_010_description": "Stimuleer invoering van elektrische auto's, vrachtwagens, bussen en treinen, en waterstofgedreven schepen en vliegtuigen. Het gebruik van elektromotoren of waterstofmotoren voor transport helpt om luchtvervuiling en de uitstoot van broeikasgassen te verminderen, indien de elektriciteit afkomstig is van een koolstofarme bron, zoals de zon of wind.",
  "policy_group_010_example_1": "Elektrische voertuigen",
  "policy_group_010_example_2": "Batterijtechnologie",
  "policy_group_010_example_3": "Oplaadinfrastructuur",
  "policy_group_010_short_title": "Elektrificering",
  "policy_group_010_title": "Elektrificering en Waterstof voor Transport",
  "policy_group_011_description": "Bevorder of verminder de energie-efficiëntie van gebouwen, apparaten en machines. Hiertoe behoort de bouw van goed geïsoleerde huizen, en het verminderen van de energievraag van fabrieken. Maatregelen voor energie-efficiëntie kunnen geld besparen door een afname van de energievraag en kunnen de gezondheid van mensen in de betreffende gebouwen verbeteren.",
  "policy_group_011_example_1": "Duurzame gebouwen",
  "policy_group_011_example_2": "Efficiënte industrie",
  "policy_group_011_example_3": "Energiebesparing",
  "policy_group_011_short_title": "Energie-efficiëntie",
  "policy_group_011_title": "Energie-efficiëntie van Gebouwen en Industrie",
  "policy_group_012_description": "Bevorder gebruik van elektriciteit en waterstof, in plaats van olie en gas in gebouwen, apparaten, verwarmingssystemen en andere machines. Gebruik van elektromotoren of waterstof leidt alleen tot verminderde uitstoot en verbeterde luchtkwaliteit als de elektriciteit van een koolstofarme bron zoals zonne-energie of windenergie komt.",
  "policy_group_012_example_1": "Elektrische verwarming",
  "policy_group_012_example_2": "Warmtepompen",
  "policy_group_012_short_title": "Elektrificering",
  "policy_group_012_title": "Elektriciteit en Waterstof voor Gebouwen en Industrie",
  "policy_group_013_description": "Ga uit van hogere of lagere bevolkingsgroei. Hoewel er een zekere verwachte trend is voor de bevolkingsgroei, kunnen stappen worden genomen zoals onderwijs voor vrouwen en toegang tot gezinsplanning, die aantoonbaar leiden tot kleinere families en dus een lagere bevolkingsgroei.",
  "policy_group_013_example_1": "Emancipatie van vrouwen",
  "policy_group_013_example_2": "Vruchtbaarheidsgraad",
  "policy_group_013_short_title": "Bevolking",
  "policy_group_013_title": "Bevolking",
  "policy_group_014_description": "Ga uit van hogere of lagere groei in geproduceerde goederen en aangeboden diensten. Economische groei wordt gemeten in Bruto Binnenlands Product (BBP) per persoon en is een belangrijke drijfveer voor consumptie. Er zijn alternatieve economische structuren om aan de behoefte van mensen te voldoen, die niet gebaseerd zijn op constante economische groei.",
  "policy_group_014_example_1": "BBP per persoon",
  "policy_group_014_example_2": "Simplicity Beweging",
  "policy_group_014_short_title": "Economische Groei",
  "policy_group_014_title": "Economische Groei",
  "policy_group_015_description": "Verander de mate van toepassing van best practices voor uitstootvermindering door afval, energieproductie en industrie. Methaan (CH<sub>4</sub>) en stikstofoxide (N<sub>2</sub>O), koolstofdioxide (CO<sub>2</sub>) en F-gassen (HFKs, PFKs en SF<sub>6</sub>&nbsp;enz.) worden allemaal uitgestoten waar er inefficiënties en lekkages zijn. CH<sub>4</sub>&nbsp;en N<sub>2</sub>O uitgestoten door vuilnisbelten en afvalwater kan verminderd worden door verbeterd ontwerp en beheer. In de fossiele energiesector kunnen methaanlekken bij energieproductie worden verminderd, in de industrie kan N<sub>2</sub>O uitstoot, bijvoorbeeld bij productie van kunstmest, en CO<sub>2</sub>&nbsp;uitstoot bij de productie van cement worden beperkt. In de chemische industrie en producten als airconditioners kunnen F-gassen beter worden beheerd.",
  "policy_group_015_example_1": "Methaan, N<sub>2</sub>O, HFKs",
  "policy_group_015_example_2": "Koelmiddelen",
  "policy_group_015_short_title": "Afval en Lekkage",
  "policy_group_015_title": "Afval en Lekkage",
  "policy_group_016_description": "Verander de mate van toepassing van best practices voor emissiereductie in landbouw en eetgewoontes. Methaan (CH<sub>4</sub>) komt vrij bij veeteelt en rijstvelden, en stikstofoxide (N<sub>2</sub>O) komt van mest en kunstmest. Betere landbouwmethodes kunnen de uitstoot direct verlagen en verandering van eetgewoontes kan de vraag naar vee en gewassen terugdringen. Dit leidt ooktot een afname van de vraag naar landbouwgrond en helpt daarmee ontbossing te voorkomen.",
  "policy_group_016_example_1": "Mestbeheer",
  "policy_group_016_example_2": "Kunstmest",
  "policy_group_016_example_3": "Plantaardige diëten",
  "policy_group_016_short_title": "Uitstoot door Landbouw",
  "policy_group_016_title": "Uitstoot door Landbouw en Voedselkeuze",
  "policy_group_017_description": "Stimuleer de aanleg van nieuwe bossen, herstel voormalig of verslechterd bos, implementeer landbouwmethodes die koolstof opslaan, produceer biochar. Deze methodes verwijderen koolstof uit de atmosfeer en slaan het op in planten en bodem. Deze koolstof kan wel weer vrijkomen op het moment dat het landgebruik verandert, ofwel opzettelijk bijvoorbeeld voor landbouw ofwel onbedoeld bij bosbranden.",
  "policy_group_017_example_1": "Bebossing",
  "policy_group_017_example_2": "CO<sub>2</sub>&nbsp;in landbouwgrond",
  "policy_group_017_example_3": "Biochar",
  "policy_group_017_short_title": "Natuurgebaseerd",
  "policy_group_017_title": "Natuurgebaseerde Verwijdering van Koolstofdioxide",
  "policy_group_018_description": "Bevorder het gebruik van technologieën om koolstofdioxide te verwijderen, zoals directe afvangst uit de lucht en opslag (DACCS) en verbeterde mineralisatie. Deze methoden zijn afhankelijk van zware industrie om koolstofdioxide direct uit de atmosfeer te verwijderen. Hoewel deze technologieën veelbelovende oplossingen bieden voor het verminderen van koolstof in de atmosfeer, vereisen ze aanzienlijke energie en investeringen om op grote schaal te implementeren. Vormen van koolstofopslag die gecombineerd worden met energie-opwekking staan onder de slider van deze energiebronnen (kolen, gas en bio-energie).",
  "policy_group_018_example_1": "Direct Air Capture",
  "policy_group_018_example_2": "Mineralisering",
  "policy_group_018_short_title": "Technologisch",
  "policy_group_018_title": "Technologische Verwijdering van Koolstofdioxide",
  "policy_group_019_description": "Stimuleer of ontmoedig de bescherming van bossen om de huidige trend van ontbossing en degradatie te veranderen. Ontbossing is het gebruik van bosgrond voor andere doeleinden, voornamelijk landbouw. Bosdegradatie is het tijdelijke verlies van bossen door oogst voor houtproducten of bio-energie. Ontbossing wordt gedreven door de behoefte aan landbouwgrond, die kan worden beïnvloed door veranderingen in het voedselsysteem onder Uitstoot door Landbouw.",
  "policy_group_019_example_1": "Bescherm bossen",
  "policy_group_019_example_2": "Nieuwe bossen",
  "policy_group_019_short_title": "Ontbossing",
  "policy_group_019_title": "Ontbossing en Verslechtering van Bestaande Bossen",
  "selector__custom": "Gepersonaliseerd",
  "selector__default": "Standaard",
  "selector__select": "Selecteer…",
  "share_by_email__enter_from_addr": "Vul je e-mailadres in",
  "share_by_email__enter_from_name": "Vul je naam in",
  "share_by_email__enter_note": "Extra opmerking bovenaan in bericht (optioneel)",
  "share_by_email__enter_to_addr": "Vul het e-mailadres van de ontvanger in",
  "share_by_email__failed": "Er is een fout opgetreden bij het sturen van de scenario e-mail. Probeer het opnieuw.",
  "share_by_email__from_label": "Van",
  "share_by_email__invalid_from_addr": "Voer een geldig e-mailadres in",
  "share_by_email__invalid_from_name": "Vul je naam in",
  "share_by_email__invalid_to_addr": "Voer een geldig e-mailadres van de ontvanger in",
  "share_by_email__note_label": "Opmerking",
  "share_by_email__preview_label": "Preview",
  "share_by_email__privacy": "We respecteren je privacy. Informatie ingevuld op dit formulier wordt gebruikt voor het versturen van één enkele e-mail naar de ontvanger.",
  "share_by_email__send": "Verstuur",
  "share_by_email__succeeded": "De scenariolink is succesvol verstuurd naar {toAddress}",
  "share_by_email__template_line1": "Er is een nieuw klimaatbeleidscenario met je gedeeld.",
  "share_by_email__template_line2": "Hier is een link naar een mondiaal klimaatscenario gemaakt met de En-ROADS simulator:",
  "share_by_email__template_line3": "Bekijk het scenario.",
  "share_by_email__template_line4": "En-ROADS is gemaakt door <i>Climate Interactive</i> en <i>MIT Sloan School of Management</i>. Bezoek {link} voor meer informatie.",
  "share_by_email__template_subject": "Met jou gedeeld: En-ROADS Klimaatscenario",
  "share_by_email__to_label": "Aan",
  "share_menu__copy_scenario_link": "Kopieer Link naar Scenario",
  "share_menu__share_by_email": "Deel via e-mail",
  "share_menu__share_on_facebook": "Deel op Facebook",
  "share_menu__share_on_linked_in": "Deel op LinkedIn",
  "share_menu__share_on_twitter": "Deel op X",
  "share_menu__share_your_scenario": "Deel je scenario",
  "temperature_box__increase_by_2100": "Temperatuur-<br>stijging in<br>2100",
  "welcome__announcement_line1": "En-ROADS is op {date} bijgewerkt met nieuwe functies en verbeteringen.",
  "welcome__announcement_line2": "Bezoek {linkRelease}deze pagina{linkClose} om meer te leren.",
  "welcome__line1": "Welkom bij En-ROADS van Climate Interactive en MIT Sloan School of Management."
}