export default {
  "__actions": "Ukrepi",
  "__actions_outcomes": "Ukrepi in rezultati",
  "__assumptions": "Predpostavke",
  "__assumptions_intro": "Spreminjajte ključne predpostavke, ki določajo model En-ROADS. Nastavitve vplivajo samo na trenutni scenarij, ne pa tudi na izhodiščni scenarij, kar omogoča primerjavo med njima.",
  "__beta": "BETA",
  "__cancel": "Prekliči",
  "__close": "Zapri",
  "__continue_to_en_roads": "Nadaljuj na En-ROADS",
  "__en_roads_climate_ambassador_training": "Usposabljanje podnebnih ambasadorjev En-ROADS",
  "__enter_full_screen": "Vstopite v celozaslonski način",
  "__exit_full_screen": "Izhod iz celozaslonskega načina",
  "__full_screen_unavailable": "Celozaslonski prikaz ni na voljo",
  "__graph": "Graf",
  "__graph_data_copied_to_the_clipboard": "Podatki iz grafa kopirani v odložišče",
  "__help": "Pomoč",
  "__here_is_a_climate_scenario": "Tu je podnebni scenarij, izdelan s simulatorjem #EnROADS, ki sta ga razvila @climateinteract in @MITSloanSusty",
  "__input_range_error_message": "Vnesite vrednost med {minValue} in {maxValue}.",
  "__invalid_url_params": "Izbrane povezave do scenarija ni mogoče pravilno naložiti. Prosimo ponovno ustvarite scenarij v zadnji različici.",
  "__kaya_graphs": "Grafi Kaya",
  "__no": "Ne",
  "__outcomes": "Rezultati",
  "__redo": "Ponovi",
  "__register_your_event": "Prijavite svoj dogodek En-ROADS",
  "__related_examples": "Sorodni primeri",
  "__related_graphs": "Sorodni grafi",
  "__reload": "Ponovno naloži",
  "__replay_last_change": "Ponovno pokaži zadnjo spremembo",
  "__reset_assumptions": "Ponastavi predpostavke",
  "__reset_graphs": "Ponastavi grafe",
  "__reset_sliders": "Ponastavi politike in predpostavke",
  "__scenario_link_copied_to_the_clipboard": "Povezava do scenarija kopirana v odložišče",
  "__sea_level_rise": "Dvig morske gladine",
  "__show_main_graphs": "Prikaži glavne grafe",
  "__show_miniature_graphs": "Prikaži pomanjšane grafe",
  "__show_more": "Pokaži več…",
  "__undo": "Razveljavi",
  "__unsupported_browser": "En-ROADS trenutno ne deluje na Android tablicah. Na računalnikih z operacijskim sistemom Windows in zaslonom na dotik se lahko En-ROADS uporablja preko sledilne plošče, ne pa tudi preko zaslona na dotik.",
  "__url_input_change_warning": "Povezava do scenarija vključuje vrednosti drsnikov, ki ne delujejo s trenutno različico simulatorja En-ROADS. Ti drsniki so bili ponastavljeni na trenutne privzete vrednosti:",
  "__url_input_value_warning": "Povezava do scenarija vključuje vrednosti drsnikov, ki so zunaj veljavnega obsega. Ti drsniki so bili ponastavljeni na trenutne privzete vrednosti:",
  "__yes": "Da",
  "advanced_section_title__carbon_pricing": "Oblikovanje cen ogljika",
  "advanced_section_title__clean_electricity_standard": "Politika čiste električne energije",
  "advanced_section_title__emissions_performance_standard": "Standard emisijskih vrednosti",
  "assumption_group_title__breakthrough_commercialization_time": "Čas komercializacije inovacije",
  "assumption_group_title__climate_system_sensitivities": "Občutljivosti podnebnega sistema",
  "assumption_group_title__economic_impact_of_climate_change": "Gospodarski vpliv podnebnih sprememb",
  "assumption_group_title__energy_supply_progress_ratios": "Stopnja napredka",
  "assumption_group_title__plant_construction_time": "Čas gradnje obrata",
  "assumption_group_title__plant_development_time": "Čas razvoja obrata",
  "assumption_group_title__sea_level_rise": "Dvig morske gladine",
  "assumptions__preset": "Prednastavljeno:",
  "assumptions__related_graph": "Sorodni graf:",
  "basic_section_header__buildings_and_industry": "Zgradbe in industrija",
  "basic_section_header__carbon_removal": "Odvzem ogljika",
  "basic_section_header__energy_supply": "Oskrba z energijo",
  "basic_section_header__growth": "Rast",
  "basic_section_header__transport": "Promet",
  "data_table_139_footnote": "Te vrednosti so odvisne od predpostavk, nastavljenih v nastavitvah <a href=\"#\">Gospodarski učinek</a>:",
  "data_table_row_001_label": "Socialni stroški ogljika v {year}",
  "data_table_row_002_label": "Diskontirana kumulativna škoda do leta 2100",
  "data_table_units__per_ton_co2": "/ tono CO<sub>2</sub>",
  "data_table_units__trillion": "bilijon",
  "data_table_value__dollars": "${num}",
  "graph_001_mini_title": "Viri porabe energije",
  "graph_001_title": "Globalni viri primarne energije",
  "graph_002_menu_title": "Globalni viri primarne energije - območje",
  "graph_002_mini_title": "Viri porabe energije",
  "graph_002_title": "Globalni viri primarne energije",
  "graph_003_title": "Poraba primarne energije iz premoga",
  "graph_005_title": "Poraba primarne energije iz nafte",
  "graph_006_menu_title": "Poraba primarne energije iz nafte - območje",
  "graph_006_title": "Poraba primarne energije iz nafte",
  "graph_007_title": "Poraba primarne energije iz zemeljskega plina",
  "graph_009_title": "Poraba primarne energije iz biomase",
  "graph_011_title": "Poraba primarne energije iz obnovljivih virov",
  "graph_012_title": "Poraba primarne energije iz jedrske energije",
  "graph_013_title": "Nova poraba prim. energije z ničelnimi izpusti ogljika",
  "graph_018_title": "Skupna primarna energija",
  "graph_024_menu_title": "Mejni stroški vetrne in sončne energije - območje",
  "graph_024_title": "Mejni stroški vetrne in sončne energije",
  "graph_026_title": "Ogljična intenzivnost primarne energije",
  "graph_028_title": "Ogljična intenzivnost primarne električne energije",
  "graph_029_mini_title": "Poraba energije",
  "graph_029_title": "Končna poraba energije",
  "graph_030_title": "Končna poraba energije glede na vir",
  "graph_031_menu_title": "Končna poraba energije glede na vir – območje",
  "graph_031_title": "Končna poraba energije glede na vir",
  "graph_033_title": "Končna poraba energije iz premoga",
  "graph_034_title": "Končna poraba energije iz nafte",
  "graph_035_title": "Končna poraba energije iz zemeljskega plina",
  "graph_036_title": "Končna poraba energije iz biomase",
  "graph_037_title": "Končna poraba jedrske energije",
  "graph_038_title": "Končna poraba energije iz obnovljivih virov",
  "graph_039_title": "Končna poraba energije z ničelnimi emisijami ogljika",
  "graph_040_title": "Končna poraba energije z nizkimi izpusti CO<sub>2</sub>",
  "graph_041_menu_title": "Končna poraba električne energije glede na vir - območje",
  "graph_041_title": "Končna poraba električne energije glede na vir",
  "graph_042_menu_title": "Končna poraba energije glede na vrsto uporabe - območje",
  "graph_042_title": "Končna poraba energije glede na vrsto uporabe",
  "graph_043_title": "% končne porabe energije iz obnovljivih virov",
  "graph_045_title": "Delež el. energije v skup. kapitalu - zgradbe & industrija",
  "graph_046_title": "Delež el. energije v skupnem kapitalu - promet",
  "graph_047_mini_title": "Ogljična intenzivnost končne energije",
  "graph_047_title": "Ogljična intenzivnost končne energije",
  "graph_048_title": "Ogljična intenzivnost končne električne energije",
  "graph_051_mini_title": "BDP na prebivalca",
  "graph_051_title": "BDP na prebivalca",
  "graph_052_title": "BDP na prebivalca po regijah",
  "graph_053_title": "Energetska intenzivnost BDP",
  "graph_054_title": "Bruto svetovni proizvod",
  "graph_057_title": "Izpusti in ponori CO<sub>2</sub>",
  "graph_058_title": "Izpusti CO<sub>2</sub>&nbsp;na prebivalca",
  "graph_059_title": "Izpusti CO<sub>2</sub>&nbsp;na dolar realnega BDP",
  "graph_061_mini_title": "Izpusti CO<sub>2</sub>&nbsp;iz proizvodnje energije",
  "graph_061_title": "Izpusti CO<sub>2</sub>&nbsp;iz proizvodnje energije",
  "graph_062_mini_title": "Neto izpusti toplogrednih plinov",
  "graph_062_title": "Neto izpusti toplogrednih plinov",
  "graph_063_menu_title": "Neto izpusti toplogrednih plinov za posamezen plin - območje",
  "graph_063_mini_title": "Neto izpust toplogred. plinov by&nbsp;Plin",
  "graph_063_title": "Neto izpusti toplogrednih plinov za posamezen plin",
  "graph_065_title": "Izpusti toplogrednih plinov brez CO<sub>2</sub>",
  "graph_067_title": "Izpusti CH<sub>4</sub>",
  "graph_068_title": "Izpusti N<sub>2</sub>O",
  "graph_069_title": "Izpusti SF<sub>6</sub>, PFC in HFC",
  "graph_074_title": "Zemljišča za odvzem ogljikovega dioksida",
  "graph_077_menu_title": "Viri neto odvzema CO<sub>2</sub>&nbsp;- območje",
  "graph_077_mini_title": "Neto odvzem CO<sub>2</sub>",
  "graph_077_title": "Viri neto odvzema CO<sub>2</sub>",
  "graph_078_mini_title": "Stroški energije",
  "graph_078_title": "Stroški energije",
  "graph_079_title": "Cena ogljika",
  "graph_082_title": "Tržna cena električne energije",
  "graph_085_title": "Skupni letni stroški energije",
  "graph_086_mini_title": "Sprememba temperature",
  "graph_086_title": "Sprememba temperature",
  "graph_087_title": "Sprememba temperature v °F",
  "graph_088_title": "Koncentracija CO<sub>2</sub>",
  "graph_089_title": "Koncentracija toplogrednih plinov",
  "graph_090_title": "Dvig morske gladine",
  "graph_091_title": "Dvig morske gladine v čevljih",
  "graph_092_title": "Zakisljevanje oceanov",
  "graph_093_title": "Prihodki in stroški iz davkov in subvencij",
  "graph_094_title": "Globalno prebivalstvo",
  "graph_095_title": "Prebivalstvo po regijah",
  "graph_097_menu_title": "Neto kumulativni odvzem CO<sub>2</sub>&nbsp;po tipu - območja",
  "graph_097_title": "Neto kumulativni odvzem CO<sub>2</sub>&nbsp;po tipu",
  "graph_101_title": "Odvzem CO<sub>2</sub>&nbsp;s pogozdovanjem",
  "graph_102_title": "Neto kumulativni izpusti CO<sub>2</sub>",
  "graph_104_mini_title": "Neto izpusti CO<sub>2</sub>",
  "graph_104_title": "Neto izpusti CO<sub>2</sub>",
  "graph_106_title": "Zgodovina gibanja temperatur",
  "graph_110_menu_title": "Mejni stroški proizvodnje električne energije glede na vir",
  "graph_110_mini_title": "Stroški električne energije",
  "graph_110_title": "Mejni stroški proizvodnje električne energije",
  "graph_111_title": "Zemljišča za odvzem ogljikovega dioksida - v akrih",
  "graph_112_menu_title": "Onesnaževanje zraka iz energetike",
  "graph_112_title": "Onesnaževanje zraka iz energetike - izpusti PM2.5",
  "graph_113_menu_title": "Onesnaževanje zraka iz energetike po virih - območje",
  "graph_113_title": "Onesnaževanje zraka iz energetike po virih - PM2.5",
  "graph_115_menu_title": "Mejni stroški proizvodnje nizkoogljične električne energije glede na vir",
  "graph_115_title": "Mejni strošek nizkoogljične proizvodnje",
  "graph_117_title": "Zemljišča za gojenje biomase za odvzem CO<sub>2</sub>",
  "graph_118_title": "Zemljišče za kmetovanje z odvzemom CO<sub>2</sub>",
  "graph_119_title": "Material za mineralizacijo",
  "graph_120_menu_title": "% porabe električne energije iz nizkoogljičnih virov",
  "graph_120_title": "% porabe električne energije iz nizkoogljičnih virov",
  "graph_121_title": "Zemljišča za kmetovanje z odvzemom CO<sub>2</sub>&nbsp;- v akrih",
  "graph_124_title": "Zemljišča za gojenje biomase za odvzem CO<sub>2</sub>&nbsp;- akri",
  "graph_125_title": "Zmanjševanje BDP v odvisnosti od temperature",
  "graph_126_title": "Zmanjševanje BDP zaradi podnebnih vplivov",
  "graph_129_title": "Globalno zmanjšanje BDP",
  "graph_130_title": "Stopnja rasti BDP na prebivalca",
  "graph_132_title": "Čas. gibanje mejnih stroškov sončne energije",
  "graph_133_title": "Gib. porabe prim. energije - premog, nafta & plin",
  "graph_134_title": "Zgodovina porabe primarne energije vetra in sonca",
  "graph_135_title": "Zgodovina neto izpustov toplogrednih plinov",
  "graph_138_title": "% porabe električne energije iz kvalificiranih virov",
  "graph_139_menu_title": "Družbeni strošek ogljika - tabela",
  "graph_139_title": "Družbeni strošek ogljika",
  "graph_140_mini_title": "Dvig morske gladine",
  "graph_140_title": "Dvig morja – zemljevid poplavne ogroženosti",
  "graph_141_title": "Verjetnost arktičnega poletja brez ledu",
  "graph_142_title": "Prebivalstvo izpostavljeno dvigu morske gladine",
  "graph_143_title": "Upad pridelka zaradi spremembe temperatur",
  "graph_144_title": "Vrste, ki izgubijo več kot 50&nbsp;% podnebnega območja",
  "graph_145_title": "Dodatne smrti zaradi ekstremne vročine",
  "graph_actions_menu__copy_data_to_clipboard": "Kopiraj v odložišče",
  "graph_actions_menu__hide_description": "Skrij opis",
  "graph_actions_menu__hide_un_pledges": "Skrij zaveze ZN (NDC)",
  "graph_actions_menu__show_description": "Prikaži opis",
  "graph_actions_menu__show_un_pledges": "Prikaži zaveze ZN (NDC)",
  "graph_actions_menu__view_in_new_window": "Ogled v novem oknu",
  "graph_actions_menu__view_larger": "Povečaj",
  "graph_dataset_label__66pct_chance_of_2degrees_c_or_15degrees_c": "66% možnost za 2&nbsp;ºC ali 1,5&nbsp;ºC",
  "graph_dataset_label__afforestation_and_reforestation": "Pogozdovanje",
  "graph_dataset_label__agricultural_soil_carbon": "Ogljik v kmetijskih tleh",
  "graph_dataset_label__all_countries_follow_ndcs": "Vse države upoštevajo NDC-je",
  "graph_dataset_label__area_of_india": "Območje Indije",
  "graph_dataset_label__at_risk_to_annual_flooding_in_millions": "Tvegajo letne poplave<br>(v milijonih)",
  "graph_dataset_label__australia": "Avstralija",
  "graph_dataset_label__baseline": "Izhodišče",
  "graph_dataset_label__baseline_in_2100": "Izhodišče leta 2100",
  "graph_dataset_label__beccs": "BECCS",
  "graph_dataset_label__biochar": "Biooglje",
  "graph_dataset_label__bioenergy": "Energija iz biomase",
  "graph_dataset_label__birds": "Ptice",
  "graph_dataset_label__butterflies_and_moths": "Metulji in vešče",
  "graph_dataset_label__central_america": "Srednja Amerika",
  "graph_dataset_label__central_europe": "Srednja Evropa",
  "graph_dataset_label__ch4": "CH4",
  "graph_dataset_label__china": "Kitajska",
  "graph_dataset_label__co2_emissions": "Izpusti CO2",
  "graph_dataset_label__co2_removals": "Odvzem CO2",
  "graph_dataset_label__coal": "Premog",
  "graph_dataset_label__coal_production": "Pridobivanje premoga",
  "graph_dataset_label__costs_of_subsidies": "Stroški subvencij",
  "graph_dataset_label__current_scenario": "Trenutni scenarij",
  "graph_dataset_label__current_scenario_in_2100": "Trenutni scenarij v letu 2100",
  "graph_dataset_label__dietz_and_stern": "Dietz & Stern",
  "graph_dataset_label__dragonflies_and_damselflies": "Raznokrili in enakokrili kačji pastirji",
  "graph_dataset_label__east_asia": "Vzhodna Azija",
  "graph_dataset_label__en_roads_baseline": "En-ROADS izhodišče",
  "graph_dataset_label__en_roads_coal": "En-ROADS premog",
  "graph_dataset_label__en_roads_gas": "En-ROADS plin",
  "graph_dataset_label__en_roads_ghg_net_emissions": "En-ROADS neto izpusti toplogred. plinov",
  "graph_dataset_label__en_roads_oil": "En-ROADS nafta",
  "graph_dataset_label__en_roads_solar": "En-ROADS sončna energija",
  "graph_dataset_label__en_roads_wind": "En-ROADS vetrna energija",
  "graph_dataset_label__eu": "EU",
  "graph_dataset_label__f_gases": "F-plini",
  "graph_dataset_label__gas": "Plin",
  "graph_dataset_label__global": "Globalno",
  "graph_dataset_label__global_gdp_in_2024": "Globalni BDP v 2024",
  "graph_dataset_label__gross_co2_removals": "Bruto odvzem CO2",
  "graph_dataset_label__hfc": "HFC",
  "graph_dataset_label__hfc_follows_kigali": "HFC sledijo sporazumu Kigali",
  "graph_dataset_label__historical_ghg_net_emissions": "Zgodovina izpustov toplogrednih plinov",
  "graph_dataset_label__hydro": "Hidroenergija",
  "graph_dataset_label__iea": "IEA",
  "graph_dataset_label__iea_coal": "IEA Premog",
  "graph_dataset_label__iea_gas": "IEA Plin",
  "graph_dataset_label__iea_oil": "IEA Nafta",
  "graph_dataset_label__iea_solar": "IEA Sončna energija",
  "graph_dataset_label__iea_wind": "IEA Vetrna energija",
  "graph_dataset_label__india": "Indija",
  "graph_dataset_label__insects": "Žuželke",
  "graph_dataset_label__invertebrates": "Nevretenčarji",
  "graph_dataset_label__irena": "IRENA",
  "graph_dataset_label__land_use_co2": "CO2 iz rabe tal",
  "graph_dataset_label__lazard": "Lazard",
  "graph_dataset_label__living_below_high_tide_line_in_millions": "Življenje pod nivojem plime<br>(v milijonih)",
  "graph_dataset_label__maize": "Koruza",
  "graph_dataset_label__mammals": "Sesalci",
  "graph_dataset_label__met_office": "Met Office",
  "graph_dataset_label__mineralization": "Mineralizacija",
  "graph_dataset_label__mineralization_rock": "Mineralizacijska kamnina",
  "graph_dataset_label__n2o": "N2O",
  "graph_dataset_label__nasa": "NASA",
  "graph_dataset_label__nasa_upper_per_lower_95pct": "NASA zgornjih/spodnjih 95&nbsp;%",
  "graph_dataset_label__net_revenue_minus_costs": "Neto: prihodki minus stroški",
  "graph_dataset_label__new_zero": "Brezogljične inovacije",
  "graph_dataset_label__new_zero_carbon_baseline": "Novo brezogljično izhodišče",
  "graph_dataset_label__north_america": "Severna Amerika",
  "graph_dataset_label__northern_europe": "Severna Evropa",
  "graph_dataset_label__nuclear": "Jedrska energija",
  "graph_dataset_label__nuclear_baseline": "Izhodišče za jedrsko energijo",
  "graph_dataset_label__oil": "Nafta",
  "graph_dataset_label__other_cdr": "Ostali načini odvzema CO2",
  "graph_dataset_label__other_developed": "Druge razvite države",
  "graph_dataset_label__other_developing": "Druge države v razvoju",
  "graph_dataset_label__pfc": "PFC",
  "graph_dataset_label__plants": "Rastline",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_at_least_once_before_2100": "Verjetnost arktičnega poletja brez ledu<br>vsaj enkrat pred letom 2100",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2050": "Verjetnost arktičnega poletja brez ledu<br>leta 2050",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2100": "Verjetnost arktičnega poletja brez ledu<br>leta 2100",
  "graph_dataset_label__renewables": "Obnovljivi viri",
  "graph_dataset_label__revenue_from_taxes": "Prihodki od davkov",
  "graph_dataset_label__rice": "Riž",
  "graph_dataset_label__sf6": "SF6",
  "graph_dataset_label__solar": "Sončna energija",
  "graph_dataset_label__south_america": "Južna Amerika",
  "graph_dataset_label__southeast_asia": "Jugovzhodna Azija",
  "graph_dataset_label__southern_europe": "Južna Evropa",
  "graph_dataset_label__soybean": "Soja",
  "graph_dataset_label__storage_cost": "Stroški shranjevanja",
  "graph_dataset_label__today": "Danes",
  "graph_dataset_label__transport_electric": "Promet (električni)",
  "graph_dataset_label__us": "ZDA",
  "graph_dataset_label__us_gdp_in_2024": "BDP ZDA leta 2024",
  "graph_dataset_label__vertebrates": "Vretenčarji",
  "graph_dataset_label__wheat": "Pšenica",
  "graph_dataset_label__wind": "Vetrna energija",
  "graph_dataset_label__wind_and_solar": "Vetrna in sončna energija",
  "graph_dataset_label__wind_and_solar_cost": "Stroški vetrne in sončne energije",
  "graph_value__percent": "{num}&nbsp;%",
  "graph_xaxis_label__temperature_change_from_1850___degrees_celsius": "Spremembe temperatur od leta 1850 - stopinje Celzija",
  "graph_yaxis_label__billion_tons_per_year": "Milijarde ton/leto",
  "graph_yaxis_label__billions_of_people": "Milijarde ljudi",
  "graph_yaxis_label__co2_equivalent_parts_per_million_ppm": "Št. delcev na mio ekvivalenta CO2 (ppm)",
  "graph_yaxis_label__co2_parts_per_million_ppm": "CO2 - št. delcev na milijon (ppm)",
  "graph_yaxis_label__degrees_celsius": "Stopinj Celzija",
  "graph_yaxis_label__degrees_fahrenheit": "Stopinj Fahrenheita",
  "graph_yaxis_label__dollars_per_gigajoule": "$/gigadžul",
  "graph_yaxis_label__dollars_per_kwh": "$/kWh",
  "graph_yaxis_label__dollars_per_mwh": "$/MWh",
  "graph_yaxis_label__dollars_per_person_per_year": "$/osebo/leto",
  "graph_yaxis_label__dollars_per_ton_co2": "$/tono CO2",
  "graph_yaxis_label__exajoule_per_trillion_dollars": "Eksadžul/bilijon $",
  "graph_yaxis_label__exajoules_per_year": "Eksadžulov/leto",
  "graph_yaxis_label__feet_ft": "Čevelj (ft)",
  "graph_yaxis_label__gigatons_co2": "Gigaton CO2",
  "graph_yaxis_label__gigatons_co2_equivalent_per_year": "Gigaton ekvivalenta CO2/leto",
  "graph_yaxis_label__gigatons_co2_per_year": "Gigaton CO2/leto",
  "graph_yaxis_label__kilograms_co2_per_mwh": "kg CO2/MWh",
  "graph_yaxis_label__megatons_ch4_per_year": "Megaton CH4/leto",
  "graph_yaxis_label__megatons_co2_per_exajoule": "Megaton CO2/eksadžul",
  "graph_yaxis_label__megatons_pm25_per_year": "Megaton PM2.5/leto",
  "graph_yaxis_label__meters_m": "Metrov (m)",
  "graph_yaxis_label__million_acres": "Milijon akrov",
  "graph_yaxis_label__million_hectares": "Milijon hektarov",
  "graph_yaxis_label__pct_reduction_in_gdp": "% zmanjšanje BDP",
  "graph_yaxis_label__percent": "Odstotek",
  "graph_yaxis_label__percent_per_year": "Odstotek/leto",
  "graph_yaxis_label__ph": "pH",
  "graph_yaxis_label__tons_co2_per_million_dollars_gdp": "Ton CO2/milijon $ BDP",
  "graph_yaxis_label__tons_co2_per_year_per_person": "Ton CO2/leto/osebo",
  "graph_yaxis_label__trillion_dollars_per_year": "Bilijon $/leto",
  "input_001_description": "<p>Davek ali subvencija v $/tono (dolar na tono premogovega) za proizvajalce premoga. Subvencija pomeni zmanjšanje stroškov energije iz premoga, davek pa poviša stroške premoga. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_001_label": "Premog (davek/subvencija)",
  "input_002_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_002_label": "Začetno leto obdavčitve/subvencioniranja premoga",
  "input_003_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_003_label": "Končno leto obdavčitve/subvencioniranja premoga",
  "input_004_description": "<p>Povečajte letno stopnjo opuščanja premogovnih elektrarn, namenjenih za proizvodnjo električne energije. Vsak odstotek pomeni večjo povprečno letno stopnjo opuščanja. Povečanje za 5 % bi bilo znatno.</p>",
  "input_004_label": "Pospešena opustitev premogovnega obrata",
  "input_007_description": "<p>Davek ali subvencija v $/boe (dolar na energijski ekvivalent sodčka nafte) za proizvajalce nafte. S subvencijo se zmanjšajo stroški energije iz nafte, z davkom pa se poveča cena nafte. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_007_label": "Nafta (davek/subvencija)",
  "input_008_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_008_label": "Začetno leto obdavčitve/subvencioniranja nafte",
  "input_009_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_009_label": "Končno leto obdavčitve/subvencioniranja nafte",
  "input_010_description": "<p>Davek ali subvencija, izražena v $/MCF (dolarjih na tisoč kubičnih čevljev) za proizvajalce plina. S subvencijo se zmanjšajo stroški energije iz plina, z davkom pa se poveča cena plina. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_010_label": "Zemeljski plin (davek/subvencija)",
  "input_011_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_011_label": "Začetno leto obdavčitve/subvencioniranja zem. plina",
  "input_012_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_012_label": "Končno leto obdavčitve/subvencioniranja zem. plina",
  "input_016_description": "<p>Subvencija ali davek v $/kWh za energijo, proizvedeno iz obnovljivih virov. Subvencija zmanjša stroške energije iz obnovljivih virov, davek pa poveča ceno obnovljivih virov. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_016_label": "Obnovljivi viri (davek/subvencija)",
  "input_017_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_017_label": "Začetno leto obdavčitve/subvencioniranja za OVE",
  "input_018_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_018_label": "Končno leto obdavčitve/subvencioniranja za OVE",
  "input_019_description": "<p>Delež, pri katerem preboj raziskav in razvoja (R&amp;R) nenadoma zmanjša stroške dobave obnovljive energije. Vrednosti predstavljajo zmanjšanje stroškov od točke, ko pride do preboja.</p>",
  "input_019_label": "OVE - prebojno zmanjšanje stroškov prek R&R",
  "input_020_description": "<p>Leto, ko se zgodi preboj. Naknadno mora priti tudi do komercializacije preboja, da ima ta učinek na trgu.</p>",
  "input_020_label": "Prebojno leto za obnovljive vire energije",
  "input_021_description": "<p>Delež, pri katerem se zaradi preboja na področju raziskav in razvoja (R&amp;R) nenadoma zmanjšajo stroški shranjevanja energije. Vrednosti pomenijo zmanjšanje stroškov od trenutka, ko se zgodi preboj.</p>",
  "input_021_label": "Shranjevanje en. - prebojno zmanjšanje stroškov z R&R",
  "input_022_description": "<p>Leto, ko se zgodi preboj. Naknadno mora priti tudi do komercializacije preboja, da ima ta učinek na trgu.</p>",
  "input_022_label": "Prebojno leto za shranjevanje en.",
  "input_023_description": "<p>Subvenciija ali davek v $/boe (dolar na energijski ekvivalent sodčka nafte) za energijo, proizvedeno iz biomase. S subvencijo se zmanjšajo stroški energije iz biomase, z davkom pa poveča njena cena. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_023_label": "Energija iz biomase (davek/subvencija)",
  "input_024_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_024_label": "Začetno leto obdavčitve/subvencioniranja en. iz biomase",
  "input_025_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_025_label": "Končno leto obdavčitve/subvencioniranja en. iz biomase",
  "input_026_description": "<p>Delež, pri katerem se zaradi preboja na področju raziskav in razvoja (R&amp;R) nenadoma zmanjšajo stroški oskrbe z energijo iz biomase. Vrednosti pomenijo zmanjšanje stroškov od trenutka, ko se zgodi preboj.</p>",
  "input_026_label": "En. iz biomase - prebojno zmanjšanje stroškov prek R&R",
  "input_027_description": "<p>Leto, ko se zgodi preboj. Naknadno mora priti tudi do komercializacije preboja, da ima ta učinek na trgu.</p>",
  "input_027_label": "Prebojno leto za energijo iz biomase",
  "input_030_description": "<p>Subvencija ali davek v $/kWh za proizvajalce jedrske energije. Subvencija zmanjša ceno jedrske energije, davek pa jo poveča. Ta ukrep se uvaja postopoma v obdobju desetih let.</p>",
  "input_030_label": "Jedrska energija (davek/subvencija)",
  "input_031_description": "<p>Leto, v katerem se bo začela subvencija ali obdavčitev</p>",
  "input_031_label": "Začetno leto obdavčitve/subvencioniranja jedrske en.",
  "input_032_description": "<p>Leto, v katerem se bo končala subvencija ali obdavčitev</p>",
  "input_032_label": "Končno leto obdavčitve/subvencioniranja jedrske en.",
  "input_033_description": "<p>Delež, pri katerem se zaradi preboja na področju raziskav in razvoja (R&amp;R) nenadoma zmanjšajo stroški oskrbe z jedrsko energijo. Vrednost 30 % pomeni 30-odstotno zmanjšanje stroškov iz vira, pri katerem se je zgodil preboj.</p>",
  "input_033_label": "Jedrska en. - prebojno znižanje stroškov prek R&R",
  "input_034_description": "<p>Leto, ko se zgodi preboj. Naknadno mora priti tudi do komercializacije preboja, da ima ta učinek na trgu.</p>",
  "input_034_label": "Prebojno leto za jedrsko energijo",
  "input_035_description": "<p>Izberite stopnjo preboja za nov vir energije:</p><p>(0) Status quo = Brez preboja.</p><p>(1) Preboj = Preboj v letu 2022, z začetno ceno, ki je dvakratnik cene premoga.</p><p>(2) Ogromen preboj = Preboj v letu 2022, z začetno ceno, ki je enaka ceni premoga.</p>",
  "input_035_label": "Preboj novih brezogljičnih tehnologij",
  "input_036_description": "<p>Leto, ko se zgodi preboj. Naknadno mora priti tudi do komercializacije preboja, da ima ta učinek na trgu.</p>",
  "input_036_label": "Prebojno leto novih brezogljičnih tehnologij",
  "input_037_description": "<p>Leta, potrebna za komercializacijo nove prebojne inovacije brez emisij (zero-carbon) (na primer od laboratorija do kataloga izdelkov).</p>",
  "input_037_label": "Čas za komercializacijo novih brezogljičnih tehnologij",
  "input_038_description": "<p>Začetni stroški nove brezogljične energije v primerjavi s stroški premoga. Če so stroški nove brezogljične energije manjši kot pri premogu, se bo povpraševanje znatno povečalo, saj bo cenovno konkurenčna drugim virom energije. Vrednost \"2\" pomeni, da je začetni strošek električne energije iz novega brezogljičnega vira v letu preboja dvakrat večji od mejnega stroška električne energije iz premoga v letu 2020.</p>",
  "input_038_label": "Začetni stroški v primerjavi s premogom",
  "input_039_label": "Cena ogljika",
  "input_040_description": "<p>Leto, ko se začne cena ogljika dvigati, da bi dosegla začetno ciljno raven cene ogljika.</p>",
  "input_040_label": "Leto začetka uvajanja cene ogljika",
  "input_041_description": "<p>Leta, ki so potrebna, da cena ogljika doseže začetno ciljno raven cene ogljika.</p>",
  "input_041_label": "Leta za dosego začetne cene ogljika",
  "input_042_description": "<p>Končna ciljna cena ogljika, ki bo linearno rasla od začetne do ciljne vrednosti v roku, določenem s časom za dosego končnega cilja emisij.</p>",
  "input_042_label": "Končna cena ogljika (popraviti \"Začetno leto...\" spodaj)",
  "input_043_description": "<p>Leto, v katerem cena ogljika začne rasti od začetne ravni do končne ciljne cene ogljika. Ta se postopoma linearno stopnjuje skozi leta, da doseže končni cilj cene ogljika.</p>",
  "input_043_label": "Začetno leto doseganja končne cene ogljika",
  "input_044_description": "<p>Leta, ki so potrebna, da cena ogljika doseže končno ciljno raven cene ogljika.</p>",
  "input_044_label": "Št. let za dosego končne cene ogljika",
  "input_045_description": "<p>Standard učinkovitosti, ki bi odvračal od virov energije z večjimi emisijami glede na njihovo ogljično intenzivnost [ton CO<sub>2</sub>&nbsp;na teradžul (TJ) energije]. Stroški se bodo pokazali, ko se bo po standardu ogljična intenzivnost znižala. Ogljična intenzivnost virov: premog 90, nafta 66, plin 51 (ton CO<sub>2</sub>/TJ).</p><p>Source:&nbsp;Environmental Protection Agency. (April 2022). <i><a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.epa.gov/system/files/documents/2022-04/ghg_emission_factors_hub.pdf\">GHG Emissions Factors Hub.</a></i></p>",
  "input_045_label": "Standard emisijskih vrednosti",
  "input_046_description": "<p>Začetno leto standarda emisijskih vrednosti.</p>",
  "input_046_label": "Začetno leto standarda emisijskih vrednosti",
  "input_047_description": "<p>Predvidena sprememba količine energije, ki jo porabijo nove stavbe, industrija, naprave in drugi stroji (vključena je tudi prenova stavb). To je merilo letnega izboljšanja energetske intenzivnosti novih stavb in industrije zaradi tehnoloških sprememb. Povečanje te vrednosti pozitivno vpliva na povprečno stopnjo izboljšanja energetske intenzivnosti v svetu, kar zmanjšuje porabo energije. Ta ukrep se izvaja postopoma v obdobju desetih let.</p>",
  "input_047_label": "Energetska učinkovitost novih zgradb in industrije",
  "input_048_description": "<p>Leto za začetek izboljšav energetske učinkovitosti stavb in industrije.</p>",
  "input_048_label": "Začetno leto",
  "input_050_description": "<p>Predvidena sprememba v količini energije, ki se porabi v prometu (npr. avtomobili, tovornjaki, letala, vlaki). To je merilo letnega izboljšanja energetske intenzivnosti novega energijsko zahtevnega kapitala, ki je posledica tehnoloških sprememb. Povečanje te vrednosti pomeni višjo povprečno stopnjo izboljšanja energetske intenzivnosti na globalni ravni in s tem manjšo porabo energije. Zmanjšanje novega kapitala za 7 % na leto pomeni 2% letno zmanjšanje povprečne energetske intenzivnosti v obdobju 2010-2050. Ta ukrep se izvaja postopoma v obdobju desetih let.</p>",
  "input_050_label": "Energetska učinkovitost novih načinov transporta",
  "input_051_description": "<p>Začetno leto uvajanja izboljšav energetske učinkovitosti v prometu.</p>",
  "input_051_label": "Začetno leto",
  "input_054_description": "<p>Začetno leto uvajanja politik za elektrifikacijo cestnega in železniškega prometa.</p>",
  "input_056_description": "<p>Začetno leto izvajanja politik za elektrifikacijo stavb in industrije.</p>",
  "input_060_description": "<p>Delež maksimalnih možnih ukrepov za zmanjšanje izpustov metana (CH<sub>4</sub>) in dušikovega oksida(N<sub>2</sub>O) iz kmetijstva in odpadkov, pri čemer 100 % predstavlja najvišjo možno stopnjo prizadevanj.</p><p>Source:&nbsp;Gerber, P. J., et al. (2013). <i><a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.fao.org/4/i3437e/i3437e00.htm\">Tackling climate change through livestock – A global assessment of emissions and mitigation opportunities</a></i>. Food and Agriculture Organization of the United Nations.</p>",
  "input_062_description": "<p>Začetno leto uvajanja drugih politik glede toplogrednih plinov.</p>",
  "input_062_label": "Začetno leto za ostale toplogredne pline",
  "input_063_action_label": "Prebivalstvo",
  "input_063_description": "<p>Nastavite svetovno prebivalstvo znotraj intervala s stopnjo zaupanja 95&nbsp;% glede na predvidevanja ZN. Enote se nanašajo na leto 2100, pri čemer 9,0 milijarde ljudi v letu 2100 pomeni najnižjo stopnjo rasti prebivalstva znotraj intervala s stopnjo zaupanja 95&nbsp;%, 11,4 milijarde ljudi v letu 2100 pa pomeni najvišjo stopnjo rasti prebivalstva znotraj intervala s stopnjo zaupanja 95&nbsp;% po ocenah ZN. Podatki: UN DESA, Population Division, 2022.</p><p>Source:&nbsp;United Nations, Department of Economic and Social Affairs, Population Division. (2024). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://population.un.org/wpp/\"><i>World Population Prospects 2024, Online Edition.</i></a></p>",
  "input_063_label": "Prebivalstvo (po scenariju ZN)",
  "input_064_description": "<p>Kratkoročna globalna povprečna letna rast BDP na osebo. Predstavlja merilo trenutne letne stopnje rasti bogastva, ki spodbuja porabo energije.</p>",
  "input_064_label": "Kratkoročna gospodarska rast (BDP na osebo)",
  "input_065_description": "<p>Odstotek maksimalne razpoložljivosti zemljišč, ki so na voljo za pogozdovanje in namenjena zasaditvi.</p>",
  "input_065_label": "Odstotek razpoložljivih zemljišč za pogozdovanje",
  "input_066_description": "<p>Začetno leto prizadevanj na področju pogozdovanja.</p>",
  "input_066_label": "Leto začetka pogozdovanja",
  "input_067_description": "<p>Skupno povečanje ponora ogljikovega dioksida (CDR) iz vseh spodaj navedenih pristopov, pri čemer 100 % pomeni ocenjeno maksimalno količino ogljika, ki ga je moč odstraniti.</p><p>Izberite “Uporabi podrobne nastavitve” za posamično upravljanje pristopov ali izbiro začetka implementacije.</p>",
  "input_067_label": "Tehnološko odstranjevanje ogljika (% maks. potenciala)",
  "input_071_description": "<p>Začetno leto prizadevanj za neposredni zajem ogljika iz zraka.</p>",
  "input_071_label": "Zajem CO<sub>2</sub>&nbsp;iz zraka (DAC) - začetno leto",
  "input_072_description": "<p>Odstotek maksimalno razpoložljivih kmetijskih zemljišč, namenjenih za pospešeno mineralizacijo, imenovano tudi pospešeno preperevanje. To vključuje vsakoletno izkopavanje, obdelavo in raztros specifičnih kamnin, kot je bazalt, ki absorbirajo CO<sub>2</sub>&nbsp;in ga pretvorijo v karbonatne minerale.</p>",
  "input_072_label": "Izboljšana mineralizacija (% maks. potenciala)",
  "input_073_description": "<p>Začetno leto prizadevanj na področju mineralizacije.</p>",
  "input_073_label": "Izboljšana mineralizacija - začetno leto",
  "input_074_description": "<p>Skupno povečanje odvzema ogljikovega dioksida (CDR) na račun praks za povečanje ogljika v kmetijskih tleh (npr. kmetovanje brez obdelave tal in preprečevanje prekomerne paše), pri čemer je 100 % največja količina ogljika, ki jo je mogoče odstraniti.</p>",
  "input_074_label": "Sekvestracija ogljika v kmet. tleh (% maks. potenciala)",
  "input_075_description": "<p>Začetno leto prizadevanj za skladiščenje ogljika v kmetijskih tleh.</p>",
  "input_075_label": "Ogljik v kmetijskih tleh - začetno leto",
  "input_076_description": "<p>Skupno povečanje odvzema ogljikovega dioksida (CDR) na račun obsežnih prizadevanj za pridelavo biooglja, pri čemer je 100 % največja količina ogljika, ki jo je mogoče odstraniti. Biooglje je organska snov, ki se jo predela v oglje in nato zakoplje, da zadrži ogljik.</p>",
  "input_076_label": "Biooglje (% maks. potenciala)",
  "input_077_description": "<p>Začetno leto prizadevanj za sekvestracijo biooglja.</p>",
  "input_077_label": "Biooglje - začetno leto",
  "input_078_description": "<p>Koliko se bo globalna temperatura povišala, če se trenutna količina ekvivalenta CO<sub>2</sub>&nbsp;v atmosferi podvoji. Poročilo IPCC AR6 iz leta 2021 navaja: “Na podlagi številnih dokazov je zelo verjeten razpon ravnovesne podnebne občutljivosti med 2&nbsp;ºC (visoka stopnja zaupanja) in 5&nbsp;ºC (srednja stopnja zaupanja). Najboljša ocena po AR6 je 3&nbsp;ºC, verjeten razpon pa med 2,5&nbsp;ºC in 4&nbsp;ºC (visoka stopnja zaupanja).”</p><p>Source:&nbsp;IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</p>",
  "input_078_label": "Podnebna občutljivost",
  "input_079_description": "<p>Sprememba hitrosti absorpcije ogljikovega dioksida v oceanih zaradi valov, tokov in mešanja plasti (vrtinčenja). Vrednost je multiplikator glede na srednjo vrednost, tako da privzeta vrednost 1 daje stopnjo, ki je enakovredna pričakovani vrednosti 4400 m/m/leto (kot pojasnjeno v referenčnem priročniku En-ROADS). Vrednost 1,1 bi pomenila 10-odstotno povečanje, vrednost 0,9 pa 10-odstotno zmanjšanje.</p><p>Source:&nbsp;Oeschger, H., et al. (1975). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.3402/tellusa.v27i2.9900\">A box diffusion model to study the carbon dioxide exchange in nature.</a> <i>Tellus, 27</i>(2), 168–192.</p>",
  "input_079_label": "Mešanje oceanov",
  "input_080_label": "Gnojenje s CO<sub>2</sub>",
  "input_082_label": "Ogljični cikel in absorpcija oceanov",
  "input_084_label": "Vpliv temperature na izpuste metana iz permafrosta in klatratov",
  "input_085_description": "<p>Prilagodi prag dviga povprečne globalne temperature površja nad predindustrijsko raven, kar sproži sproščanje metana iz permafrosta in klatratov. Pod to mejno temperaturo se predpostavlja, da so emisije iz teh virov enake nič. Nad tem pragom se predpostavlja, da emisije naraščajo linearno s temperaturo.</p>",
  "input_085_label": "Temperaturni prag za permafrost in klatrate",
  "input_087_description": "<p>Odstotek shranjenega ogljika, ki se letno izgubi po sekvestraciji pri mineralizaciji. Na podlagi poročila IPCC WG1 AR5 (poglavje 6, preglednica 6.15) in predpostavke, da je izguba shranjenega ogljika 0 % na leto, kar temelji na predpostavki IPCC o stalnosti.</p><p>Source:&nbsp;IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</p>",
  "input_088_description": "<p>Odstotek shranjenega ogljika, ki se letno izgubi po sekvestraciji pri uporabi biooglja. Na podlagi poročila IPCC WG1 AR5 (poglavje 6, preglednica 6.15) in predpostavke, da dolgoročna izguba znaša 0,2&nbsp;% letno.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</li>\n<li>Caldecott, B., Lomax, G., &amp; Workman, M. (2015). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://ora.ox.ac.uk/objects/uuid:258c4d8e-3ea7-4b72-a24e-44acd01405d1\">Stranded carbon assets and negative emissions technologies [Working paper].</a> In Stranded Assets Programme. Smith School of Enterprise and the Environment, University of Oxford.</li>\n</ul>",
  "input_091_description": "<p>Odstotek shranjenega ogljika, ki se letno izgubi po sekvestraciji pri prizadevanjih za vezavo ogljika v kmetijskih tleh. Na podlagi poročila IPCC WG1 AR5 (poglavje 6, preglednica 6.15) in tipičnih stopenj sproščanja ogljika iz zemlje, določenih z optimizacijo podatkov o gozdovih v ZDA, ki so ocenjene na 1% letno.</p><p>Source:&nbsp;IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</p>",
  "input_095_description": "<p>Največja količina CO<sub>2</sub>, ki se jo letno odvzame iz ozračja prek uporabe biooglja.</p><p>Source:&nbsp;The Royal Society &amp; Royal Academy of Engineering. (2018). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://royalsociety.org/-/media/policy/projects/greenhouse-gas-removal/royal-society-greenhouse-gas-removal-report-2018.pdf/\"><i>Greenhouse gas removal.</i></a> p. 67 Table 2.</p>",
  "input_095_label": "Biooglje",
  "input_096_description": "<p>Največja količina CO<sub>2</sub>, ki se jo letno odvzame iz ozračja prek shranjevanja ogljika v kmetijskih tleh.</p><p>Source:&nbsp;The Royal Society &amp; Royal Academy of Engineering. (2018). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://royalsociety.org/-/media/policy/projects/greenhouse-gas-removal/royal-society-greenhouse-gas-removal-report-2018.pdf/\"><i>Greenhouse gas removal.</i></a> p. 67 Table 2.</p>",
  "input_096_label": "Ogljik v kmetijskih tleh",
  "input_110_action_label": "Čas komercializacije inovacije (jedrska energija)",
  "input_110_description": "<p>Leta, potrebna za dosego polnega potenciala zmanjšanja stroškov prebojne tehnologije za zmanjšanje obratovalnih, vzdrževalnih ter investicijskih stroškov jedrske elektrarne za proizvodnjo električne energije.</p>",
  "input_110_label": "Jedrska energija",
  "input_112_action_label": "Čas komercializacije inovacije (obnovljivi viri energije)",
  "input_112_description": "<p>Leta, potrebna za dosego polnega potenciala zmanjšanja stroškov prebojne tehnologije za zmanjšanje obratovalnih, vzdrževalnih ter investicijskih stroškov obnovljivih virov za proizvodnjo električne energije.</p>",
  "input_112_label": "Obnovljivi viri",
  "input_117_action_label": "Čas komercializacije inovacije (dobavljena energija iz biomase)",
  "input_117_description": "<p>Leta, potrebna za dosego polnega potenciala zmanjšanja stroškov prebojne tehnologije za zmanjšanje obratovalnih, vzdrževalnih ter investicijskih stroškov elektrarne na bioenergijo.</p>",
  "input_117_label": "Energija iz biomase",
  "input_131_action_label": "Čas razvoja obrata (jedrska energija)",
  "input_131_description": "<p>Število let od odločitve za gradnjo obrata do začetka gradnje. Vključuje načrtovanje, financiranje in pridobivanje dovoljenj.</p>",
  "input_131_label": "Jedrska energija",
  "input_132_action_label": "Čas razvoja obrata (hidroenergija)",
  "input_132_description": "<p>Število let od odločitve za gradnjo obrata do začetka gradnje. Vključuje načrtovanje, financiranje in pridobivanje dovoljenj.</p>",
  "input_132_label": "Hidroenergija",
  "input_133_action_label": "Čas razvoja obrata (obnovljivi viri)",
  "input_133_description": "<p>Število let od odločitve za gradnjo obrata do začetka gradnje. Vključuje načrtovanje, financiranje in pridobivanje dovoljenj.</p>",
  "input_133_label": "Obnovljivi viri",
  "input_134_action_label": "Čas razvoja obrata (novi brezogljični viri)",
  "input_134_description": "<p>Število let od odločitve za gradnjo obrata do začetka gradnje. Vključuje načrtovanje, financiranje in pridobivanje dovoljenj.</p>",
  "input_134_label": "Novi brezogljični viri",
  "input_139_action_label": "Čas gradnje obrata (jedrska energija)",
  "input_139_description": "<p>Število let od začetka gradnje novega obrata do zaključka gradnje. Predpostavlja se, da so bili pridobivanje dovoljenj, načrtovanje in financiranje izvedeni pred gradnjo in torej vključeni v fazo 'Razvoj obrata'.</p>",
  "input_139_label": "Jedrska energija",
  "input_140_action_label": "Čas izgradnje obrata (hidroenergija)",
  "input_140_description": "<p>Število let od začetka gradnje novega obrata do zaključka gradnje. Predpostavlja se, da so bili pridobivanje dovoljenj, načrtovanje in financiranje izvedeni pred gradnjo in torej vključeni v fazo 'Razvoj obrata'.</p>",
  "input_140_label": "Hidroenergija",
  "input_141_action_label": "Čas gradnje obrata (obnovljivi viri)",
  "input_141_description": "<p>Število let od začetka gradnje novega obrata do zaključka gradnje. Predpostavlja se, da so bili pridobivanje dovoljenj, načrtovanje in financiranje izvedeni pred gradnjo in torej vključeni v fazo 'Razvoj obrata'.</p>",
  "input_141_label": "Obnovljivi viri",
  "input_142_action_label": "Čas gradnje obrata (novi brezogljični viri)",
  "input_142_description": "<p>Število let od začetka gradnje novega obrata do zaključka gradnje. Predpostavlja se, da so bili pridobivanje dovoljenj, načrtovanje in financiranje izvedeni pred gradnjo in torej vključeni v fazo 'Razvoj obrata'.</p>",
  "input_142_label": "Novi brezogljični viri",
  "input_155_description": "<p>Največji delež zmogljivosti shranjevanja, ki ga je mogoče pokriti s pristopi, kot je prilagajanje odjema, pri katerem se poraba energije preusmerja na čas, ko je energija iz obnovljivih virov na voljo (na primer v elektroenergetskih omrežjih, ki slonijo na sončni energiji, je to takrat, ko sije sonce).</p>",
  "input_155_label": "Maks. potencial za tehnologijo prilagajanja odjema el. energije",
  "input_160_action_label": "Omejitev pretoka na viru (hidroenergija)",
  "input_160_description": "<p>Raven porabe energije (merjena v EJ/leto), pri kateri se stroški začnejo povečevati zaradi doseganja meje smiselno izvedljive letne oskrbe s hidroenergijo. Stroški bi se na primer povečali, ko bi se izrabile dobre lokacije in bi bile za nadaljevanje širitve potrebne manj zaželene lokacije.</p>",
  "input_160_label": "Hidroenergija",
  "input_166_action_label": "Stopnja napredka (premog)",
  "input_166_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za bodoče konstrukcije. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_166_label": "Premog",
  "input_167_action_label": "Stopnja napredka (nafta)",
  "input_167_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_167_label": "Nafta",
  "input_168_action_label": "Stopnja napredka (plin)",
  "input_168_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_168_label": "Plin",
  "input_169_action_label": "Stopnja napredka (energija iz biomase)",
  "input_169_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_169_label": "Energija iz biomase",
  "input_170_action_label": "Stopnja napredka (jedrska energija)",
  "input_170_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_170_label": "Jedrska energija",
  "input_171_action_label": "Stopnja napredka (obnovljivi viri)",
  "input_171_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_171_label": "Obnovljivi viri",
  "input_172_action_label": "Stopnja napredka (hidroenergija)",
  "input_172_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_172_label": "Hidroenergija",
  "input_173_action_label": "Stopnja napredka (novi brezogljični viri)",
  "input_173_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_173_label": "Novi brezogljični viri",
  "input_174_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_174_label": "Shranjevanje",
  "input_175_description": "<p>Koliko se stroški zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za novogradnje. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_176_description": "<p>Tehnologija prilagajanja odjema električne energije zajema tehnologije, strojno opremo ter programsko opremo, ki omogočajo prilagajanje odjema industrijskih porabnikov in gospodinjstev z namenom boljše izkoriščenosti elektroenergetskega omrežja. Stopnja napredka pomeni, koliko se stroški vsega omenjenega zmanjšajo zaradi učenja, izkušenj in ekonomije obsega. Nižja vrednost pomeni hitrejše učenje. Z vsako podvojitvijo kumulativnih inštaliranih zmogljivosti se stroški pomnožijo s stopnjo napredka. Če je na primer stopnja napredka 0,8, se stroški s podvojitvijo izkušenj zmanjšajo za 20&nbsp;%. Ta predpostavka velja za nove sisteme. Pretekle vrednosti so umerjene na znane stroške in zmogljivost.</p><p class=\"sources-header\">Sources:&nbsp;</p><ul>\n<li>Junginger, M., van Sark, W., &amp; Faaij, A. (2010). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.4337/9781849806848\"><i>Technological learning in the energy sector: Lessons for policy, industry and science.</i></a> Edward Elgar.</li>\n<li>McDonald, A., &amp; Schrattenholzer, L. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1016/s0301-4215(00)00122-1\">Learning rates for Energy Technologies.</a> <i>Energy Policy, 29</i>(4), 255–261.</li>\n</ul>",
  "input_176_label": "Tehnologija prilagajanja odjema el. energije",
  "input_196_description": "<p>Zmanjšanje uporabe obratov za obdelavo premoga in premogovnih elektrarn. Polno izvajanje tega nestroškovnega vzvoda politike se v 10-letnem obdobju linearno povečuje. Vrednost 0&nbsp;% pomeni, da se načrtovana uporaba premoga ne spremeni, 50&nbsp;% pomeni, da se načrtovana uporaba premoga razpolovi glede na uporabo brez te politike, 100&nbsp;% pa pomeni popolno ukinitev uporabe premoga kot goriva.</p>",
  "input_196_label": "% zmanjšanja rabe premoga",
  "input_198_description": "<p>Zmanjšanje uporabe rafinerij nafte in elektrarn na nafto. Polno izvajanje tega nestroškovnega vzvoda politike se v 10-letnem obdobju linearno povečuje. Vrednost 0&nbsp;% pomeni, da se načrtovana uporaba nafte ne spremeni. Vrednost 50&nbsp;% pomeni, da je načrtovana uporaba nafte za polovico manjša od tiste brez te politike. Vrednost 100&nbsp;% pomeni opustitev uporabe nafte kot goriva.</p>",
  "input_198_label": "% zmanjšanja rabe nafte",
  "input_200_description": "<p>Zmanjšanje uporabe obratov za predelavo plina in plinskih elektrarn. Polno izvajanje tega nestroškovnega vzvoda politike se v 10-letnem obdobju linearno povečuje. Vrednost 0&nbsp;% pomeni, da se načrtovana uporaba plina ne spremeni. Vrednost 50&nbsp;% pomeni, da je načrtovana uporaba plina za polovico manjša od tiste brez te politike. Vrednost 100&nbsp;% pomeni popolno opustitev uporabe plina kot goriva.</p>",
  "input_200_label": "% zmanjšanja rabe plina",
  "input_202_description": "<p>Leto za začetek zmanjševanja uporabe</p>",
  "input_202_label": "% zmanjšanja rabe premoga - začetno leto",
  "input_203_description": "<p>Leto za prenehanje zmanjševanja uporabe</p>",
  "input_203_label": "% zmanjšanja rabe premoga - končno leto",
  "input_204_description": "<p>Leto za začetek zmanjševanja uporabe</p>",
  "input_204_label": "% zmanjšanja rabe nafte - začetno leto",
  "input_205_description": "<p>Leto za prenehanje zmanjševanja uporabe</p>",
  "input_205_label": "% zmanjšanja rabe nafte - končno leto",
  "input_206_description": "<p>Leto za začetek zmanjševanja uporabe</p>",
  "input_206_label": "% zmanjšanja rabe plina - začetno leto",
  "input_207_description": "<p>Leto za prenehanje zmanjševanja uporabe</p>",
  "input_207_label": "% zmanjšanja rabe plina - končno leto",
  "input_208_label": "Uporabite podrobne nastavitve",
  "input_209_label": "Uporabite podrobne nastavitve",
  "input_210_label": "Uporabite podrobne nastavitve",
  "input_214_label": "Maksimalna razpoložljiva zemljišča za pogozdovanje",
  "input_215_description": "<p>Obseg obstoječih kmetijskih zemljišč, na katerih je potrebno uporabljati izboljšane prakse obdelave, da bi v tleh lahko shranili več ogljika.</p><p>Source:&nbsp;Smith, P., et al. (2015). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1038/nclimate2870\">Biophysical and economic limits to negative CO<sub>2</sub>&nbsp;emissions.</a> <i>Nature Climate Change, 6</i>(1), 42–50.</p>",
  "input_215_label": "Površina zemljišč, potrebna za vezavo ogljika v kmet. tleh, na enoto odvzetega CO<sub>2</sub>",
  "input_218_label": "Čas za zagotovitev zemljišč za pogozdovanje",
  "input_219_description": "<p>Povprečno število let, potrebnih za zasaditev novih dreves, po tem, ko je zemljišče na voljo</p>",
  "input_219_label": "Čas izvedbe pogozdovanja",
  "input_221_description": "<p>Časovni okvir, v katerem se zmanjša uporaba premoga, nafte in plina. Vpliva na učinek drsnikov \"% zmanjšanja uporabe\" v naprednih pogledih premoga, nafte in zemeljskega plina.</p>",
  "input_221_label": "Prilagoditveni čas za uporabo premoga, nafte ali plina",
  "input_222_description": "<p>Količina izpustov delcev PM2,5, ki nastajajo pri kurjenju premoga. Izpusti PM2,5 se merijo kot masa (v Megatonah), ki se sprosti na enoto energije (EJ oz. eksadžul) porabljenega premoga. Vrednost lahko spremenite, da odraža spremembe v intenzivnosti izpustov (npr. zaradi zmanjšanja vrednosti Mton/EJ). Razpon omogoča spreminjanje faktorja izpustov od 50&nbsp;% do 150&nbsp;% privzete vrednosti.</p><p>Source:&nbsp;Klimont, Z., et al. (2017). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.5194/acp-17-8681-2017\">Global anthropogenic emissions of particulate matter including black carbon.</a> <i>Atmospheric Chemistry and Physics</i>, 17(14), 8681–8723.</p>",
  "input_222_label": "Premog",
  "input_223_description": "<p>Količina izpustov delcev PM2,5, ki nastajajo pri kurjenju nafte. Izpusti PM2,5 se merijo kot masa (v Megatonah), ki se sprosti na enoto energije (EJ oz. eksadžul) porabljene nafte. Vrednost lahko spremenite, da odraža spremembe v intenzivnosti izpustov (npr. zaradi zmanjšanja vrednosti Mton/EJ). Razpon omogoča spreminjanje faktorja izpustov od 50&nbsp;% do 150&nbsp;% privzete vrednosti.</p><p>Source:&nbsp;Klimont, Z., et al. (2017). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.5194/acp-17-8681-2017\">Global anthropogenic emissions of particulate matter including black carbon.</a> <i>Atmospheric Chemistry and Physics</i>, 17(14), 8681–8723.</p>",
  "input_223_label": "Nafta",
  "input_224_description": "<p>Količina izpustov delcev PM2,5, ki nastajajo pri kurjenju plina. Izpusti PM2,5 se merijo kot masa (v Megatonah), ki se sprosti na enoto energije (EJ oz. eksadžul) porabljenega plina. Vrednost lahko spremenite, da odraža spremembe v intenzivnosti izpustov (npr. zaradi zmanjšanja vrednosti Mton/EJ). Razpon omogoča spreminjanje faktorja izpustov od 50&nbsp;% do 150&nbsp;% privzete vrednosti.</p><p>Source:&nbsp;Klimont, Z., et al. (2017). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.5194/acp-17-8681-2017\">Global anthropogenic emissions of particulate matter including black carbon.</a> <i>Atmospheric Chemistry and Physics</i>, 17(14), 8681–8723.</p>",
  "input_224_label": "Plin",
  "input_225_description": "<p>Količina izpustov delcev PM2,5, ki nastajajo pri kurjenju biogoriva. Izpusti PM2,5 se merijo kot masa (v Megatonah), ki se sprosti na enoto energije (EJ oz. eksadžul) porabljenega biogoriva. Vrednost lahko spremenite, da odraža spremembe v intenzivnosti izpustov (npr. zaradi zmanjšanja vrednosti Mton/EJ). Razpon omogoča spreminjanje faktorja izpustov od 50&nbsp;% do 150&nbsp;% privzete vrednosti.</p><p>Source:&nbsp;Lükewille, A., et al. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1023/a:1013807101561\">A Module to Calculate Primary Particulate Matter Emissions and Abatement Measures in Europe.</a> <i>Water, Air, and Soil Pollution, 130</i>(1/4), 229–234.</p>",
  "input_225_label": "Energija iz biomase",
  "input_230_action_label": "Omejitev pretoka na viru (veter)",
  "input_230_description": "<p>Raven porabe energije (merjena v EJ/leto), pri kateri se stroški začnejo povečevati zaradi doseganja meje uresničljive letne oskrbe z vetrno energijo. Stroški bi se na primer povečali, ko bi bile dobre lokacije izkoriščene in bi bile za nadaljevanje širitve potrebne manj zaželene lokacije.</p>",
  "input_230_label": "Vetrna energija",
  "input_231_action_label": "Omejitev pretoka na viru (sončna energija)",
  "input_231_description": "<p>Raven porabe energije (merjena v EJ/leto), pri kateri se stroški začnejo povečevati zaradi doseganja meje uresničljive letne oskrbe s sončno energijo. Stroški bi se na primer povečali, ko bi bile dobre lokacije izkoriščene in bi bile za nadaljevanje širitve potrebne manj zaželene lokacije.</p>",
  "input_231_label": "Sončna energija",
  "input_232_action_label": "Omejitev pretoka na viru (geotermalna energija)",
  "input_232_description": "<p>Raven porabe energije (merjena v EJ/leto), pri kateri se stroški začnejo povečevati zaradi doseganja meje uresničljive letne oskrbe z geotermalno energijo. Stroški bi se na primer povečali, ko bi bile dobre lokacije izkoriščene in bi bile za nadaljevanje širitve potrebne manj zaželene lokacije.</p>",
  "input_232_label": "Geotermalna energija",
  "input_233_action_label": "Omejitev pretoka na viru (drugi obnovljivi viri energije)",
  "input_233_description": "<p>Raven porabe energije (merjena v EJ/leto), pri kateri se stroški začnejo povečevati zaradi doseganja meje uresničljive letne oskrbe z drugimi obnovljivimi viri. Stroški bi se na primer povečali, ko bi bile dobre lokacije izkoriščene in bi bile za nadaljevanje širitve potrebne manj zaželene lokacije.</p>",
  "input_233_label": "Drugi obnovljivi viri energije",
  "input_235_description": "<p>Dolgoročna letna rast BDP na osebo. To je merilo letne stopnje rasti bogastva, ki spodbuja potrošnjo energije. Stopnja \"Kratkoročne gospodarske rasti\" se približuje stopnji \"Dolgoročne gospodarske rasti\" v \"Prehodnem obdobju\".</p>",
  "input_235_label": "Dolgoročna gospodarska rast (BDP na osebo)",
  "input_236_description": "<p>Čas, ki je potreben, da se stopnja \"Kratkoročne gospodarske rasti\" približa stopnji \"Dolgoročne gospodarske rasti\".</p>",
  "input_236_label": "Prehodno obdobje",
  "input_237_label": "Maksimalna površina za mineralizacijo",
  "input_238_label": "Uporaba kamnine za mineralizacijo",
  "input_239_description": "<p>Energija za proizvodnjo materiala za mineralizacijo. Ob upoštevanju sekundarnih emisij po Beerlingu in drugih ter ogljične intenzivnosti za leto 2020 dobimo 0,12-0,45; povprečno 0,36 GJ/tono kamnine</p><p>Source:&nbsp;Beerling, D. J., et al. (2020). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1038/s41586-020-2448-9\">Potential for large-scale CO<sub>2</sub>&nbsp;removal via enhanced rock weathering with croplands.</a> <i>Nature, 583</i>(7815), 242–248.</p>",
  "input_239_label": "Energetska intenzivnost mineralizacije",
  "input_240_description": "<p>Globalno povprečje stopnje absorpcije CO<sub>2</sub>&nbsp;na enoto uporabljene mineralizacijske kamnine - nekaj kamnine vsako leto razpade in jo je potrebno nadomestiti. Izračunano po Beerlingu in drugih (2020), upoštevaje neto odvzem brez sekundarnih izpustov, deljeno s povprečjem ton kamnine, kar da 0,16-0,3; povprečje 0,22 CO<sub>2</sub>/tono kamnine.</p><p>Source:&nbsp;Beerling, D. J., et al. (2020). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://doi.org/10.1038/s41586-020-2448-9\">Potential for large-scale CO<sub>2</sub>&nbsp;removal via enhanced rock weathering with croplands.</a> <i>Nature, 583</i>(7815), 242–248.</p>",
  "input_240_label": "Specifični potencial mineralizacije",
  "input_241_description": "<p>Leta za izgradnjo potrebne infrastrukture in prevzem prakse s strani kmetij (to dvoje lahko poteka vzporedno). Sprejetje subvencioniranih kmetovalskih praks lahko traja od 10 do 60 let.</p><p>Source:&nbsp;Fuglie, K. O., &amp; Kascak, C. A. (2001). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.jstor.org/stable/1349955\">Adoption and Diffusion of Natural-Resource-Conserving Agricultural Technology.</a> <i>Review of Agricultural Economics, 23</i>(2), 386-403.</p>",
  "input_241_label": "Čas za uvedbo mineralizacije",
  "input_242_label": "Maksimalno zmanjšanje BDP",
  "input_243_label": "Zmanjšanje BDP pri podnebnih vplivih zvišanja temp. za 1,5 °C",
  "input_245_description": "<p>Določite politiko, v skladu s katero mora minimalni odstotek električne energije izvirati iz kvalificiranih čistih virov električne energije, kot so obnovljivi viri energije. S spodnjimi drsniki prilagodite podrobnosti.</p>",
  "input_245_label": "Uporaba standarda čiste električne energije",
  "input_246_description": "<p>Vrsta(e) virov energije, katerih uporaba je upravičena z vidika izpolnjevanja standarda za čisto električno energijo. Obnovljivi viri energije (veter, sonce, voda in geotermalna energija) so vedno vključeni. Če označite druga polja, lahko dodate poljubno število naslednjih virov: jedrska energija, nova brezogljična energija (če obstaja), fosilna goriva z zajemanjem in shranjevanjem ogljika (CCS), energija iz biomase in/ali zemeljski plin.</p>",
  "input_246_label": "Viri, ki veljajo za čisto električno energijo",
  "input_247_description": "<p>Ciljni minimalni delež električne energije iz kvalificiranih virov za doseganje standarda čiste električne energije. Cilj se doseže po obdobju postopnega uvajanja, ki je določeno z drsnikom \"Leta za dosego standarda čiste električne energije\".</p>",
  "input_247_label": "Ciljni % el. energije iz kvalificiranih virov",
  "input_248_description": "<p>Začetno leto standarda čiste električne energije.</p>",
  "input_248_label": "Začetno leto standarda čiste električne energije",
  "input_249_description": "<p>Čas za postopno uvedbo standarda čiste električne energije. Začetni odstotek se začne pri obstoječem stanju (status quo) in se v tem času poveča na ciljni % električne energije iz kvalificiranih virov.</p>",
  "input_249_label": "Leta za dosego standarda čiste električne energije",
  "input_252_description": "<p>Družbena diskontna stopnja (SDR) se uporablja pri analizi stroškov in koristi ukrepov, ki vplivajo na javno blaginjo, vključno z blaginjo prihodnjih generacij. V okviru podnebnih sprememb se SDR uporablja za izračun sedanje vrednosti koristi ukrepov za zmanjšanje globalnega segrevanja, saj se bodo ti zaradi dolge življenjske dobe toplogrednih plinov v ozračju pojavljali postopoma v obdobju naslednjih nekaj sto let. Upoštevati je treba, da družbena diskontna stopnja ni enaka diskontni stopnji, ki bi jo podjetje lahko uporabilo za oceno, ali naj izvede naložbo, za katero bi moralo podjetje porabiti sredstva danes, da bi lahko povečala dobiček podjetja v prihodnosti. Namesto tega predstavlja skrb danes živečih ljudi za blaginjo prihodnjih generacij. Višja kot je družbena diskontna stopnja, manj pomembna je blaginja prihodnjih generacij.</p><p>Vrednost družbene diskontne stopnje, ki se uporablja v študijah o podnebnih spremembah, je sporna. Nekateri zagovarjajo zelo nizke ali celo ničelne vrednosti, medtem ko drugi uporabljajo vrednosti 3&nbsp;%/leto ali višje. Raziskava iz leta 2015, v kateri je sodelovalo 200 strokovnjakov, je pokazala, \"92 odstotkov strokovnjakov navaja, da bi jim ustrezala SDR nekje v intervalu od 1 do 3 odstotkov [na leto], več kot trem četrtinam pa se zdi sprejemljiva SDR 2 odstotka [na leto].\" (Glej <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"http://doi.org/10.1257/pol.20160240\">Drupp in drugi (2018). Discounting Disentangled. American, Economic Journal: Economic Policy 10(4) 109-134.</a> in <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.lse.ac.uk/granthaminstitute/wp-content/uploads/2015/06/Working-Paper-172-Drupp-et-al.pdf\">Drupp in drugi (2015)</a>. Glej tudi <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.lse.ac.uk/granthaminstitute/explainers/what-are-social-discount-rates/\">What are Social Discount Rates?</a>)</p>",
  "input_252_label": "Družbena diskontna stopnja",
  "input_253_description": "<p>Odstotek shranjenega ogljika, ki se letno izgubi po sekvestraciji pri zajemanju in shranjevanju ogljika (CCS) s fosilnimi gorivi (premog, nafta in plin). V poročilu IPCC WG3 AR5 (poglavje 7, točka 7.5.5) so obravnavane metode za zagotavljanje stalnosti. Poleg tega poročilo WG1 AR5 (poglavje 6, tabela 6.15) predvideva, da je izguba shranjenega ogljika 0 % na leto pri BECCS in DAC , ki uporabljata enake metode shranjevanja.</p><p>Source:&nbsp;IPCC. (2023). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/syr/\"><i>Climate Change 2023: Synthesis Report. Contribution of Working Groups I, II and III to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change</i></a>.</p>",
  "input_259_description": "<p>Začetno leto uvajanja politik za elektrifikacijo zračnega in ladijskega prometa.</p>",
  "input_263_label": "Obnovljivi viri",
  "input_264_label": "Jedrska energija",
  "input_265_label": "Novi brezogljični viri",
  "input_266_label": "Fosilna goriva s CCS",
  "input_267_label": "Energija iz biomase",
  "input_268_label": "Zemeljski plin",
  "input_284_label": "Leta za dosego drugih ciljev za toplogredne pline",
  "input_285_description": "<p>Odraža učinek večjega ali manjšega dviga morske gladine zaradi taljenja ledene plošče na Antarktiki od že upoštevanega v izhodiščnem scenariju. Po poročilu IPCC AR6 je srednja ocena dviga gladine zaradi taljenja ledene plošče na Antarktiki po scenariju SSP3-7.0, ki je najbližji izhodiščnemu scenariju En-ROADS, 0,11 m.</p><p>Source:&nbsp;IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</p>",
  "input_285_label": "Dvig morske gladine zaradi taljenja ledene plošče na Antarktiki",
  "input_286_description": "<p>Odraža učinek večjega ali manjšega dviga morske gladine zaradi taljenja ledene plošče na Grenlandiji od že upoštevanega v izhodiščnem scenariju. Po poročilu IPCC AR6 je srednja ocena dviga gladine zaradi taljenja ledene plošče na Antarktiki po scenariju SSP3-7.0, ki je najbližji izhodiščnemu scenariju En-ROADS, 0,11 m.</p><p>Source:&nbsp;IPCC. (2021). <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https://www.ipcc.ch/report/ar6/wg1/#FullReport\"><i>Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change.</i></a> Chapter 7, Section 7.5.5.</p>",
  "input_286_label": "Dvig morske gladine zaradi taljenja ledene plošče na Grenlandiji",
  "input_482_action_label": "Preostanek prvotnega vira (premog)",
  "input_482_label": "Premog",
  "input_483_action_label": "Preostanek prvotnega vira (nafta)",
  "input_483_label": "Nafta",
  "input_484_action_label": "Preostanek prvotnega vira (plin)",
  "input_484_label": "Plin",
  "input_range__breakthrough": "preboj",
  "input_range__discouraged": "odvračanje",
  "input_range__future_breakthrough": "prihodnji preboj",
  "input_range__high": "visok",
  "input_range__high_growth": "visoka rast",
  "input_range__highest_growth": "najvišja rast",
  "input_range__highly_increased": "močno povečano",
  "input_range__highly_reduced": "močno zmanjšano",
  "input_range__highly_subsidized": "močno subvencionirano",
  "input_range__highly_taxed": "visoko obdavčeno",
  "input_range__huge_breakthrough": "ogromen preboj",
  "input_range__increased": "povečano",
  "input_range__low": "nizko",
  "input_range__low_growth": "nizka rast",
  "input_range__lowest_growth": "najnižja rast",
  "input_range__medium": "srednje",
  "input_range__medium_growth": "srednja rast",
  "input_range__near_term_breakthrough": "kratkoročni preboj",
  "input_range__negative_growth": "negativna rast",
  "input_range__no_growth": "ni rasti",
  "input_range__status_quo": "status quo",
  "input_range__subsidized": "subvencionirano",
  "input_range__taxed": "obdavčeno",
  "input_range__very_high": "zelo visoko",
  "input_range__very_highly_taxed": "zelo visoko obdavčeno",
  "input_units__billion_people_in_2100": "milijarda ljudi leta 2100",
  "input_units__degrees_c": "ºC",
  "input_units__dollars_per_boe": "$/boe",
  "input_units__dollars_per_kwh": "$/kWh",
  "input_units__dollars_per_mcf": "$/Mcf (milijon kub. čevljev)",
  "input_units__dollars_per_ton": "$/tono",
  "input_units__dollars_per_ton_co2": "$/tono CO<sub>2</sub>",
  "input_units__ej_per_year": "EJ/leto",
  "input_units__gj_per_ton_rock": "GJ/tono kamnine",
  "input_units__gtons_co2_per_year": "Gton CO<sub>2</sub>/leto",
  "input_units__mha": "Mha",
  "input_units__mtons_per_ej": "Mton/EJ",
  "input_units__pct": "%",
  "input_units__pct_per_year": "%/leto",
  "input_units__ratio": "razmerje",
  "input_units__ton_co2_per_tj": "ton CO<sub>2</sub>/TJ",
  "input_units__years": "leta",
  "map__error_failed_to_load": "Zemljevida trenutno ni bilo mogoče naložiti.",
  "map__legend_change_in_days_range": "{low} do {high}",
  "map__map_year": "Leto zemljevida:",
  "map__show_baseline": "Prikaži izhodišče",
  "map__show_current_scenario": "Prikaži trenutni scenarij",
  "map__temperature_by_year": "{temp} do {year}",
  "map_slr__error_internet_required": "Zemljevidi dviga morske gladine zahtevajo stabilno internetno povezavo.",
  "map_slr__loading": "Nalaganje zemljevida Climate Central…",
  "map_slr__map_type": "Tip zemljevida:",
  "map_slr__map_type_21st_century": "21. stoletje",
  "map_slr__map_type_longterm": "Dolgoročno ravnovesje",
  "menu__actions_and_outcomes": "Ukrepi in rezultati",
  "menu__assumptions": "Predpostavke",
  "menu__en_roads_overview": "En-ROADS pregled",
  "menu__en_roads_training": "En-ROADS usposabljanje",
  "menu__en_roads_user_guide": "En-ROADS uporabniški priročnik",
  "menu__graph_selection": "Izbira grafov",
  "menu__graphs": "Grafi",
  "menu__help": "Pomoč",
  "menu__kaya_graphs": "Grafi Kaya",
  "menu__language": "Jezik",
  "menu__main_graphs": "Glavni grafi",
  "menu__metric_units": "Metrične enote",
  "menu__miniature_graphs": "Pomanjšani grafi",
  "menu__play_sounds": "Predvajaj zvoke",
  "menu__related_examples": "Sorodni primeri",
  "menu__release_notes": "Opombe k izdaji",
  "menu__reset_assumptions": "Ponastavi predpostavke",
  "menu__reset_policies": "Ponastavi politike",
  "menu__reset_policies_and_assumptions": "Ponastavi politike in predpostavke",
  "menu__return_to_default_graphs": "Vrnite se na privzete grafe",
  "menu__show_graph_tooltips": "Pokaži namige za orodja za grafe",
  "menu__simulation": "Simulacija",
  "menu__slider_information": "Informacije o drsnikih",
  "menu__support": "Podpora",
  "menu__us_units": "Ameriške enote",
  "menu__uses_for_en_roads": "Možnosti uporabe za En-ROADS",
  "menu__video_tours": "Video vodniki",
  "menu__view": "Ogled",
  "menu_graphs__co2_emissions": "Izpusti CO<sub>2</sub>",
  "menu_graphs__final_energy_consumption_totals": "Skupna končna poraba energije",
  "menu_graphs__final_energy_consumption_types": "Vrste končne porabe energije",
  "menu_graphs__financial": "Finance",
  "menu_graphs__greenhouse_gas_emissions": "Izpusti toplogrednih plinov",
  "menu_graphs__impacts": "Vplivi",
  "menu_graphs__model_comparison_history": "Primerjava modelov - zgodovinsko",
  "menu_graphs__population_and_gdp": "Prebivalstvo in BDP",
  "menu_graphs__primary_energy_demand_totals": "Skupna poraba primarne energije",
  "menu_graphs__primary_energy_demand_types": "Vrste porabe primarne energije",
  "menu_graphs__view_more_graphs": "Prikaži več grafov",
  "outcome_13_label": "Diskontirana kumulativna škoda do leta 2100",
  "outcome_13_units_metric": "bilijon $",
  "outcome_1_label": "Zvišanje temperature leta 2100",
  "outcome_1_units_metric": "ºC",
  "outcome_1_units_us": "ºF",
  "outcome_2_label": "Koncentracija CO<sub>2</sub>&nbsp;leta 2100",
  "outcome_2_units_metric": "ppm",
  "outcome_3_label": "Dvig morske gladine leta 2100",
  "outcome_3_units_metric": "m",
  "outcome_3_units_us": "ft",
  "outcome_4_label": "Skupni preprečeni izpusti CO<sub>2</sub>&nbsp;do 2100",
  "outcome_4_units_metric": "gigaton CO<sub>2</sub>",
  "policy_group_001_description": "Odvračanje ali spodbujanje pridobivanja premoga in njegovega kurjenja v elektrarnah. Premog je najbolj škodljivo fosilno gorivo z vidika povzročenih emisij ogljika in onesnaževalcev zraka, ki imajo hude posledice za zdravje. Kljub temu je prevladujoč vir energije na svetu, saj sta njegovo izkopavanje in prevoz razmeroma poceni.",
  "policy_group_001_example_1": "Davki",
  "policy_group_001_example_2": "Manj subvencij",
  "policy_group_001_example_3": "Onesnaževanje zraka",
  "policy_group_001_short_title": "Premog",
  "policy_group_001_title": "Premog",
  "policy_group_002_description": "Odvračanje ali spodbujanje vrtanja, rafiniranja in porabe nafte za energijo. Nafta je fosilno gorivo, ki se pogosto uporablja kot gorivo za avtomobile, ladje in letala, poleg tega pa tudi za industrijo, ogrevanje in električno energijo. Dostop do nafte je sprožil večje konflikte, razlitja nafte pa ogrožajo ekosisteme in vodo.",
  "policy_group_002_example_1": "Manj subvencij",
  "policy_group_002_example_2": "Cevovodi",
  "policy_group_002_example_3": "Odprodaja",
  "policy_group_002_short_title": "Nafta",
  "policy_group_002_title": "Nafta",
  "policy_group_003_description": "Odvračanje ali spodbujanje vrtanja in kurjenja zemeljskega plina za pridobivanje energije. Zemeljski plin je fosilno gorivo, ki se uporablja za proizvodnjo električne energije, ogrevanje in industrijo. Pri zgorevanju se sprošča ogljikov dioksid (četudi manj kot pri premogu in nafti), ob uhajanju v ozračje pa je problem to, da vsebuje veliko metana. Vrtanje zemeljskega plina porablja velike količine vode, lahko pa pride tudi do onesnaženja.",
  "policy_group_003_example_1": "Hidravlično lomljenje",
  "policy_group_003_example_2": "Cevovodi",
  "policy_group_003_example_3": "Odprodaja",
  "policy_group_003_short_title": "Zemeljski plin",
  "policy_group_003_title": "Zemeljski plin",
  "policy_group_004_description": "Odvračanje ali spodbujanje uporabe dreves, odpadkov in kmetijskih pridelkov za proizvodnjo energije. Energija iz biomase nastane pri kurjenju oz. sežiganju živih organskih snovi v trdni (npr. lesni peleti), tekoči (npr. etanol) ali plinski (npr. metan, ki se sprošča pri razgradnji) obliki. Obstajajo različni viri, pri čemer so nekateri trajnostni, drugi pa celo slabši od kurjenja premoga.",
  "policy_group_004_example_1": "Biogoriva",
  "policy_group_004_example_2": "Lesno gorivo",
  "policy_group_004_short_title": "Energija iz biomase",
  "policy_group_004_title": "Energija iz biomase",
  "policy_group_005_description": "Spodbujanje ali odvračanje gradnje sončnih, geotermalnih in vetrnih elektrarn. Obnovljivi viri vključujejo vetrno, sončno, geotermalno in hidroenergijo ter druge tehnologije, ki proizvajajo energijo z minimalno ali nič izpusti ogljikovega dioksida oziroma brez onesnaževanja zraka. Opomba: Jedrska energija in energija iz biomase se obravnavata ločeno.",
  "policy_group_005_example_1": "Vetrna, sončna in hidro",
  "policy_group_005_example_2": "Čista energija",
  "policy_group_005_example_3": "Subvencije",
  "policy_group_005_short_title": "Obnovljivi viri",
  "policy_group_005_title": "Obnovljivi viri",
  "policy_group_006_description": "Spodbujanje ali zaviranje gradnje jedrskih elektrarn. Proizvodnja električne energije v jedrskih obratih sicer ne povzroča izpustov ogljikovega dioksida, a proizvede odpadke, s katerimi je potrebno ravnati več stoletij.",
  "policy_group_006_example_1": "Sevanje",
  "policy_group_006_example_2": "Skladiščenje odpadkov",
  "policy_group_006_short_title": "Jedrska energija",
  "policy_group_006_title": "Jedrska energija",
  "policy_group_007_description": "Odkrijte popolnoma nov poceni vir električne energije, ki ne povzroča izpustov toplogrednih plinov. Nekateri ugibajo, da bi ta preboj lahko predstavljala jedrska fuzija ali jedrska fisija na osnovi torija, vendar so z vsakim novim virom energije povezana neznana tveganja. Odločite se, kdaj bo prišlo do preboja, kakšen bo začetni strošek v primerjavi s premogom in kako dolge bodo zamude pri komercializaciji in širjenju.",
  "policy_group_007_example_1": "Torijevi fisijski reaktorji",
  "policy_group_007_example_2": "Jedrska fuzija",
  "policy_group_007_short_title": "Novi brezogljični viri",
  "policy_group_007_title": "Novi brezogljični viri",
  "policy_group_008_description": "Določite globalno ceno ogljika, ki bo podražila vire energije glede na količino ogljikovega dioksida, ki ga proizvedejo, ali uvedite standard za čisto električno energijo ali emisijski standard. Proizvajalci energije bi lahko dodatne stroške prenesli na svoje odjemalce, zato mora biti politika zasnovana tako, da se čim bolj zmanjša vpliv na najrevnejše prebivalce.",
  "policy_group_008_example_1": "Cena ogljika",
  "policy_group_008_example_2": "Trgovanje z emisijami",
  "policy_group_008_short_title": "Cena ogljika",
  "policy_group_008_title": "Cene ogljika in energetski standardi",
  "policy_group_009_description": "Povečajte ali zmanjšajte energetsko učinkovitost vozil, ladijskega prometa, letalskega prometa in transporta. Energetska učinkovitost vključuje med drugim hibridne avtomobile, razširjen javni prevoz in druge načine, kako potovati ob nižji porabi energije. Uporaba energetsko učinkovitejših praks lahko izboljša javno zdravje in prihrani denar.",
  "policy_group_009_example_1": "Hibridni avtomobili",
  "policy_group_009_example_2": "Hodljivost",
  "policy_group_009_example_3": "Javni prevoz",
  "policy_group_009_short_title": "Energetska učinkovitost",
  "policy_group_009_title": "Energetska učinkovitost prometa",
  "policy_group_010_description": "Povečajte nakup novih električnih avtomobilov, tovornjakov, avtobusov, po možnosti celo ladij in letal. Uporaba električnih motorjev za transport pripomore k zmanjšanju izpustov toplogrednih plinov in onesnaževanja, če električna energija izvira iz nizkoogljičnih virov, kot sta sončna in vetrna energija.",
  "policy_group_010_example_1": "Električna vozila",
  "policy_group_010_example_2": "Tehnologija baterij",
  "policy_group_010_example_3": "Polnilna infrastruktura",
  "policy_group_010_short_title": "Elektrifikacija",
  "policy_group_010_title": "Elektrifikacija prometa",
  "policy_group_011_description": "Povečajte ali zmanjšajte energetsko učinkovitost zgradb, naprav in drugih strojev. Energetska učinkovitost vključuje med drugim gradnjo dobro izoliranih domov ter zmanjševanje porabe energije v tovarnah. Energetsko učinkovite prakse lahko prihranijo denar zaradi manjših energetskih potreb ter izboljšajo zdravje ljudi v takih zgradbah.",
  "policy_group_011_example_1": "Zelene stavbe",
  "policy_group_011_example_2": "Učinkovita industrija",
  "policy_group_011_example_3": "Varčevanje z energijo",
  "policy_group_011_short_title": "Energetska učinkovitost",
  "policy_group_011_title": "Energetska učinkovitost stavb in industrije",
  "policy_group_012_description": "Povečajte porabo električne energije na račun goriv, kot sta nafta ali plin, v zgradbah, ogrevalnih sistemih in drugih strojih. Uporaba električnih motorjev pripomore k manjšim izpustom in boljši kakovosti zraka le pod pogojem, da je električna energija proizvedena iz nizkoogljičnih virov, kot sta sončna ali vetrna energija.",
  "policy_group_012_example_1": "Električno ogrevanje",
  "policy_group_012_example_2": "Velike baterije",
  "policy_group_012_short_title": "Elektrifikacija",
  "policy_group_012_title": "Elektrifikacija v zgradbah in industriji",
  "policy_group_013_description": "Predvidevajte večjo ali manjšo rast prebivalstva. Čeprav obstaja predvidena krivulja rasti prebivalstva, so določeni dejavniki, kot sta izobraževanje žensk in dostop do možnosti načrtovanja družine, ki dokazano pospešujejo premik v smeri manjših družin, kar bi upočasnilo rast prebivalstva.",
  "policy_group_013_example_1": "Opolnomočenje žensk",
  "policy_group_013_example_2": "Stopnje rodnosti",
  "policy_group_013_short_title": "Prebivalstvo",
  "policy_group_013_title": "Prebivalstvo",
  "policy_group_014_description": "Predvidevajte večjo ali manjšo rast proizvedenega blaga in storitev. Gospodarska rast se meri z bruto domačim proizvodom (BDP) na osebo in je ključni dejavnik porabe energije. Obstajajo alternative za zadovoljevanje potreb ljudi prek gospodarskih okvirov, ki ne slonijo na stalni rasti BDP.",
  "policy_group_014_example_1": "BDP na osebo",
  "policy_group_014_example_2": "Gibanje za preprostost",
  "policy_group_014_short_title": "Gospodarska rast",
  "policy_group_014_title": "Gospodarska rast",
  "policy_group_018_short_title": "Tehnološki",
  "policy_group_019_short_title": "Krčenje gozdov",
  "selector__custom": "Po meri",
  "selector__default": "Privzeto",
  "selector__select": "Izberite…",
  "share_by_email__enter_from_addr": "Vnesi svoj elektronski naslov",
  "share_by_email__enter_from_name": "Vnesite svoje ime",
  "share_by_email__enter_note": "Dodatna opomba na vrhu (neobvezno)",
  "share_by_email__enter_to_addr": "Vnesite elektronski naslov prejemnika",
  "share_by_email__failed": "Pri pošiljanju scenarija prek elektronske pošte je prišlo do napake. Poskusite znova.",
  "share_by_email__from_label": "Od",
  "share_by_email__invalid_from_addr": "Vnesite veljaven elektronski naslov pošiljatelja",
  "share_by_email__invalid_from_name": "Vnesite svoje ime",
  "share_by_email__invalid_to_addr": "Vnesite veljaven elektronski naslov prejemnika",
  "share_by_email__note_label": "Opomba",
  "share_by_email__preview_label": "Predogled",
  "share_by_email__privacy": "Spoštujemo vašo zasebnost. Podatki iz tega obrazca se bodo uporabili le za enkratno elektronsko sporočilo prejemniku.",
  "share_by_email__send": "Pošlji",
  "share_by_email__succeeded": "Povezava do scenarija je bila uspešno poslana na {toAddress}",
  "share_by_email__template_line1": "Nov scenarij klimatske politike je bil dan v skupno rabo z vami.",
  "share_by_email__template_line2": "Tu je povezava do globalnega podnebnega scenarija, ki je bil izdelan s simulatorjem En-ROADS:",
  "share_by_email__template_line3": "Oglejte si ga.",
  "share_by_email__template_line4": "En-ROADS je plod razvoja <i>Climate Interactive</i> in <i>MIT Sloan Sustainability Initiative</i>. Za več informacij obiščite {link}.",
  "share_by_email__template_subject": "V skupni rabi z vami: En-ROADS podnebni scenarij",
  "share_by_email__to_label": "Za",
  "share_menu__copy_scenario_link": "Kopiraj povezavo do scenarija",
  "share_menu__share_by_email": "Delite prek e-pošte",
  "share_menu__share_on_facebook": "Delite na Facebooku",
  "share_menu__share_on_linked_in": "Delite na LinkedInu",
  "share_menu__share_on_twitter": "Delite na Twitterju",
  "share_menu__share_your_scenario": "Delite svoj scenarij",
  "temperature_box__increase_by_2100": "Dvig<br>temperature<br>do 2100",
  "welcome__announcement_line1": "En-ROADS je bil posodobljen {date} z novimi funkcijami in izboljšavami.",
  "welcome__line1": "Dobrodošli na En-ROADS, energetsko-podnebnem simulatorju, ki sta ga razvili organizaciji Climate Interactive in MIT Sloan Sustainability Initiative."
}