export default {
  "__actions": "Eylemler",
  "__actions_outcomes": "Eylemler ve Sonuçlar",
  "__assumptions": "Varsayımlar",
  "__assumptions_intro": "En-ROADS modelini çalıştıran önemli varsayımlara ulaşın ve değiştirin. Bu ayarlar, karşılaştırma yapılabilmesi için, yalnızca Mevcut Senaryo'yu etkiler. Referans Senaryo'yu etkilemez.",
  "__beta": "BETA",
  "__cancel": "İptal",
  "__close": "Kapat",
  "__continue_to_en_roads": "En-ROADS'a devam et",
  "__detailed_settings_active": "detaylı ayarlar aktif",
  "__en_roads_climate_ambassador_training": "En-ROADS İklim Elçisi Eğitimi",
  "__enter_full_screen": "Tam ekrana geç",
  "__exit_full_screen": "Tam ekrandan çık",
  "__full_screen_unavailable": "Tam ekran kullanılamıyor",
  "__graph": "Grafik",
  "__graph_dashed_baseline": "Kesikli çizgiler Referans Senaryoyu temsil eder",
  "__graph_data_copied_to_the_clipboard": "Grafik verisi panoya kopyalandı",
  "__help": "Yardım",
  "__here_is_a_climate_scenario": "İşte, @climateinteract ve @MITSloanSusty tarafından geliştirilen #EnROADS benzetimi ile hazırlanan bir iklim senaryosu",
  "__input_range_error_message": "{minValue} ve {maxValue} arasında bir değer girin.",
  "__invalid_url_params": "Denediğiniz senaryo bağlantısı eski ve uygun biçimde yüklenemedi. Lütfen senaryoyu son sürümde yeniden yaratın.",
  "__kaya_graphs": "Kaya Grafikleri",
  "__no": "Hayır",
  "__outcomes": "Sonuçlar",
  "__redo": "Yeniden yap",
  "__register_your_event": "En-ROADS Etkinliğinizi Kaydedin",
  "__related_examples": "İlgili Örnekler",
  "__related_graphs": "İlgili Grafikler",
  "__reload": "Tekrar yükle",
  "__replay_last_change": "Son değişikliği yeniden oynat",
  "__reset_assumptions": "Varsayımları sıfırla",
  "__reset_graphs": "Grafikleri ilk durumuna getir",
  "__reset_sliders": "Politika ve varsayımları ilk durumuna getir",
  "__scenario_link_copied_to_the_clipboard": "Senaryo bağlantısı panoya kopyalandı",
  "__sea_level_rise": "Deniz Seviyesi Yükselmesi",
  "__show_all_regions": "Tüm bölgeleri göster…",
  "__show_main_graphs": "Temel grafikleri göster",
  "__show_miniature_graphs": "Mini grafikleri göster",
  "__show_more": "Daha fazlasını göster…",
  "__undo": "Geri al",
  "__unsupported_browser": "En-ROADS şimdilik Android tabletlerde çalışmıyor. En-ROADS, dokunmatik ekranı olan Windows kişisel bilgisayarlarda, dokunmatik ekranla değil dokunmatik yüzey ile çalışabilir.",
  "__url_input_change_warning": "Senaryo linki güncel En-ROADS sürümü ile uyumlu olmayan kaydırıcı değerleri içeriyor. Bu kaydırıcılar güncel sürümde varsayılan değerlere ayarlandılar:",
  "__url_input_value_warning": "Senaryo linki geçerli aralıkta olmayan kaydırıcı değerleri içeriyor. Bu kaydırıcılar güncel sürümde varsayılan değerlere ayarlandılar:",
  "__yes": "Evet",
  "advanced_section_title__carbon_pricing": "Karbon fiyatlama",
  "advanced_section_title__clean_electricity_standard": "Temiz elektrik standardı",
  "advanced_section_title__emissions_performance_standard": "Salım başarım standardı",
  "assumption_category_title__carbon_capture_and_removals": "Karbon yakalama ve giderimleri",
  "assumption_category_title__earth_system": "Yeryüzü sistemi",
  "assumption_category_title__economy": "Ekonomi",
  "assumption_category_title__energy": "Enerji",
  "assumption_group_title__agriculture": "Tarım",
  "assumption_group_title__air_pollution_from_energy": "Enerji kaynaklı hava kirliliği",
  "assumption_group_title__bioenergy": "Biyoenerji",
  "assumption_group_title__breakthrough_commercialization_time": "Çığır açıcı buluşun ticarileşme zamanı",
  "assumption_group_title__carbon_dioxide_capture_and_transport": "Karbondioksit yakalama ve ulaşım",
  "assumption_group_title__carbon_dioxide_storage": "Karbondioksit depolama",
  "assumption_group_title__climate_system_sensitivities": "İklim sistemi duyarlılıkları",
  "assumption_group_title__economic_impact_of_climate_change": "İklim değişikliğinin ekonomik etkisi",
  "assumption_group_title__electricity_storage_and_demand_response": "Elektrik depolama ve talep yanıtı",
  "assumption_group_title__electrification_and_energy_efficiency": "Elektrifikasyon",
  "assumption_group_title__energy_supply_policy_timing": "Politika zamanlaması",
  "assumption_group_title__energy_supply_progress_ratios": "İlerleme oranı",
  "assumption_group_title__forest_fires": "Orman yangınları",
  "assumption_group_title__initial_fossil_fuel_resource_remaining": "Kalan fosil yakıt kaynağı (başlangıç)",
  "assumption_group_title__land_carbon_and_methane_cycles": "Arazi karbon ve metan kaynakları",
  "assumption_group_title__methane_n2o_and_f_gases": "Metan, N<sub>2</sub>O ve F-gazları",
  "assumption_group_title__plant_construction_time": "Tesis yapım zamanı",
  "assumption_group_title__plant_development_time": "Tesis geliştirme zamanı",
  "assumption_group_title__renewables_flow_constraint_on_source": "Yenilenebilirler için kaynak nedenli akış kısıtlamaları",
  "assumption_group_title__sea_level_rise": "Deniz seviyesi yükselmesi",
  "assumptions__preset": "Ön ayar:",
  "assumptions__related_graph": "İlgili Grafik:",
  "basic_section_header__buildings_and_industry": "Yapılar ve endüstri",
  "basic_section_header__carbon_removal": "Karbon Giderimi",
  "basic_section_header__energy_supply": "Enerji Arzı",
  "basic_section_header__growth": "Büyüme",
  "basic_section_header__other_sources_of_greenhouse_gases": "Diğer Sera Gazı Kaynakları",
  "basic_section_header__transport": "Ulaşım",
  "data_table_139_footnote": "Bu değerler <a href=\"#\">Ekonomik Etki</a> ayarları ile ayarlanan varsayımlara bağlıdır:",
  "data_table_row_001_label": "{year} yılında Karbonun Sosyal Maliyeti",
  "data_table_row_002_label": "2100 boyunca İndirilmiş Birikimli Hasar",
  "data_table_units__per_ton_co2": "/ ton CO<sub>2</sub>",
  "data_table_units__trillion": "trilyon",
  "data_table_value__dollars": "${num}",
  "graph_001_mini_title": "Birincil Enerji Talebi",
  "graph_001_title": "Birincil Enerjinin Küresel Kaynakları",
  "graph_002_menu_title": "Birincil Enerjinin Küresel Kaynakları - Alan",
  "graph_002_mini_title": "Birincil Enerji Talebi",
  "graph_002_title": "Birincil Enerjinin Küresel Kaynakları",
  "graph_003_title": "Kömür Birincil Enerji Talebi",
  "graph_005_title": "Petrol Birincil Enerji Talebi",
  "graph_006_menu_title": "Kullanım Alanına Göre Petrol Birincil Enerji Talebi",
  "graph_006_title": "Kullanıma Göre Petrol Birincil Enerji Talebi",
  "graph_007_title": "Doğal Gaz Birincil Enerji Talebi",
  "graph_009_title": "Biyoenerji Birincil Enerji Talebi",
  "graph_011_title": "Yenilenebilir Enerji Birincil Enerji Talebi",
  "graph_012_title": "Nükleer Birincil Enerji Talebi",
  "graph_013_title": "Yeni Sıfır Karbon Birincil Enerji Talebi",
  "graph_018_title": "Toplam Birincil Enerji",
  "graph_024_menu_title": "Yenilenebilir Enerji Marjinal Maliyeti — Alan",
  "graph_024_title": "Yenilenebilir Enerji Marjinal Maliyeti",
  "graph_026_title": "Birincil Enerjinin Karbon Yoğunluğu",
  "graph_028_title": "Birincil Elektrik Enerjisinin Karbon Yoğunluğu",
  "graph_029_mini_title": "Enerji Talebi",
  "graph_029_title": "Nihai Enerji Tüketimi",
  "graph_030_title": "Kaynağına göre Nihai Enerji Tüketimi",
  "graph_031_menu_title": "Kaynağına Göre Nihai Enerji Tüketimi - Alan",
  "graph_031_title": "Kaynağına Göre Nihai Enerji Tüketimi",
  "graph_033_title": "Kömür Nihai Enerji Tüketimi",
  "graph_034_title": "Petrol Nihai Enerji Tüketimi",
  "graph_035_title": "Doğal Gaz Nihai Enerji Tüketimi",
  "graph_036_title": "Biyoenerji Nihai Enerji Tüketimi",
  "graph_037_title": "Nükleer Nihai Enerji Tüketimi",
  "graph_038_title": "Yenilenebilir Nihai Enerji Tüketimi",
  "graph_039_title": "Yeni Sıfır Karbon Nihai Enerji Tüketimi",
  "graph_040_title": "Düşük Karbon Nihai Enerji Tüketimi",
  "graph_041_menu_title": "Kaynağına Göre Nihai Elektrik Enerjisi—Alan",
  "graph_041_title": "Kaynağına Göre Elektrik Nihai Enerji Tüketimi",
  "graph_042_menu_title": "Son Kullanıma Göre Nihai Enerji Tüketimi—Alan",
  "graph_042_title": "Son Kullanıma göre Nihai Enerji Tüketimi",
  "graph_043_title": "Nihai Enerji Tüketiminde Yenilenebilir %'si",
  "graph_045_title": "Toplam Yapı ve Endüstri Ekipmanları Elektrik Payı",
  "graph_046_title": "Toplam Ulaşım Elektrik Payı",
  "graph_047_mini_title": "Nihai Enerjinin Karbon Yoğunluğu",
  "graph_047_title": "Nihai Enerjinin Karbon Yoğunluğu",
  "graph_048_title": "Nihai Elektrik Enerjisinin Karbon Yoğunluğu",
  "graph_051_mini_title": "Kişi başına GSYH",
  "graph_051_title": "Kişi başına GSYH",
  "graph_052_title": "Bölgelere Göre Kişi başına GSYH",
  "graph_053_title": "GSYH'nın Enerji Yoğunluğu",
  "graph_054_title": "Gayri Safi Küresel Hasıla",
  "graph_055_title": "Kaynağına Göre Enerji CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_057_title": "CO<sub>2</sub>&nbsp;Emisyonları ve Giderimleri",
  "graph_058_title": "Kişi Başına CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_059_title": "GSYH'nin Karbon Yoğunluğu",
  "graph_061_mini_title": "Enerji Kaynaklı CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_061_title": "Enerji Kaynaklı CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_062_mini_title": "Net Sera Gazı Emisyonu",
  "graph_062_title": "Net Sera Gazı Emisyonu",
  "graph_063_menu_title": "Gaza Göre Sera Gazı Net Salımları—Alan",
  "graph_063_mini_title": "Sera Gazı Emisyonu ve Giderimi",
  "graph_063_title": "Gaza Göre Net Sera Gazı Emisyonu",
  "graph_065_title": "CO<sub>2</sub>&nbsp;Dışındaki Sera Gazı Emisyonu",
  "graph_067_title": "Metan Emisyonları",
  "graph_068_title": "N<sub>2</sub>O Emisyonu",
  "graph_069_title": "Türüne Göre F Gazı Emisyonları",
  "graph_073_title": "Net İnsan Kaynaklı CO<sub>2</sub>&nbsp;Giderimi",
  "graph_074_title": "Karbondioksit Giderimi için Arazi",
  "graph_075_title": "Biyoenerji Dışı Arazi Kullanımı Kaynaklı Net CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_076_title": "Arazi Kullanımı Kaynaklı Net CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_077_menu_title": "Net CO<sub>2</sub>&nbsp;Giderimlerinin Kaynakları—Alan",
  "graph_077_mini_title": "CO<sub>2</sub>&nbsp;Giderimleri",
  "graph_077_title": "Net CO<sub>2</sub>&nbsp;Giderimlerinin Kaynakları",
  "graph_078_mini_title": "Enerji Maliyeti",
  "graph_078_title": "Enerji Maliyeti",
  "graph_079_title": "Karbon Fiyatı",
  "graph_082_title": "Elektriğin Pazar Fiyatı",
  "graph_085_title": "Enerjinin Toplam Yıllık Maliyeti",
  "graph_086_mini_title": "Sıcaklık",
  "graph_086_title": "Sıcaklık Değişikliği",
  "graph_087_title": "Sıcaklık Değişikliği °F",
  "graph_088_title": "CO<sub>2</sub>&nbsp;Yoğunluğu",
  "graph_089_title": "Sera Gazı Yoğunluğu",
  "graph_090_title": "Deniz Seviyesi Yükselmesi",
  "graph_091_title": "Deniz Seviyesi Yükselmesi—Feet",
  "graph_092_title": "Okyanus Asitlik Derecesi",
  "graph_093_title": "Vergi ve Yardım Kaynaklı Gelir ve Maliyet",
  "graph_094_title": "Küresel Nüfus",
  "graph_095_title": "Bölgelere göre Nüfus",
  "graph_097_menu_title": "Türüne göre Net Birikmiş CO<sub>2</sub>&nbsp;Giderimi—Alan",
  "graph_097_title": "Türüne göre Net Birikmiş CO<sub>2</sub>&nbsp;Giderimi",
  "graph_101_title": "Ormanlaştırma kaynaklı CO<sub>2</sub>&nbsp;Giderimi",
  "graph_102_title": "Net Birikmiş CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_104_mini_title": "Net CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_104_title": "Net CO<sub>2</sub>&nbsp;Emisyonu",
  "graph_106_title": "Sıcaklık Geçmişi",
  "graph_110_menu_title": "Kaynağına göre Elektrik Üretiminin Marjinal Maliyeti",
  "graph_110_mini_title": "Elektriğin Maliyeti",
  "graph_110_title": "Elektrik Üretiminin Marjinal Maliyeti",
  "graph_111_title": "Karbondioksit Giderimi için Arazi—Akre",
  "graph_112_menu_title": "Enerji Kaynaklı Hava Kirliliği",
  "graph_112_title": "Enerji Kaynaklı Hava Kirliliği — PM2.5 Emisyonu",
  "graph_113_menu_title": "Kaynaklarına göre Enerji kaynaklı Hava Kirliliği—Alan",
  "graph_113_title": "Enerji Kaynaklı Hava Kirliliği — PM2.5",
  "graph_115_menu_title": "Kaynağına göre Elektrik Üretiminin Düşük Karbon Marjinal Maliyeti",
  "graph_115_title": "Düşük Karbon Marjinal Üretim Maliyeti",
  "graph_117_menu_title": "CO<sub>2</sub>&nbsp;Giderimi Biyokütle Yetiştirme için Arazi—Alan",
  "graph_117_title": "CO<sub>2</sub>-Gideren Biyokütle Büyütme için Arazi",
  "graph_118_title": "CO<sub>2</sub>&nbsp;Giderimi ile Tarım için Arazi",
  "graph_119_title": "Topraklaşma için Yığın Malzeme",
  "graph_120_menu_title": "Elektrik Tüketiminde Düşük Karbon %‘si",
  "graph_120_title": "Elektrik Tüketiminde Düşük-Karbon %‘si",
  "graph_121_title": "CO<sub>2</sub>&nbsp;Giderimi ile Tarım için Arazi—Akre",
  "graph_124_menu_title": "CO<sub>2</sub>&nbsp;Giderimi Biyokütle Yetiştirme için Arazi—Alan",
  "graph_124_title": "CO<sub>2</sub>-Gideren Biyokütle Büyütme için Arazi—Akre",
  "graph_125_title": "Sıcaklığa göre GSYİH azalması",
  "graph_126_title": "İklim Etkilerinden GSYİH azalması",
  "graph_129_title": "Küresel GSYİH Kaybı",
  "graph_130_title": "Kişi başına GSYİH Büyüme Hızı",
  "graph_132_title": "Güneş Elektriğinin Marjinal Maliyet Geçmişi",
  "graph_133_title": "Kömür, Petrol ve Gaz Birincil Enerji Talep Geçmişi",
  "graph_134_title": "Rüzgar ve Güneş Birincil Enerji Talep Geçmişi",
  "graph_135_title": "Sera Gazı Net Salımları Geçmişi",
  "graph_138_title": "Uygun Kaynaklardan Elektrik Tüketim %'si",
  "graph_139_menu_title": "Karbonun Sosyal Maliyeti—Tablo",
  "graph_139_title": "Karbonun Sosyal Maliyeti",
  "graph_140_mini_title": "Deniz Seviyesi Yükselmesi",
  "graph_140_title": "Deniz Seviyesi Yükselmesi—Sel Risk Haritası",
  "graph_141_title": "Kuzey Kutbu'nda Buzsuz Yaz Olasılığı",
  "graph_142_title": "Deniz Seviyesi Yükselmesine Maruz Kalan Nüfus",
  "graph_143_title": "Isınma Nedeniyle Mahsül Veriminde Düşüş",
  "graph_144_title": "İklimsel Dağılımının %50'den Fazlasını Kaybeden Türler",
  "graph_145_title": "Bölgelere Göre Aşırı Sıcaktan Ölümler",
  "graph_146_title": "Ormansal Biyoenerji Kaynaklı Toplam CO<sub>2</sub>&nbsp;Net Emisyonları",
  "graph_147_title": "Yaşa Göre Orman Alanı",
  "graph_148_title": "Orman Alanı",
  "graph_149_title": "Tarım Arazisi Alanı",
  "graph_151_menu_title": "Hammadde Bazında Biyoenerji Birincil Enerji Talebi - Alan",
  "graph_151_title": "Hammaddeye Göre Biyoenerji Birincil Enerji Talebi",
  "graph_152_menu_title": "Kaynağına Göre Metan Emisyonları - Alan",
  "graph_152_title": "Kaynağına Göre Metan Emisyonları",
  "graph_153_menu_title": "Kaynağına Göre N<sub>2</sub>O Emisyonları - Alan",
  "graph_153_title": "Kaynağına Göre N<sub>2</sub>O Emisyonları",
  "graph_154_title": "Ormansal Biyoenerji Kaynaklı Brüt CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_156_title": "Ormansal Biyoenerji Kaynaklı Net CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_157_menu_title": "Türüne Göre CO<sub>2</sub>&nbsp;Giderimi - Alan",
  "graph_157_title": "Türe Göre CO<sub>2</sub>&nbsp;Giderimleri",
  "graph_161_menu_title": "Kaynağına Göre CCS Tarafından Yakalanan CO<sub>2</sub>&nbsp;- Alan",
  "graph_161_title": "Kaynağına Göre CCS Tarafından Tutulan CO<sub>2</sub>",
  "graph_163_title": "Arazi Kaynaklı CO<sub>2</sub>&nbsp;Giderimleri",
  "graph_164_title": "Kömür Kaynaklı CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_165_title": "Petrol Kaynaklı CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_166_title": "Doğal Gaz Kaynaklı CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_168_title": "Fosil Yakıtlar Kaynaklı CO<sub>2</sub>&nbsp;Emisyonları",
  "graph_169_title": "Ormansızlaştırma",
  "graph_171_title": "Ormanların Karbon Yoğunluğu",
  "graph_175_menu_title": "Ormansızlaşma ve Olgun Orman Tahribatı—Alan",
  "graph_175_title": "Ormansızlaşma ve Olgun Orman Tahribatı",
  "graph_177_menu_title": "Biyoenerji için Hasat Edilen Arazi—Alan",
  "graph_177_title": "Biyoenerji için Hasat Edilen Arazi",
  "graph_178_title": "Ormansızlaşma ve Olgun Orman Tahribatı",
  "graph_183_title": "Mahsül Verimi",
  "graph_185_title": "Hayvansal Gıda Yüzdesi",
  "graph_191_menu_title": "Orman Kaynaklı CO<sub>2</sub>&nbsp;Brüt Emisyonları—Alan",
  "graph_191_title": "Orman Kaynaklı CO<sub>2</sub>&nbsp;Brüt Emisyonları",
  "graph_196_title": "Ulaşım Satışlarında Elektrik Payı",
  "graph_197_title": "Yapı ve Endüstri Ekipmanları Satışlarında Elektrik Payı",
  "graph_207_menu_title": "Kullanıma Göre ve CCS ile Kömür Birincil Enerji Talebi - Alan",
  "graph_207_title": "Kullanıma Göre ve CCS ile Kömür Birincil Enerji Talebi",
  "graph_208_menu_title": "Kullanıma Göre ve CCS ile Doğal Gaz Birincil Enerji Talebi - Alan",
  "graph_208_title": "CCS ve Kullanıma Göre Doğalgaz Birincil Enerji Talebi",
  "graph_209_menu_title": "Kullanıma Göre ve CCS ile Biyoenerji Birincil Enerji Talebi - Alan",
  "graph_209_title": "CCS ve Kullanıma Göre Biyoenerji Birincil Enerji Talebi",
  "graph_211_menu_title": "Ormanlardaki Karbon—Alan",
  "graph_211_title": "Ormanlardaki Karbon",
  "graph_220_caption_1850": "At <span class=\"caption-value\">{temperature}</span><br>aşırı sıcaklık olayları<br>50 yıl içinde<br>muhtemelen<span class=\"caption-value\">1 defa</span><br>meydana geldi",
  "graph_220_caption_future": "<span class=\"caption-value\">{temperature}</span><br>aşırı sıcaklık olayları<br>muhtemelen 50 yılda <span class=\"caption-value\">{years} yıl</span><br> gerçekleşecek<br>",
  "graph_220_caption_today": "<span class=\"caption-value\">{temperature}</span><br>aşırı sıcaklık olayları<br>şu anda muhtemelen<br>50 yılda <span class=\"caption-value\">{years} yıl</span><br> gerçekleşmekte",
  "graph_220_title": "Aşırı Sıcak Hava Sıklığı",
  "graph_224_title": "Petrol Piyasa Fiyatı",
  "graph_225_title": "Doğalgaz Piyasa Fiyatı",
  "graph_230_title": "Metan Konsantrasyonu",
  "graph_233_menu_title": "Teknolojiye Göre Kurulu Enerji Depolama Kapasitesi",
  "graph_233_title": "Teknolojiye Göre Kurulu Enerji Depolama Kapasitesi",
  "graph_234_menu_title": "Süresine Göre Kurulu Enerji Depolama Kapasitesi",
  "graph_234_title": "Süresine Göre Kurulu Enerji Depolama Kapasitesi",
  "graph_235_title": "Ortalama Seviyelendirilmiş Enerji Depolama Maliyeti",
  "graph_246_title": "Fosil Yakıtlardan Birincil Enerji",
  "graph_247_menu_title": "Yenilenebilir Enerji Türüne Göre Nihai Enerji Tüketimi",
  "graph_247_title": "Yenilenebilir Enerji Türüne Göre Nihai Enerji Tüketimi",
  "graph_249_title": "Değişken Yenilenebilir Kaynaklı Elektrik Tüketimi %",
  "graph_251_title": "Aşırı Sıcak Günler—Harita",
  "graph_252_title": "Isınma Kaynaklı Orman Yangını Riskli Günler—Harita",
  "graph_253_title": "Aşırı Nemli ve Sıcak Günler—Harita",
  "graph_257_title": "Isınma Kaynaklı Ekosistem Değişimleri",
  "graph_258_title": "Kişi Başına Metan Emisyonları",
  "graph_259_title": "GSYİH Metan Yoğunluğu",
  "graph_260_title": "Tarımın Metan Yoğunluğu",
  "graph_261_title": "Toplam Tarımsal Üretim",
  "graph_262_title": "Birincil Enerjinin Metan Yoğunluğu",
  "graph_263_title": "Atıkların Metan Yoğunluğu",
  "graph_265_menu_title": "Kaynağa Göre Enerjiden Kaynaklanan Metan Emisyonları - Alan",
  "graph_265_title": "Kaynağına Göre Enerji Kaynaklı Metan Emisyonları",
  "graph_269_title": "Isınma Nedeniyle Kurak Arazi Genişlemesi",
  "graph_270_title": "Kasırga ve Tayfunlara Maruz Kalan Nüfus",
  "graph_275_title": "Aşırı Sıcaklar Nedeniyle Ölümler",
  "graph_278_title": "Isınma Nedeniyle Okyanuslardaki Yaşam Kaybı",
  "graph_279_title": "Endemik Hayvan Türlerinin Yok Olma Riski",
  "graph_280_title": "Aşırı Sıcaklar Nedeniyle Açık Havada İşgücü Kayıpları",
  "graph_281_title": "Isınma Nedeniyle Sıtma ve Dang Humması Ek Maruziyet",
  "graph_282_menu_title": "Türüne Göre F Gazı Emisyonları - Alan",
  "graph_282_title": "Türe Göre F Gazı Emisyonları",
  "graph_283_menu_title": "Kümülatif F-gaz Emisyonları—Alan",
  "graph_283_title": "Kümülatif F-gazı Emisyonları",
  "graph_287_title": "CO<sub>2</sub>&nbsp;Yoğunluğu ile Mahsulde Besleyicilik Azalması",
  "graph_289_title": "Elektrik Nihai Enerji Tüketimi",
  "graph_292_title": "Nehir Taşkınlarına Maruz Kalan Nüfus",
  "graph_300_title": "Uzun Süreli Kuraklık Olasılığı—Harita",
  "graph_actions_menu__copy_data_to_clipboard": "Verileri Kopyala",
  "graph_actions_menu__hide_description": "Açıklamayı Gizle",
  "graph_actions_menu__hide_no_impact_from_temp": "\"Sıcaklığın etkisi yok\"u gizle",
  "graph_actions_menu__hide_un_pledges": "BM Taahhütlerini Gizle",
  "graph_actions_menu__show_description": "Açıklamayı Göster",
  "graph_actions_menu__show_no_impact_from_temp": "\"Sıcaklığın etkisi yok\"u göster",
  "graph_actions_menu__show_un_pledges": "BM Taahhütlerini Göster",
  "graph_actions_menu__view_in_new_window": "Yeni Pencerede Görüntüle",
  "graph_actions_menu__view_larger": "Daha Büyük Görüntüle",
  "graph_dataset_label__0_50_years": "0-50 yıl",
  "graph_dataset_label__50_100_years": "50-100 yıl",
  "graph_dataset_label__66pct_chance_of_2degrees_c_or_15degrees_c": "%66 ihtimalle 2ºC veya 1.5ºC",
  "graph_dataset_label__afforestation_and_reforestation": "Ormanlaştırma",
  "graph_dataset_label__ag_soil_carbon": "Tarım Toprak Karbonu",
  "graph_dataset_label__agricultural_soil_carbon": "Tarımsal toprak karbonu",
  "graph_dataset_label__agriculture": "Tarım",
  "graph_dataset_label__all_countries_follow_ndcs": "Tüm Ülkeler Taahhütlerine Uyuyor",
  "graph_dataset_label__area_of_india": "Hindistan'ın yüz ölçümü",
  "graph_dataset_label__area_of_sahara_desert": "Sahra Çölü Alanı",
  "graph_dataset_label__area_of_south_america": "Güney Amerika Alanı",
  "graph_dataset_label__at_risk_to_annual_flooding_in_millions": "Yıllık sel riski altında<br>(milyon)",
  "graph_dataset_label__australia": "Avustralya",
  "graph_dataset_label__baseline": "Referans Senaryo",
  "graph_dataset_label__baseline_in_2100": "2100'de Referans Senaryo",
  "graph_dataset_label__beccs": "BECCS",
  "graph_dataset_label__biochar": "Biyokömür",
  "graph_dataset_label__bioenergy": "Biyoenerji",
  "graph_dataset_label__birds": "Kuşlar",
  "graph_dataset_label__burke_2015": "Burke 2015",
  "graph_dataset_label__burke_2018_default": "Burke 2018 (varsayılan)",
  "graph_dataset_label__butterflies_and_moths": "Kelebekler ve Güveler",
  "graph_dataset_label__carbon_in_plants": "Bitkilerdeki Karbon",
  "graph_dataset_label__carbon_in_soils": "Topraktaki Karbon",
  "graph_dataset_label__central_america": "Orta Amerika",
  "graph_dataset_label__central_europe": "Orta Avrupa",
  "graph_dataset_label__ch4": "CH4",
  "graph_dataset_label__china": "Çin",
  "graph_dataset_label__co2_emissions": "CO2 Emisyonu",
  "graph_dataset_label__co2_removals": "CO2 Giderimi",
  "graph_dataset_label__coal": "Kömür",
  "graph_dataset_label__coal_production": "Kömür Üretimi",
  "graph_dataset_label__cost_parity": "Maliyet Paritesi",
  "graph_dataset_label__costs_of_subsidies": "Devlet yardımlarının maliyeti",
  "graph_dataset_label__crops": "Ekinler",
  "graph_dataset_label__current_scenario": "Mevcut Senaryo",
  "graph_dataset_label__current_scenario_discounted": "Mevcut Senaryo – İndirgenmiş",
  "graph_dataset_label__current_scenario_in_2100": "2100'de Mevcut Senaryo",
  "graph_dataset_label__daccs": "DACCS",
  "graph_dataset_label__daily": "Günlük",
  "graph_dataset_label__deforestation": "Ormansızlaştırma",
  "graph_dataset_label__degradation___bioenergy": "Tahribat - Biyoenerji",
  "graph_dataset_label__degradation___fires_from_warming": "Tahribat- Isınma Kaynaklı Yangınlar",
  "graph_dataset_label__degradation___wood_products": "Tahribat - Ahşap Ürünler",
  "graph_dataset_label__dengue": "Dang humması",
  "graph_dataset_label__dietz_and_stern": "Dietz ve Stern",
  "graph_dataset_label__dragonflies_and_damselflies": "Yusufçuklar ve Kızböcekleri",
  "graph_dataset_label__east_asia": "Doğu Asya",
  "graph_dataset_label__electric": "Elektrik",
  "graph_dataset_label__electric_with_ccs": "CCS'li Elektrik",
  "graph_dataset_label__en_roads_baseline": "En-ROADS Referans Senaryo",
  "graph_dataset_label__en_roads_coal": "En-ROADS Kömür",
  "graph_dataset_label__en_roads_gas": "En-ROADS Gaz",
  "graph_dataset_label__en_roads_ghg_net_emissions": "En-ROADS Sera Gazı Net salımları",
  "graph_dataset_label__en_roads_oil": "En-ROADS Petrol",
  "graph_dataset_label__en_roads_solar": "En-ROADS Güneş",
  "graph_dataset_label__en_roads_wind": "En-ROADS Rüzgar",
  "graph_dataset_label__energy_production": "Enerji Üretimi",
  "graph_dataset_label__eu": "AB",
  "graph_dataset_label__f_gases": "F-gazları",
  "graph_dataset_label__farmland": "Tarım Arazisi",
  "graph_dataset_label__forest": "Orman",
  "graph_dataset_label__fossil_fuel_co2": "Fosil Yakıt CO2",
  "graph_dataset_label__gas": "Gaz",
  "graph_dataset_label__global": "Küresel",
  "graph_dataset_label__global_gdp_in_2024": "2024 Küresel GSYİH",
  "graph_dataset_label__gross_co2_removals": "Brüt CO2 Giderimi",
  "graph_dataset_label__hfc": "HFC",
  "graph_dataset_label__hfc_follows_kigali": "HFC Kigali'ye Uyar",
  "graph_dataset_label__historical_ghg_net_emissions": "Sera Gazı Net Salımları Geçmişi",
  "graph_dataset_label__hourly": "Saatlik",
  "graph_dataset_label__howard_and_sterner": "Howard ve Sterner",
  "graph_dataset_label__hydro": "Hidro",
  "graph_dataset_label__hydrogen_storage": "Hidrojen Depolama",
  "graph_dataset_label__iea": "UEA",
  "graph_dataset_label__iea_coal": "UEA Kömür",
  "graph_dataset_label__iea_gas": "UEA Gaz",
  "graph_dataset_label__iea_oil": "UEA Petrol",
  "graph_dataset_label__iea_solar": "UEA Güneş",
  "graph_dataset_label__iea_wind": "UEA Rüzgar",
  "graph_dataset_label__in_2100": "2100 yılında",
  "graph_dataset_label__india": "Hindistan",
  "graph_dataset_label__industry": "Endüstri",
  "graph_dataset_label__insects": "Böcekler",
  "graph_dataset_label__invertebrates": "Omurgasızlar",
  "graph_dataset_label__irena": "UYEA",
  "graph_dataset_label__land_removals": "Arazi Giderimleri",
  "graph_dataset_label__land_species": "Karasal Türler",
  "graph_dataset_label__land_use_co2": "Arazi Kullanım CO2",
  "graph_dataset_label__lazard": "Lazard",
  "graph_dataset_label__living_below_high_tide_line_in_millions": "Yüksek gelgit çizgisinin altında yaşayan<br>(milyon)",
  "graph_dataset_label__maize": "Mısır",
  "graph_dataset_label__malaria": "Sıtma",
  "graph_dataset_label__mammals": "Memeliler",
  "graph_dataset_label__marine_animal": "Deniz Hayvanı",
  "graph_dataset_label__marine_species": "Denizel Türler",
  "graph_dataset_label__met_office": "Met Office",
  "graph_dataset_label__mineralization": "Topraklaşma",
  "graph_dataset_label__mineralization_rock": "Topraklaşma Kayası",
  "graph_dataset_label__montreal_gases": "Montreal gazları",
  "graph_dataset_label__more_than_100_years": "100 yıldan fazla",
  "graph_dataset_label__n2o": "N2O",
  "graph_dataset_label__nasa": "NASA",
  "graph_dataset_label__nasa_upper_per_lower_95pct": "NASA alt/üst %95",
  "graph_dataset_label__net_bioenergy": "Net Biyoenerji",
  "graph_dataset_label__net_revenue_minus_costs": "Net: Gelir eksi maliyet",
  "graph_dataset_label__new_zero": "Yeni Sıfır Karbon",
  "graph_dataset_label__new_zero_carbon_baseline": "Yeni Sıfır Karbon Referans Senaryo",
  "graph_dataset_label__north_america": "Kuzey Amerika",
  "graph_dataset_label__northern_europe": "Kuzey Avrupa",
  "graph_dataset_label__nuclear": "Nükleer",
  "graph_dataset_label__nuclear_baseline": "Nükleer Referans Senaryo",
  "graph_dataset_label__ocean_removals": "Okyanus Giderimleri",
  "graph_dataset_label__oil": "Petrol",
  "graph_dataset_label__other_cdr": "Diğer CDR",
  "graph_dataset_label__other_developed": "Diğer Gelişmiş",
  "graph_dataset_label__other_developing": "Diğer Gelişmekte Olan",
  "graph_dataset_label__other_storage": "Diğer Depolama",
  "graph_dataset_label__pfc": "PFC",
  "graph_dataset_label__phytoplankton": "Fitoplankton",
  "graph_dataset_label__plants": "Bitkiler",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_at_least_once_before_2100": "Kuzey Kutbu'nda buzsuz yaz olasılığı<br>2100 öncesi en az bir kere",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2050": "Kuzey Kutbu'nda buzsuz yaz olasılığı<br>2050'de",
  "graph_dataset_label__probability_of_ice_free_arctic_summer_in_2100": "Kuzey Kutbu'nda buzsuz yaz olasılığı<br>2100'de",
  "graph_dataset_label__renewables": "Yenilenebilir Enerji",
  "graph_dataset_label__revenue_from_taxes": "Vergilerden gelir",
  "graph_dataset_label__rice": "Pirinç",
  "graph_dataset_label__scenario_if_no_economic_impact_from_temp": "Sıcaklık kaynaklı ekonomik etki olmayan senaryo",
  "graph_dataset_label__seasonal": "Mevsimsel",
  "graph_dataset_label__sf6": "SF6",
  "graph_dataset_label__solar": "Güneş",
  "graph_dataset_label__south_america": "Güney Amerika",
  "graph_dataset_label__southeast_asia": "Güneydoğu Asya",
  "graph_dataset_label__southern_africa": "Güney Afrika",
  "graph_dataset_label__southern_europe": "Güney Avrupa",
  "graph_dataset_label__soybean": "Soya Fasulyesi",
  "graph_dataset_label__storage_cost": "Depolama Maliyeti",
  "graph_dataset_label__today": "Bugün",
  "graph_dataset_label__transport_electric": "Ulaşım (elektrik)",
  "graph_dataset_label__us": "ABD",
  "graph_dataset_label__us_gdp_in_2024": "2024'da ABD GSYİH",
  "graph_dataset_label__vertebrates": "Omurgalılar",
  "graph_dataset_label__waste": "Atık",
  "graph_dataset_label__waste_per_other": "Atık/Diğer",
  "graph_dataset_label__west_asia": "Batı Asya",
  "graph_dataset_label__wheat": "Buğday",
  "graph_dataset_label__wind": "Rüzgar",
  "graph_dataset_label__wind_and_solar": "Rüzgar ve Güneş",
  "graph_dataset_label__wind_and_solar_cost": "Rüzgar ve Güneş Maliyeti",
  "graph_dataset_label__wood": "Odun",
  "graph_dataset_label__zooplankton": "Zooplankton",
  "graph_menu__favorites_empty_detail": "Favorilerinizi kaydetmeye başlamak için herhangi bir grafiğin yanındaki yıldızı tıklayın.",
  "graph_menu__favorites_empty_title": "Henüz favori yok",
  "graph_menu__favorites_title": "Favoriler",
  "graph_menu__search_empty_title": "Sonuç bulunamadı",
  "graph_menu__search_placeholder": "Grafiklerde ara",
  "graph_menu__view_as_grid": "Izgara olarak görüntüle",
  "graph_menu__view_as_list": "Liste olarak görüntüle",
  "graph_menu_grouping__agriculture": "Tarım",
  "graph_menu_grouping__atmosphere": "Atmosfer",
  "graph_menu_grouping__ecosystems_and_biodiversity": "Ekosistemler ve Biyoçeşitlilik",
  "graph_menu_grouping__emissions_from_land_use": "Arazi Kullanımı Kaynaklı Emisyonlar",
  "graph_menu_grouping__extreme_weather": "Aşırı Hava Olayları",
  "graph_menu_grouping__fluorinated_gases": "Florlu Gazlar",
  "graph_menu_grouping__forestry": "Ormancılık",
  "graph_menu_grouping__general": "Genel",
  "graph_menu_grouping__health_and_economy": "Sağlık ve Ekonomi",
  "graph_menu_grouping__land_use": "Arazi Kullanımı",
  "graph_menu_grouping__methane": "Metan",
  "graph_menu_grouping__nitrous_oxide": "Nitröz Oksit",
  "graph_menu_grouping__oceans": "Okyanuslar",
  "graph_menu_grouping__totals": "Toplam",
  "graph_value__percent": "{num}%",
  "graph_xaxis_label__temperature_change_from_1850___degrees_celsius": "1850'den bu yana Sıcaklık Değişimi—Derece Santigrat",
  "graph_yaxis_label__billion_tons_per_year": "Milyar ton/yıl",
  "graph_yaxis_label__billions_of_people": "Milyar Kişi",
  "graph_yaxis_label__ch4_parts_per_million_ppm": "CH4 milyonda bir parça (ppm)",
  "graph_yaxis_label__co2_equivalent_parts_per_million_ppm": "Milyonda birim CO2 eşdeğeri (ppm)",
  "graph_yaxis_label__co2_parts_per_million_ppm": "Milyonda birim CO2 (ppm)",
  "graph_yaxis_label__days_per_year_per_worker": "Günler/yıl/işçi",
  "graph_yaxis_label__deaths_per_100000_people_per_year": "100.000 kişi/yıl başına ölümler",
  "graph_yaxis_label__degrees_celsius": "Derece Santigrat",
  "graph_yaxis_label__degrees_fahrenheit": "Fahrenheit Derece",
  "graph_yaxis_label__dollars_per_boe": "$/boe (varil petrol eşdeğeri)",
  "graph_yaxis_label__dollars_per_gigajoule": "$/gigajul",
  "graph_yaxis_label__dollars_per_kwh": "$/kWsa",
  "graph_yaxis_label__dollars_per_mcf": "$/MCF",
  "graph_yaxis_label__dollars_per_mwh": "$/MWsa",
  "graph_yaxis_label__dollars_per_person_per_year": "$/kişi/yıl",
  "graph_yaxis_label__dollars_per_ton_co2": "$/ton CO2",
  "graph_yaxis_label__exajoule_per_trillion_dollars": "Ekzajoule/Trilyon $",
  "graph_yaxis_label__exajoules": "Eksajul",
  "graph_yaxis_label__exajoules_per_year": "Ekzajoule/yıl",
  "graph_yaxis_label__exposure_per_100000_people_per_year": "100.000 kişi/yıl başına maruz kalma",
  "graph_yaxis_label__feet_ft": "Fit (ft)",
  "graph_yaxis_label__gigatons_c": "Gigaton C",
  "graph_yaxis_label__gigatons_co2": "Gigaton CO2",
  "graph_yaxis_label__gigatons_co2_equivalent": "Gigaton CO2 eşdeğeri",
  "graph_yaxis_label__gigatons_co2_equivalent_per_year": "Gigaton CO2 eşiti/yıl",
  "graph_yaxis_label__gigatons_co2_per_year": "Gigaton CO2/yıl",
  "graph_yaxis_label__gigatons_produced_per_year": "Gigaton üretimi/yıl",
  "graph_yaxis_label__kg_ch4_per_ton_of_waste": "kg CH4/ton atık",
  "graph_yaxis_label__kg_ch4_per_ton_produced": "Üretilen kg CH4/ton",
  "graph_yaxis_label__kg_ch4_per_year_per_person": "kg CH4/yıl/kişi",
  "graph_yaxis_label__kg_per_year_per_hectare": "kg/yıl/hektar",
  "graph_yaxis_label__kilograms_co2_per_mwh": "kg CO2/MWh",
  "graph_yaxis_label__kilotons_ch4_per_exajoule": "Kiloton CH4/eksajul",
  "graph_yaxis_label__megatons_ch4_per_year": "Megaton CH4/yıl",
  "graph_yaxis_label__megatons_co2_per_exajoule": "Megaton CO2/ekzajoule",
  "graph_yaxis_label__megatons_nitrogen_per_year": "Megaton nitrojen/yıl",
  "graph_yaxis_label__megatons_pm25_per_year": "Megaton PM2.5/yıl",
  "graph_yaxis_label__meters_m": "Metre (m)",
  "graph_yaxis_label__million_acres": "Milyon Akre",
  "graph_yaxis_label__million_hectares": "Milyon hektar",
  "graph_yaxis_label__million_hectares_per_year": "Milyon hektar/yıl",
  "graph_yaxis_label__millions_of_people_per_year": "Milyon kişi/yıl",
  "graph_yaxis_label__pct_reduction_in_gdp": "GSYİH Azalma %'si",
  "graph_yaxis_label__percent": "Yüzde",
  "graph_yaxis_label__percent_loss": "Kayıp yüzdesi",
  "graph_yaxis_label__percent_of_species": "Türlerin yüzdesi",
  "graph_yaxis_label__percent_per_year": "Yüzde/yıl",
  "graph_yaxis_label__ph": "pH",
  "graph_yaxis_label__ratio": "Oran",
  "graph_yaxis_label__tons_ch4_per_million_dollars_gdp": "Ton CH4/milyon $ GSYH",
  "graph_yaxis_label__tons_co2_per_million_dollars_gdp": "Ton CO2/milyon $ GSYH",
  "graph_yaxis_label__tons_co2_per_year_per_person": "Ton CO2/yıl/kişi",
  "graph_yaxis_label__tonsc_per_hectare": "ton C/hektar",
  "graph_yaxis_label__trillion_dollars_per_year": "Trilyon $/yıl",
  "input_001_label": "Kömür (vergi/devlet desteği)",
  "input_002_label": "Kömür vergi/devlet desteği başlama yılı",
  "input_003_label": "Kömür vergi/devlet desteği bitme yılı",
  "input_004_label": "Kömür tesisinin hızlandırılmış kullanım dışı bırakılması",
  "input_007_label": "Petrol (vergi/devlet desteği)",
  "input_008_label": "Petrol vergi/devlet desteği başlama yılı",
  "input_009_label": "Petrol vergi/devlet desteği bitiş yılı",
  "input_010_label": "Doğal Gaz (vergi/devlet desteği)",
  "input_011_label": "Doğal Gaz vergi/devlet desteği başlama yılı",
  "input_012_label": "Doğal Gaz vergi/devlet desteği bitiş yılı",
  "input_016_label": "Yenilenebilir Enerji (vergi/devlet desteği)",
  "input_017_label": "Yenilenebilir Enerji vergi/devlet desteği başlama yılı",
  "input_018_label": "Yenilenebilir Enerji vergi/devlet desteği bitiş yılı",
  "input_019_label": "Yenilenebilir Enerji çığır açıcı maliyet düşmesi",
  "input_020_label": "Yenilenebilir Enerji çığır açan buluş yılı",
  "input_021_label": "Diğer depolama çığır açıcı maliyet düşmesi",
  "input_022_label": "Diğer depolama çığır açıcı buluş yılı",
  "input_023_label": "Biyoenerji (vergi/devlet desteği)",
  "input_024_label": "Biyoenerji vergi/devlet desteği başlama yılı",
  "input_025_label": "Biyoenerji vergi/devlet desteği bitiş yılı",
  "input_026_label": "Biyoenerji çığır açıcı maliyet düşmesi",
  "input_027_label": "Biyoenerji çığır açıcı buluş yılı",
  "input_030_label": "Nükleer (vergi/devlet desteği)",
  "input_031_label": "Nükleer vergi/devlet desteği başlama yılı",
  "input_032_label": "Nükleer vergi/devlet desteği bitiş yılı",
  "input_033_label": "Nükleer Ar-Ge çığır açıcı maliyet düşmesi",
  "input_034_label": "Nükleer çığır açıcı buluş yılı",
  "input_035_label": "Çığır açıcı Yeni Sıfır Karbon",
  "input_036_label": "Çığır açıcı Yeni Sıfır Karbon yılı",
  "input_037_label": "Yeni Sıfır Karbon ticarileşme zamanı",
  "input_038_label": "Kömüre göre başlangıç maliyeti",
  "input_039_label": "Karbon Fiyatı",
  "input_040_label": "Yeni karbon fiyatının devreye alınma yılı",
  "input_041_label": "İlk karbon fiyatına ulaşmak için gereken yıl",
  "input_042_label": "Son karbon fiyatı (aşağıdaki \"... başlama yılı\"nı ayarlayın)",
  "input_043_label": "Son karbon fiyatına ulaşmaya başlama yılı",
  "input_044_label": "Son karbon fiyatına ulaşma için gereken yıl",
  "input_045_label": "Emisyon başarım standartı",
  "input_046_label": "Emisyon başarım standartı başlama yılı",
  "input_047_label": "Yeni yapıların ve endüstrinin enerji verimliliği",
  "input_048_label": "Başlama yılı",
  "input_050_label": "Yeni ulaşımın enerji verimliliği",
  "input_051_label": "Başlama yılı",
  "input_053_action_label": "Akaryakıtlı ulaşım satış sınırı—kara ve demiryolu",
  "input_053_label": "Akaryakıtlı ulaşım satış sınırı",
  "input_054_action_label": "Elektrifikasyon politikası başlangıç yılı—kara ve demiryolu",
  "input_054_label": "Elektrifikasyon politikası başlangıç yılı",
  "input_055_label": "Akaryakıtlı ulaşım satış sınırı",
  "input_056_label": "Elektrifikasyon politikası başlangıç yılı",
  "input_057_label": "Ormansızlaştırma ve Olgun Orman Tahribatı (artır/azalt)",
  "input_060_label": "Tarımdan kaynaklanan metan ve azot oksit",
  "input_061_label": "Atık ve kaçak kaynaklı metan ve diğer gazlar",
  "input_062_label": "Atık ve kayıp-kaçak eylemleri için başlangıç yılı",
  "input_063_action_label": "Nüfus",
  "input_063_label": "Nüfus (BM Senaryo aralığı)",
  "input_064_label": "Kısa vadeli ekonomik büyüme (kişi başına GSYH)",
  "input_065_label": "Ormanlaştırmaya elverişli arazi yüzdesi",
  "input_066_label": "Ormanlaştırma başlama yılı",
  "input_067_label": "Teknolojik karbon giderimi",
  "input_071_label": "Doğrudan hava yakalama sübvansiyonu başlangıç yılı",
  "input_072_label": "Hızlandırılmış mineral çözülmesi",
  "input_073_label": "Hızlandırılmış mineral çözülmesi başlama yılı",
  "input_074_label": "Tarımsal toprak karbonu tutma",
  "input_075_label": "Tarımsal toprak karbonu başlama yılı",
  "input_076_label": "Biyoçar",
  "input_077_label": "Biyolojik kömür başlama yılı",
  "input_078_label": "İklim duyarlılığı",
  "input_079_label": "Okyanus karışımı",
  "input_080_label": "CO<sub>2</sub>&nbsp;gübreleme",
  "input_082_label": "Karbon döngüsü okyanus tutması",
  "input_083_label": "Sıcaklığın CH<sub>4</sub>&nbsp;solunum oranlarına etkisi",
  "input_084_label": "Sıcaklığın donmuş topraklardan (permafrost) metan emisyonuna etkisi",
  "input_085_label": "Donmuş toprak ve kafes bileşikler için sıcaklık eşiği",
  "input_087_label": "Mineralizasyon kayıp oranı",
  "input_088_label": "Biyokömür kayıp oranı",
  "input_091_label": "Tarımsal toprak karbon kaybı oranı",
  "input_095_label": "Biyokömür",
  "input_096_label": "Tarımsal toprak karbonu",
  "input_110_action_label": "Çığır açıcı buluşun ticarileşme zamanı (Nükleer)",
  "input_110_label": "Nükleer",
  "input_112_action_label": "Çığır açıcı buluşun ticarileşme zamanı (Yenilenebilir Enerji)",
  "input_112_label": "Yenilenebilir Enerji",
  "input_117_action_label": "Çığır açıcı buluşun ticarileşme zamanı (Ulaşılan biyoenerji)",
  "input_117_label": "Biyoenerji",
  "input_131_action_label": "Tesis geliştirme zamanı (Nükleer)",
  "input_131_label": "Nükleer",
  "input_132_action_label": "Tesis geliştirme zamanı (Hidro)",
  "input_132_label": "Hidro",
  "input_133_action_label": "Tesis geliştirme zamanı (Yenilenebilir Enerji)",
  "input_133_label": "Yenilenebilir Enerji",
  "input_134_action_label": "Tesis geliştirme süresi (Yeni sıfır karbon)",
  "input_134_label": "Yeni Sıfır Karbon",
  "input_139_action_label": "Tesis yapım zamanı (Nükleer)",
  "input_139_label": "Nükleer",
  "input_140_action_label": "Tesis yapım zamanı (Hidro)",
  "input_140_label": "Hidro",
  "input_141_action_label": "Tesis yapım zamanı (Yenilenebilir Enerji)",
  "input_141_label": "Yenilenebilir Enerji",
  "input_142_action_label": "Tesis yapım süresi (Yeni sıfır karbon)",
  "input_142_label": "Yeni Sıfır Karbon",
  "input_155_label": "Talep yanıtı için maksimum potansiyel",
  "input_160_action_label": "Kaynak üzerinde akış kısıtı (Hidro)",
  "input_160_label": "Hidro",
  "input_166_action_label": "İlerleme oranı (Kömür)",
  "input_166_label": "Kömür",
  "input_167_action_label": "İlerleme oranı (Petrol)",
  "input_167_label": "Petrol",
  "input_168_action_label": "İlerleme oranı (Gaz)",
  "input_168_label": "Gaz",
  "input_169_action_label": "İlerleme oranı (Biyoenerji)",
  "input_169_label": "Biyoenerji",
  "input_170_action_label": "İlerleme oranı (Nükleer)",
  "input_170_label": "Nükleer",
  "input_171_action_label": "İlerleme oranı (Yenilenebilir Enerji)",
  "input_171_label": "Yenilenebilir Enerji",
  "input_172_action_label": "İlerleme oranı (Hidro)",
  "input_172_label": "Hidro",
  "input_173_action_label": "İlerleme oranı (Yeni Sıfır Karbon)",
  "input_173_label": "Yeni Sıfır Karbon",
  "input_174_label": "Diğer depolama gelişme oranı",
  "input_175_label": "İlerleme oranı (ekipman)",
  "input_176_label": "Talep yanıtı gelişme oranı",
  "input_196_label": "Kömür kullanımında azalma %'si",
  "input_197_label": "Yeni kömür altyapısını azaltma yılı",
  "input_198_label": "Petrol kullanımı azalma %'si",
  "input_199_label": "Yeni petrol altyapısı azaltma yılı",
  "input_200_label": "Gaz kullanımı azalma %'si",
  "input_201_label": "Yeni doğal gaz altyapısını azaltma yılı",
  "input_202_label": "Kömür kullanım azalma %'si başlama yılı",
  "input_203_label": "Kömür kullanım azalma %'si bitiş yılı",
  "input_204_label": "Petrol kullanımı azalma %'si başlama yılı",
  "input_205_label": "Petrol kullanımı azalma %'si bitiş yılı",
  "input_206_label": "Gaz kullanımı azalma %'si başlama yılı",
  "input_207_label": "Gaz kullanımı azalma %'si bitiş yılı",
  "input_208_label": "Ayrıntılı ayarları kullan",
  "input_209_label": "Ayrıntılı ayarları kullan",
  "input_210_label": "Ayrıntılı ayarları kullan",
  "input_211_label": "Yeni kömür altyapısını azalt",
  "input_212_label": "Yeni petrol altyapısını azalt",
  "input_213_label": "Yeni doğal gaz altyapısını azalt",
  "input_214_label": "Ormanlaştırma için uygun en fazla arazi",
  "input_215_label": "Kaldırılan her birim başına tarımsal toprak karbonu için gereken arazi",
  "input_218_label": "Ormanlaştırma için arazi elde etme süresi",
  "input_219_label": "Ormanlaştırma için ekme süresi",
  "input_221_label": "Kömür, petrol ve doğalgaz kullanımında düzenleme için gereken yıllar",
  "input_222_label": "Kömür",
  "input_223_label": "Petrol",
  "input_224_label": "Gaz",
  "input_225_label": "Biyoyakıt",
  "input_230_action_label": "Kaynak üzerindeki akış kısıtı (Rüzgar)",
  "input_230_label": "Rüzgar",
  "input_231_action_label": "Kaynak üzerindeki akış kısıtı (Güneş)",
  "input_231_label": "Güneş",
  "input_232_action_label": "Kaynak üzerindeki akış kısıtı (Yerısıl)",
  "input_232_label": "Yerısıl",
  "input_233_action_label": "Kaynak üzerindeki akış kısıtı (Diğer yenilenebilirlier)",
  "input_233_label": "Diğer yenilenebilirler",
  "input_235_label": "Uzun vadeli ekonomik büyüme (kişi başına GSYH)",
  "input_236_label": "Geçiş süresi",
  "input_237_label": "En çok topraklaşma alanı",
  "input_238_label": "Topraklaşma kaya uygulaması",
  "input_239_label": "Topraklaşmanın enerji yoğunluğu",
  "input_240_label": "Özgül topraklaşma potansiyeli",
  "input_241_label": "Topraklaşma uygulama zamanı",
  "input_242_label": "GSYİH'de en fazla azalma",
  "input_243_label": "İklim Etkileri sonucu 1.5ºC'ta GSYİH azalması",
  "input_245_label": "Temiz enerji standardını kullan",
  "input_246_label": "Temiz elektrik nitelemesine uygun olan kaynaklar",
  "input_247_label": "Uygun kaynaklardan hedeflenen elektrik %'si",
  "input_248_label": "Temiz elektrik standardı başlama yılı",
  "input_249_label": "Temiz elektrik standardına ulaşmak için gereken yıl",
  "input_251_label": "İlerleme oranı",
  "input_252_label": "Sosyal indirim oranı",
  "input_253_label": "CO<sub>2</sub>&nbsp;depolama sızıntı oranı",
  "input_258_action_label": "Akaryakıtlı ulaşım satış sınırı—hava and deniz",
  "input_258_label": "Akaryakıtlı ulaşım satış sınırı",
  "input_259_action_label": "Elektrifikasyon politikası başlangıç yılı—hava ve deniz",
  "input_259_label": "Elektrifikasyon politikası başlangıç yılı",
  "input_260_label": "Akaryakıtlı ekipman satışlarını sınırlama zamanı",
  "input_261_action_label": "Akaryakıtlı ulaşım satışlarını sınırlama zamanı—kara ve demiryolu",
  "input_261_label": "Akaryakıtlı ulaşım satışlarını sınırlama zamanı",
  "input_262_action_label": "Akaryakıtlı ulaşım satışlarını sınırlama zamanı—have and deniz",
  "input_262_label": "Akaryakıtlı ulaşım satışlarını sınırlama zamanı",
  "input_263_label": "Yenilenebilirler",
  "input_264_label": "Nükleer",
  "input_265_label": "Yeni sıfır-karbon",
  "input_266_label": "CCS ile fosil yakıt",
  "input_267_label": "Biyoenerji",
  "input_268_label": "Doğal gaz",
  "input_284_label": "Atık ve kaçak eylemlerinin gerçekleştirilmesi için yıllar",
  "input_285_label": "Antarktika buz tabakası erimesinin deniz seviyesi yükselmesine katkısı",
  "input_286_label": "Grönland buz tabakası erimesinin deniz seviyesi yükselmesine katkısı",
  "input_287_label": "Hayvansal gıdalar",
  "input_288_label": "Potansiyel mahsul verimi",
  "input_292_label": "Biyoenerji için ağaç hammaddeleri (vergi/devlet desteği)",
  "input_293_label": "Biyoenerji için mahsul hammaddeleri (vergi/teşvik)",
  "input_294_label": "Biyoenerji için atık/diğer hammaddeler (vergi/teşvik)",
  "input_298_label": "Karbon fiyatı karbon yakalama ve depolamayı (CCS) teşvik eder",
  "input_304_label": "Sıcaklığın mahsul verimine etkisi",
  "input_305_label": "Gıda atıkları",
  "input_306_label": "Detaylı ayarları kullan",
  "input_307_label": "Ormansızlaştırmayı azalt",
  "input_308_label": "Ormansızlaştırmayı azaltmaya başlangıç yılı",
  "input_309_label": "Ormansızlaştırma politikasını gerçekleştirme süresi",
  "input_310_label": "Olgun orman tahribatını azalt",
  "input_311_label": "Detaylı ayarları kullan",
  "input_312_label": "Karbon fiyatlaması biyoenerji emisyonları için geçerlidir",
  "input_313_label": "Yeni biyoenerji altyapısını azalt",
  "input_314_label": "Yeni biyoenerji altyapısını azaltma yılı",
  "input_315_label": "Olgun orman tahribatını azaltmaya başlama yılı",
  "input_316_label": "Olgun orman tahribatı politikasını gerçekleştirme süresi",
  "input_318_label": "CO<sub>2</sub>&nbsp;gübreleme sınırı",
  "input_319_label": "Sıcaklığın CO<sub>2</sub>&nbsp;solunum oranlarına etkisi",
  "input_320_label": "Ağaç maliyetinin ikiye katlanması için gerekli orman hasadı",
  "input_321_label": "Biyoenerji mahsul maliyetinin ikiye katlanması için gerekli tarım arazisi hasadı",
  "input_322_label": "Biyoenerji hammaddeleri",
  "input_327_label": "Hayvan yemi dönüşüm oranı",
  "input_328_label": "Mahsul CH<sub>4</sub>&nbsp;emisyon faktörü değişim oranı",
  "input_329_label": "Mahsul N<sub>2</sub>O emisyon faktörü değişim oranı",
  "input_330_label": "Hayvancılık CH<sub>4</sub>&nbsp;emisyon faktörü değişim oranı",
  "input_331_label": "Hayvancılık N<sub>2</sub>O emisyon faktörü değişim oranı",
  "input_332_label": "Elektrikli ulaşım devlet desteği",
  "input_334_label": "Elektrikli ulaşım devlet desteği bitiş yılı",
  "input_337_label": "Elektrikli ekipman devlet desteği bitiş yılı",
  "input_347_label": "İlerleme oranı (DACCS)",
  "input_349_label": "Ekonomik hasar formülasyonu",
  "input_351_action_label": "Karbon yakalama ve depolama (CCS) verimliliği",
  "input_351_label": "Yakalama verimliliği",
  "input_360_label": "İlerleme oranı (enerji kullanımı)",
  "input_369_label": "İklim değişikliği ekonomik büyümeyi yavaşlatır",
  "input_370_label": "Gelecekteki talebi karşılamak için şarj altyapısı kurun",
  "input_371_label": "Gelecekteki talebi karşılamak için ulaşım şarj altyapısı kurma süresi",
  "input_372_label": "Detaylı ayarları kullan",
  "input_373_label": "Elektrikli ulaşım devlet desteği ve şarj altyapısı",
  "input_375_label": "Elektrikli ekipman devlet desteği",
  "input_379_label": "Isınma nedeniyle orman yangınlarında artış",
  "input_380_label": "Ormanların yok olmasına neden olan ciddi orman yangınlarının yüzdesi",
  "input_392_label": "Depolanan hidrojende sızıntı oranı",
  "input_401_label": "Ayrıntılı ayarları kullan",
  "input_402_label": "Çiftlik hayvanları kaynaklı metan ve nitröz oksit",
  "input_403_label": "Mahsullerden metan ve nitröz oksit",
  "input_404_label": "Atıklardan metan ve nitröz oksit",
  "input_405_label": "Enerji sistemlerinden metan kaçağı",
  "input_406_label": "Endüstri kaynaklı nitröz oksit",
  "input_410_label": "Enerji tedarik vergileri veya sübvansiyonlarının elde edilmesi için gereken yıllar",
  "input_411_label": "Enerji verimliliği iyileştirme oranlarına ulaşmak için yıllar",
  "input_412_label": "Kömür, petrol, doğalgaz ve biyoenerjide yeni altyapı azaltımlarına ulaşmak için yıllar",
  "input_414_label": "CCS ile Biyoenerji",
  "input_415_label": "F-gazları",
  "input_416_label": "2°C'de ekosistem değişimi riski altındaki küresel arazi alanının yüzdesi",
  "input_417_label": "Doğa temelli karbon giderimi",
  "input_418_label": "Ayrıntılı ayarları kullan",
  "input_419_label": "Enerji sistemlerinde metanın maksimum azaltılması",
  "input_421_label": "Tarımsal emisyon eylemleri için başlangıç yılı",
  "input_422_label": "Tarımsal emisyon eylemlerini başarmak için süre",
  "input_424_label": "Biyokütlenin karbon yoğunluğu dengesi",
  "input_425_label": "Ağaçlandırılan arazinin büyüme oranındaki değişim",
  "input_432_label": "Uygulamalardan kaynaklanan F gazı ve diğer endüstriyel emisyonların maksimum azaltılması",
  "input_433_label": "F gazının alternatiflerle maksimum azaltılması",
  "input_434_label": "Maksimum F gazı imha oranı",
  "input_435_label": "Montreal gazlarının mevcut yıl stoğu",
  "input_482_action_label": "Başlangıçta kalan kaynak (Kömür)",
  "input_482_label": "Kömür",
  "input_483_action_label": "Başlangıçta kalan kaynak (Petrol)",
  "input_483_label": "Petrol",
  "input_484_action_label": "Başlangıçta kalan kaynak (Gaz)",
  "input_484_label": "Gaz",
  "input_range__breakthrough": "çığır açıcı",
  "input_range__discouraged": "caydırılmış",
  "input_range__future_breakthrough": "gelecekte çığır açıcı",
  "input_range__high": "yüksek",
  "input_range__high_growth": "yüksek büyüme",
  "input_range__highest_growth": "en yüksek büyüme",
  "input_range__highly_increased": "çok artmış",
  "input_range__highly_reduced": "çok azaltılmış",
  "input_range__highly_subsidized": "yüksek oranda desteklenmiş",
  "input_range__highly_taxed": "yüksek vergilendirilmiş",
  "input_range__huge_breakthrough": "büyük çığır açıcı",
  "input_range__increased": "artmış",
  "input_range__low": "düşük",
  "input_range__low_growth": "düşük büyüme",
  "input_range__lowest_growth": "en düşük büyüme",
  "input_range__medium": "orta",
  "input_range__medium_growth": "orta düzeyde büyüme",
  "input_range__near_term_breakthrough": "yakın gelecekte çığır açıcı",
  "input_range__negative_growth": "negatif büyüme",
  "input_range__no_growth": "büyümeme",
  "input_range__reduced": "azaltılmış",
  "input_range__status_quo": "mevcut durum",
  "input_range__subsidized": "desteklenmiş",
  "input_range__taxed": "vergilendirilmiş",
  "input_range__very_high": "çok yüksek",
  "input_range__very_highly_taxed": "çok yüksek vergilendirilmiş",
  "input_units__billion_people_in_2100": "2100 yılında milyar kişi",
  "input_units__degrees_c": "ºC",
  "input_units__dollars_per_barrel": "$/varil",
  "input_units__dollars_per_boe": "$/boe",
  "input_units__dollars_per_kwh": "$/kWsa",
  "input_units__dollars_per_mcf": "$/MCF",
  "input_units__dollars_per_ton": "$/ton",
  "input_units__dollars_per_ton_co2": "$/ton CO<sub>2</sub>",
  "input_units__ej_per_year": "EJ/yıl",
  "input_units__gj_per_ton_rock": "GJ/ton kaya",
  "input_units__gtons_co2_per_year": "Gton CO<sub>2</sub>/yıl",
  "input_units__gtons_co2e": "Gton CO<sub>2</sub>e",
  "input_units__meters_by_2100": "metre (2100'e kadar)",
  "input_units__meters_meters_per_year": "metre*metre/yıl",
  "input_units__mha": "Mha",
  "input_units__mtons_per_ej": "Mton/EJ",
  "input_units__pct": "%",
  "input_units__pct_of_diet_by_2100": "diyet yüzdesi (2100'e kadar)",
  "input_units__pct_of_food_produced_by_2100": "üretilen gıda %'si (2100'e kadar)",
  "input_units__pct_of_land_available": "mevcut arazi yüzdesi",
  "input_units__pct_of_max_potential": "Maksimum potansiyel yüzdesi",
  "input_units__pct_of_potential_reduction": "Potansiyel azaltım yüzdesi",
  "input_units__pct_of_purchase_cost": "satın alma maliyeti yüzdesi",
  "input_units__pct_of_required": "gerekli %",
  "input_units__pct_per_degrees_c": "ºC başına %",
  "input_units__pct_per_year": "%/yıl",
  "input_units__pct_per_year_per_degrees_c": "ºC başına yıllık %",
  "input_units__ratio": "oran",
  "input_units__times_2020_value_by_2100": "çarpı 2020 değeri (2100'de)",
  "input_units__ton_co2_per_tj": "ton CO<sub>2</sub>/TJ",
  "input_units__ton_co2_per_ton_rock": "ton CO<sub>2</sub>/ton kaya",
  "input_units__tons_c_per_hectare": "ton C/hektar",
  "input_units__years": "yıl",
  "map__error_failed_to_load": "Harita şu an yüklenemiyor.",
  "map__error_internet_required": "Haritalar istikrarlı bir internet bağlantısı gerektirir.",
  "map__legend_annual_likelihood_of_drought": "Yıllık 12+ ay kuraklık olasılığı",
  "map__legend_change_in_days_range": "{low} ila {high}",
  "map__legend_change_in_wildfire_days": "Orman yangını tehlikesi olan gün sayısındaki yıllık değişim",
  "map__legend_days_per_year_above_temp": "Yılda {temp_c} ({temp_f}) üzerindeki gün sayısı",
  "map__legend_days_per_year_above_temp_wet_bulb": "Islak hazne sıcaklığı yılda {temp_c} ({temp_f}) üzerindeki gün sayısı",
  "map__map_year": "Harita Yılı:",
  "map__search_places": "Yer ara",
  "map__show_baseline": "Referans senaryo göster",
  "map__show_current_scenario": "Mevcut senaryo göster",
  "map__temperature_by_year": "{year}'de {temp}",
  "map_slr__error_internet_required": "Deniz seviyesi yükselme haritaları sabit bir internet bağlantısı gerektirir.",
  "map_slr__loading": "Climate Central haritası yükleniyor…",
  "map_slr__map_type": "Harita Türü:",
  "map_slr__map_type_21st_century": "21'inci yüzyıl",
  "map_slr__map_type_21st_century_with_surge": "Fırtına Dalgalanması ile 21. Yüzyıl",
  "map_slr__map_type_longterm": "Uzun Dönem Denge",
  "map_slr__meters": "{num} m",
  "map_slr__storm_surge": "Fırtına Dalgalanması:",
  "menu__actions_and_outcomes": "Eylemler ve Sonuçlar",
  "menu__assumptions": "Varsayımlar",
  "menu__en_roads_overview": "En-ROADS'a Genel Bakış",
  "menu__en_roads_training": "En-ROADS Eğitimi",
  "menu__en_roads_user_guide": "En-ROADS Kullanıcı Kılavuzu",
  "menu__graph_selection": "Grafik Seçim",
  "menu__graphs": "Grafikler",
  "menu__help": "Yardım",
  "menu__kaya_graphs": "Kaya Grafikleri",
  "menu__language": "Dil",
  "menu__main_graphs": "Temel Grafikler",
  "menu__metric_units": "Metrik Birimler",
  "menu__miniature_graphs": "Mini Grafikler",
  "menu__model_technical_reference": "Model Teknik Referansı",
  "menu__play_sounds": "Sesleri çal",
  "menu__related_examples": "İlgili Örnekler",
  "menu__release_notes": "Sürüm Notları",
  "menu__reset_assumptions": "Varsayımları ilk durumuna getir",
  "menu__reset_policies": "Politikaları ilk durumuna getir",
  "menu__reset_policies_and_assumptions": "Politika ve Varsayımları ilk durumuna getir",
  "menu__return_to_default_graphs": "Varsayılan Grafiklere dön",
  "menu__show_graph_tooltips": "Grafik İpuçlarını Göster",
  "menu__simulation": "Simülasyon",
  "menu__slider_information": "Sürgü ile ilgili bilgi",
  "menu__support": "Destek",
  "menu__us_units": "ABD Birimleri",
  "menu__uses_for_en_roads": "En-ROADS'un kullanım alanları",
  "menu__video_tours": "Video turları",
  "menu__view": "Görüntü",
  "menu_graphs__co2_emissions": "CO<sub>2</sub>&nbsp;Emisyonu",
  "menu_graphs__co2_removals": "CO<sub>2</sub>&nbsp;Giderimleri",
  "menu_graphs__final_energy_consumption_totals": "Nihai Enerji Tüketim Toplamları",
  "menu_graphs__final_energy_consumption_types": "Nihai Enerji Tüketim Türleri",
  "menu_graphs__financial": "Finansal",
  "menu_graphs__greenhouse_gas_emissions": "Sera Gazı Emisyonu",
  "menu_graphs__impacts": "Etkiler",
  "menu_graphs__land_forestry_and_food": "Arazi, Ormancılık ve Gıda",
  "menu_graphs__model_comparison_history": "Model Karşılaştırma—Geçmiş",
  "menu_graphs__population_and_gdp": "Nüfus ve GSYH",
  "menu_graphs__primary_energy_demand_totals": "Birincil Enerji Talep Toplamları",
  "menu_graphs__primary_energy_demand_types": "Birincil Enerji Talep Türleri",
  "menu_graphs__view_more_graphs": "Daha fazla grafik görün",
  "outcome_13_label": "2100 boyunca İndirilmiş Birikimli Hasar",
  "outcome_13_units_metric": "trilyon $",
  "outcome_1_label": "2100 yılı Sıcaklık artışı",
  "outcome_1_units_metric": "ºC",
  "outcome_1_units_us": "ºF",
  "outcome_2_label": "2100 yılı CO<sub>2</sub>&nbsp;Yoğunluğu",
  "outcome_2_units_metric": "ppm",
  "outcome_3_label": "2100 yılı Deniz Düzeyi Yükselmesi",
  "outcome_3_units_metric": "m",
  "outcome_3_units_us": "ft",
  "outcome_4_label": "2100 yılına kadar önlenen birikimli CO<sub>2</sub>&nbsp;miktarı",
  "outcome_4_units_metric": "gigaton CO<sub>2</sub>",
  "policy_group_001_description": "Kömürün çıkarılmasını ve termik santrallerde yakılmasını caydırın ya da teşvik edin. Gerek karbon emisyonu gerekse ciddi sağlık tehlikelerine neden olan hava kirleticiliği bakımından kömür en zararlı fosil yakıttır. Ancak çıkarılması ve taşınması görece ucuz olduğu için, küresel olarak baskın bir enerji kaynağıdır.Kömürün çıkarılmasını ve termik santrallerde yakılmasını caydırın ya da teşvik edin.",
  "policy_group_001_example_1": "Vergiler",
  "policy_group_001_example_2": "Daha az devlet yardımı",
  "policy_group_001_example_3": "Hava kirliliği",
  "policy_group_001_short_title": "Kömür",
  "policy_group_001_title": "Kömür",
  "policy_group_002_description": "Petrolün enerji için çıkarılmasını, rafine edilmesini ve tüketilmesini caydırın ya da teşvik edin. Petrol; endüstride, ısıtmada ve elektrikte olduğu gibi, araçlarda, gemilerde ve uçaklarda yaygın olarak kullanılan bir fosil yakıttır. Petrole erişim pek çok anlaşmazlıklara neden olmuştur ve petrol sızıntısı ekosistem ve su için zararlı olabilir.",
  "policy_group_002_example_1": "Daha az devlet yardımı",
  "policy_group_002_example_2": "Boru hatları",
  "policy_group_002_example_3": "Tasfiye",
  "policy_group_002_short_title": "Petrol",
  "policy_group_002_title": "Petrol",
  "policy_group_003_description": "Doğal gazın enerji için çıkarılmasını ve yakılmasını caydırın ya da teşvik edin. Doğal gaz; elektrik, ısıtma ve endüstri için kullanılan bir fosil yakıttır. Yandığında (kömür ve petrole göre daha az olsa da) karbondioksit salar ve eğer havaya sızarsa, yüksek oranda metan içerir. Doğal gaz çıkarımında büyük miktarda su kullanılır ve kirliliğe neden olabilir.",
  "policy_group_003_example_1": "Hidrolik kırılma",
  "policy_group_003_example_2": "Boru hatları",
  "policy_group_003_example_3": "Tasfiye",
  "policy_group_003_short_title": "Doğal Gaz",
  "policy_group_003_title": "Doğal Gaz",
  "policy_group_004_description": "Ağaçların, orman atığının ve tarım ürünlerinin enerji için kullanımını caydırın ya da teşvik edin. Bu kaynaklar katı, sıvı veya gaz olarak yakıldıklarında enerji üretirler. Bazı kaynaklar sürdürülebilir enerji kaynakları iken diğerleri kömür yakmaktan daha kötü olabilir. Karbon yakalama ve depolama teknolojisi biyoenerji ile birlikte kullanılabilir (BECCS) fakat henüz yaygın bir şekilde kullanılmamıştır.",
  "policy_group_004_example_1": "Biyoyakıt",
  "policy_group_004_example_2": "Yakacak odun",
  "policy_group_004_short_title": "Biyoenerji",
  "policy_group_004_title": "Biyoenerji",
  "policy_group_005_description": "Güneş panelleri, jeotermal ve rüzgar türbinleri kurmayı teşvik edin ya da caydırın. Yenilenebilir enerji; rüzgar, güneş, jeotermal, hidroelektrik vb gibi çok az karbondioksit emisyonu veya hava kirliliği yapan ya da hiç yapmayan teknolojileri içerir. Nükleer ve biyoenerjinin ayrı tutulduğuna dikkat edin.",
  "policy_group_005_example_1": "Rüzgar, Güneş, Hidro",
  "policy_group_005_example_2": "Temiz enerji",
  "policy_group_005_example_3": "Enerji depolama",
  "policy_group_005_short_title": "Yenilenebilir Enerji",
  "policy_group_005_title": "Yenilenebilir Enerji",
  "policy_group_006_description": "Nükleer güç santrallarını caydırın ya da teşvik edin. Nükleer güç santralları karbondioksit salımı yapmaz ancak yüzlerce yıl gözetilmesi gereken atık üretir.",
  "policy_group_006_example_1": "Işınım",
  "policy_group_006_example_2": "Atık depolama",
  "policy_group_006_short_title": "Nükleer",
  "policy_group_006_title": "Nükleer",
  "policy_group_007_description": "Sera gazı salmayan yepyeni ve ucuz bir elektrik kaynağı bulun. Nükleer füzyonun veya toryum temelli nükleer fisyonun böyle çığır açıcı bir ilerleme sağlayacağını düşünenler var ancak herhangi bir yeni enerji kaynağının bilinmeyen riskleri bulunur. Çığır açıcı ilerlemenin ne zaman oalcağına, kömüre göre başlangıç maliyetinin ne olacağına ve ticarileşme ve çoğaltmanın ne kadar gecikme ile olacağına karar verin.",
  "policy_group_007_example_1": "Toryum fisyonu",
  "policy_group_007_example_2": "Nükleer füzyon",
  "policy_group_007_short_title": "Yeni Sıfır Karbon",
  "policy_group_007_title": "Yeni Sıfır Karbon",
  "policy_group_008_description": "Saldıkları karbondioksite bağlı olarak enerji kaynaklarının daha pahalı olmasına neden olacak bir küresel karbon fiyatı belirleyin veya bir temiz elektrik standardı veya salım peformans standardı yasası çıkarın. Enerji üreticileri ek maliyetleri müşterilerine yansıtabilirler, bu nedenle politika en yoksulu en az etkileyecek biçimde tasarlanmalıdır.",
  "policy_group_008_example_1": "Karbon Fiyatı",
  "policy_group_008_example_2": "Salım üst sınırı ve ticareti",
  "policy_group_008_short_title": "Karbon Fiyatı",
  "policy_group_008_title": "Karbon Fiyatlama ve Enerji Standartları",
  "policy_group_009_description": "Araçlar, gemicilik, havacılık ve ulaşım sistemlerinin enerji verimliliğini artırın ya da azaltın. Enerji verimliliği hibrid araçlar, yaygınlaştırılmış toplu taşıma ve insanların daha az enerji ile gezinmelerini sağlayacak yöntemler içerir. Enerji verimliliği daha yüksek ulaşım alışkanlıkları benimsemek toplum sağlığını iyileştirir ve tasarruf sağlar.",
  "policy_group_009_example_1": "Hibrit araba",
  "policy_group_009_example_2": "Yürünebilirlik",
  "policy_group_009_example_3": "Toplu taşıma",
  "policy_group_009_short_title": "Enerji Verimliliği",
  "policy_group_009_title": "Ulaşım Enerji Verimliliği",
  "policy_group_010_description": "Elektrikli otomobillerin, kamyonların, otobüslerin, trenlerin ve hatta gemilerin ve uçakların satın alınmasını artırın. Ulaşım için elektrik motorları kullanmak, elektrik ancak güneş veya rüzgar gibi düşük karbonlu kaynaklardan elde ediliyorsa, ulaşım kaynaklı sera gaz emisyonunu azaltmaya yardımcı olur.",
  "policy_group_010_example_1": "Elektrikli araçlar",
  "policy_group_010_example_2": "Pil teknolojisi",
  "policy_group_010_example_3": "Yükleme altyapısı",
  "policy_group_010_short_title": "Elektrifikasyon",
  "policy_group_010_title": "Ulaşım Elektrifikasyonu",
  "policy_group_011_description": "Yapıların, elektrikli aletlerinin ve diğer makinelerin enerji verimliliğini artırın ya da azaltın. Enerji verimliliği; iyi yalıtılmış yapılar yapmak ve fabrikaların kullandığı enerji miktarını azaltmak gibi şeyler içerir. Enerji verimliliği uygulamaları, enerji gereksinimini azaltarak tasarruf edilmesi yanında o yapılardaki insanların sağlığının da iyileşmesine neden olabilir.",
  "policy_group_011_example_1": "Yeşil yapılar",
  "policy_group_011_example_2": "Verimli endüstri",
  "policy_group_011_example_3": "Enerji korunumu",
  "policy_group_011_short_title": "Enerji Verimliliği",
  "policy_group_011_title": "Yapı ve Endüstri Enerji Verimliliği",
  "policy_group_012_description": "Binalarda, elektrikli aletlerde, ısıtma sistemlerinde ve diğer makinelerde; petrol ve gaz gibi yakıtlar yerine elektrik kullanımını artırın. Elektrik motorları kullanmak, elektrik ancak güneş veya rüzgar gibi düşük karbonlu kaynaklardan elde ediliyorsa emisyonların azalmasına ve hava kalitesinin iyileşmesine yardımcı olur.",
  "policy_group_012_example_1": "Elektrikle ısıtma",
  "policy_group_012_example_2": "Isı pompaları",
  "policy_group_012_short_title": "Elektrifikasyon",
  "policy_group_012_title": "Yapıların ve Endüstrinin Elektrifikasyonu",
  "policy_group_013_description": "Yüksek ya da düşük nüfus büyümesi varsayın. Nüfus büyümesi için beklenen davranış örüntüleri olmakla birlikte, kadınların eğitimi ve aile planlamasına erişim gibi, küçük ailelere yönelimi artıran ve böylece nüfus büyüme hızını düşüren çeşitli adımlar var.",
  "policy_group_013_example_1": "Kadınların güçlendirilmesi",
  "policy_group_013_example_2": "Doğurganlık oranları",
  "policy_group_013_short_title": "Nüfus",
  "policy_group_013_title": "Nüfus",
  "policy_group_014_description": "Üretilen ürünlerin ve sağlanan hizmetlerin hızlı ya da yavaş büyümesini varsayın. Ekonomik Büyüme, kişi başına Gayri Safi Yurt İçi Hasıla (GSYİH) ile ölçülür ve enerji tüketiminin anahtar etkenidir. İnsanların gereksinimlerini, sabit GSYİH artışı temelinde olmayan ekonomik çerçeveler üzerinden karşılayan seçenekler vardır.",
  "policy_group_014_example_1": "Kişi başına GSYH",
  "policy_group_014_example_2": "Yalınlık akımı",
  "policy_group_014_short_title": "Ekonomik Büyüme",
  "policy_group_014_title": "Ekonomik Büyüme",
  "policy_group_015_description": "Atık, enerji ve endüstriyle ilgili en iyi emisyon uygulamalarının benimsenme düzeyini değiştirin. Atık depolama alanlarından ve atık su sistemlerinden kaynaklanan metan (CH<sub>4</sub>) ve nitröz oksit (N<sub>2</sub>O) emisyonları, gelişmiş tasarım ve atık yönetimi yoluyla azaltılabilir. Fosil yakıt operasyonlarından kaynaklanan metan sızıntılarını giderin ve gübre üretimi gibi endüstriyel süreçlerden kaynaklanan N<sub>2</sub>O emisyonlarını yönetin. Kimya endüstrisinde ve klima gibi tüketim mallarında F gazlarını (HFC'ler, PFC'ler, SF<sub>6</sub>&nbsp;ve diğerleri) yönetin.",
  "policy_group_015_example_1": "Metan, N<sub>2</sub>O, HFC'ler",
  "policy_group_015_example_2": "Soğutucu akışkanlar",
  "policy_group_015_short_title": "Atık ve Kayıp-Kaçak",
  "policy_group_015_title": "Atık ve Kayıp-Kaçak",
  "policy_group_016_description": "Tarımda ve gıda alışkanlıklarında en iyi emisyon uygulamalarının benimsenme düzeyini değiştirin. Metan (CH<sub>4</sub>) inekler ve pirinç tarlaları gibi kaynaklardan ortaya çıkarken, nitröz oksit (N<sub>2</sub>O) suni ve doğal gübrelerden salınır. İyileştirilmiş tarım yöntemleri emisyonları doğrudan azaltabilir ve değişen gıda alışkanlıkları, hayvancılık ve mahsullere olan talebi azaltarak yeni tarım arazisi ihtiyacını azaltabilir ve ormansızlaşmanın önlenmesine yardımcı olabilir.",
  "policy_group_016_example_1": "Gübre yönetimi",
  "policy_group_016_example_2": "Suni Gübre",
  "policy_group_016_example_3": "Bitki bazlı diyetler",
  "policy_group_016_short_title": "Tarımsal Emisyonlar",
  "policy_group_016_title": "Tarımsal Emisyonlar ve Gıda Seçimleri",
  "policy_group_017_description": "Ormanların genişletilmesi (ağaçlandırma), bozulmuş olanların restorasyonu, karbon yakalayan tarımsal uygulamaların uygulanması ve biyoçar üretiminin teşvik edilmesi. Bu doğa temelli yöntemler, karbondioksiti atmosferden giderebilir ve bitkilerde ve toprakta depolayabilir. Bununla birlikte, tarımsal faaliyetler veya kontrol edilemeyen yangınlar gibi kazara meydana gelen olaylar yoluyla arazi değiştirilirse bu karbon tekrar atmosfere salınabilir.",
  "policy_group_017_example_1": "Ormanlaştırma",
  "policy_group_017_example_2": "Tarımsal Toprak Karbonu",
  "policy_group_017_example_3": "Biyoçar",
  "policy_group_017_short_title": "Doğa-Temelli",
  "policy_group_017_title": "Doğa-Temelli Karbondioksit Giderimi",
  "policy_group_018_description": "Doğrudan havadan yakalama ve gelişmiş mineralizasyon gibi karbondioksit giderim teknolojilerinin kullanımını teşvik edin. Bu yöntemler, karbondioksitin atmosferden doğrudan uzaklaştırılması için ağır sanayiye ihtiyaç duyar. Bu teknolojiler atmosferik karbonu azaltmak için umut verici çözümler sunarken, büyük ölçekte uygulanması için önemli miktarda enerji ve yatırım gerekir.",
  "policy_group_018_example_1": "Doğrudan Hava Yakalama",
  "policy_group_018_example_2": "Mineralizasyon",
  "policy_group_018_short_title": "Teknolojik",
  "policy_group_018_title": "Teknolojik Karbondioksit Giderimi",
  "policy_group_019_description": "Mevcut ormansızlaştırma ve tahribat eğilimini değiştirmek için ormanların korunmasını teşvik edin veya caydırın. Ormansızlaştırma, orman arazilerinin başta tarım olmak üzere diğer kullanımlar için dönüştürülmesidir. Orman tahribatı, odun ürünleri veya biyoenerji amaçlı hasat nedeniyle ormanların geçici olarak kaybedilmesidir. Ormansızlaştırma, tarım arazisi ihtiyacından kaynaklanmaktadır, ve gıda sistemindeki değişikliklerden etkilenebilir (Tarımsal Emisyonlar kısmında).",
  "policy_group_019_example_1": "Ormanların Korunması",
  "policy_group_019_example_2": "Yeni ormanlar",
  "policy_group_019_short_title": "Ormansızlaştırma",
  "policy_group_019_title": "Ormansızlaştırma ve Doğal Yaşlı Orman Tahribatı",
  "selector__custom": "Özel",
  "selector__default": "Varsayılan",
  "selector__select": "Seç…",
  "share_by_email__enter_from_addr": "Kendi e-posta adresinizi girin",
  "share_by_email__enter_from_name": "Adınızı girin",
  "share_by_email__enter_note": "Yukarıya eklenen ek not (isteğe bağlı)",
  "share_by_email__enter_to_addr": "Alıcının e-posta adresini girin",
  "share_by_email__failed": "Senaryo e-postasını gönderirken bir hata oluştu. Lütfen yeniden deneyin.",
  "share_by_email__from_label": "Kimden",
  "share_by_email__invalid_from_addr": "Geçerli bir gönderen e-posta adresi girin",
  "share_by_email__invalid_from_name": "Adınızı girin",
  "share_by_email__invalid_to_addr": "Geçerli bir alıcı e-posta adresi girin",
  "share_by_email__note_label": "Not",
  "share_by_email__preview_label": "Ön izleme",
  "share_by_email__privacy": "Gizliliğinize saygı duyuyoruz. Bu forma girilen bilgiler alıcıya bir tek e-posta göndermek için kullanıldı.",
  "share_by_email__send": "Gönder",
  "share_by_email__succeeded": "Senaryo bağlantısı {toAddress} adresine başarıyla gönderildi",
  "share_by_email__template_line1": "Yeni bir iklim politika senaryosu sizinle paylaşıldı.",
  "share_by_email__template_line2": "En-ROADS simülatörü ile yaratılan özel-oluşturulmuş küresel iklim senaryosu için bağlantı:",
  "share_by_email__template_line3": "Şuna bir bakın.",
  "share_by_email__template_line4": "En-ROADS <i>Climate Interactive</i> ve <i>MIT Sloan İşletme Okulu</i> tarafından geliştirilmiştir. Daha fazla bilgi için {link} bağlantısını ziyaret edebilirsiniz.",
  "share_by_email__template_subject": "Sizinle paylaşıldı: En-ROADS İklim Senaryosu",
  "share_by_email__to_label": "Kime",
  "share_menu__copy_scenario_link": "Senaryo Bağlantısını Kopyala",
  "share_menu__share_by_email": "E-posta ile Paylaş",
  "share_menu__share_on_facebook": "Facebook'da Paylaş",
  "share_menu__share_on_linked_in": "LinkedIn'de Paylaş",
  "share_menu__share_on_twitter": "X'de Paylaş",
  "share_menu__share_your_scenario": "Senaryonuzu Paylaşın",
  "temperature_box__increase_by_2100": "2100'e kadar<br>Sıcaklık<br>Artışı",
  "welcome__announcement_line1": "En-ROADS, {date} tarihinde yeni özellikler ve iyileştirmelerle güncellendi.",
  "welcome__announcement_line2": "Daha fazla bilgi edinmek için lütfen {linkRelease}yeni sürüm notlarımızı {linkClose} ziyaret edin.",
  "welcome__line1": "Climate Interactive ve MIT Sloan İşletme Okulu tarafından geliştirilen En-ROADS'a hoş geldiniz."
}